INCLUDE "%MOD_FOLDER%/lib/pnp-monster/spider/64.tpa" // Gargantuan Spider
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/spider/58.tpa" // Ghostwalk Spider
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/spider/56.tpa" // Giant Spider
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/spider/62.tpa" // Hairy Spider
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/spider/55.tpa" // Huge Spider
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/spider/65.tpa" // Hunting Spider
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/spider/57.tpa" // Phase Spider
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/spider/59.tpa" // Sword Spider
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/spider/63.tpa" // Vortex Spider
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/spider/60.tpa" // Wraith Spider
LAF integrate_sectypes END
