import chalk from "chalk";
import figureSet from "figures";
import { CONSTRUCT_BONUS_HIT_POINT } from "../../config/creatures";
import { GLOBAL_CONFIG } from "../../config/generate";
import { Creature, CreatureData } from "../model/final/creature";
import { ItemAbilityLocationEnum, ItemFlagEnum } from "../model/final/enums";
import { Item } from "../model/final/item";
import { RawCreatureAutoGenerate } from "../model/raw/creature";
import { CreatureSize } from "../model/raw/enum";
import { convertMovement } from "./misc.func";
import { PLAYER_CLASS_IDENTIFIERS } from "../model/ids/class";
import { SAVING_THROWS } from "../model/constants";
import { stringify } from "querystring";

export class CreatureService {
  static instance = new CreatureService();

  autogenerateData(p: {
    autoGenerate: RawCreatureAutoGenerate;
    data: CreatureData;
    creature: Creature;
    parent?: CreatureData;
  }) {
    if (p.autoGenerate.hitPoints && p.data.hp === undefined)
      this.autogenerateHitPoints({
        data: p.data,
        creature: p.creature,
        parent: p.parent,
      });
    if (p.autoGenerate.thac0 && p.data.thac0 === undefined)
      this.autogenerateThac0(p.data, p.parent);
    if (p.autoGenerate.savingThrows && p.data.saveBreath === undefined)
      this.autogenerateSavingThrows(p.data, p.parent);
  }

  checkWeapons(creature: Creature) {
    for (const item of creature.items) {
      if (item.location === ItemAbilityLocationEnum.Weapon) {
        this.checkWeapon(creature, item);
      }
    }
  }

  private checkWeapon(creature: Creature, item: Item) {
    const level = creature.data.level1;
    const enchantments = [
      { hd: 4, hp: 1, enchant: 1 },
      { hd: 6, hp: 2, enchant: 2 },
      { hd: 8, hp: 3, enchant: 3 },
      { hd: 10, hp: 4, enchant: 4 },
    ].reverse();
    const ranges: { size: CreatureSize; range: number }[] = [
      { size: "Tiny", range: 0 },
      { size: "Small", range: 1 },
      { size: "Medium", range: 1 },
      { size: "Large", range: 2 },
      { size: "Huge", range: 2 },
      { size: "Gargantuan", range: 3 },
    ];
    if (
      level !== undefined &&
      item.enchantment === undefined &&
      creature.autoGenerate.enchantment
    ) {
      const enchant = enchantments.find(
        (e) =>
          level > e.hd ||
          (level == e.hd &&
            !!creature.data.bonusHp &&
            creature.data.bonusHp >= e.hp)
      );
      if (enchant) {
        // console.log(creature.data.class, 'enchant:', enchant.enchant);
        item.enchantment = enchant.enchant;
        if (
          enchant.enchant &&
          (!item.flags || !item.flags.includes(ItemFlagEnum.Magical))
        ) {
          item.flags = item.flags ?? [];
          item.flags.push(ItemFlagEnum.Magical);
        }
      }
    }
    if (
      item.location === ItemAbilityLocationEnum.Weapon &&
      item.projectile === undefined &&
      item.range === undefined &&
      creature.autoGenerate.meleeRange
    ) {
      const range = ranges.find((r) => r.size === creature.data.size);
      if (range) {
        console.log(creature.data.class, "range:", range.range);
        item.range = range.range;
      }
    }
  }

  private autogenerateHitPoints(p: {
    data: CreatureData;
    creature: Creature;
    parent?: CreatureData;
  }) {
    const level = p.data.level1 ?? p.parent?.level1;
    if (!level)
      throw new Error(`Can't generate hit points because level1 is unknown`);
    const constitutionTable: { [index: number]: number } = {
      15: 1,
      16: 2,
      17: 3,
      18: 4,
      19: 5,
      20: 5,
      21: 6,
      22: 6,
      23: 6,
      24: 7,
      25: 7,
    };
    const size: CreatureSize = p.data.size ?? p.parent?.size ?? "Tiny";
    let bonusHitPoints = p.data.bonusHp ?? p.parent?.bonusHp ?? 0;
    const constructBonusHP = p.creature.additionalData.immunities.includes(
      "construct"
    )
      ? (
          CONSTRUCT_BONUS_HIT_POINT.find((c) => c.size === size) as {
            size: CreatureSize;
            hp: number;
          }
        ).hp
      : 0;
    const isPlayerClass = PLAYER_CLASS_IDENTIFIERS.includes(
      p.data.class ?? p.parent?.class ?? "NO_CLASS"
    );
    const constitution = p.data.constitution ?? p.parent?.constitution ?? 10;
    const conHPPerLevel =
      GLOBAL_CONFIG.constitutionAffectHitPoint && !isPlayerClass
        ? constitutionTable[constitution] ?? 0
        : 0;
    const baseHP = level * 8;
    const constitutionHP =
      constructBonusHP === 0 ? Math.min(level, 9) * conHPPerLevel : 0;
    const specialBonusHp = p.data.specialBonusHp ?? 0;
    if (constitutionHP > 0 || constructBonusHP > 0) {
      bonusHitPoints = 0;
    }
    let log = `${figureSet.arrowRight} Level: ${level}, hit points: ${baseHP} (base)`;
    if (constitutionHP > 0) log = `${log} + ${constitutionHP} (con)`;
    if (specialBonusHp > 0) log = `${log} + ${specialBonusHp} (special)`;
    if (constructBonusHP > 0) log = `${log} + ${constructBonusHP} (construct)`;
    p.data.hp =
      baseHP +
      constitutionHP +
      bonusHitPoints +
      specialBonusHp +
      constructBonusHP;
    console.log(`${log} = ${p.data.hp}`);
  }

  private autogenerateThac0(data: CreatureData, parent?: CreatureData) {
    let level = data.level1 ?? parent?.level1;
    if (!level)
      throw new Error(`Can't generate hit points because level1 is unknown`);
    if (!!data.bonusHp && data.bonusHp >= 3) {
      level++;
      console.log(
        `${figureSet.arrowRight} calculating THAC0 as a level ${level} creature`
      );
    }
    const thac0Table: { [index: number]: number } = {
      1: 20,
      2: 19,
      3: 17,
      4: 17,
      5: 15,
      6: 15,
      7: 13,
      8: 13,
      9: 11,
      10: 11,
      11: 9,
      12: 9,
      13: 7,
      14: 7,
      15: 5,
      16: 5,
      17: 3,
      18: 3,
      19: 1,
      20: 1,
      21: -1,
      22: -1,
      23: -3,
      24: -3,
      25: -5,
      26: -5,
      27: -7,
      28: -8,
      29: -10,
      30: -10,
    };
    if (data.thac0 !== undefined)
      console.log(
        chalk.yellowBright(
          `${figureSet.warning} level: ${level}, hp bonus: ${data.bonusHp}, thac0: ${data.thac0}, calculated: ${thac0Table[level]}`
        )
      );
    if (data.thac0 === undefined) data.thac0 = thac0Table[level];
  }

  convertMovement(movement: number): number {
    return convertMovement(movement);
  }

  private autogenerateSavingThrows(data: CreatureData, parent?: CreatureData) {
    const level = data.level1 ?? parent?.level1;
    if (!level)
      throw new Error(`Can't generate thac0 because level1 is unknown`);
    const classe = data.class ?? parent?.class ?? "";
    let key: keyof typeof SAVING_THROWS = "fighter";
    if (classe === "DRUID" || classe === "CLERIC") key = "priest";
    else if (classe === "MAGE") key = "wizard";
    const table = SAVING_THROWS[key];
    const saves = table.find(
      (t) => level >= t.levels[0] && level <= t.levels[1]
    ) as {
      saveDeath: number;
      saveWand: number;
      savePolymorph: number;
      saveBreath: number;
      saveSpell: number;
    };
    if (key !== "fighter")
      console.log(
        `${
          figureSet.arrowRight
        } Level: ${level}, class: ${classe}, saving throws table: ${key}, ${JSON.stringify(
          saves
        )}`
      );
    data.saveDeath = saves.saveDeath;
    data.saveWand = saves.saveWand;
    data.savePolymorph = saves.savePolymorph;
    data.saveBreath = saves.saveBreath;
    data.saveSpell = saves.saveSpell;
  }

  getStrengthModifier(data: CreatureData): number {
    if (!data.strength || data.strength < 17) return 0;
    const table = [
      { str: 17, modifier: 1 },
      { str: 18, strEx: [0, 50], modifier: 1 },
      { str: 18, strEx: [51, 99], modifier: 2 },
      { str: 18, strEx: [100, 100], modifier: 3 },
      { str: 19, modifier: 3 },
      { str: 20, modifier: 3 },
      { str: 21, modifier: 4 },
      { str: 22, modifier: 4 },
      { str: 23, modifier: 5 },
      { str: 24, modifier: 6 },
      { str: 25, modifier: 7 },
    ];
    const item = table.find((t) => {
      const exStrength = data.exceptionalStrength ?? 0;
      const checkStr = t.str === data.strength;
      const checkStrEx =
        t.strEx === undefined ||
        (exStrength >= t.strEx[0] && exStrength <= t.strEx[1]);
      return checkStr && checkStrEx;
    }) as { modifier: number };
    return item.modifier;
  }

  getAttacksPerRound(value: number): number {
    if (value === 0.5) {
      return 6;
    } else if (value === 1.5) {
      return 7;
    } else if (value === 2.5) {
      return 8;
    } else if (value === 3.5) {
      return 9;
    } else if (value === 4.5) {
      return 10;
    } else if (value < 6) return value;
    throw new Error(`Can't set more than 5 attacks per round: ${value}`);
  }
}
