import chalk from "chalk";
import figureSet from "figures";
import {
  CONSTRUCT_BONUS_HIT_POINT,
  CreatureSize,
  creatureSizes,
} from "../../config/creatures";
import { GLOBAL_CONFIG } from "../../config/generate";
import { SAVING_THROWS } from "../model/constants";
import {
  BaseCreature,
  Creature,
  CreatureAutoGenerate,
} from "../model/creature/creature";
import {
  ItemAbilityLocationEnum,
  ItemFlagEnum,
} from "../model/spell-item/effect.enums";
import { PLAYER_CLASS_IDENTIFIERS } from "../model/ids/class";
import { CreatureData } from "../model/creature/data";
import { Weapon } from "../model/spell-item/spell-item";
import utils from "./utils/utils.service";
import { convertMovement } from "./utils/misc.func";

class CreatureService {
  check(creature: Creature) {
    this.checkData({
      creature,
      base: creature,
      isAdjustment: false,
    });
    for (const a of creature.adjustments) {
      this.checkData({
        creature,
        base: a,
        isAdjustment: true,
      });
    }
  }

  checkData(p: {
    creature: Creature;
    base: BaseCreature;
    isAdjustment: boolean;
  }): void {
    const data = p.base.data;
    const additionalData = p.base.additionalData;
    console.log(p.base.files);
    if (p.creature.attack?.dualWielding && !p.isAdjustment) {
      if (!data.apr)
        throw new Error(
          "Attacks per round need to be set for dual wielding flag"
        );
      data.apr -= 1;
      console.log(
        `${figureSet.arrowRight} setting dual wield: ${data.apr} APR +1 offhand`
      );
    }
    if (data.dexterity !== undefined && data.ac !== undefined) {
      const bonus = this.getDexterityArmorClassBonus(data);
      if (bonus) {
        console.log(
          `${figureSet.arrowRight} AC reduced to ${data.ac - bonus} (was ${
            data.ac
          }) because of dexterity bonus (${bonus})`
        );
        data.ac -= bonus;
      }
    }
    this.checkMovement(p);
    this.transformAttackPerRound(p.creature.data);
    if (data.kit === "BARBARIAN") {
      additionalData.immunities.push("backstab");
    }
    this.autogenerateData({
      data,
      autoGenerate: p.creature.autoGenerate,
      creature: p.creature,
      parent: p.isAdjustment ? p.creature.data : undefined,
    });
  }

  private checkMovement(p: {
    creature: Creature;
    base: BaseCreature;
    isAdjustment: boolean;
  }) {
    const data = p.base.data;
    const additionalData = p.base.additionalData;
    if (additionalData.movement.value === -1 && !p.isAdjustment)
      throw new Error("movement not set !");
    if (additionalData.movement.value > -1) {
      data.movement = this.convertMovement(additionalData.movement.value);
      console.log(`${figureSet.arrowRight} movement set to ${data.movement}`);
    }
    const movement = data.movement ?? p.creature.data.movement;
    if (data.kit === "BARBARIAN" && movement) {
      data.movement = movement + 2;
      console.log(
        `${figureSet.arrowRight} movement increased to ${data.movement} (barbarian): `
      );
    }
  }

  private transformAttackPerRound(data?: CreatureData) {
    if (!data || !data.apr) return;
    try {
      return this.getAttacksPerRound(data.apr);
    } catch {
      data.doubleApr = true;
      if (data.movement) {
        data.movement = Math.round(data.movement / 2);
      }
      switch (data.apr) {
        case 6:
          data.apr = 3;
          break;
        case 7:
          data.apr = 9;
          break;
        case 8:
          data.apr = 4;
          break;
        case 9:
          data.apr = 10;
          break;
        case 10:
          data.apr = 5;
          break;
      }
    }
  }

  autogenerateData(p: {
    autoGenerate: CreatureAutoGenerate;
    data: CreatureData;
    creature: Creature;
    parent: CreatureData | undefined;
  }) {
    if (p.autoGenerate.hitPoints && p.data.hp === undefined)
      this.autogenerateHitPoints({
        data: p.data,
        creature: p.creature,
        parent: p.parent,
      });
    if (p.autoGenerate.thac0 && p.data.thac0 === undefined)
      this.autogenerateThac0(p.data, p.parent);
    if (p.autoGenerate.savingThrows && p.data.saveBreath === undefined)
      this.autogenerateSavingThrows(p.data, p.parent);
  }

  checkWeapons(creature: Creature) {
    for (const item of creature.items) {
      if (item.header?.location === ItemAbilityLocationEnum.Weapon) {
        this.checkWeapon(creature, item as Weapon);
      }
    }
  }

  private checkWeapon(creature: Creature, weapon: Weapon) {
    const level = creature.data.level1;
    const enchantments = [
      { hd: 4, hp: 1, enchant: 1 },
      { hd: 6, hp: 2, enchant: 2 },
      { hd: 8, hp: 3, enchant: 3 },
      { hd: 10, hp: 4, enchant: 4 },
    ].reverse();
    if (
      level !== undefined &&
      weapon.enchantment === undefined &&
      creature.autoGenerate.enchantment
    ) {
      const enchant = enchantments.find(
        (e) =>
          level > e.hd ||
          (level == e.hd &&
            !!creature.data.bonusHp &&
            creature.data.bonusHp >= e.hp)
      );
      if (enchant) {
        // console.log(creature.data.class, 'enchant:', enchant.enchant);
        weapon.enchantment = enchant.enchant;
        if (
          enchant.enchant &&
          (!weapon.flags || !weapon.flags.includes(ItemFlagEnum.Magical))
        ) {
          weapon.flags = weapon.flags ?? [];
          weapon.flags.push(ItemFlagEnum.Magical);
        }
      }
    }
    if (
      weapon.header.projectile === undefined &&
      weapon.header.range === undefined &&
      creature.autoGenerate.meleeRange
    ) {
      const range = creatureSizes.find((c) => c.size === creature.data.size);
      if (range) {
        console.log(
          `${figureSet.arrowRight} Melee range: ${range.attackRange}`
        );
        weapon.header.range = range.attackRange;
      }
    }
  }

  private autogenerateHitPoints(p: {
    data: CreatureData;
    creature: Creature;
    parent?: CreatureData;
  }) {
    const level = p.data.level1;
    if (!level && !p.parent)
      throw new Error(`Can't generate hit points because level1 is unknown`);
    else if (!level) return;
    const constitutionTable: { [index: number]: number } = {
      15: 1,
      16: 2,
      17: 3,
      18: 4,
      19: 5,
      20: 5,
      21: 6,
      22: 6,
      23: 6,
      24: 7,
      25: 7,
    };
    const size: CreatureSize = p.data.size ?? p.parent?.size ?? "Tiny";
    let bonusHitPoints = p.data.bonusHp ?? p.parent?.bonusHp ?? 0;
    const constructBonusHP = p.creature.additionalData.immunities.includes(
      "construct"
    )
      ? (
          CONSTRUCT_BONUS_HIT_POINT.find((c) => c.size === size) as {
            size: CreatureSize;
            hp: number;
          }
        ).hp
      : 0;
    const isPlayerClass = PLAYER_CLASS_IDENTIFIERS.includes(
      p.data.class ?? p.parent?.class ?? "NO_CLASS"
    );
    const constitution = p.data.constitution ?? p.parent?.constitution ?? 10;
    const conHPPerLevel =
      GLOBAL_CONFIG.constitutionAffectHitPoint && !isPlayerClass
        ? constitutionTable[constitution] ?? 0
        : 0;
    let hpPerHD = 8;
    if (utils.hasImmunity(p.creature.additionalData.immunities, "ooze"))
      hpPerHD = 10;
    const baseHP = level * hpPerHD;
    const constitutionHP =
      constructBonusHP === 0 ? Math.min(level, 9) * conHPPerLevel : 0;
    const specialBonusHp = p.data.specialBonusHp ?? 0;
    if (constitutionHP > 0 || constructBonusHP > 0) {
      bonusHitPoints = 0;
    }
    let log = `${figureSet.arrowRight} Level: ${level}, hit points: ${baseHP} (base)`;
    if (constitutionHP > 0) log = `${log} + ${constitutionHP} (con)`;
    if (specialBonusHp > 0) log = `${log} + ${specialBonusHp} (special)`;
    if (constructBonusHP > 0) log = `${log} + ${constructBonusHP} (construct)`;
    p.data.hp =
      baseHP +
      constitutionHP +
      bonusHitPoints +
      specialBonusHp +
      constructBonusHP;
    console.log(`${log} = ${p.data.hp}`);
  }

  private autogenerateThac0(data: CreatureData, parent?: CreatureData) {
    let level = data.level1;
    if (!level && !parent)
      throw new Error(`Can't generate thac0 because level1 is unknown`);
    else if (!level) return;
    if (!!data.bonusHp && data.bonusHp >= 3) {
      level++;
      console.log(
        `${figureSet.arrowRight} calculating THAC0 as a level ${level} creature`
      );
    }
    const thac0Table: { [index: number]: number } = {
      1: 20,
      2: 19,
      3: 17,
      4: 17,
      5: 15,
      6: 15,
      7: 13,
      8: 13,
      9: 11,
      10: 11,
      11: 9,
      12: 9,
      13: 7,
      14: 7,
      15: 5,
      16: 5,
      17: 3,
      18: 3,
      19: 1,
      20: 1,
      21: -1,
      22: -1,
      23: -3,
      24: -3,
      25: -5,
      26: -5,
      27: -7,
      28: -8,
      29: -10,
      30: -10,
    };
    if (data.thac0 !== undefined)
      console.log(
        chalk.yellowBright(
          `${figureSet.warning} level: ${level}, hp bonus: ${data.bonusHp}, thac0: ${data.thac0}, calculated: ${thac0Table[level]}`
        )
      );
    if (data.thac0 === undefined) data.thac0 = thac0Table[level];
  }

  convertMovement(movement: number): number {
    return convertMovement(movement);
  }

  private autogenerateSavingThrows(data: CreatureData, parent?: CreatureData) {
    const level = data.level1;
    if (!level && !parent)
      throw new Error(`Can't generate saving throws because level1 is unknown`);
    else if (!level) return;
    const classe = data.class ?? parent?.class ?? "";
    let key: keyof typeof SAVING_THROWS = "fighter";
    if (classe === "DRUID" || classe === "CLERIC") key = "priest";
    else if (classe === "MAGE") key = "wizard";
    const table = SAVING_THROWS[key];
    const saves = table.find(
      (t) => level >= t.levels[0] && level <= t.levels[1]
    ) as {
      saveDeath: number;
      saveWand: number;
      savePolymorph: number;
      saveBreath: number;
      saveSpell: number;
    };
    if (key !== "fighter")
      console.log(
        `${
          figureSet.arrowRight
        } Level: ${level}, class: ${classe}, saving throws table: ${key}, ${JSON.stringify(
          saves
        )}`
      );
    data.saveDeath = saves.saveDeath;
    data.saveWand = saves.saveWand;
    data.savePolymorph = saves.savePolymorph;
    data.saveBreath = saves.saveBreath;
    data.saveSpell = saves.saveSpell;
  }

  getStrengthModifier(data: CreatureData): number {
    if (!data.strength || data.strength < 17) return 0;
    const table = [
      { str: 17, modifier: 1 },
      { str: 18, strEx: [0, 50], modifier: 1 },
      { str: 18, strEx: [51, 99], modifier: 2 },
      { str: 18, strEx: [100, 100], modifier: 3 },
      { str: 19, modifier: 3 },
      { str: 20, modifier: 3 },
      { str: 21, modifier: 4 },
      { str: 22, modifier: 4 },
      { str: 23, modifier: 5 },
      { str: 24, modifier: 6 },
      { str: 25, modifier: 7 },
    ];
    const item = table.find((t) => {
      const exStrength = data.exceptionalStrength ?? 0;
      const checkStr = t.str === data.strength;
      const checkStrEx =
        t.strEx === undefined ||
        (exStrength >= t.strEx[0] && exStrength <= t.strEx[1]);
      return checkStr && checkStrEx;
    }) as { modifier: number };
    return item.modifier;
  }

  getDexterityArmorClassBonus(data: CreatureData): number {
    if (!data.dexterity || data.dexterity < 15) return 0;
    const table = [
      { dex: 15, modifier: -1 },
      { dex: 16, modifier: -2 },
      { dex: 17, modifier: -3 },
      { dex: 18, modifier: -4 },
      { dex: 19, modifier: -4 },
      { dex: 20, modifier: -4 },
      { dex: 21, modifier: -5 },
      { dex: 22, modifier: -5 },
      { dex: 23, modifier: -5 },
      { dex: 24, modifier: -6 },
      { dex: 25, modifier: -6 },
    ];
    const item = table.find((t) => t.dex === data.dexterity) as {
      modifier: number;
    };
    return item.modifier;
  }

  getFinalArmorClass(base: BaseCreature) {
    if (base.data.dexterity === undefined || base.data.ac === undefined)
      throw new Error(`can't calculate final AC because of missing data`);
    return base.data.ac + this.getDexterityArmorClassBonus(base.data);
  }

  getAttacksPerRound(value: number): number {
    if (value === 0.5) {
      return 6;
    } else if (value === 1.5) {
      return 7;
    } else if (value === 2.5) {
      return 8;
    } else if (value === 3.5) {
      return 9;
    } else if (value === 4.5) {
      return 10;
    } else if (value < 6) return value;
    throw new Error(`Can't set more than 5 attacks per round: ${value}`);
  }
}

const creatureService = new CreatureService();
export default creatureService;
