import figureSet from "figures";
import { BaseCreature, Creature, CreatureAutoGenerate } from "../model/creature/creature";
import { CreatureData } from "../model/creature/data";
import { AttackPerRoundTable } from "../model/game-data/attack-per-round";
import { DexterityTable } from "../model/game-data/dexterity";
import { SAVING_THROWS } from "../model/game-data/saving-throws";
import { StrengthTable } from "../model/game-data/strength";
import { Thac0Table } from "../model/game-data/thac0";
import { ItemAbilityLocationEnum } from "../model/spell-item/effect.enums";
import { Weapon } from "../model/spell-item/spell-item";
import hitPointService from "./hit-point.service";
import itemService from "./item.service";
import kitService from "./kit.service";
import logService from "./log.service";
import weaponService from "./weapon.service";

class CreatureService {
  check(creature: Creature) {
    this.checkData({
      creature,
      base: creature,
      isAdjustment: false,
    });
    for (const a of creature.adjustments) {
      this.checkData({
        creature,
        base: a,
        isAdjustment: true,
      });
    }
  }

  checkData(p: { creature: Creature; base: BaseCreature; isAdjustment: boolean }): void {
    const data = p.base.data;
    logService.log(`base files: ${JSON.stringify(p.base.files)}`);
    kitService.applyKit(p.creature, p.isAdjustment ? p.base : undefined);
    this.checkDualWielding({ ...p, data });
    this.checkDexterityArmorClassBonus(data);
    this.checkMovement(p);
    this.transformAttackPerRound(p.creature.data);
    this.autogenerateData({
      data,
      autoGenerate: p.creature.autoGenerate,
      creature: p.creature,
      parent: p.isAdjustment ? p.creature.data : undefined,
    });
  }

  checkWeapons(creature: Creature) {
    for (const item of creature.items) {
      if (item.header?.location === ItemAbilityLocationEnum.Weapon) {
        weaponService.checkWeapon(creature, item as Weapon);
      }
    }
  }

  getAttacksPerRound(value: number): {
    apr: number;
    value: number;
    doubleApr: boolean;
  } {
    const item = AttackPerRoundTable.find((t) => t.apr === value);
    if (!item) {
      throw new Error(`attack per round not found in table: ${value}`);
    }
    return item;
  }

  getStrengthBonus(data: Partial<CreatureData>): {
    hit: number;
    damage: number;
  } {
    if (data.strength === undefined) return { hit: 0, damage: 0 };
    const exStrength = data.exceptionalStrength ?? 0;
    const item = StrengthTable.find((t) => {
      const checkStr = t.str === data.strength;
      const checkStrEx =
        t.strEx === undefined || (exStrength >= t.strEx[0] && exStrength <= t.strEx[1]);
      return checkStr && checkStrEx;
    });
    if (!item) {
      throw new Error(`strength not found in table: ${data.strength}/${exStrength}`);
    }
    return item;
  }

  getFinalArmorClass(base: BaseCreature) {
    if (base.data.dexterity === undefined || base.data.ac === undefined)
      throw new Error(`can't calculate final AC because of missing data`);
    return base.data.ac + this.getDexterityArmorClassBonus(base.data);
  }

  private checkDualWielding(p: {
    creature: Creature;
    base: BaseCreature;
    isAdjustment: boolean;
    data: CreatureData;
  }): void {
    if (!p.isAdjustment && this.hasOffhandWeapon(p.creature)) {
      logService.log(`${figureSet.arrowRight} dual wielding detected`);
      p.creature.attack.dualWielding = true;
    }
    if (!p.creature.attack.dualWielding || p.isAdjustment) return;
    if (!p.data.apr) {
      throw new Error("Attacks per round need to be set for dual wielding flag");
    }
    p.data.apr -= 1;
    logService.log(`${figureSet.arrowRight} setting dual wield: ${p.data.apr} APR +1 offhand`);
  }

  private hasOffhandWeapon(creature: Creature): boolean {
    const equippedItem = creature.data.items.equipped.find((i) =>
      itemService.isSlotIncluded([i], "SHIELD"),
    );
    const item = creature.items.find((i) => i.file === equippedItem?.file);
    return item?.header?.location === ItemAbilityLocationEnum.Weapon;
  }

  private checkMovement(p: { creature: Creature; base: BaseCreature; isAdjustment: boolean }) {
    const data = p.base.data;
    if (!data.movement && !p.isAdjustment) throw new Error("movement not set !");
    const movement = data.movement ?? p.creature.data.movement;
    if (data.kit === "BARBARIAN") {
      data.movement = movement.clone();
      data.movement.bonus += 2;
      logService.log(
        `${figureSet.arrowRight} movement increased to ${data.movement.getGameValue()} (barbarian): `,
      );
    }
  }

  private transformAttackPerRound(data?: Partial<CreatureData>) {
    if (!data?.apr) return;
    const apr = this.getAttacksPerRound(data.apr);
    data.apr = apr.value;
    if (data.movement) {
      data.movement.hasImprovedHaste = apr.doubleApr;
    }
  }

  private autogenerateData(p: {
    autoGenerate: CreatureAutoGenerate;
    data: Partial<CreatureData>;
    creature: Creature;
    parent: CreatureData | undefined;
  }) {
    if (p.autoGenerate.hitPoints && p.data.hp === undefined) {
      this.autogenerateHitPoints({
        data: p.data,
        creature: p.creature,
        parent: p.parent,
      });
    }
    if (p.autoGenerate.thac0 && p.data.thac0 === undefined) {
      this.autogenerateThac0(p.data, p.parent);
    }
    if (p.data.saveBreath === undefined) {
      this.autogenerateSavingThrows({
        data: p.data,
        parent: p.parent,
        options: p.autoGenerate.savingThrows,
      });
    }
  }

  private autogenerateHitPoints(p: {
    data: Partial<CreatureData>;
    creature: Creature;
    parent?: CreatureData;
  }) {
    const value = hitPointService.getHitPoints(p);
    if (value) p.data.hp = value;
  }

  private autogenerateThac0(data: Partial<CreatureData>, parent?: CreatureData) {
    let level = data.level1?.pnpValue;
    if (!level && !parent) throw new Error(`Can't generate thac0 because level1 is unknown`);
    else if (!level) return;
    if (!!data.bonusHp && data.bonusHp >= 3) {
      level++;
      logService.log(`${figureSet.arrowRight} calculating THAC0 as a level ${level} creature`);
    }
    const item = Thac0Table.find((t) => t.level === level);
    if (!item) {
      throw new Error(`thac0 not found in table for level ${level}`);
    }
    if (data.thac0 !== undefined)
      logService.warn(
        `${figureSet.warning} level: ${level}, hp bonus: ${data.bonusHp ?? 0}, thac0: ${data.thac0}, calculated: ${item.thac0}`,
      );
    else data.thac0 = item.thac0;
  }

  convertMovement(movement: number): number {
    // aVENGER was using a coef of 0.75
    return Math.round(movement * 0.8);
  }

  private getSavingThrows(p: Exclude<CreatureAutoGenerate["savingThrows"], undefined>) {
    let key: keyof typeof SAVING_THROWS = "fighter";
    if (p.classe === "DRUID" || p.classe === "CLERIC") key = "priest";
    else if (p.classe === "MAGE") key = "wizard";
    const table = SAVING_THROWS[key];
    const saves = table.find((t) => p.level >= t.levels[0] && p.level <= t.levels[1]) as {
      saveDeath: number;
      saveWand: number;
      savePolymorph: number;
      saveBreath: number;
      saveSpell: number;
    };
    if (key !== "fighter")
      logService.log(
        `${figureSet.arrowRight} Level: ${p.level}, class: ${
          p.classe ?? "none"
        }, saving throws table: ${key}, ${JSON.stringify(saves)}`,
      );
    return {
      saveDeath: saves.saveDeath - (p.bonus?.saveDeath ?? 0),
      saveWand: saves.saveWand - (p.bonus?.saveWand ?? 0),
      savePolymorph: saves.savePolymorph - (p.bonus?.savePolymorph ?? 0),
      saveBreath: saves.saveBreath - (p.bonus?.saveBreath ?? 0),
      saveSpell: saves.saveSpell - (p.bonus?.saveSpell ?? 0),
    };
  }

  private autogenerateSavingThrows({
    data,
    parent,
    options,
  }: {
    data: Partial<CreatureData>;
    parent?: CreatureData;
    options: CreatureAutoGenerate["savingThrows"];
  }) {
    const level = data.level1;
    if (!level && !parent)
      throw new Error(`Can't generate saving throws because level1 is unknown`);
    else if (!level) return;
    const classe = data.class ?? parent?.class;
    const saves = this.getSavingThrows({
      level: options?.level ?? level.pnpValue,
      classe: options?.classe ?? classe,
      bonus: options?.bonus,
    });
    data.saveDeath = saves.saveDeath;
    data.saveWand = saves.saveWand;
    data.savePolymorph = saves.savePolymorph;
    data.saveBreath = saves.saveBreath;
    data.saveSpell = saves.saveSpell;
  }

  private checkDexterityArmorClassBonus(data: Partial<CreatureData>) {
    if (data.dexterity === undefined || data.ac === undefined) return;
    const bonus = this.getDexterityArmorClassBonus(data);
    if (bonus) {
      logService.log(
        `${figureSet.arrowRight} AC reduced to ${data.ac - bonus} (was ${
          data.ac
        }) because of dexterity bonus (${bonus})`,
      );
      data.ac -= bonus;
    }
  }

  private getDexterityArmorClassBonus(data: Partial<CreatureData>): number {
    if (data.dexterity === undefined) return 0;
    const item = DexterityTable.find((t) => t.dex === data.dexterity);
    if (!item) {
      throw new Error(`dexterity not found in table: ${data.dexterity}`);
    }
    return item.ac;
  }
}

const creatureService = new CreatureService();
export default creatureService;
