export type RawBonusHPHealFlag = "RaiseDead" | "RemoveAllEffects";

export type RawInvisibilityType = "Normal" | "Improved" | "Weak";

export type ItemSlot =
  | "HELMET"
  | "ARMOR"
  | "SHIELD"
  | "GLOVES"
  | "LRING"
  | "RRING"
  | "AMULET"
  | "BELT"
  | "BOOTS"
  | "WEAPON1"
  | "WEAPON2"
  | "WEAPON3"
  | "WEAPON4"
  | "QUIVER1"
  | "QUIVER2"
  | "QUIVER3"
  | "QUIVER4"
  | "CLOAK"
  | "QITEM1"
  | "QITEM2"
  | "QITEM3";

export const WEAPON_SLOTS: ItemSlot[] = [
  "WEAPON1",
  "WEAPON2",
  "WEAPON3",
  "WEAPON4",
];

export type RawProjectileExplosionEffect =
  | "FIRE"
  | "CLOUD"
  | "CLOUDKILL"
  | "STORM"
  | "GREASE"
  | "WEB"
  | "METEOR"
  | "WILTING"
  | "WEIRD"
  | "ENTANGLE"
  | "COLORSPRAY"
  | "CONECOLD"
  | "HOLYSMITE"
  | "UNHOLYSMITE"
  | "PRISMATICSPRAY"
  | "DRAGONFIRE"
  | "STORMOFVENGEANCE"
  | "DRAGONPURPLEFIRE"
  | "DRAGONACID"
  | "CUSTOM"
  | "NONE";

export type RawProjectileAnimation =
  | "FIRE_RING"
  | "FIRE_RING_BRIGHT"
  | "CHUNKS"
  | "EXPLODING_ARM"
  | "EXPLODING_HEAD"
  | "EXPLODING_FOOT"
  | "EXPLODING_TORSO"
  | "EXPLODING_LEG"
  | "SMOKE_PUFF_LARGE"
  | "SMOKE_PUFF_SMALL"
  | "TRAP_SKULL"
  | "TRAP_GLYPH"
  | "CLOUD_TRAVEL"
  | "CLOUD_STATIC"
  | "STORM_TRAVEL"
  | "STORM_STATIC"
  | "GREASE_TRAVEL"
  | "GREASE_STATIC"
  | "WEB_TRAVEL"
  | "WEB_STATIC"
  | "NULL_ANIMATION";

export type RawAreaProjectile =
  | "TrapVisible"
  | "TriggeredByInanimateObjects"
  | "TriggeredByCondition"
  | "DelayedTrigger"
  | "UseSecondaryProjectile"
  | "UseFragmentGraphics"
  | "AffectOnlyEnemies"
  | "AffectOnlyAllies"
  | "MageLevelDuration"
  | "ClericLevelDuration"
  | "DrawAnimation"
  | "Coneshaped"
  | "IgnoreLOS"
  | "DelayedExplosion"
  | "SkipFirstCondition"
  | "SingleTarget";

export type RawProjectileType = "AreaOfEffect" | "NoBAM" | "SingleTarget";

export type RawProjectileBehavior =
  | "ShowSparkle"
  | "UseHeight"
  | "LoopFireSound"
  | "LoopImpactSound"
  | "IgnoreCenter"
  | "DrawAsBackground"
  | "AllowSavingGame"
  | "LoopSpreadAnimation";

export type RawParticleColor =
  | "None"
  | "Black"
  | "Blue"
  | "Chromatic"
  | "Gold"
  | "Green"
  | "Purple"
  | "Red"
  | "White"
  | "Ice"
  | "Stone"
  | "Magenta"
  | "Orange";

export type RawProjectileExtendedFlags =
  | "BounceFromWalls"
  | "PassTarget"
  | "DrawCenterVvcOnce"
  | "HitImmediately"
  | "FaceTarget"
  | "CurvedPathUnknownStillNotImplementedOnEeGames"
  | "StartRandomFrame"
  | "Pillar"
  | "SemiTransparentTrailPuffVef"
  | "TintedTrailPuffVef"
  | "MultipleProjectiles"
  | "DefaultSpellOnMissed"
  | "FallingPath"
  | "Comet"
  | "LinedUpAreaOfEffect"
  | "RectangularAreaOfEffect"
  | "DrawBehindTarget"
  | "CastingGlowEffect"
  | "TravelDoor"
  | "StopFadeAfterHit"
  | "DisplayMessage"
  | "RandomPath"
  | "StartRandomSequence"
  | "ColourPulseOnHit"
  | "TouchProjectile"
  | "NegateFirstCreatureTarget"
  | "NegateSecondCreatureTarget"
  | "UseEitherIds"
  | "DelayedPayload"
  | "LimitedPathCount"
  | "IwdStyleCheck"
  | "CasterAffected";

export type RawBamProjectileFlags =
  | "EnableBamColouring"
  | "EnableSmoke"
  | "ColoredSmoke"
  | "EnableAreaLightingUsage"
  | "EnableAreaHeightUsage"
  | "EnableShadow"
  | "EnableLightSpot"
  | "EnableBrightenFlags"
  | "LowLevelBrighten"
  | "HighLevelBrighten";

export type RawCastSpellOnConditionType =
  | "HitBy([ANYONE])"
  | "See([EVILCUTOFF])"
  | "HPPercentLT(Myself,50)"
  | "HPPercentLT(Myself,25)"
  | "HPPercentLT(Myself,10)"
  | "StateCheck(Myself,STATE_HELPLESS)"
  | "StateCheck(Myself,STATE_POISONED)"
  | "AttackedBy([ANYONE])"
  | "PersonalSpaceDistance([ANYONE],4)"
  | "PersonalSpaceDistance([ANYONE],10)"
  | "Delay(Extra)"
  | "TookDamage()"
  | "Killed([ANYONE])"
  | "TimeOfDay(Extra)"
  | "PersonalSpaceDistance([ANYONE],Extra)"
  | "StateCheck([ANYONE],Extra)"
  | "Die()"
  | "Died([ANYONE])"
  | "TurnedBy([ANYONE])"
  | "HPLT(Myself,Extra)"
  | "HPPercentLT(Myself,Extra)"
  | "CheckSpellState(Myself,Extra)";

export type RawDispelEffectType =
  | "AlwaysDispel"
  | "UseCasterLevel"
  | "UseSpecificLevel";

export type RawDispelEffectWeaponType =
  | "AlwaysDispel"
  | "DoNotDispel"
  | "ChanceOfDispel";

export type RawCastSpellOnConditionTarget =
  | "Myself"
  | "LastHitter"
  | "NearestEnemy"
  | "Nearest";

export type RawTranslucencyType = "DrawInstantly" | "FadeIn" | "FadeOut";

export type RawProtectionFromWeaponsType =
  | "Enchanted"
  | "Magical"
  | "NonMagical"
  | "Silver"
  | "NonSilver"
  | "NonSilverNonMagical"
  | "TwoHanded"
  | "OneHanded"
  | "Cursed"
  | "NonCursed"
  | "ColdIron"
  | "NonColdIron";

export type RawProficiencyType =
  | "PROFICIENCYBASTARDSWORD"
  | "PROFICIENCYLONGSWORD"
  | "PROFICIENCYSHORTSWORD"
  | "PROFICIENCYAXE"
  | "PROFICIENCYTWOHANDEDSWORD"
  | "PROFICIENCYKATANA"
  | "PROFICIENCYSCIMITARWAKISASHININJATO"
  | "PROFICIENCYDAGGER"
  | "PROFICIENCYWARHAMMER"
  | "PROFICIENCYSPEAR"
  | "PROFICIENCYHALBERD"
  | "PROFICIENCYFLAILMORNINGSTAR"
  | "PROFICIENCYMACE"
  | "PROFICIENCYQUARTERSTAFF"
  | "PROFICIENCYCROSSBOW"
  | "PROFICIENCYLONGBOW"
  | "PROFICIENCYSHORTBOW"
  | "PROFICIENCYDART"
  | "PROFICIENCYSLING"
  | "PROFICIENCYBLACKJACK"
  | "PROFICIENCY2HANDED"
  | "PROFICIENCYSWORDANDSHIELD"
  | "PROFICIENCYSINGLEWEAPON"
  | "PROFICIENCY2WEAPON"
  | "PROFICIENCYCLUB";

export type RawColor =
  | "RustTintedBlack"
  | "DarkBronze"
  | "DarkGold"
  | "LightGold"
  | "Auburn"
  | "MediumSilver"
  | "DarkSilver"
  | "LightMetallicGreen"
  | "DarkMuddishBrown"
  | "LightMuddishBrown"
  | "LightPureGold"
  | "LightRoseRed"
  | "LightCarnationPink"
  | "LightPureSilver"
  | "DarkPureSilver"
  | "EasterGreen"
  | "SilverGold"
  | "PaleBlue"
  | "Blue"
  | "DarkRoseRed"
  | "DarkMoldyGreen"
  | "DarkIronGrey"
  | "DarkBrown"
  | "LightCopper"
  | "BrownGold"
  | "DarkPureGold"
  | "Wood"
  | "Silver"
  | "GhostlyGreyishSilver"
  | "RedTintedBlack"
  | "LightIronGrey"
  | "LightSeaBlue"
  | "DarkSeaGreen"
  | "DarkMetallicPurple"
  | "GhostlyGreen"
  | "DarkGhostlyPink"
  | "LightDirtyYellow"
  | "DarkDirtyYellow"
  | "LightDirtBrown"
  | "DarkDirtBrown"
  | "DarkDirtyCopper"
  | "MediumBrown"
  | "LightBlurryGrey"
  | "DarkDirtishBrown"
  | "LightMagenta"
  | "DarkMagenta"
  | "LightRed"
  | "DarkRed"
  | "LightBronze"
  | "DarkRust"
  | "DarkYellow"
  | "DarkOliveGreen"
  | "LightGreen"
  | "Green"
  | "DarkGreen"
  | "Turquoise"
  | "DarkSeaBlue"
  | "LightBlue"
  | "DarkBlue"
  | "LightPurple"
  | "DarkPurple"
  | "Lavender"
  | "DarkLavender"
  | "LightGrey"
  | "DarkGrey"
  | "ReallyDarkGrey"
  | "FadedBlack"
  | "ShinyGold"
  | "ShinyBlue"
  | "ShinyGreen"
  | "LightMetallicRed"
  | "FrostBlue"
  | "SteelGrey"
  | "ChristmasGreen"
  | "PureWhite"
  | "PureBlack"
  | "PureRed"
  | "PureGreen"
  | "PureBlue"
  | "LightSilver"
  | "SaturatedBronze"
  | "FadedGold"
  | "DarkMetallicBlue"
  | "DarkAdamantiteGrey"
  | "Peachy"
  | "PureGold"
  | "ChromeGreen"
  | "DarkPoopyBrown"
  | "ChromePink"
  | "MetallicPink"
  | "MoldyGold"
  | "DarkChoclate"
  | "LightChocolate"
  | "DarkCementGrey"
  | "Rhubarb"
  | "LightDirtishBrown"
  | "ChromeBlue"
  | "LightMintyBlue"
  | "LeafGreen"
  | "GoldenGold"
  | "DarkAshGrey"
  | "MetallicRed"
  | "SeaBlue"
  | "ForestGreen"
  | "DarkChromePurple"
  | "White"
  | "PalePink"
  | "Khaki"
  | "PinkishGrey"
  | "Terracotta"
  | "Ash"
  | "BurntSienna"
  | "Seafoam"
  | "Fog"
  | "YetAnotherBrown"
  | "Sunkissed"
  | "MediumOrchid"
  | "DarkOrchid"
  | "DarkerOrchid"
  | "DarkestOrchid"
  | "LightTeal"
  | "DarkTeal"
  | "LightRoyalBlue"
  | "DarkRoyalBlue"
  | "LightNavyBlue"
  | "DarkNavyBlue";

export type RawItemCategory =
  | "Miscellaneous"
  | "Amulets"
  | "ArmorSlot"
  | "Belts"
  | "Boots"
  | "Arrows"
  | "Bracers"
  | "Headgear"
  | "Rings"
  | "Shields"
  | "Bullets"
  | "Bows"
  | "Daggers"
  | "Maces"
  | "Slings"
  | "SmallSwords"
  | "LargeSwords"
  | "Hammers"
  | "MorningStars"
  | "Flails"
  | "Darts"
  | "Axes"
  | "Quarterstaves"
  | "Crossbows"
  | "HandToHandWeapons"
  | "Spears"
  | "Halberds"
  | "Bolts"
  | "CloaksAndRobes"
  | "Wands"
  | "Bucklers"
  | "Clubs"
  | "LargeShields"
  | "MediumShields"
  | "SmallShields"
  | "Greatswords"
  | "LeatherArmor"
  | "StuddedLeather"
  | "ChainMail"
  | "SplintMail"
  | "PlateMail"
  | "FullPlate"
  | "HideArmor"
  | "Robes"
  | "ScaleMail"
  | "BastardSwords"
  | "Hats"
  | "Gloves";

export type RawBerserkType = "Combat" | "Always";

export type RawKillTargetDeathType =
  | "Burning"
  | "Crushed"
  | "Normal"
  | "Exploding"
  | "Stoned"
  | "Freezing"
  | "ExplodingStoned"
  | "ExplodingFreezing"
  | "Electrified"
  | "Disintegration"
  | "ExplodingNoDrop";

export type RawCharmType =
  | "NeutralCharm"
  | "HostileCharm"
  | "NeutralDireCharm"
  | "HostileDireCharm"
  | "Controlled"
  | "ThrullCharm"
  | "NeutralCharmNoFeedback"
  | "HostileCharmNoFeedback"
  | "NeutralDomination"
  | "HostileDomination"
  | "ControlledNoFeedback"
  | "ThrullCharmNoFeedback";

export type RawDiseaseType =
  | "OneDamagePerSecond"
  | "AmoundDamagePerRound"
  | "AmountDamagePerSecond"
  | "OneDamagePerAmountSeconds"
  | "ReduceStrengthByAmount"
  | "ReduceDexterityByAmount"
  | "ReduceConstitutionByAmount"
  | "ReduceIntelligenceByAmount"
  | "ReduceWisdomByAmount"
  | "ReduceCharismaByAmount"
  | "SlowEffect"
  | "MoldTouchSingle"
  | "MoldTouchDecrement"
  | "Contagion";

export type RawRegenerationType =
  | "AmountHPperSecond"
  | "AmountHPpercentagePerSecond"
  | "AmountHPperSecondBis"
  | "OneHPperAmountSeconds";

export type RawItemAnimation =
  | "LeatherArmor"
  | "Chainmail"
  | "PlateMail"
  | "Robe1"
  | "Robe2"
  | "Robe3"
  | "Axe"
  | "Shortbow"
  | "Bow"
  | "Crossbow"
  | "SmallShield1"
  | "MediumShield1"
  | "LargeShield1"
  | "MediumShield2"
  | "SmallShield2"
  | "LargeShield2"
  | "LargeShield3"
  | "MediumShield3"
  | "Club"
  | "Buckler"
  | "SmallShield"
  | "MediumShield"
  | "LargeShield"
  | "Dagger"
  | "Flail1"
  | "Flail2"
  | "FlamingSwordBlue"
  | "Flail3"
  | "Flail"
  | "FlamingSword"
  | "GlowingStaff"
  | "HelmetSmallVerticalHorns"
  | "HelmetLargeHorizontalHorns"
  | "HelmetFeatherWings"
  | "HelmetTopPlume"
  | "HelmetDragonWings"
  | "HelmetFeatherSideburns"
  | "HelmetLargeCurvedHorns"
  | "Helmet8"
  | "Halberd"
  | "Helmet9"
  | "Helmet10"
  | "Helmet11"
  | "Helmet12"
  | "Helmet13"
  | "Helmet14"
  | "Helmet15"
  | "Helmet16"
  | "Helmet17"
  | "Helmet18"
  | "Helmet19"
  | "Circlet"
  | "Helmet20"
  | "Mace"
  | "MorningStar"
  | "QuarterStaff1"
  | "QuarterStaff2"
  | "QuarterStaff3"
  | "QuarterStaffMetal"
  | "BastardSword"
  | "LongSword"
  | "TwoHandedSword"
  | "Katana"
  | "Scimitar"
  | "Sling"
  | "Spear"
  | "ShortSword"
  | "WarHammer"
  | "Wings";

export type RawEffectTeleportType =
  | "Default"
  | "SourceToTarget"
  | "ReturnToSavedLocation"
  | "ExchangedSourceAndTarget";

export type RawEffectHasteType = "NormalHaste" | "ImprovedHaste" | "WeakHaste";

export type CreatureSize =
  | "Tiny"
  | "Small"
  | "Medium"
  | "Large"
  | "Huge"
  | "Gargantuan"
  | "Colossal";

export type RawEffectColorLocation =
  | "ArmorGreyBeltAmulet"
  | "ArmorTealMinorColor"
  | "ArmorPinkMajorColor"
  | "ArmorYellowSkinColor"
  | "ArmorRedStrapLeather"
  | "ArmorBlueArmorTrimming"
  | "ArmorGreenHair"
  | "WeaponGreyHeadBladeStaffMajor"
  | "WeaponTealStaffMinor"
  | "WeaponPink"
  | "WeaponYellow"
  | "WeaponRedGripStaffMinor"
  | "WeaponBlueHeadBladeMinor"
  | "WeaponGreen"
  | "ShieldGreyHub"
  | "ShieldTealInterior"
  | "ShieldPinkPanel"
  | "ShieldYellow"
  | "ShieldRedGrip"
  | "ShieldBlueBodyTrim"
  | "ShieldGreen"
  | "HelmetGreyWings"
  | "HelmetTealDetail"
  | "HelmetPinkPlume"
  | "HelmetYellow"
  | "HelmetRedFace"
  | "HelmetBlueExterior"
  | "HelmetGreen"
  | "CharacterColor";

export type RawItemAbilityType = "Melee" | "Ranged" | "Magical";

export type RawEffectCastSpellType =
  | "NormalCastingNonInterruptible"
  | "CastInstantlyAtCasterLevel"
  | "CastInstantlyAtSpecifiedLevel";

export type RawEffectIDSFile =
  | "EA"
  | "GENERAL"
  | "RACE"
  | "CLASS"
  | "SPECIFIC"
  | "GENDER"
  | "ALIGN"
  | "KIT";

export type RawItemAbilityLocation =
  | "None"
  | "Weapon"
  | "Spell"
  | "Item"
  | "Ability";

export type RawItemAbilityTarget =
  | "None"
  | "LivingActor"
  | "Inventory"
  | "DeadActor"
  | "AnyPointWithinRange"
  | "Caster";

export type RawItemAbilitySecondaryType =
  | "None"
  | "SpellProtections"
  | "SpecificProtections"
  | "IllusionaryProtections"
  | "MagicAttack"
  | "DivinationAttack"
  | "Conjuration"
  | "CombatProtections"
  | "Contingency"
  | "Battleground"
  | "OffensiveDamage"
  | "Disabling"
  | "Combination";

export type RawAbilityDamageType =
  | "None"
  | "Piercing"
  | "Crushing"
  | "Slashing"
  | "Missile"
  | "Fist"
  | "PiercingOrCrushing"
  | "PiercingOrSlashing"
  | "CrushingOrSlashing"
  | "BluntMissile";

export type RawSpellType =
  | "Special"
  | "Wizard"
  | "Priest"
  | "Psionic"
  | "Innate"
  | "BardSong";

export type RawItemFlag =
  | "CriticalItem"
  | "TwoHanded"
  | "Droppable"
  | "Displayable"
  | "Cursed"
  | "NotCopyable"
  | "Magical"
  | "LeftHanded"
  | "Silver"
  | "ColdIron"
  | "OffHanded"
  | "Conversable";

export type RawItemAbilityFlag =
  | "AddStrengthBonus"
  | "Breakable"
  | "DamageStrengthBonus"
  | "Thac0StrengthBonus"
  | "BreakSanctuary"
  | "Hostile"
  | "RechargeAfterResting"
  | "BypassArmor";

export type RawSpellFlag =
  | "BreakSanctuary"
  | "Hostile"
  | "NoLOSRequired"
  | "AllowSpotting"
  | "OutdoorsOnly"
  | "CanTargetInvisible"
  | "CastableWhenSilenced";

export type RawEffectTarget =
  | "None"
  | "Self"
  | "PresetTarget"
  | "Party"
  | "Everyone"
  | "EveryoneExceptParty"
  | "CasterGroup"
  | "TargetGroup"
  | "EveryoneExceptSelf"
  | "OriginalCaster";

export type RawEffectTiming =
  | "InstantLimited"
  | "InstantPermanentUntilDeath"
  | "InstantWhileEquipped"
  | "DelayLimited"
  | "DelayPermanent"
  | "DelayWhileEquipped"
  | "LimitedAfterDuration"
  | "PermanentAfterDuration"
  | "EquippedAfterDuration"
  | "InstantPermanent"
  | "InstantLimitedTicks";

export type RawEffectDispelResistance =
  | "NaturalNonMagical"
  | "DispelNotBypassResistance"
  | "NotDispelBypassResistance"
  | "DispelBypassResistance";

export type RawEffectDamageType =
  | "Crushing"
  | "Acid"
  | "Cold"
  | "Electricity"
  | "Fire"
  | "Piercing"
  | "Poison"
  | "Magic"
  | "Missile"
  | "Slashing"
  | "MagicFire"
  | "MagicCold"
  | "Stunning";

export type RawEffectDamageMode =
  | "Normal"
  | "SetToValue"
  | "SetToPercent"
  | "ReduceByPercentage";

export type RawSaveType =
  | "Spell"
  | "Breath"
  | "ParalyzePoisonDeath"
  | "RodStaffWand"
  | "PetrifyPolymorph";

export type RawEffectFlags =
  | "TransferHPToCasterCumulative"
  | "TransferHPToTargetCumulative"
  | "FistDamageOnly"
  | "TransferHPToCasterNonCumulative"
  | "TransferHPToTargetNonCumulative"
  | "SuppressDamageFeedback"
  | "LimitToCurrentHPOfTargetMinusMinHP"
  | "LimitToCurrentMaxHPDifferenceOfCaster"
  | "SaveForHalf"
  | "FailForHalf"
  | "DoesNotWakeSlepeers";

export type RawEffectVisualEffectLocation =
  | "OverTargetUnattached"
  | "OverTargetAttached"
  | "AtTargetPoint";

export type RawEffectStatisticModifier =
  | "Increment"
  | "Set"
  | "Percentage"
  | "Special";

export type RawEffectModifierType =
  | "Increment"
  | "Set"
  | "SetPercentOf"
  | "MultiplyPercent";

export type RawLightingEffectTarget = "SpellTarget" | "TargetPoint";

export type RawLightingEffect =
  | "NecromancyAir"
  | "NecromancyEarth"
  | "NecromancyWater"
  | "AlterationAir"
  | "AlterationEarth"
  | "AlterationWater"
  | "EnchantmentAir"
  | "EnchantmentEarth"
  | "EnchantmentWater"
  | "AbjurationAir"
  | "AbjurationEarth"
  | "AbjurationWater"
  | "IllusionAir"
  | "IllusionEarth"
  | "IllusionWater"
  | "ConjureAir"
  | "ConjureEarth"
  | "ConjureWater"
  | "InvocationAir"
  | "InvocationEarth"
  | "InvocationWater"
  | "DivinationAir"
  | "DivinationEarth"
  | "DivinationWater"
  | "MushroomFire"
  | "MushroomGray"
  | "MushroomGreen"
  | "ShaftFire"
  | "ShaftLight"
  | "ShaftWhite"
  | "HitDoor"
  | "HitFingerOfDeath";

export type RawEffectBonusTo =
  | "AllWeapons"
  | "CrushingWeapons"
  | "MissileWeapons"
  | "PiercingWeapons"
  | "SlashingWeapons"
  | "SetBaseArmorClassToValue";

export type RawPortraitIcon =
  | "Charm"
  | "DireCharm"
  | "RigidThinking"
  | "Confused"
  | "Berserk"
  | "Intoxicated"
  | "Poisoned"
  | "Diseased"
  | "Blind"
  | "ProtectionFromEvil"
  | "ProtectionFromPetrification"
  | "ProtectionFromMissiles"
  | "MagicArmor"
  | "Held"
  | "Sleep"
  | "Shielded"
  | "ProtectionFromFire"
  | "Blessed"
  | "Chant"
  | "FreeAction"
  | "Barkskin"
  | "Strength"
  | "Heroism"
  | "Invulnerable"
  | "ProtectionFromAcid"
  | "ProtectionFromCold"
  | "ResistFireCold"
  | "ProtectionFromElectricity"
  | "ProtectionFromMagic"
  | "ProtectionFromUndead"
  | "ProtectionFromPoison"
  | "NonDetectable"
  | "GoodLuck"
  | "BadLuck"
  | "Silenced"
  | "Cursed"
  | "Panic"
  | "ResistFear"
  | "Haste"
  | "Fatigue"
  | "BardSong"
  | "Slow"
  | "Regenerate"
  | "Domination"
  | "Hopelessness"
  | "GreaterMalison"
  | "SpiritArmor"
  | "Chaos"
  | "Feebleminded"
  | "DefensiveHarmony"
  | "ChampionStrength"
  | "Dying"
  | "MindShield"
  | "EnergyDrain"
  | "PolymorphSelf"
  | "Stun"
  | "Regeneration"
  | "Perception"
  | "MasterThievery"
  | "EnergyDrain2"
  | "HolyPower"
  | "CloakOfFear"
  | "IronSkins"
  | "MagicResistance"
  | "RighteousMagic"
  | "SpellTurning"
  | "RepulsingUndead"
  | "SpellDeflection"
  | "FireshieldRed"
  | "FireshieldBlue"
  | "ProtectionFromNormalWeapon"
  | "ProtectionFromMagicWeapon"
  | "TenserTransformation"
  | "SpellShield"
  | "Mislead"
  | "ContingencyActive"
  | "ProtectedFromTheElements"
  | "ProjectedImage"
  | "Maze"
  | "Imprisonment"
  | "Stoneskin"
  | "KAI"
  | "CalledShot"
  | "SpellFailure"
  | "OffensiveSpin"
  | "DefensiveSpin"
  | "IntelligenceDrainedByMindFlayer"
  | "Regenerating"
  | "InDialog"
  | "InStore"
  | "NegativePlaneProtection"
  | "AbilityScoreDrained"
  | "SpellSequencerActive"
  | "ProtectedFromEnergy"
  | "Magnetized"
  | "AbleToPoisonWeapons"
  | "SettingTrap"
  | "GlassDust"
  | "BladeBarrier"
  | "DeathWard"
  | "Doom"
  | "Decaying"
  | "Acid"
  | "Vocalize"
  | "Mantle"
  | "MiscastMagic"
  | "MagicResistanceLowered"
  | "SpellImmunity"
  | "TrueSeeing"
  | "DetectingTrapsIllusions"
  | "ImprovedHaste"
  | "SpellTrigger"
  | "Deaf"
  | "Enfeebled"
  | "Infravision"
  | "Friends"
  | "ShieldOfTheArchons"
  | "SpellTrap"
  | "AbsoluteImmunity"
  | "ImprovedMantle"
  | "Farsight"
  | "GlobeOfInvulnerability"
  | "MinorGlobeOfInvulnerability"
  | "ProtectedFromMagicalEnergy"
  | "Polymorphed"
  | "OtilukeResilientSphere"
  | "Nauseated"
  | "GhostArmor"
  | "Glitterdust"
  | "Webbed"
  | "Unconscious"
  | "MentalCombat"
  | "PhysicalMirror"
  | "RepulseUndead"
  | "ChaoticCommands"
  | "DrawUponHolyMight"
  | "StrengthOfOne"
  | "Bleeding"
  | "Rage"
  | "BoonOfLathander"
  | "StormShield"
  | "Enraged"
  | "StunningBlow"
  | "QuiveringPalm"
  | "Entangled"
  | "Grease"
  | "Smite"
  | "Hardiness"
  | "PowerAttack"
  | "WhirlwindAttack"
  | "GreaterWhirlwindAttack"
  | "MagicFlute"
  | "CriticalStrike"
  | "GreaterDeathblow"
  | "Deathblow"
  | "AvoidDeath"
  | "Assassination"
  | "Evasion"
  | "GreaterEvasion"
  | "ImprovedAlacrity"
  | "AuraOfFlamingDeath"
  | "GlobeOfBlades"
  | "ImprovedChaosShield"
  | "ChaosShield"
  | "FireElementalTransformation"
  | "EarthElementalTransformation"
  | "EnchantedWeapon"
  | "SpiritWard"
  | "EtherGate"
  | "ShamanicDance"
  | "ChaosOfBattle"
  | "Unknown"
  | "Repulsion"
  | "IncreasedMovementRate"
  | "ImmunityAbjuration"
  | "ImmunityConjuration"
  | "ImmunityDivination"
  | "ImmunityEnchantment"
  | "ImmunityIllusion"
  | "ImmunityEvocation"
  | "ImmunityNecromancy"
  | "ImmunityAlteration"
  | "FlamingFists"
  | "FrozenFist"
  | "ArmorOfFaith";

export type RawPoisonType =
  | "OneDamagePerSecond"
  | "OneDamagePerSecondBis"
  | "AmountDamagePerSecond"
  | "OneDamagePerAmountSecond";
