/**
 * Returns column and row index of the 2DA entry that matches the specified search text of the given 2da file.
 */
DEFINE_PATCH_FUNCTION GET_2DA_ENTRY_OF
INT_VAR
  row_match = "-1"  // neg. value indicates to search all rows
  col_match = "-1"  // neg. value indicates to search all columns
STR_VAR
  file          = ~~  // the 2da filename
  entry_match   = ~~  // search text
RET
  row col
BEGIN
  INNER_ACTION BEGIN
    COPY_EXISTING - ~%file%.2da~ ~override~
      LPF GET_2DA_ENTRY INT_VAR row_match col_match STR_VAR entry_match RET row col END
    BUT_ONLY IF_EXISTS
  END
END


/**
 * Returns column and row index of the 2DA entry that matches the specified search text of the given 2da file.
 */
DEFINE_PATCH_FUNCTION GET_2DA_ENTRY
INT_VAR
  row_match = "-1"  // neg. value indicates to search all rows
  col_match = "-1"  // neg. value indicates to search all columns
STR_VAR
  entry_match   = ~~  // search text
RET
  row col
BEGIN
  SET row = "-1"
  SET col = "-1"
  COUNT_2DA_COLS numCols
  COUNT_2DA_ROWS numCols numRows
  SET rowOffset = (numCols = 1 || numCols = 2) ? 1 : 0  // to compensate for 2DA headers
  SET rowMin = (row_match < 0) ? 0 : row_match
  SET rowMax = (row_match < 0) ? (numRows - 1) : row_match
  SET colMin = (col_match < 0) ? 0 : col_match
  SET colMax = (col_match < 0) ? (numCols - 1) : col_match
  FOR (curRow = rowMin + rowOffset; curRow <= rowMax; ++curRow) BEGIN
    FOR (curCol = colMin; curCol <= colMax; ++curCol) BEGIN
      READ_2DA_ENTRY curRow curCol numCols value
      PATCH_IF (~%entry_match%~ STR_EQ ~%value%~) BEGIN
        SET row = curRow - rowOffset
        SET col = curCol
        SET curRow = rowMax + 1
        SET curCol = colMax + 1
      END
    END
  END
END

DEFINE_ACTION_FUNCTION HIDE_SPELL
INT_VAR
  hide = 1
  silent = 0    // Silent error, will produce a warning if 1
STR_VAR 
  ids = ""
  resource = ""
BEGIN
  COPY_EXISTING ~hidespl.2da~ ~override~
    COUNT_2DA_COLS cols
    PATCH_IF NOT cols = 4 BEGIN
      PATCH_FAIL "hide_spell: unexpected number of columns '%cols%'."
    END
    PATCH_IF "%resource%" STRING_EQUAL_CASE "" BEGIN
      INNER_ACTION BEGIN
        LAF GET_RESOURCE_FROM_SPELL_IDS STR_VAR ids RET resource END
      END
    END
    PATCH_IF "%resource%" STRING_EQUAL_CASE "" BEGIN
      PATCH_IF silent = 1 BEGIN
        PATCH_WARN "hide_spell: resource name for spell '%ids%' not found."
      END ELSE BEGIN
        PATCH_FAIL "hide_spell: resource name for spell '%ids%' not found."
      END
    END ELSE BEGIN
      LPF GET_2DA_ENTRY INT_VAR col_match = 0 STR_VAR entry_match = EVAL "%resource%" RET row END
      PATCH_IF NOT (row = 0 - 1) AND hide = 0 BEGIN
        REMOVE_2DA_ROW row cols
      END ELSE PATCH_IF NOT (row = 0 - 1) BEGIN
        SET_2DA_ENTRY row 1 cols 1
      END ELSE PATCH_IF hide = 1 BEGIN
        COUNT_2DA_ROWS cols rows
        INSERT_2DA_ROW rows cols "%resource% 1 0 0"
      END
    END
  BUT_ONLY
END
