DEFINE_PATCH_FUNCTION poison_immunity
	INT_VAR index = 8
	STR_VAR result = ""
BEGIN
	DEFINE_ARRAY spells BEGIN
		~SPWI016~
		~SPWI502~
		~dvckill~
		~RR#WI502~
		~SPIN979~
		~SPIN642~
		~RR#SPOI1~
		~RR#spwrt~
	END
	DEFINE_ARRAY identifiers BEGIN  END
	PATCH_PHP_EACH identifiers AS _ => ids BEGIN
		LPF getResourceFromSpellIds STR_VAR ids RET result END
		SPRINT $spells(~%index%~) ~%result%~
		SET index = index + 1
	END
	LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR effects="25" prevent_icons="6" strings="14017 14662 26215 25425" spells END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=173 parameter1=100 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=328 parameter2=141 special=1 END
END

DEFINE_PATCH_FUNCTION disease_immunity
	INT_VAR index = 9
	STR_VAR result = ""
BEGIN
	DEFINE_ARRAY spells BEGIN
		~SPWI409~
		~FL#CSDIS~
		~RR#DPDIS~
		~fl#glor2~
		~fl#mum~
		~fl#gmum~
		~fl#zomsd~
		~rr#gassp~
		~rr#bogaz~
	END
	DEFINE_ARRAY identifiers BEGIN CLERIC_CAUSE_DISEASE END
	PATCH_PHP_EACH identifiers AS _ => ids BEGIN
		LPF getResourceFromSpellIds STR_VAR ids RET result END
		SPRINT $spells(~%index%~) ~%result%~
		SET index = index + 1
	END
	LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR effects="78" prevent_icons="7" strings="31238" spells END
END

DEFINE_PATCH_FUNCTION bleeding_immunity
	INT_VAR index = 1
	STR_VAR result = ""
BEGIN
	DEFINE_ARRAY spells BEGIN
		~RR#BLEED~
	END
	DEFINE_ARRAY identifiers BEGIN  END
	PATCH_PHP_EACH identifiers AS _ => ids BEGIN
		LPF getResourceFromSpellIds STR_VAR ids RET result END
		SPRINT $spells(~%index%~) ~%result%~
		SET index = index + 1
	END
	LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR prevent_icons="137" strings="25137" spells END
END

DEFINE_PATCH_FUNCTION abilityDrain_immunity
BEGIN
	LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR effects="19 15 44 10" strings="26184" END
END

DEFINE_PATCH_FUNCTION hold_immunity
	INT_VAR index = 2
	STR_VAR result = ""
BEGIN
	DEFINE_ARRAY spells BEGIN
		~SPPR208~
		~SPWI306~
	END
	DEFINE_ARRAY identifiers BEGIN  END
	PATCH_PHP_EACH identifiers AS _ => ids BEGIN
		LPF getResourceFromSpellIds STR_VAR ids RET result END
		SPRINT $spells(~%index%~) ~%result%~
		SET index = index + 1
	END
	LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR effects="109 175" prevent_icons="13" strings="14102 14650 25866 31799" animations="SPFLAYER SPMINDAT" spells END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=328 parameter2=157 special=1 END
END

DEFINE_PATCH_FUNCTION stun_immunity
BEGIN
	LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR effects="45 210" prevent_icons="55" strings="14043 25862 26050" END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=328 parameter2=149 special=1 END
END

DEFINE_PATCH_FUNCTION energyDrain_immunity
BEGIN
	LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR effects="216" strings="25802 25803 25804 25805 25806" END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=328 parameter2=159 special=1 END
END

DEFINE_PATCH_FUNCTION sleep_immunity
BEGIN
	LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR effects="39 217" prevent_icons="14 130" strings="12047 12958 13027 14001 17405 20438 25130 26040 26371" END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=328 parameter2=145 special=1 END
END

DEFINE_PATCH_FUNCTION charm_immunity
BEGIN
	LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR effects="5 241" prevent_icons="0 1 43" strings="26206 14672 31787 14780 158915" animations="SPNWCHRM" END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=328 parameter2=137 special=1 END
END

DEFINE_PATCH_FUNCTION fear_immunity
	INT_VAR index = 29
	STR_VAR result = ""
BEGIN
	DEFINE_ARRAY spells BEGIN
		~SPIN203~
		~SPIN536~
		~SPIN807~
		~SPIN882~
		~SPIN890~
		~SPIN895~
		~SPIN981~
		~SPPR416~
		~SPPR706~
		~SPWI125~
		~SPWI205~
		~SPWI811~
		~SPWI899~
		~SPWI956~
		~SPWM123~
		~fl#cnefr~
		~fl#shafi~
		~fl#tchfr~
		~dw#licfi~
		~ca#sfear~
		~A^causfr~
		~rr#dcfea~
		~rr#dcfa1~
		~rr#dcfa2~
		~rr#dmfea~
		~rr#scare~
		~rr#wi811~
		~DVFEARSM~
		~DVHORRO~
	END
	DEFINE_ARRAY identifiers BEGIN WIZARD_EMOTION_FEAR END
	PATCH_PHP_EACH identifiers AS _ => ids BEGIN
		LPF getResourceFromSpellIds STR_VAR ids RET result END
		SPRINT $spells(~%index%~) ~%result%~
		SET index = index + 1
	END
	LPF ADD_IMMUNITY_CRE_ITM_SPL INT_VAR displaySpellIneffective=1 STR_VAR effects="24 23 106" prevent_icons="36" strings="14007 17427 20568 25818" animations="CDHORROR" spells END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=328 parameter2=106 special=1 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=328 parameter2=139 special=1 END
END

DEFINE_PATCH_FUNCTION fatigue_immunity
	INT_VAR index = 1
	STR_VAR result = ""
BEGIN
	DEFINE_ARRAY spells BEGIN
		~SPWI508~
	END
	DEFINE_ARRAY identifiers BEGIN  END
	PATCH_PHP_EACH identifiers AS _ => ids BEGIN
		LPF getResourceFromSpellIds STR_VAR ids RET result END
		SPRINT $spells(~%index%~) ~%result%~
		SET index = index + 1
	END
	LPF ADD_IMMUNITY_CRE_ITM_SPL INT_VAR displaySpellIneffective=1 STR_VAR effects="93" spells END
END

DEFINE_PATCH_FUNCTION confusion_immunity
	INT_VAR index = 10
	STR_VAR result = ""
BEGIN
	DEFINE_ARRAY spells BEGIN
		~SPPR709~
		~SPWI401~
		~SPIN582~
		~SPIN704~
		~SPIN839~
		~SPIN976~
		~SPPR983~
		~MISC3M~
		~A#SHA07~
		~RR#WI401~
	END
	DEFINE_ARRAY identifiers BEGIN  END
	PATCH_PHP_EACH identifiers AS _ => ids BEGIN
		LPF getResourceFromSpellIds STR_VAR ids RET result END
		SPRINT $spells(~%index%~) ~%result%~
		SET index = index + 1
	END
	LPF ADD_IMMUNITY_CRE_ITM_SPL INT_VAR displaySpellIneffective=1 STR_VAR effects="128" prevent_icons="3" strings="14791 14782 25807" animations="SPCONFUS" spells END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=328 parameter2=153 special=1 END
END

DEFINE_PATCH_FUNCTION magicMissile_immunity
	INT_VAR index = 3
	STR_VAR result = ""
BEGIN
	DEFINE_ARRAY spells BEGIN
		~SPWI003~
		~SPWI112~
		~RR#WI112~
	END
	DEFINE_ARRAY identifiers BEGIN WIZARD_MORDENKAINENS_FORCE_MISSILES END
	PATCH_PHP_EACH identifiers AS _ => ids BEGIN
		LPF getResourceFromSpellIds STR_VAR ids RET result END
		SPRINT $spells(~%index%~) ~%result%~
		SET index = index + 1
	END
	LPF ADD_IMMUNITY_CRE_ITM_SPL INT_VAR displaySpellIneffective=1 STR_VAR spells END
END

DEFINE_PATCH_FUNCTION blindness_immunity
	INT_VAR index = 21
	STR_VAR result = ""
BEGIN
	DEFINE_ARRAY spells BEGIN
		~spdr101.spl~
		~spin595.spl~
		~spin878.spl~
		~spin893.spl~
		~spin929.spl~
		~spin931.spl~
		~sppr704.spl~
		~sppr707.spl~
		~spwi106.spl~
		~spwi118.spl~
		~spwi224.spl~
		~spwi714.spl~
		~spwi815.spl~
		~spwi958.spl~
		~spwm178.spl~
		~chalcy2.itm~
		~gorwom4.itm~
		~halb06.itm~
		~sorb.itm~
		~sw1h51.itm~
		~wand19.itm~
	END
	DEFINE_ARRAY identifiers BEGIN CLERIC_CLOUD_OF_PESTILENCE CLERIC_SUNSCORCH END
	PATCH_PHP_EACH identifiers AS _ => ids BEGIN
		LPF getResourceFromSpellIds STR_VAR ids RET result END
		SPRINT $spells(~%index%~) ~%result%~
		SET index = index + 1
	END
	LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR effects="74" prevent_icons="8" spells END
END

DEFINE_PATCH_FUNCTION fireSpells_immunity
	INT_VAR index = 42
	STR_VAR result = ""
BEGIN
	DEFINE_ARRAY spells BEGIN
		~SPIN561~
		~SPIN819~
		~SPWI022~
		~SPWI103~
		~SPIN131~
		~SPWI217~
		~SPWI940~
		~SPWI304~
		~DVFBALL~
		~SPIN160~
		~SPWI001~
		~SPWI957~
		~WAND05~
		~RR#WI304~
		~SPWI523~
		~CDSLSUN~
		~A#KOS09~
		~RR#WI103~
		~RR#WI523~
		~SPWI712~
		~A#KOS14~
		~SPWI810~
		~DW#TRPIN~
		~SPWI911~
		~SPWI922~
		~SPIN719~
		~SPWISH24~
		~DW#TRPMS~
		~SPPR705~
		~CA#FSTOM~
		~RR#PR705~
		~RR#MFIFF~
		~RR#MFIFJ~
		~RR#MFIHA~
		~RR#MMAHE~
		~rr#eimhe~
		~rr#eimfb~
		~rr#ezafb~
		~rr#eburn~
		~rr#englf~
		~RR#GWOF1~
		~rr#gfbth~
	END
	DEFINE_ARRAY identifiers BEGIN WIZARD_BELTYNS_BURNING_BLOOD WIZARD_SHROUD_OF_FLAME CLERIC_SUNSCORCH CLERIC_PRODUCE_FIRE CLERIC_WALL_OF_FIRE END
	PATCH_PHP_EACH identifiers AS _ => ids BEGIN
		LPF getResourceFromSpellIds STR_VAR ids RET result END
		SPRINT $spells(~%index%~) ~%result%~
		SET index = index + 1
	END
	LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR spells END
END

DEFINE_PATCH_FUNCTION coldSpells_immunity
	INT_VAR index = 15
	STR_VAR result = ""
BEGIN
	DEFINE_ARRAY spells BEGIN
		~SPWI404~
		~RR#WI404~
		~SPWI503~
		~d1#wi503~
		~DVCONEC~
		~RR#WI503~
		~SPCRYO01~
		~SPIN133~
		~SPIN158~
		~SPIN162~
		~SPIN833~
		~WAND06~
		~rr#icew~
		~rr#efrzn~
		~rr#ehyis~
	END
	DEFINE_ARRAY identifiers BEGIN WIZARD_OTILUKES_FREEZING_SPHERE WIZARD_SNILLOCS_SNOWBALL_SWARM WIZARD_ICELANCE END
	PATCH_PHP_EACH identifiers AS _ => ids BEGIN
		LPF getResourceFromSpellIds STR_VAR ids RET result END
		SPRINT $spells(~%index%~) ~%result%~
		SET index = index + 1
	END
	LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR spells END
END

DEFINE_PATCH_FUNCTION electricalSpells_immunity
	INT_VAR index = 22
	STR_VAR result = ""
BEGIN
	DEFINE_ARRAY spells BEGIN
		~CDSTAF12~
		~SPCL722~
		~SPIN579~
		~SPIN714~
		~SPIN932~
		~SPIN933~
		~SIN989~
		~SPWI002~
		~SPWI017~
		~SPWI025~
		~SPWI026~
		~SPWI027~
		~SPWI308~
		~SPWI399~
		~SPWI997~
		~RR#WI308~
		~SPDR601~
		~SPWI615~
		~SPBLUN29~
		~SPPR302~
		~SPPR987~
		~SPIN597~
	END
	DEFINE_ARRAY identifiers BEGIN CLERIC_STATIC_CHARGE END
	PATCH_PHP_EACH identifiers AS _ => ids BEGIN
		LPF getResourceFromSpellIds STR_VAR ids RET result END
		SPRINT $spells(~%index%~) ~%result%~
		SET index = index + 1
	END
	LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR spells END
END

DEFINE_PATCH_FUNCTION acidSpells_immunity
	INT_VAR index = 6
	STR_VAR result = ""
BEGIN
	DEFINE_ARRAY spells BEGIN
		~SPIN994~
		~SPWI614~
		~A#CYR11~
		~SPIN596~
		~SPIN691~
		~SPIN913~
	END
	DEFINE_ARRAY identifiers BEGIN WIZARD_VITRIOLIC_SPHERE WIZARD_ACID_STORM END
	PATCH_PHP_EACH identifiers AS _ => ids BEGIN
		LPF getResourceFromSpellIds STR_VAR ids RET result END
		SPRINT $spells(~%index%~) ~%result%~
		SET index = index + 1
	END
	LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR spells END
END

DEFINE_PATCH_FUNCTION cureSpells_immunity
	INT_VAR index = 39
	STR_VAR result = ""
BEGIN
	DEFINE_ARRAY spells BEGIN
		~SPPR103~
		~A#JUSTCL~
		~ca#culw~
		~L#KORIEP~
		~A7Q6CURE~
		~SPPR401~
		~CA#CURSW~
		~SPIN200~
		~SPIN958~
		~SPPR404~
		~cdilnps~
		~scrl08~
		~SPIN201~
		~SPPR502~
		~SPPR514~
		~A#RE11~
		~DVMCURE~
		~RR#PR514~
		~SPPR607~
		~SPWM168~
		~SPWISH39~
		~spin711~
		~spin679~
		~SPIN101~
		~FINP101~
		~fl#bp101~
		~SPIN202~
		~SPIN551~
		~SPIN986~
		~SPPR414~
		~SPPR510~
		~SPCL211~
		~BHAAL1A~
		~RR#DCSW~
		~rr#csw~
		~rr#ccw~
		~rr#harm~
		~sppr608~
		~sppr699~
	END
	DEFINE_ARRAY identifiers BEGIN CLERIC_CAUSE_MODERATE_WOUNDS CLERIC_CURE_MODERATE_WOUNDS CLERIC_CAUSE_LIGHT_WOUNDS CLERIC_CAUSE_MEDIUM_WOUNDS CLERIC_MASS_CAUSE_LIGHT_WOUNDS CLERIC_CURE_MEDIUM_WOUNDS END
	PATCH_PHP_EACH identifiers AS _ => ids BEGIN
		LPF getResourceFromSpellIds STR_VAR ids RET result END
		SPRINT $spells(~%index%~) ~%result%~
		SET index = index + 1
	END
	LPF ADD_IMMUNITY_CRE_ITM_SPL INT_VAR displaySpellIneffective=1 STR_VAR spells END
END

DEFINE_PATCH_FUNCTION cloudSpells_immunity
	INT_VAR index = 20
	STR_VAR result = ""
BEGIN
	DEFINE_ARRAY spells BEGIN
		~SPWI004~
		~SPWI016~
		~SPWI213~
		~SPWI502~
		~SPWI614~
		~A#CYR11~
		~SPWI810~
		~DW#TRPIN~
		~SPIN673~
		~dvckill~
		~SPIN940~
		~SPIN979~
		~SPIN642~
		~RR#WI502~
		~RR#MMSWF~
		~RR#FCLD~
		~RR#FTVAP~
		~RR#MOZSC~
		~RR#ECHSF~
		~RR#WI213~
	END
	DEFINE_ARRAY identifiers BEGIN CLERIC_CLOUD_OF_PESTILENCE END
	PATCH_PHP_EACH identifiers AS _ => ids BEGIN
		LPF getResourceFromSpellIds STR_VAR ids RET result END
		SPRINT $spells(~%index%~) ~%result%~
		SET index = index + 1
	END
	LPF ADD_IMMUNITY_CRE_ITM_SPL INT_VAR displaySpellIneffective=1 STR_VAR spells END
END

DEFINE_PATCH_FUNCTION web_immunity
	INT_VAR index = 13
	STR_VAR result = ""
BEGIN
	DEFINE_ARRAY spells BEGIN
		~SPDR201~
		~SPIN566~
		~SPIN575~
		~SPIN683~
		~SPWI215~
		~D0SPIWEB~
		~ETTERWEB~
		~spletter~
		~wand14~
		~wtpin05~
		~rr#spweb~
		~rr#spwr2~
		~rr#wi215~
	END
	DEFINE_ARRAY identifiers BEGIN  END
	PATCH_PHP_EACH identifiers AS _ => ids BEGIN
		LPF getResourceFromSpellIds STR_VAR ids RET result END
		SPRINT $spells(~%index%~) ~%result%~
		SET index = index + 1
	END
	LPF ADD_IMMUNITY_CRE_ITM_SPL INT_VAR displaySpellIneffective=1 STR_VAR effects="157" prevent_icons="129" spells END
END

DEFINE_PATCH_FUNCTION entangle_immunity
	INT_VAR index = 5
	STR_VAR result = ""
BEGIN
	DEFINE_ARRAY spells BEGIN
		~SPPR105~
		~SPWM111~
		~SPIN688~
		~RR#SMENT~
		~RR#FENTG~
	END
	DEFINE_ARRAY identifiers BEGIN WIZARD_CHARM_PLANTS END
	PATCH_PHP_EACH identifiers AS _ => ids BEGIN
		LPF getResourceFromSpellIds STR_VAR ids RET result END
		SPRINT $spells(~%index%~) ~%result%~
		SET index = index + 1
	END
	LPF ADD_IMMUNITY_CRE_ITM_SPL INT_VAR displaySpellIneffective=1 STR_VAR spells END
END

DEFINE_PATCH_FUNCTION insectSpells_immunity
	INT_VAR index = 8
	STR_VAR result = ""
BEGIN
	DEFINE_ARRAY spells BEGIN
		~SPPR319~
		~SPPR517~
		~SPPR717~
		~SPIN689~
		~DW#VBAT1~
		~DW#VBAT2~
		~CA#IPLAG~
		~U#HFDTPD~
	END
	DEFINE_ARRAY identifiers BEGIN  END
	PATCH_PHP_EACH identifiers AS _ => ids BEGIN
		LPF getResourceFromSpellIds STR_VAR ids RET result END
		SPRINT $spells(~%index%~) ~%result%~
		SET index = index + 1
	END
	LPF ADD_IMMUNITY_CRE_ITM_SPL INT_VAR displaySpellIneffective=1 STR_VAR spells END
END

DEFINE_PATCH_FUNCTION petrification_immunity
	INT_VAR index = 2
	STR_VAR result = ""
BEGIN
	DEFINE_ARRAY spells BEGIN
		~SPWI604~
		~SPWI604D~
	END
	DEFINE_ARRAY identifiers BEGIN  END
	PATCH_PHP_EACH identifiers AS _ => ids BEGIN
		LPF getResourceFromSpellIds STR_VAR ids RET result END
		SPRINT $spells(~%index%~) ~%result%~
		SET index = index + 1
	END
	LPF ADD_IMMUNITY_CRE_ITM_SPL INT_VAR displaySpellIneffective=1 STR_VAR effects="134" strings="14665 25863" spells END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=328 parameter2=155 special=1 END
END

DEFINE_PATCH_FUNCTION polymorph_immunity
	INT_VAR index = 3
	STR_VAR result = ""
BEGIN
	DEFINE_ARRAY spells BEGIN
		~SPIN538~
		~SPWI415~
		~CA#PAOO~
	END
	DEFINE_ARRAY identifiers BEGIN  END
	PATCH_PHP_EACH identifiers AS _ => ids BEGIN
		LPF getResourceFromSpellIds STR_VAR ids RET result END
		SPRINT $spells(~%index%~) ~%result%~
		SET index = index + 1
	END
	LPF ADD_IMMUNITY_CRE_ITM_SPL INT_VAR displaySpellIneffective=1 STR_VAR prevent_icons="124" strings="14128 25124 31729 31732 31757" spells END
END

DEFINE_PATCH_FUNCTION vorpal_immunity
BEGIN
	LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR effects="13 55" strings="14026" END
END

DEFINE_PATCH_FUNCTION earthquake_immunity
	INT_VAR index = 6
	STR_VAR result = ""
BEGIN
	DEFINE_ARRAY spells BEGIN
		~SPOGRE01~
		~SPPR720~
		~rr#equa~
		~CA#EQ~
		~CDTLQAK~
		~rr#r2mud~
	END
	DEFINE_ARRAY identifiers BEGIN  END
	PATCH_PHP_EACH identifiers AS _ => ids BEGIN
		LPF getResourceFromSpellIds STR_VAR ids RET result END
		SPRINT $spells(~%index%~) ~%result%~
		SET index = index + 1
	END
	LPF ADD_IMMUNITY_CRE_ITM_SPL INT_VAR displaySpellIneffective=1 STR_VAR spells END
END

DEFINE_PATCH_FUNCTION cold_immunity
BEGIN
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=28 parameter1=100 parameter2=1 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=85 parameter1=100 parameter2=1 END
END

DEFINE_PATCH_FUNCTION physical_immunity
BEGIN
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=86 parameter1=100 parameter2=1 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=88 parameter1=100 parameter2=1 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=89 parameter1=100 parameter2=1 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=87 parameter1=100 parameter2=1 END
END

DEFINE_PATCH_FUNCTION unturnable_immunity
BEGIN
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=297 parameter2=1 END
END

DEFINE_PATCH_FUNCTION illusion_immunity
	INT_VAR index = 6
	STR_VAR result = ""
BEGIN
	DEFINE_ARRAY spells BEGIN
		~sppr704~
		~spwi106~
		~IKDB2~
		~spwi125~
		~spwi223~
		~spwm178~
	END
	DEFINE_ARRAY identifiers BEGIN  END
	PATCH_PHP_EACH identifiers AS _ => ids BEGIN
		LPF getResourceFromSpellIds STR_VAR ids RET result END
		SPRINT $spells(~%index%~) ~%result%~
		SET index = index + 1
	END
	LPF ADD_IMMUNITY_CRE_ITM_SPL INT_VAR displaySpellIneffective=1 STR_VAR spells END
END

DEFINE_PATCH_FUNCTION necromancyEffects_immunity
	INT_VAR index = 11
	STR_VAR result = ""
BEGIN
	DEFINE_ARRAY spells BEGIN
		~sppr313~
		~sppr314~
		~spwi117~
		~spwi117d~
		~spwi119~
		~spwi221~
		~spwi313~
		~spwi314~
		~spwi812~
		~spwi812d~
		~spwi914~
	END
	DEFINE_ARRAY identifiers BEGIN  END
	PATCH_PHP_EACH identifiers AS _ => ids BEGIN
		LPF getResourceFromSpellIds STR_VAR ids RET result END
		SPRINT $spells(~%index%~) ~%result%~
		SET index = index + 1
	END
	LPF ADD_IMMUNITY_CRE_ITM_SPL INT_VAR displaySpellIneffective=1 STR_VAR spells END
	LPF cureSpells_immunity END
END

DEFINE_PATCH_FUNCTION deathEffects_immunity
BEGIN
	LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR effects="209 13 55" END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=328 parameter2=151 special=1 END
END

DEFINE_PATCH_FUNCTION deathSpell_immunity
	INT_VAR index = 2
	STR_VAR result = ""
BEGIN
	DEFINE_ARRAY spells BEGIN
		~SPWI605~
		~cdxvdth~
	END
	DEFINE_ARRAY identifiers BEGIN  END
	PATCH_PHP_EACH identifiers AS _ => ids BEGIN
		LPF getResourceFromSpellIds STR_VAR ids RET result END
		SPRINT $spells(~%index%~) ~%result%~
		SET index = index + 1
	END
	LPF ADD_IMMUNITY_CRE_ITM_SPL INT_VAR displaySpellIneffective=1 STR_VAR spells END
END

DEFINE_PATCH_FUNCTION mindSpells_immunity
BEGIN
	LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR effects="3" END
	LPF charm_immunity END
	LPF fear_immunity END
	LPF confusion_immunity END
	LPF illusion_immunity END
END

DEFINE_PATCH_FUNCTION hover_immunity
	INT_VAR index = 12
	STR_VAR result = ""
BEGIN
	DEFINE_ARRAY spells BEGIN
		~SPIN561~
		~SPIN819~
		~SPIN994~
		~SPWI022~
		~SPIN914~
		~SPOGRE01~
		~SPPR720~
		~rr#equa~
		~CA#EQ~
		~CDTLQAK~
		~SPWI101~
		~rr#r2mud~
	END
	DEFINE_ARRAY identifiers BEGIN  END
	PATCH_PHP_EACH identifiers AS _ => ids BEGIN
		LPF getResourceFromSpellIds STR_VAR ids RET result END
		SPRINT $spells(~%index%~) ~%result%~
		SET index = index + 1
	END
	LPF ADD_IMMUNITY_CRE_ITM_SPL INT_VAR displaySpellIneffective=1 STR_VAR spells END
	LPF entangle_immunity END
	LPF web_immunity END
END

DEFINE_PATCH_FUNCTION backstab_immunity
BEGIN
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=292 parameter2=1 END
END

DEFINE_PATCH_FUNCTION criticalHit_immunity
BEGIN
END

DEFINE_PATCH_FUNCTION devourBrain_immunity
BEGIN
	LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR effects="19" END
END

DEFINE_PATCH_FUNCTION construct_immunity
BEGIN
	LPF poison_immunity END
	LPF sleep_immunity END
	LPF hold_immunity END
	LPF bleeding_immunity END
	LPF stun_immunity END
	LPF disease_immunity END
	LPF deathEffects_immunity END
	LPF necromancyEffects_immunity END
	LPF mindSpells_immunity END
	LPF backstab_immunity END
	LPF criticalHit_immunity END
	LPF backstab_immunity END
	LPF abilityDrain_immunity END
	LPF energyDrain_immunity END
	LPF fatigue_immunity END
	LPF petrification_immunity END
	LPF insectSpells_immunity END
	LPF infravision_immunity END
END

DEFINE_PATCH_FUNCTION elemental_immunity
BEGIN
	LPF poison_immunity END
	LPF sleep_immunity END
	LPF hold_immunity END
	LPF bleeding_immunity END
	LPF stun_immunity END
	LPF criticalHit_immunity END
	LPF backstab_immunity END
	LPF devourBrain_immunity END
	LPF petrification_immunity END
	LPF insectSpells_immunity END
	LPF infravision_immunity END
END

DEFINE_PATCH_FUNCTION skeletal_immunity
BEGIN
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=86 parameter1=50 parameter2=1 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=89 parameter1=50 parameter2=1 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=88 parameter1=50 parameter2=1 END
	LPF cold_immunity END
	LPF coldSpells_immunity END
END

DEFINE_PATCH_FUNCTION extraplanar_immunity
BEGIN
	LPF cureSpells_immunity END
	LPF deathSpell_immunity END
END

DEFINE_PATCH_FUNCTION plant_immunity
BEGIN
	LPF disease_immunity END
	LPF bleeding_immunity END
	LPF petrification_immunity END
	LPF stun_immunity END
	LPF hold_immunity END
	LPF polymorph_immunity END
	LPF confusion_immunity END
	LPF charm_immunity END
	LPF fear_immunity END
	LPF sleep_immunity END
	LPF illusion_immunity END
	LPF poison_immunity END
	LPF insectSpells_immunity END
	LPF entangle_immunity END
END

DEFINE_PATCH_FUNCTION infravision_immunity
BEGIN
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=63 END
END

DEFINE_PATCH_FUNCTION seeInvisible_immunity
BEGIN
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=193 parameter2=1 END
END

DEFINE_PATCH_FUNCTION fireballSpell_immunity
	INT_VAR index = 9
	STR_VAR result = ""
BEGIN
	DEFINE_ARRAY spells BEGIN
		~BDBLOWUP~
		~BDDAUSTO~
		~BDKORLAS~
		~BDMORLIS~
		~c0ausp03~
		~SPWI001~
		~SPWI304~
		~SPIN957~
		~wand05a~
	END
	DEFINE_ARRAY identifiers BEGIN  END
	PATCH_PHP_EACH identifiers AS _ => ids BEGIN
		LPF getResourceFromSpellIds STR_VAR ids RET result END
		SPRINT $spells(~%index%~) ~%result%~
		SET index = index + 1
	END
	LPF ADD_IMMUNITY_CRE_ITM_SPL INT_VAR displaySpellIneffective=1 STR_VAR spells END
END

DEFINE_PATCH_FUNCTION lightningBoltSpell_immunity
	INT_VAR index = 14
	STR_VAR result = ""
BEGIN
	DEFINE_ARRAY spells BEGIN
		~b_tal10~
		~c0dm302~
		~spcl722~
		~spdr301~
		~spin714~
		~spin933~
		~spin989~
		~SPWI002~
		~SPWI017~
		~SPWI231~
		~SPWI308~
		~SPWI399~
		~SPWI997~
		~wand07~
	END
	DEFINE_ARRAY identifiers BEGIN  END
	PATCH_PHP_EACH identifiers AS _ => ids BEGIN
		LPF getResourceFromSpellIds STR_VAR ids RET result END
		SPRINT $spells(~%index%~) ~%result%~
		SET index = index + 1
	END
	LPF ADD_IMMUNITY_CRE_ITM_SPL INT_VAR displaySpellIneffective=1 STR_VAR spells END
END

DEFINE_PATCH_FUNCTION flameArrowSpell_immunity
	INT_VAR index = 6
	STR_VAR result = ""
BEGIN
	DEFINE_ARRAY spells BEGIN
		~d5f2303~
		~d5p2303~
		~d5p2303W~
		~d5y391i~
		~SPWI303~
		~SPWI888~
	END
	DEFINE_ARRAY identifiers BEGIN  END
	PATCH_PHP_EACH identifiers AS _ => ids BEGIN
		LPF getResourceFromSpellIds STR_VAR ids RET result END
		SPRINT $spells(~%index%~) ~%result%~
		SET index = index + 1
	END
	LPF ADD_IMMUNITY_CRE_ITM_SPL INT_VAR displaySpellIneffective=1 STR_VAR spells END
END

DEFINE_PATCH_FUNCTION incorporeal_immunity
BEGIN
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=120 parameter2=2 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=66 parameter1=99 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=9 parameter1=2105376000 parameter2=1966335 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=61 parameter1=1511938560 parameter2=1638400 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=142 parameter2=23 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=0 parameter1=3 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=278 parameter1=4 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=30 parameter1=50 parameter2=1 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=84 parameter1=50 parameter2=1 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=28 parameter1=50 parameter2=1 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=85 parameter1=50 parameter2=1 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=29 parameter1=50 parameter2=1 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=27 parameter1=50 parameter2=1 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=31 parameter1=50 parameter2=1 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=86 parameter1=50 parameter2=1 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=87 parameter1=50 parameter2=1 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=88 parameter1=50 parameter2=1 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=89 parameter1=50 parameter2=1 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=173 parameter1=50 END
END

DEFINE_PATCH_FUNCTION missileWeapons_immunity
BEGIN
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=1 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=2 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=3 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=4 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=6 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=7 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=8 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=9 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=10 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=11 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=12 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=13 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=14 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=15 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=16 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=17 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=18 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=19 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=26 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=27 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=28 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=29 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=30 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=31 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=32 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=33 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=34 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=35 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=55 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=56 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=57 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=58 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=59 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=102 END
	LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=232 END
END

DEFINE_PATCH_FUNCTION airAffinity_immunity
BEGIN
END

DEFINE_PATCH_FUNCTION earthAffinity_immunity
BEGIN
	LPF earthquake_immunity END
END
