INCLUDE "%MOD_FOLDER%/lib/common/2da.tpa"
INCLUDE "%MOD_FOLDER%/lib/common/ids.tpa"
INCLUDE "%MOD_FOLDER%/lib/common/spell_item.tpa"
INCLUDE "%MOD_FOLDER%/lib/common/convert.tpa"
INCLUDE "%MOD_FOLDER%/lib/common/alter_effect.tph"           // David W. improved effect functions
INCLUDE "%MOD_FOLDER%/lib/common/functions.tpa"              // Common aTweaks functions
INCLUDE "%MOD_FOLDER%/lib/common/immune-trait.tpa"           // Common aTweaks functions
INCLUDE ~%MOD_FOLDER%/lib/common/regexp.tph~                 // allows regexp to match tabs and newlines (from the G3 BG2 Fixpack)
INCLUDE ~%MOD_FOLDER%/lib/common/iwd1fix.tpa~                // fix some IDS file issues with IWD1 to ensure proper script compiling
INCLUDE "%MOD_FOLDER%/lib/common/comp_vars.tpa"              // Game engines stuff
INCLUDE ~%MOD_FOLDER%/lib/common/spell_to_innate.tph~
INCLUDE "%MOD_FOLDER%/lib/common/patch_creature.tph"
INCLUDE "%MOD_FOLDER%/lib/common/patch_creature_script.tph"

// FJ_SPL_ITM_REINDEX -> FJ_SPL_ITM_REINDEX
// FJ_CRE_EFF_V2 -> FJ_CRE_EFF_V2
// FJ_CRE_REINDEX -> FL#FJ_CRE_REINDEX OR FJ_CRE_REINDEX
// FJ_CRE_VALIDITY -> FL#FJ_CRE_VALIDITY OR FJ_CRE_VALIDITY
