// DEFINE_PATCH_FUNCTION configure_itm_header
// INT_VAR
//   f_Header = "-1"
//   f_TargetType = "-1"
//   f_Type = "-1"
//   f_Identify = "-1"
//   f_Slot = "-1"
//   f_Target = "-1"
//   f_Range = "-1"
//   f_Launcher = "-1"
//   f_Speed = "-1"
//   f_ToHit = "-1"
//   f_Damage = "-1"
//   f_NumDice = "-1"
//   f_DieSize = "-1"
//   f_DamageType = "-1"
//   f_Flags = "-1"
//   f_Charges = "-1"
//   f_Drained = "-1"
//   f_Projectile = "-1"
//   f_Overhand = "-1"
//   f_Backhand = "-1"
//   f_Thrust = "-1"
//   f_Arrow = "-1"
//   f_Bolt = "-1"
//   f_Bullet = "-1"
// STR_VAR
//   f_Icon = flEmpty
// BEGIN
//   READ_LONG  0x64 ao
//   FOR (i=0;i<SHORT_AT 0x68;++i) BEGIN
//     READ_BYTE ao + 0x38*i type
//     PATCH_IF type = f_TargetType OR i = f_Header OR (f_Header < 0 AND f_TargetType < 0) BEGIN
//       WRITE_BYTE   ao + 0x38*i        f_Type < 0 ? THIS : f_Type
//       WRITE_BYTE   ao + 0x38*i + 0x2  f_Slot < 0 ? THIS : f_Slot
//       PATCH_IF "%f_Icon%" STRING_COMPARE flEmpty BEGIN
//         WRITE_ASCIIE ao + 0x38*i + 0x4  "%f_Icon%"
//       END
//       WRITE_BYTE   ao + 0x38*i + 0xc  f_Target < 0 ? THIS : f_Target
//       WRITE_SHORT  ao + 0x38*i + 0xe  f_Range < 0 ? THIS : f_Range
//       WRITE_BYTE   ao + 0x38*i + 0x12 f_Speed < 0 ? THIS : f_Speed
//       WRITE_SHORT  ao + 0x38*i + 0x14 f_ToHit < 0 ? THIS : f_ToHit
//       WRITE_BYTE   ao + 0x38*i + 0x16 f_DieSize < 0 ? THIS : f_DieSize
//       WRITE_BYTE   ao + 0x38*i + 0x18 f_NumDice < 0 ? THIS : f_NumDice
//       WRITE_SHORT  ao + 0x38*i + 0x1a f_Damage < 0 ? THIS : f_Damage
//       WRITE_SHORT  ao + 0x38*i + 0x1c f_DamageType < 0 ? THIS : f_DamageType
//       WRITE_SHORT  ao + 0x38*i + 0x22 f_Charges < 0 ? THIS : f_Charges
//       WRITE_SHORT  ao + 0x38*i + 0x24 f_Drained < 0 ? THIS : f_Drained
//       WRITE_LONG   ao + 0x38*i + 0x26 f_Flags < 0 ? THIS : f_Flags
//       WRITE_SHORT  ao + 0x38*i + 0x2a f_Projectile < 0 ? THIS : f_Projectile
//       WRITE_SHORT  ao + 0x38*i + 0x2c f_Overhand < 0 ? THIS : f_Overhand
//       WRITE_SHORT  ao + 0x38*i + 0x2e f_Backhand < 0 ? THIS : f_Backhand
//       WRITE_SHORT  ao + 0x38*i + 0x30 f_Thrust < 0 ? THIS : f_Thrust
//       WRITE_SHORT  ao + 0x38*i + 0x32 f_Arrow < 0 ? THIS : f_Arrow
//       WRITE_SHORT  ao + 0x38*i + 0x34 f_Bolt < 0 ? THIS : f_Bolt
//       WRITE_SHORT  ao + 0x38*i + 0x36 f_Bullet < 0 ? THIS : f_Bullet
//     END
//   END
// END


// // Writes to the more and less common fields of the item melee header
// DEFINE_PATCH_FUNCTION configure_weapon_header
// INT_VAR
//   f_Slot = 1
//   f_Target = 1
//   f_Range = 1
//   f_Speed = 0
//   f_ToHit = 0
//   f_Damage = 0
//   f_NumDice = 0
//   f_DieSize = 0
//   f_DamageType = 0
//   f_Flags = 1
//   f_Charges = 0
//   f_Drained = 1
//   f_Projectile = 1
//   f_Overhand = 34
//   f_Backhand = 33
//   f_Thrust = 33
//   f_Arrow = 0
//   f_Bolt = 0
//   f_Bullet = 0
// STR_VAR
//   f_Icon = ~~
// BEGIN
//   LPF configure_itm_header
//     INT_VAR
//       f_TargetType = 1
//       f_Slot
//       f_Target
//       f_Range
//       f_Speed
//       f_ToHit
//       f_Damage
//       f_NumDice
//       f_DieSize
//       f_DamageType
//       f_Flags
//       f_Charges
//       f_Drained
//       f_Projectile
//       f_Overhand
//       f_Backhand
//       f_Thrust
//       f_Arrow
//       f_Bolt
//       f_Bullet
//     STR_VAR
//       f_Icon
//   END
// END
