// Adds immunity to the provided spell to blindness-causing spells and items
DEFINE_ACTION_FUNCTION add_blindness_immunity STR_VAR f_Spell = "" BEGIN
  // Begin: Add Spells from IWDification mod or stratagems mods
  ACTION_IF IDS_OF_SYMBOL("spell" "CLERIC_SUNSCORCH") > 0 BEGIN
    OUTER_SET code=IDS_OF_SYMBOL("spell" "CLERIC_SUNSCORCH")
    OUTER_SET code=code - 1000
    OUTER_SPRINT IWDsuns "SPpr%code%"
  END ELSE BEGIN
    OUTER_SPRINT IWDsuns ""
  END
  ACTION_IF IDS_OF_SYMBOL("spell" "CLERIC_CLOUD_OF_PESTILENCE") > 0 BEGIN
    OUTER_SET code=IDS_OF_SYMBOL("spell" "CLERIC_CLOUD_OF_PESTILENCE")
    OUTER_SET code=code - 1000
    OUTER_SPRINT IWDcldp "SPpr%code%"
  END ELSE BEGIN
    OUTER_SPRINT IWDcldp ""
  END 
  // End: Add Spells from IWDification mod or stratagems mods
  ACTION_FOR_EACH ~file~ IN
        ~spdr101.spl~
        ~spin595.spl~
        ~spin878.spl~
        ~spin893.spl~
        ~spin929.spl~
        ~spin931.spl~
        ~sppr704.spl~
        ~sppr707.spl~
        ~spwi106.spl~
        ~spwi118.spl~
        ~spwi224.spl~
        ~spwi714.spl~
        ~spwi815.spl~
        ~spwi958.spl~
        ~spwm178.spl~
        ~chalcy2.itm~
        ~gorwom4.itm~
          ~halb06.itm~
            ~sorb.itm~
          ~sw1h51.itm~
          ~wand19.itm~
			 ~%IWDsuns%.spl~	// Sunscorch (IWDification)
			 ~%IWDcldp%.spl~ // Cloud of Pestilence (IWDification)
  BEGIN
    ACTION_IF FILE_EXISTS_IN_GAME ~%file%~ BEGIN
      COPY_EXISTING ~%file%~ ~override~
        PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
          LPF add_conditional_immunity INT_VAR f_Condition = 74 STR_VAR f_Spell END
        END
      BUT_ONLY_IF_IT_CHANGES
    END
  END
END

// Magic Missile spell immunity
DEFINE_PATCH_FUNCTION magic_missile_immunity BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "SPL" BEGIN
    PATCH_FAIL ~Function magic_missile_immunity was not configured for spell, file: %SOURCE_RES%~
  END
  // Begin : Add Spells from IWDification mod or stratagems mods
  PATCH_IF IDS_OF_SYMBOL("spell" "WIZARD_MORDENKAINENS_FORCE_MISSILES") > 0 BEGIN
    SET code=IDS_OF_SYMBOL("spell" "WIZARD_MORDENKAINENS_FORCE_MISSILES")
    SET code=code - 2000
    SPRINT IWDmfm "SPwi%code%"
    SPRINT IWDmfmb "SPwi%code%B"
  END ELSE BEGIN
    SPRINT IWDmfm ""
    SPRINT IWDmfmb ""
  END
  // End : Add Spells from IWDification mod or stratagems mods
  DEFINE_ARRAY spells BEGIN  
    ~SPWI003~   // Magic Missile
    ~SPWI112~   // Magic Missile
    ~RR#WI112~  // aTweaks' Magic Missile
    ~%IWDmfm%~  // Mordenkainen's Force Missiles (IWDification)
    ~%IWDmfmb%~ // Mordenkainen's Force Missiles (IWDification)
  END
  LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR spells END
END

// Fire spell immunities, area effect spell immunities (prevents friendly fire and such)
DEFINE_PATCH_FUNCTION fire_spell_immunities BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "SPL" BEGIN
    PATCH_FAIL ~Function fire_spell_immunities was not configured for spell, file: %SOURCE_RES%~
  END
  // Begin : Add Spells from IWDification mod or stratagems mods
  PATCH_IF IDS_OF_SYMBOL("spell" "WIZARD_BELTYNS_BURNING_BLOOD") > 0 BEGIN
    SET code=IDS_OF_SYMBOL("spell" "WIZARD_BELTYNS_BURNING_BLOOD")
    SET code=code - 2000
    SPRINT IWDbbb "SPwi%code%"
  END ELSE BEGIN
    SPRINT IWDbbb ""
  END
  PATCH_IF IDS_OF_SYMBOL("spell" "WIZARD_SHROUD_OF_FLAME") > 0 BEGIN
    SET code=IDS_OF_SYMBOL("spell" "WIZARD_SHROUD_OF_FLAME")
    SET code=code - 2000
    SPRINT IWDshrf "SPwi%code%"
  END ELSE BEGIN
	  SPRINT IWDshrf ""
  END	
  PATCH_IF IDS_OF_SYMBOL("spell" "CLERIC_SUNSCORCH") > 0 BEGIN
    SET code=IDS_OF_SYMBOL("spell" "CLERIC_SUNSCORCH")
    SET code=code - 1000
    SPRINT IWDsuns "SPpr%code%"
  END ELSE BEGIN
    SPRINT IWDsuns ""
  END
  PATCH_IF IDS_OF_SYMBOL("spell" "CLERIC_PRODUCE_FIRE") > 0 BEGIN
	  SET code=IDS_OF_SYMBOL("spell" "CLERIC_PRODUCE_FIRE")
    SET code=code - 1000
    SPRINT IWDprdf "SPpr%code%"
  END ELSE BEGIN
	  SPRINT IWDprdf ""
  END
  PATCH_IF IDS_OF_SYMBOL("spell" "CLERIC_WALL_OF_FIRE") > 0 BEGIN
	  SET code=IDS_OF_SYMBOL("spell" "CLERIC_WALL_OF_FIRE")
    SET code=code - 1000
    SPRINT wallf "SPpr%code%"
  END ELSE BEGIN
	  SPRINT wallf ""
  END
  // End : Add Spells from IWDification mod or stratagems mods
  DEFINE_ARRAY spells BEGIN  
    ~SPIN561~  // Fire Giant Lava Pit (FIRE_GIANT_LAVA)
    ~SPIN819~  // Lava Burst (LAVA_BURST)
    ~SPWI022~  // Lava Pit (TRAP_MUCK)
    ~SPWI103~  // Burning Hands
    ~SPIN131~  // Burning Hands
    ~SPWI217~  // Agannazar's Scorcher
    ~SPWI940~  // Agannazar's Scorcher
    ~SPWI304~  // Fireball
    ~DVFBALL~  // Fireball (IRR + SRR)
    ~SPIN160~  // Breath Fireball
    ~SPWI001~  // Fireball
    ~SPWI957~  // Fireball
    ~WAND05~   // Fireball (IRR)
    ~RR#WI304~ // Pit Fiend Fireball
    ~SPWI523~  // Sunfire
    ~CDSLSUN~  // Sunfire (mod)
    ~A#KOS09~  // Sunfire (Divine Remix)
    ~RR#WI103~ // RR's burning hand
    ~RR#WI523~ // RR's Sunfire (Blazing Glory buckler)
    ~SPWI712~  // Delayed Blast Fireball
    ~A#KOS14~  // Delayed Blast Fireball (Divine Remix)  
    ~SPWI810~  // Incendiary Cloud
    ~DW#TRPIN~ // Incendiary Cloud (Stratagems)
    ~SPWI911~  // Meteor Swarm
    ~SPWI922~  // Dragon's Breath
    ~SPIN719~  // Meteor Swarm
    ~SPWISH24~ // Meteor Swarm
    ~DW#TRPMS~ // Meteor Swarm (Stratagems)
    ~SPPR705~  // Fire Storm
    ~CA#FSTOM~ // Fire Storm (PnP Deva)
    ~RR#PR705~ // Fire Storm (atweaks)
    ~RR#MFIFF~ // Flame Fan (Fire Mephit)
    ~RR#MFIFJ~ // Flame Jet (Fire Mephit)
    ~RR#MFIHA~ // Heat Aura (Fire Mephit)
    ~RR#MMAHE~ // Heat Emission (Magma Mephit)
    ~rr#eimhe~ // Heat Emission (Imix)
    ~rr#eimfb~ // Fireball, 20d6 (Imix)
    ~rr#ezafb~ // Fireball, 12d6 (Zaaman Rul)
    ~rr#eburn~ // Burn (Fire Elemental on-hit effect)
    ~rr#englf~ // Engulf, part 1 (Greater Fire Elemental on-hit effect)
    ~RR#GWOF1~ // Wall of Fire (Efreet)
    ~rr#gfbth~ // Fire breath (Guardian Genie)
    ~%IWDprdf%~// Produe Fire (IWDification)
    ~%IWDbbb%~ // Beltyn's Burning Blood (IWDification)
    ~%IWDshrf%~// Shroud of Flame (IWDification)
    ~%IWDsuns%~// Sunscorch (IWDification)
    ~%wallf%~  // Wall of Fire (SpellPack)
  END
  LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR spells END
END

// Cold spell immunities, area effect spell immunities (prevents friendly fire and such)
DEFINE_PATCH_FUNCTION cold_spell_immunities BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "SPL" BEGIN
    PATCH_FAIL ~Function cold_spell_immunities was not configured for spell, file: %SOURCE_RES%~
  END
  // Begin : Add Spells from IWDification mod or stratagems mods
  PATCH_IF IDS_OF_SYMBOL("spell" "WIZARD_OTILUKES_FREEZING_SPHERE") > 0 BEGIN
    SET code=IDS_OF_SYMBOL("spell" "WIZARD_OTILUKES_FREEZING_SPHERE")
    SET code=code - 2000
    SPRINT IWDofrs "SPwi%code%"
  END ELSE BEGIN
    SPRINT IWDofrs ""
  END
  PATCH_IF IDS_OF_SYMBOL("spell" "WIZARD_SNILLOCS_SNOWBALL_SWARM") > 0 BEGIN  
    SET code=IDS_OF_SYMBOL("spell" "WIZARD_SNILLOCS_SNOWBALL_SWARM")
    SET code=code - 2000
    SPRINT IWDsss "SPwi%code%"
  END ELSE BEGIN
	  SPRINT IWDsss ""
  END
  PATCH_IF IDS_OF_SYMBOL("spell" "WIZARD_ICELANCE") > 0 BEGIN  
    SET code=IDS_OF_SYMBOL("spell" "WIZARD_ICELANCE")
    SET code=code - 2000
    SPRINT IWDIcel "SPwi%code%"
  END ELSE BEGIN
	  SPRINT IWDIcel ""
  END
  // End : Add Spells from IWDification mod or stratagems mods
  DEFINE_ARRAY spells BEGIN  
       ~SPWI404~ // Ice Storm
      ~RR#WI404~ // %MOD_FOLDER%/RR Ice Storm
       ~SPWI503~ // Cone of Cold
      ~d1#wi503~ // Cone of Cold (mod)
       ~DVCONEC~ // Cone of Cold (IR)
      ~RR#WI503~ // Cone of Cold (%MOD_FOLDER%/RR)
      ~SPCRYO01~ // Cone of Cold (mod)
       ~SPIN133~ // Cone of Cold (mod)
       ~SPIN158~ // Cone of Cold (mod)
       ~SPIN162~ // Cone of Cold (mod)
       ~SPIN833~ // Dragon Cone of Cold
        ~WAND06~ // Cone of Cold (IR)
       ~rr#icew~ // aTweaks' Wall of Ice
      ~rr#efrzn~ // aTweaks' Freeze (Cryonax)
      ~rr#ehyis~ // aTweaks' Ice Storn (Olhydra's version)
     ~%IWDofrs%~ // Otiluke's Freezing Sphere (IWDification)
      ~%IWDsss%~ // Snilloc's Snowball Swarm (IWDification)
     ~%IWDIcel%~ // Icelance (IWDification)
  END
  LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR spells END
END


// Electrical spell immunities, area effect spell immunities (prevents friendly fire and such)
DEFINE_PATCH_FUNCTION electrical_spell_immunities BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "SPL" BEGIN
    PATCH_FAIL ~Function electrical_spell_immunities was not configured for spell, file: %SOURCE_RES%~
  END
  // Begin : Add Spells from IWDification mod or stratagems mods
  PATCH_IF IDS_OF_SYMBOL("spell" "CLERIC_STATIC_CHARGE") > 0 BEGIN
    SET code=IDS_OF_SYMBOL("spell" "CLERIC_STATIC_CHARGE")
    SET code=code - 1000
    SPRINT IWDstch "SPpr%code%"
  END ELSE BEGIN
    SPRINT IWDstch ""
  END
  // End : Add Spells from IWDification mod or stratagems mods
  DEFINE_ARRAY spells BEGIN  
        ~CDSTAF12~ // Lightning Bolt
        ~SPCL722~  // Lightning Bolt
        ~SPIN579~  // Lightning Bolt
        ~SPIN714~  // Lightning Bolt
        ~SPIN932~  // Lightning Bolt
        ~SPIN933~  // Lightning Bolt
        ~SIN989~   // Lightning Bolt
        ~SPWI002~  // Lightning Bolt
        ~SPWI017~  // Minor Lightning Bolt
        ~SPWI025~  // Minor Lightning Bolt
        ~SPWI026~  // Minor Lightning Bolt
        ~SPWI027~  // Minor Lightning Bolt
        ~SPWI308~  // Lightning Bolt
        ~SPWI399~  // Lightning Bolt
        ~SPWI997~  // Lightning Bolt
       ~RR#WI308~  // RR/aTweaks Lightning Bolt
        ~SPDR601~  // Chain Lightning
        ~SPWI615~  // Chain Lightning
       ~SPBLUN29~  // Chain Lightning
        ~SPPR302~  // Call Lightning
        ~SPPR987~  // Call Lightning
        ~SPIN597~  // Blue Dragon Lightning Breath
      ~%IWDstch%~  // Static Charge (IWDification)
  END
  LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR spells END
END

// Acid spell immunities, area effect spell immunities (prevents friendly fire and such)
DEFINE_PATCH_FUNCTION acid_spell_immunities BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "SPL" BEGIN
    PATCH_FAIL ~Function acid_spell_immunities was not configured for spell, file: %SOURCE_RES%~
  END
  // Begin : Add Spells from IWDification mod or stratagems mods
  PATCH_IF IDS_OF_SYMBOL("spell" "WIZARD_VITRIOLIC_SPHERE") > 0 BEGIN
    SET code=IDS_OF_SYMBOL("spell" "WIZARD_VITRIOLIC_SPHERE")
    SET code=code - 2000
    SPRINT IWDvsph "SPwi%code%"
  END ELSE BEGIN
    SPRINT IWDofrs ""
  END
  PATCH_IF IDS_OF_SYMBOL("spell" "WIZARD_ACID_STORM") > 0 BEGIN
    SET code=IDS_OF_SYMBOL("spell" "WIZARD_ACID_STORM")
    SET code=code - 2000
    SPRINT IWDastm "SPwi%code%"
  END ELSE BEGIN
	  SPRINT IWDastm ""
  END
  // End : Add Spells from IWDification mod or stratagems mods
  DEFINE_ARRAY spells BEGIN  
        ~SPIN994~   // Acid Pools in Durlag's Tower (ACID_DAMAGE_1)
        ~SPWI614~   // Death Fog
        ~A#CYR11~   // Death Fog (Divine Remix)
        ~SPIN596~   // Brown Dragon Acid Breath
        ~SPIN691~   // Black Dragon Breath
        ~SPIN913~   // Mimic Acid				
				~%IWDvsph%~ // Vitriolic Sphere (IWDification)
				~%IWDastm%~ // Acid Storm (IWDification)
  END
  LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR spells END
END


// Poison spell immunities, area effect spell immunities (prevents friendly fire and such)
DEFINE_PATCH_FUNCTION poison_spell_immunities BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "SPL" BEGIN
    PATCH_FAIL ~Function poison_spell_immunities was not configured for spell, file: %SOURCE_RES%~
  END
  DEFINE_ARRAY spells BEGIN  
    ~SPWI016~  // Cloudkill (trap)
    ~SPWI502~  // Cloudkill
    ~dvckill~  // Cloudkill (IR/SR)
    ~RR#WI502~ // RR/aTweaks Cloudkill
    ~SPIN979~  // Golem Gas Cloud
    ~SPIN642~  // Poisonous Cloud
    ~RR#SPOI1~ // Spiders Class F poison
    ~RR#spwrt~ // Wraith Spiders Class F poison
  END
  LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR spells END
END

// Poison immunity
DEFINE_PATCH_FUNCTION poison_immunity BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "SPL" BEGIN
    PATCH_FAIL ~Function poison_immunity was not configured for spell, file: %SOURCE_RES%~
  END
  LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR effects=25 prevent_icons=6 display_icons=30 strings="14017 14662" END
  LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=173 parameter1=100 END
END

// Cure & cause wound spell immunities
DEFINE_PATCH_FUNCTION cure_spell_immunities BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "SPL" BEGIN
    PATCH_FAIL ~Function cure_spell_immunities was not configured for spell, file: %SOURCE_RES%~
  END
  // Begin : Add Spells from IWDification mod or stratagems mods
  PATCH_IF IDS_OF_SYMBOL("spell" "CLERIC_CAUSE_MODERATE_WOUNDS") > 0 BEGIN
    SET code=IDS_OF_SYMBOL("spell" "CLERIC_CAUSE_MODERATE_WOUNDS")
    SET code=code - 1000
    SPRINT IWDcamw "SPpr%code%"
  END ELSE BEGIN
    SPRINT IWDcamw ""
  END
  PATCH_IF IDS_OF_SYMBOL("spell" "CLERIC_CURE_MODERATE_WOUNDS") > 0 BEGIN
    SET code=IDS_OF_SYMBOL("spell" "CLERIC_CURE_MODERATE_WOUNDS")
    SET code=code - 1000
    SPRINT IWDcumw "SPpr%code%"
  END ELSE BEGIN
    SPRINT IWDcumw ""
  END
  PATCH_IF IDS_OF_SYMBOL("spell" "CLERIC_CAUSE_LIGHT_WOUNDS") > 0 BEGIN
    SET code=IDS_OF_SYMBOL("spell" "CLERIC_CAUSE_LIGHT_WOUNDS")
    SET code=code - 1000
    SPRINT IWDcalw "SPpr%code%"
  END ELSE BEGIN
    SPRINT IWDcalw ""
  END
  PATCH_IF IDS_OF_SYMBOL("spell" "CLERIC_CAUSE_MEDIUM_WOUNDS") > 0 BEGIN
    SET code=IDS_OF_SYMBOL("spell" "CLERIC_CAUSE_MEDIUM_WOUNDS")
    SET code=code - 1000
    SPRINT IWDcame "SPpr%code%"
  END ELSE BEGIN
    SPRINT IWDcame ""
  END
  PATCH_IF IDS_OF_SYMBOL("spell" "CLERIC_MASS_CAUSE_LIGHT_WOUNDS") > 0 BEGIN
    SET code=IDS_OF_SYMBOL("spell" "CLERIC_MASS_CAUSE_LIGHT_WOUNDS")
    SET code=code - 1000
    SPRINT IWDmcaw "SPpr%code%"
  END ELSE BEGIN
    SPRINT IWDmcaw ""
  END
  PATCH_IF IDS_OF_SYMBOL("spell" "CLERIC_CURE_MEDIUM_WOUNDS") > 0 BEGIN
    SET code=IDS_OF_SYMBOL("spell" "CLERIC_CURE_MEDIUM_WOUNDS")
    SET code=code - 1000
    SPRINT IWDcume "SPpr%code%"
  END ELSE BEGIN
    SPRINT IWDcume ""
  END
  // End : Add Spells from IWDification mod or stratagems mods
  DEFINE_ARRAY spells BEGIN  
    ~SPPR103~   // Cure Light Wounds
    ~A#JUSTCL~  // Cure Light Wounds (Divine Remix)
    ~ca#culw~   // Cure Light Wounds (PnP Deva)              
    ~L#KORIEP~  // Cure Light Wounds (mod) 
    ~A7Q6CURE~  // Cure Light Wounds (afaaq)  
    ~%srcumo%~  // Cure Medium Wounds  (Spell Revisions)
    ~%IWDcumw%~ // Cure moderate Wounds  (IWDification)
    ~%IWDcume%~ // Cure Medium Wounds
    ~SPPR401~   // Cure Serious Wounds
    ~CA#CURSW~  // Cure Serious Wounds (PnP Deva)
    ~SPIN200~   // Cure Serious Wounds
    ~SPIN958~   // Cure Serious Wounds
    ~SPPR404~   // Neutralize Poison
    ~cdilnps~   // Neutralize Poison (mod)
    ~scrl08~    // Neutralize Poison (IR)
    ~SPIN201~   // Neutralize Poison
    ~SPPR502~   // Cure Critical Wounds
    ~SPPR514~   // Mass Cure
    ~A#RE11~    // Mass Cure (Divine Remix)
    ~DVMCURE~   // Mass Cure (IR/SR)
    ~RR#PR514~  // Mass Cure (atweaks temple)
    ~SPPR607~   // Heal
    ~SPWM168~   // Heal (Wild Mage) 
    ~SPWISH39~  // Heal
    ~spin711~   // Heal
    ~spin679~   // Heal
    ~SPIN101~   // Cure Light Wounds (Bhaalpower)
    ~FINP101~   // Cure Light Wounds (TOB Bhaalpower Ascension)
    ~fl#bp101~  // Cure Light Wounds (TOB Bhaalpower atweal)
    ~%IWDcalw%~ // Cause Light Wounds (IWDification)
    ~%IWDcamw%~ // Cause moderate Wounds (IWDification)				
    ~SPIN202~   // Cause Serious Wounds               
    ~SPIN551~   // Cause Serious Wounds (Hive Mother)
    ~SPIN986~   // Cause Serious Wounds (Beholder)
    ~SPPR414~   // Cause Serious Wounds
    ~SPPR510~   // Cause critical Wounds
    ~%IWDcame%~ // Cause medium Wounds (IWDification)	
    ~%IWDmcaw%~ // Mass Cause Light Wounds (IWDification)	
    ~SPCL211~   // Paladin Lay On Hands
    ~BHAAL1A~   // Mass Healing (Bhaalpower restored by Ascension/UB)
    ~RR#DCSW~   // RR/aTweaks Cause Serious Wounds (Marilith)
    ~rr#csw~    // aTweaks Cause Serious Wounds (externalized)
    ~rr#ccw~    // aTweaks Cause Critical Wounds (externalized)
    ~rr#harm~   // aTweaks Harm (externalized)
    ~sppr608~   // Harm
    ~sppr699~   // Harm
  END
  LPF ADD_IMMUNITY_CRE_ITM_SPL INT_VAR displaySpellIneffective=1 STR_VAR spells END
END

// Cloud spell immunities
DEFINE_PATCH_FUNCTION cloud_spell_immunities BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "SPL" BEGIN
    PATCH_FAIL ~Function cloud_spell_immunities was not configured for spell, file: %SOURCE_RES%~
  END
  // Begin : Add Spells from IWDification mod or stratagems mods
  PATCH_IF IDS_OF_SYMBOL("spell" "CLERIC_CLOUD_OF_PESTILENCE") > 0 BEGIN
    SET code=IDS_OF_SYMBOL("spell" "CLERIC_CLOUD_OF_PESTILENCE")
    SET code=code - 1000
    SPRINT IWDcldp "SPpr%code%"
  END ELSE BEGIN
    SPRINT IWDcldp ""
  END
  // End : Add Spells from IWDification mod or stratagems mods
  DEFINE_ARRAY spells BEGIN  
    ~SPWI004~   // Stinking Cloud (trap)
    ~SPWI016~   // Cloudkill (trap)
    ~SPWI213~   // Stinking Cloud
    ~SPWI502~   // Cloudkill
    ~SPWI614~   // Death Fog
    ~A#CYR11~   // Death Fog (Divine Remix)
    ~SPWI810~   // Incendiary Cloud
    ~DW#TRPIN~  // Incendiary Cloud (Stratagems)
    ~%IWDcldp%~ // Cloud of Pestilence (IWDification)            
    ~SPIN673~   // Cloudkill
    ~dvckill~   // Cloudkill (IR/SR)
    ~SPIN940~   // Stinking Cloud (mephit)
    ~SPIN979~   // Golem Gas Cloud
    ~SPIN642~   // Poisonous Cloud
    ~RR#WI502~  // aTweaks' Cloudkill (used by Marilith)
    ~RR#MMSWF~  // Wall of Fog (aTweaks' Mist Mephit)
    ~RR#FCLD~   // Fog Cloud (aTweaks' Sirine)
    ~RR#FTVAP~  // Toxic Vapors (aTweaks' Mustard Jelly)
    ~RR#MOZSC~  // Stinking Cloud (aTweaks' Ooze Mephit)
    ~RR#ECHSF~  // Solid Fog (aTweaks)
    ~RR#WI213~  // Stinking Cloud (aTweaks)
  END
  LPF ADD_IMMUNITY_CRE_ITM_SPL INT_VAR displaySpellIneffective=1 STR_VAR spells END
END

// Disease immunity
DEFINE_PATCH_FUNCTION disease_immunity BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "SPL" BEGIN
    PATCH_FAIL ~Function disease_immunity was not configured for spell, file: %SOURCE_RES%~
  END
  // Begin : Add Spells from IWDification mod or stratagems mods
  PATCH_IF IDS_OF_SYMBOL("spell" "CLERIC_CAUSE_DISEASE") > 0 BEGIN
    SET code=IDS_OF_SYMBOL("spell" "CLERIC_CAUSE_DISEASE")
    SET code=code - 1000
    SPRINT IWDcdis "SPpr%code%"
  END ELSE BEGIN
    SPRINT IWDcdis ""
  END
  // End : Add Spells from IWDification mod or stratagems mods
  DEFINE_ARRAY spells BEGIN  
    ~SPWI409~   // Contagion
    ~FL#CSDIS~  // aTweaks' Cause Disease
    ~RR#DPDIS~  // aTweaks' Pit Fiend disease
    ~fl#glor2~  // aTweaks' Ghoul Lord disease
    ~fl#mum~    // aTweaks' Mummy disease
    ~fl#gmum~   // aTweaks' Greater Mummy disease
    ~fl#zomsd~  // aTweaks' Zombie Sea disease
    ~rr#gassp~  // aTweaks' (plant) Spore Explosion disease
    ~rr#bogaz~  // aTweaks' Boalisk disease
    ~%IWDcdis%~ // Cause Disease  (IWDification)
  END
  LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR effects=78 prevent_icons=7 strings="39752 54337" spells END
END

// Bleeding immunity
DEFINE_PATCH_FUNCTION bleeding_immunity BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "SPL" BEGIN
    PATCH_FAIL ~Function bleeding_immunity was not configured for spell, file: %SOURCE_RES%~
  END
  DEFINE_ARRAY spells BEGIN RR#BLEED END
  LPF ADD_IMMUNITY_CRE_ITM_SPL INT_VAR prevent_icons=137 strings=54335 STR_VAR spells END
END

// Web immunity
DEFINE_PATCH_FUNCTION web_immunity BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "SPL" BEGIN
    PATCH_FAIL ~Function web_immunity was not configured for spell, file: %SOURCE_RES%~
  END
  DEFINE_ARRAY spells BEGIN  
    ~SPDR201~  // Web (druid version)
    ~SPIN566~  // Mimic Web
    ~SPIN575~  // Vortex web
    ~SPIN683~  // Web Tangle
    ~SPWI215~  // Web (wizard version)
    ~D0SPIWEB~ // Web (D0QUESTPACK)
    ~ETTERWEB~ // Web (heartwood)
    ~spletter~ // Web (heartwood)
    ~wand14~   // Web (IR/IRR)
    ~wtpin05~  // Web (wtp familiar)
    ~rr#spweb~ // aTweaks web tangle
    ~rr#spwr2~ // Wraith web
    ~rr#wi215~ // web (aTweaks)	 			   
  END
  LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR effects=157 prevent_icons=129 spells displaySpellIneffective=1 END
END

// Entangle spell and ability immunities
DEFINE_PATCH_FUNCTION entangle_immunities BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "SPL" BEGIN
    PATCH_FAIL ~Function entangle_immunities was not configured for spell, file: %SOURCE_RES%~
  END
  PATCH_IF IDS_OF_SYMBOL("spell" "WIZARD_CHARM_PLANTS") > 0 BEGIN					// SpellPack Charm plants
    SET code=IDS_OF_SYMBOL("spell" "WIZARD_CHARM_PLANTS") - 2000
    SPRINT spchpl "SPwi%code%"
  END ELSE BEGIN
    SPRINT spchpl ""
  END
  DEFINE_ARRAY spells BEGIN  
    ~SPPR105~  // Entangle (Priest)
    ~SPWM111~  // Entangle (Wild Mage)
    ~SPIN688~  // Plant Growth (Black Dragon)
    ~RR#SMENT~ // Shambler Entangle (RR)
    ~RR#FENTG~ // Hamadryad Entangle (aTweaks)
    ~%spchpl%~ // Charm plants (SpellPack)
  END
  LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR spells displaySpellIneffective=1 END
END

// Insect spell immunities
DEFINE_PATCH_FUNCTION insect_spell_immunities BEGIN
  DEFINE_ARRAY spells BEGIN  
    ~SPPR319~  // Summon Insects
    ~SPPR517~  // Insect Plague
    ~SPPR717~  // Creeping Doom
    ~SPIN689~  // Summon Insects (Black Dragon)
    ~DW#VBAT1~ // Bat Cloud (SCSII)
    ~DW#VBAT2~ // Bat Cloud (SCSII)
    ~CA#IPLAG~ // Insect Plague (PnP Deva)
    ~U#HFDTPD~ // Insect Plague (Ruad)
  END
  LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR spells duration=120 resist_dispel=3 power=3 displaySpellIneffective=1 END
END

// Air Affinity
DEFINE_PATCH_FUNCTION air_affinity BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "SPL" BEGIN
    PATCH_FAIL ~Function air_affinity was not configured for spell, file: %SOURCE_RES%~
  END
  DEFINE_ASSOCIATIVE_ARRAY flyers BEGIN
    118 => 4  // Wyvern
    123 => 4  // Beholder
    136 => 4  // Mist
    139 => 4  // Mephit
    146 => 4  // Dragon
    193 => 5  // Djinni
    196 => 5  // Noble Djinni
    156 => 4  // Solar
    157 => 4  // Antisolar
    158 => 4  // Planatar
    159 => 4  // Darkplanatar
    186 => 5  // Elemental_Air
  END
  PATCH_PHP_EACH flyers AS p1 => p2 BEGIN
    // Damage vs. Creature Type Modifier, Self, Instant/Permanent, IDS Entry, IDS File, Damage bonus
    LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=179 parameter1=EVALUATE_BUFFER "%p1%" parameter2=EVALUATE_BUFFER "%p2%" parameter3=4 END
    // THAC0 vs. Creature Type Modifier, Self, Instant/Permanent, IDS Entry, IDS File, THAC0 bonus
    LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=178 parameter1=EVALUATE_BUFFER "%p1%" parameter2=EVALUATE_BUFFER "%p2%" parameter3=1 END
  END
END

// Earth Affinity
DEFINE_PATCH_FUNCTION earth_affinity BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "SPL" BEGIN
    PATCH_FAIL ~Function earth_affinity was not configured for spell, file: %SOURCE_RES%~
  END
  DEFINE_ASSOCIATIVE_ARRAY air_and_water BEGIN
    118 => 4  // Wyvern
    123 => 4  // Beholder
    131 => 4  // Sahuagin
    135 => 4  // Kuo-Toa
    136 => 4  // Mist
    139 => 4  // Mephit
    146 => 4  // Dragon
    193 => 5  // Djinni
    196 => 5  // Noble Djinni
    156 => 4  // Solar
    157 => 4  // Antisolar
    158 => 4  // Planatar
    159 => 4  // Darkplanatar
    186 => 5  // Elemental_Air
    132 => 5  // Fairy_Nereid
  END
  DEFINE_ARRAY spells BEGIN  
    ~SPOGRE01~ // Earthquake (Ogremoch)
     ~SPPR720~ // Earthquake (Priest version)
     ~rr#equa~ // Earthquake (aTweaks)
       ~CA#EQ~ // Earthquake (PnP Deva)
     ~CDTLQAK~ // Earthquake (mod)
    ~rr#r2mud~ // Rock to mud spell (Dao)
  END
  LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR spells displaySpellIneffective=1 END
  PATCH_PHP_EACH air_and_water AS p1 => p2 BEGIN
    // Damage vs. Creature Type Modifier, Self, Instant/Permanent, IDS Entry, IDS File, Damage bonus
    LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=179 parameter1=EVALUATE_BUFFER "%p1%" parameter2=EVALUATE_BUFFER "%p2%" parameter3="-2" END
    // THAC0 vs. Creature Type Modifier, Self, Instant/Permanent, IDS Entry, IDS File, THAC0 bonus
    LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=178 parameter1=EVALUATE_BUFFER "%p1%" parameter2=EVALUATE_BUFFER "%p2%" parameter3="-2" END
  END
END

// Petrification immunity
DEFINE_PATCH_FUNCTION petrification_immunity BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "SPL" BEGIN
    PATCH_FAIL ~Function petrification_immunity was not configured for spell, file: %SOURCE_RES%~
  END
  LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR effects=134 strings=14665 END
END

// Missile weapon immunity
DEFINE_PATCH_FUNCTION missile_weapon_immunity BEGIN
  PATCH_FOR_EACH ~missile~ IN
    ~1~  // Arrow of Slaying
    ~2~  // Exploding Arrow
    ~3~  // Acid Arrow
    ~4~  // Arrow/Arrow +1
    ~6~  // Throwing Axe
    ~7~  // Throwing Axe
    ~8~  // Bolt
    ~9~  // Throwing Axe
    ~10~ // Throwing Axe
    ~11~ // Bolt+1, Bolt of Biting/Polymorph
    ~12~ // Exploding Bolt
    ~13~ // Bolt (?)
    ~14~ // Bolt
    ~15~ // Bolt of Lightning
    ~16~ // Bullet
    ~17~ // Bullet +1, Sunstone Bullet
    ~18~ // Bullet
    ~19~ // Bullet
    ~26~ // Throwing Dagger
    ~27~ // Throwing Dagger (?)
    ~28~ // Throwing Dagger (?)
    ~29~ // Fire Tooth +3
    ~30~ // Throwing Dagger (?)
    ~31~ // Asp's Nest, Dart of Stunning...
    ~32~ // Dart
    ~33~ // Dart (?)
    ~34~ // Dart (?)
    ~35~ // Dart (?)
    ~55~ // Spear
    ~56~ // Spear
    ~57~ // Spear
    ~58~ // Spear
    ~59~ // Spear
    ~102~ // Flame Arrow Blue
    ~232~ // Energy Spear (Gesen's Bow)
  BEGIN
    LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=83 parameter2=EVAL "%missile%" END
  END
END

// Sleep immunity
DEFINE_PATCH_FUNCTION sleep_immunity BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "SPL" BEGIN
    PATCH_FAIL ~Function sleep_immunity was not configured for spell, file: %SOURCE_RES%~
  END
  LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR effects=39 prevent_icons="14 130" strings="14001 20438" END  
END

// Charm immunity
DEFINE_PATCH_FUNCTION charm_immunity BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "SPL" BEGIN
    PATCH_FAIL ~Function charm_immunity was not configured for spell, file: %SOURCE_RES%~
  END
  LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR effects=5 prevent_icons="0 1 43" strings="8364 14672 14780" animations="SPNWCHRM" END  
END

// Fear immunity
DEFINE_PATCH_FUNCTION fear_immunity BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "SPL" BEGIN
    PATCH_FAIL ~Function fear_immunity was not configured for spell, file: %SOURCE_RES%~
  END
  PATCH_IF IDS_OF_SYMBOL("spell" "WIZARD_EMOTION_FEAR") > 0 BEGIN					// SpellPack Charm plants
    SET code=(IDS_OF_SYMBOL("spell" "WIZARD_EMOTION_FEAR") - 2000 )
    SPRINT spfear "SPwi%code%"
  END ELSE BEGIN
    SPRINT spfear ""
  END
  DEFINE_ARRAY spells BEGIN  
    ~SPIN203~  // Cloak of Fear
    ~SPIN536~  // Fear
    ~SPIN807~  // Salyer Fear
    ~SPIN882~  // Vampire Fear
    ~SPIN890~  // Demon Fear
    ~SPIN895~  // Dragon Fear
    ~SPIN981~  // Fear
    ~SPPR416~  // Cloak of Fear
    ~SPPR706~  // Symbol, Fear
    ~SPWI125~  // Spook
    ~SPWI205~  // Horror
    ~SPWI811~  // Symbol, Fear
    ~SPWI899~  // Symbol, Fear
    ~SPWI956~  // Symbol, Fear
    ~SPWM123~  // Symbol, Fear
    ~fl#cnefr~ // Fear
    ~fl#shafi~ // Fear
    ~fl#tchfr~ // Fear
    ~dw#licfi~ // Fear Aura
    ~ca#sfear~ // Symbol, Fear
    ~A^causfr~ // Cause Fear
    ~rr#dcfea~ // Cause Fear
    ~rr#dcfa1~ // Aura of Fear
    ~rr#dcfa2~ // Aura of Fear
    ~rr#dmfea~ // Blast of Fear
    ~rr#scare~ // Cloak of Fear
    ~rr#wi811~ // Symbol, Fear
    ~DVFEARSM~ // Panic
    ~DVHORRO~  // Panic
    ~%spfear%~ // Emotion: Fear
  END
  LPF ADD_IMMUNITY_CRE_ITM_SPL INT_VAR displaySpellIneffective=1 STR_VAR effects="106 23 24" prevent_icons=36 strings="14007 17427 20568" spells animations="CDHORROR" END
END

// Confusion immunity
DEFINE_PATCH_FUNCTION confusion_immunity BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "SPL" BEGIN
    PATCH_FAIL ~Function confusion_immunity was not configured for spell, file: %SOURCE_RES%~
  END
  DEFINE_ARRAY spells BEGIN  
    ~SPPR709~ // Confusion (priest version)
    ~SPWI401~ // Confusion (wizard version)
    ~SPIN582~ // Confusion
    ~SPIN704~ // Confusion
    ~SPIN839~ // Confusion
    ~SPIN976~ // Confusion
    ~SPPR983~ // Confusion
    ~MISC3M~  // Confusion (Divine Remix)
    ~A#SHA07~ // Confusion (Divine Remix)
    ~RR#WI401~// Confusion (atweaks)
  END
  LPF ADD_IMMUNITY_CRE_ITM_SPL INT_VAR displaySpellIneffective=1 STR_VAR effects=128 prevent_icons=3 strings="14791 14782" spells animations="SPCONFUS" END
END

// Hold immunity
DEFINE_PATCH_FUNCTION hold_immunity BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "SPL" BEGIN
    PATCH_FAIL ~Function hold_immunity was not configured for spell, file: %SOURCE_RES%~
  END
  LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR effects="109 175" prevent_icons=13 strings=14102 animations="SPFLAYER SPMINDAT" END
END                                                                                    // ends DEFINE_PATCH_FUNCTION

// Stun immunity
DEFINE_PATCH_FUNCTION stun_immunity BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "SPL" BEGIN
    PATCH_FAIL ~Function stun_immunity was not configured for spell, file: %SOURCE_RES%~
  END
  LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR effects="45 210" prevent_icons=55 strings="1280 14043" END
END                                                                                    // ends DEFINE_PATCH_FUNCTION

// Polymorph immunity
DEFINE_PATCH_FUNCTION polymorph_immunity BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "SPL" BEGIN
    PATCH_FAIL ~Function polymorph_immunity was not configured for spell, file: %SOURCE_RES%~
  END
  DEFINE_ARRAY spells BEGIN  
    ~SPIN538~ // Polymorph Other
    ~SPWI415~ // Polymorph Other
    ~CA#PAOO~ // Polymorph Other (Pnp Celestial)
  END
  LPF ADD_IMMUNITY_CRE_ITM_SPL INT_VAR displaySpellIneffective=1 STR_VAR effects=135 prevent_icons=124 strings="339 351 809 1482 54332 14128" spells END
END

// Vorpal immunity
DEFINE_PATCH_FUNCTION vorpal_immunity BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "SPL" BEGIN
    PATCH_FAIL ~Function vorpal_immunity was not configured for spell, file: %SOURCE_RES%~
  END
  LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR effects="55 13" strings="64285 14026 10554" END
END

// Skeletal traits
DEFINE_PATCH_FUNCTION add_skeletal_traits BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE CRE AND SOURCE_SIZE > 0x2d3 BEGIN
    WRITE_BYTE 0x5a 100 //Cold
    WRITE_BYTE 0x5f 100 //Magic cold
    WRITE_BYTE 0x60 50  //Slashing
    WRITE_BYTE 0x62 50  //Piercinc
    WRITE_BYTE 0x63 50  //Missile
    LPF cold_spell_immunities END
  END ELSE BEGIN
    PATCH_FAIL ~Incorrect file type or below minimum size~
  END
END

// Immunity to Turn Undead
DEFINE_PATCH_FUNCTION unturnable BEGIN
  PATCH_IF !("%SOURCE_EXT%" STRING_EQUAL_CASE "CRE") BEGIN
    PATCH_FAIL ~Function unturnable was not configured for spell or item, file: %SOURCE_RES%~
  END
  LPF ADD_CRE_EFFECT INT_VAR opcode=297 target=1 timing=9 paramater2=1 END
END

// Illusion immmunity
DEFINE_PATCH_FUNCTION illusion_immunity BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "SPL" BEGIN
    PATCH_FAIL ~Function illusion_immunity was not configured for spell, file: %SOURCE_RES%~
  END
  DEFINE_ARRAY spells BEGIN  
    sppr704 //Nature's beauty
    spwi106 //Blindness
    IKDB2   //Spook (mod)
    spwi125 //Spook
    spwi223 //Deafness
    spwm178 //Blindness (Wild mage)
  END
  LPF ADD_IMMUNITY_CRE_ITM_SPL INT_VAR displaySpellIneffective=1 STR_VAR spells END
END

// Extraplanar traits
DEFINE_PATCH_FUNCTION extraplanar_traits BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "SPL" BEGIN
    PATCH_FAIL ~Function extraplanar_traits was not configured for spell, file: %SOURCE_RES%~
  END
  DEFINE_ARRAY spells BEGIN  
    ~SPWI605~ // Death Spell
    ~cdxvdth~ // Death Spell (mod)
  END
  LPF ADD_IMMUNITY_CRE_ITM_SPL INT_VAR displaySpellIneffective=1 STR_VAR spells END
  LPF cure_spell_immunities END                                        
END

// Hover (flight) spell immunities
DEFINE_PATCH_FUNCTION hover_immunities BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "SPL" BEGIN
    PATCH_FAIL ~Function hover_immunities was not configured for spell, file: %SOURCE_RES%~
  END
  DEFINE_ARRAY spells BEGIN  
    ~SPIN561~ // Fire Giant Lava Pit (FIRE_GIANT_LAVA)
    ~SPIN819~ // Lava Burst (LAVA_BURST)
    ~SPIN994~ // Acid Pools in Durlag's Tower (ACID_DAMAGE_1)
    ~SPWI022~ // Lava Pit (TRAP_MUCK)
    ~SPIN914~ // Mimic Glue
   ~SPOGRE01~ // Earthquake (Ogremoch)
    ~SPPR720~ // Earthquake (Priest version)
    ~rr#equa~ // Earthquake (aTweaks)
      ~CA#EQ~ // Earthquake (PnP Deva)
    ~CDTLQAK~ // Earthquake (mod)
    ~SPWI101~ // Grease
   ~rr#r2mud~	// Rock to mud spell (Dao)
  END
  LPF ADD_IMMUNITY_CRE_ITM_SPL STR_VAR spells END
  LPF entangle_immunities END                                          
  LPF web_immunity END
END

// Plant traits
DEFINE_PATCH_FUNCTION plant_traits BEGIN
  LPF disease_immunity END
  LPF bleeding_immunity END
  LPF petrification_immunity END
  LPF stun_immunity END
  LPF hold_immunity END
  LPF polymorph_immunity END
  LPF confusion_immunity END
  LPF charm_immunity END
  LPF fear_immunity END
  LPF sleep_immunity END
  LPF illusion_immunity END
  LPF poison_immunity END
  LPF insect_spell_immunities END
  LPF entangle_immunities END
END
