COMPILE ~%MOD_FOLDER%/lib/pnp-monster/basilisk/ja#m3.baf~
COMPILE ~%MOD_FOLDER%/lib/pnp-monster/basilisk/ja#m3su.baf~

CREATE ITM "ja#m3w1"
	WRITE_LONG 0x64 0x72
	WRITE_SHORT 0x68 1
	WRITE_LONG 0x6a 0xaa
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x72 1
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 1
	WRITE_SHORT 0x84 3
	WRITE_BYTE 0x88 6
	WRITE_BYTE 0x8a 1
	WRITE_SHORT 0x8e 3
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
	LPF set_enchantment INT_VAR enchantment = 0 END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 25
			target = 2
			parameter1 = 6
			parameter2 = 3
			probability1 = 100
			savingthrow = 4
			savebonus = "4"
	END

CREATE ITM "ja#m3w2"
	WRITE_LONG 0x64 0x72
	WRITE_SHORT 0x68 1
	WRITE_LONG 0x6a 0xaa
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x72 1
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 1
	WRITE_SHORT 0x84 3
	WRITE_BYTE 0x88 8
	WRITE_BYTE 0x8a 2
	WRITE_SHORT 0x8e 1
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
	LPF set_enchantment INT_VAR enchantment = 0 END

ACTION_FOR_EACH ~file~ IN
	AC#BASGR
	BASILG
	BASILGSU
	BASILMUT
	BASILNAD
	BD302BAS
	BPBASG01
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~BASILG1~
			REMOVE_CRE_ITEM ~BASILG2~
			REMOVE_CRE_ITEM ~BASILG3~
			ADD_CRE_ITEM ~ja#m3w1~ #0 #0 #0 ~UNDROPPABLE~ ~weapon1~ EQUIP
			ADD_CRE_ITEM ~ja#m3w2~ #0 #0 #0 ~UNDROPPABLE~ ~weapon2~
			ADD_MEMORIZED_SPELL ~ja#1m2~ #0 ~innate~ (1)
			ADD_MEMORIZED_SPELL ~ja#2m2~ #0 ~innate~ (1)
			LPF patchCreature
				INT_VAR
					level1=10
					strength=20
					dexterity=8
					constitution=19
					intelligence=7
					wisdom=12
					charisma=11
					movement=6
					hp=80
					ac=2
					thac0=11
					apr=3
					xpv=7000
					alignment=34
					saveDeath=8
					saveWand=10
					savePolymorph=9
					saveBreath=9
					saveSpell=11
					morale=16
					moraleBreak=4
					moraleRecovery=15
					general=255
					race=102
					class=103
					gender=4
					sex=4
					enforce=1
			END
			DEFINE_ARRAY removeScripts BEGIN
				GBASILSK
				SHOUT
				WTASIGHT
				wtrunsgt
				DW2MP0GE
				DW2RC2MO
			END
			LPF patchCreatureScript STR_VAR script=ja#m3 removeScripts skipFiles END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~BASILGSU~) BEGIN 
				DEFINE_ARRAY removeScripts BEGIN
					ja#m3
					GBASILSK
					SHOUT
					WTASIGHT
					wtrunsgt
					DW2MP0GE
					DW2RC2MO
				END
				LPF patchCreatureScript STR_VAR script=ja#m3su removeScripts skipFiles END
			END
		BUT_ONLY_IF_IT_CHANGES
	END
END