// Summons are destroyed on death
IF
	Die()
THEN
	RESPONSE #100
		DestroySelf()
END

// Detect combat
IF
	Global("JA#COMBAT","LOCALS",0)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
		Shout(98)
END

// React to shouts
IF
	Global("JA#COMBAT","LOCALS",0)
	Heard(LastSummonerOf(Myself),98)
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
END

// Summon follow summoner
IF
	Global("JA#COMBAT","LOCALS",0)
	!StateCheck(Myself,STATE_BLIND)
	ActionListEmpty()
	!See(NearestEnemyOf(Myself))
	!See(LastSummonerOf(Myself))
	HPGT(LastSummonerOf(Myself),0)
	Range(LastSummonerOf(Myself),150)
THEN
	RESPONSE #100
		MoveToObject(LastSummonerOf(Myself))
END

// Do nothing if combat is not started
IF
	Global("JA#COMBAT","LOCALS",0)
	ActionListEmpty()
THEN
	RESPONSE #100
		NoAction()
END

// Track players if allegiance is not GOODCUTOFF
IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	!See(NearestEnemyOf(Myself))
	Range(Player1,150)
	!CheckStatGT(Player1,0,SANCTUARY)
	!StateCheck(Player1,STATE_CHARMED)
	!StateCheck(Player1,STATE_REALLY_DEAD)
	!StateCheck(Player1,STATE_INVISIBLE)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	See(Player1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	!See(NearestEnemyOf(Myself))
	Range(Player2,150)
	!CheckStatGT(Player2,0,SANCTUARY)
	!StateCheck(Player2,STATE_CHARMED)
	!StateCheck(Player2,STATE_REALLY_DEAD)
	!StateCheck(Player2,STATE_INVISIBLE)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	See(Player2)
THEN
	RESPONSE #100
		MoveToObject(Player2)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	!See(NearestEnemyOf(Myself))
	Range(Player3,150)
	!CheckStatGT(Player3,0,SANCTUARY)
	!StateCheck(Player3,STATE_CHARMED)
	!StateCheck(Player3,STATE_REALLY_DEAD)
	!StateCheck(Player3,STATE_INVISIBLE)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	See(Player3)
THEN
	RESPONSE #100
		MoveToObject(Player3)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	!See(NearestEnemyOf(Myself))
	Range(Player4,150)
	!CheckStatGT(Player4,0,SANCTUARY)
	!StateCheck(Player4,STATE_CHARMED)
	!StateCheck(Player4,STATE_REALLY_DEAD)
	!StateCheck(Player4,STATE_INVISIBLE)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	See(Player4)
THEN
	RESPONSE #100
		MoveToObject(Player4)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	!See(NearestEnemyOf(Myself))
	Range(Player5,150)
	!CheckStatGT(Player5,0,SANCTUARY)
	!StateCheck(Player5,STATE_CHARMED)
	!StateCheck(Player5,STATE_REALLY_DEAD)
	!StateCheck(Player5,STATE_INVISIBLE)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	See(Player5)
THEN
	RESPONSE #100
		MoveToObject(Player5)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	!See(NearestEnemyOf(Myself))
	Range(Player6,150)
	!CheckStatGT(Player6,0,SANCTUARY)
	!StateCheck(Player6,STATE_CHARMED)
	!StateCheck(Player6,STATE_REALLY_DEAD)
	!StateCheck(Player6,STATE_INVISIBLE)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	See(Player6)
THEN
	RESPONSE #100
		MoveToObject(Player6)
END

// Track last seen enemy if allegiance is GOODCUTOFF
IF
	Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	!See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),150)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

// Random walking outside of combat
IF
	ActionListEmpty()
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		RandomWalk()
		Wait(2)
END

// Petrification
IF
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	OR(9)
		!Range(NearestEnemyOf(Myself),30)
		CheckStatGT(NearestEnemyOf(Myself),0,HELD)
		General(NearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(NearestEnemyOf(Myself),STATE_REALLY_DEAD)
		StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
		!See(NearestEnemyOf(Myself))
		RandomNumGT(1000,100)
	OR(9)
		!Range(SecondNearestEnemyOf(Myself),30)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
		General(SecondNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_INVISIBLE)
		!See(SecondNearestEnemyOf(Myself))
		RandomNumGT(1000,111)
	OR(9)
		!Range(ThirdNearestEnemyOf(Myself),30)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
		General(ThirdNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_INVISIBLE)
		!See(ThirdNearestEnemyOf(Myself))
		RandomNumGT(1000,125)
	OR(9)
		!Range(FourthNearestEnemyOf(Myself),30)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
		General(FourthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_INVISIBLE)
		!See(FourthNearestEnemyOf(Myself))
		RandomNumGT(1000,143)
	OR(9)
		!Range(FifthNearestEnemyOf(Myself),30)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
		General(FifthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_INVISIBLE)
		!See(FifthNearestEnemyOf(Myself))
		RandomNumGT(1000,167)
	OR(9)
		!Range(SixthNearestEnemyOf(Myself),30)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
		General(SixthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_INVISIBLE)
		!See(SixthNearestEnemyOf(Myself))
		RandomNumGT(1000,200)
	OR(9)
		!Range(SeventhNearestEnemyOf(Myself),30)
		CheckStatGT(SeventhNearestEnemyOf(Myself),0,HELD)
		General(SeventhNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SeventhNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_INVISIBLE)
		!See(SeventhNearestEnemyOf(Myself))
		RandomNumGT(1000,250)
	OR(9)
		!Range(EighthNearestEnemyOf(Myself),30)
		CheckStatGT(EighthNearestEnemyOf(Myself),0,HELD)
		General(EighthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(EighthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_INVISIBLE)
		!See(EighthNearestEnemyOf(Myself))
		RandomNumGT(1000,333)
	OR(9)
		!Range(NinthNearestEnemyOf(Myself),30)
		CheckStatGT(NinthNearestEnemyOf(Myself),0,HELD)
		General(NinthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NinthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_INVISIBLE)
		!See(NinthNearestEnemyOf(Myself))
		RandomNumGT(1000,500)
	OR(8)
		!Range(TenthNearestEnemyOf(Myself),30)
		CheckStatGT(TenthNearestEnemyOf(Myself),0,HELD)
		General(TenthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(TenthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_INVISIBLE)
		!See(TenthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Continue()
END

IF
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	Range(LastSeenBy(Myself),30)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		ForceSpellRES("ja#m2s1",LastSeenBy(Myself))
		SetGlobalTimer("JA#ROUND","LOCALS",6)
END

// Attack NEAREST enemy
IF
	OR(6)
		General(NearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(NearestEnemyOf(Myself),STATE_REALLY_DEAD)
		StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
		!See(NearestEnemyOf(Myself))
	OR(6)
		General(SecondNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_INVISIBLE)
		!See(SecondNearestEnemyOf(Myself))
	OR(6)
		General(ThirdNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_INVISIBLE)
		!See(ThirdNearestEnemyOf(Myself))
	OR(6)
		General(FourthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_INVISIBLE)
		!See(FourthNearestEnemyOf(Myself))
	OR(6)
		General(FifthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_INVISIBLE)
		!See(FifthNearestEnemyOf(Myself))
	OR(6)
		General(SixthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_INVISIBLE)
		!See(SixthNearestEnemyOf(Myself))
	OR(6)
		General(SeventhNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SeventhNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_INVISIBLE)
		!See(SeventhNearestEnemyOf(Myself))
	OR(6)
		General(EighthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(EighthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_INVISIBLE)
		!See(EighthNearestEnemyOf(Myself))
	OR(6)
		General(NinthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NinthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_INVISIBLE)
		!See(NinthNearestEnemyOf(Myself))
	OR(6)
		General(TenthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(TenthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_INVISIBLE)
		!See(TenthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Continue()
END

IF
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

