COMPILE ~%MOD_FOLDER%/lib/pnp-monster/basilisk/ja#m2.baf~
COMPILE ~%MOD_FOLDER%/lib/pnp-monster/basilisk/ja#m2su.baf~

COPY_EXISTING "gaze.pro" ~override/ja#1m2.pro~
	READ_SHORT 0x08 type
	PATCH_IF (%type% = 1) BEGIN
		INSERT_BYTES 0x100 0x100
	END
	PATCH_IF (%type% != 3) BEGIN
		INSERT_BYTES 0x200 0x100
	END
	WRITE_SHORT 0x08 3
	WRITE_LONG 0x200 2112
	WRITE_SHORT 0x204 255
	WRITE_SHORT 0x206 255
	WRITE_SHORT 0x212 0x4001
	WRITE_BYTE 0x217 255
	WRITE_SHORT 0x224 60
ADD_PROJECTILE ~override/ja#1m2.pro~ ~Basilisk petrifying gaze~

CREATE SPL "ja#1m2"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x28
	WRITE_SHORT 0x68 1
	WRITE_LONG 0x6a 0x9a
	WRITE_SHORT 0x72 2
	WRITE_SHORT 0x82 1
	WRITE_SHORT 0x1c 4
	WRITE_BYTE 0x27 11
	WRITE_LONG 0x34 1
	WRITE_SHORT 0x74 4
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 30
	SAY NAME1 @4002 SAY NAME2 @4002
	SAY UNIDENTIFIED_DESC ~Any creature, that can see and within 30 feet of the basilisk, must save vs petrify at -4. On a failed save, the creature is petrified until freed by the greater restoration spell or other magic.~
	WRITE_SHORT 0x98 (IDS_OF_SYMBOL (~projectl~ ~ja#1m2~)) + 1
	LPF ADD_EFFECT
		INT_VAR
			opcode = 134
			target = 2
			parameter1 = 0
			parameter2 = 0
			probability1 = 100
			savingthrow = 16
			savebonus = "-4"
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 139
			target = 2
			parameter1 = RESOLVE_STR_REF(@4004)
			parameter2 = 0
			probability1 = 100
			savingthrow = 16
			savebonus = "-4"
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 174
			target = 2
			parameter1 = 0
			parameter2 = 0
			probability1 = 100
			savingthrow = 16
			savebonus = "-4"
		STR_VAR
			resource = "MISC_06B"
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 215
			target = 2
			parameter1 = 0
			parameter2 = 0
			probability1 = 100
			savingthrow = 16
			savebonus = "-4"
		STR_VAR
			resource = "SPFLESHS.VVC"
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 61
			target = 2
			parameter1 = 2021160960
			parameter2 = 1638400
			probability1 = 100
			savingthrow = 16
			savebonus = "-4"
		END

CREATE SPL "ja#2m2"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x28
	WRITE_SHORT 0x68 1
	WRITE_LONG 0x6a 0x9a
	WRITE_SHORT 0x72 2
	WRITE_SHORT 0x82 1
	WRITE_SHORT 0x1c 4
	WRITE_BYTE 0x27 11
	WRITE_LONG 0x34 1
	WRITE_SHORT 0x74 4
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 30
	SAY NAME1 @4002 SAY NAME2 @4002
	SAY UNIDENTIFIED_DESC ~Any creature, that can see and within 30 feet of the basilisk, must save vs petrify at -4.
On a failed save, the creature magically begins to turn to stone and is restrained.
It must repeat the saving throw at the end of its next turn. On a success, the effect ends. On a failure, the creature is petrified until freed by the greater restoration spell or other magic.~
	WRITE_SHORT 0x98 (IDS_OF_SYMBOL (~projectl~ ~ja#2m2~)) + 1
	LPF ADD_EFFECT
		INT_VAR
			opcode = 139
			target = 2
			parameter1 = RESOLVE_STR_REF(@4005)
			parameter2 = 0
			probability1 = 100
			savingthrow = 16
			savebonus = "-4"
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 139
			target = 2
			parameter1 = RESOLVE_STR_REF(@4003)
			parameter2 = 0
			timing = 1
			probability1 = 100
			savingthrow = 16
			savebonus = "-4"
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 141
			target = 2
			parameter1 = 0
			parameter2 = 13
			timing = 1
			probability1 = 100
			savingthrow = 16
			savebonus = "-4"
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 40
			target = 2
			parameter1 = 0
			parameter2 = 0
			duration = 12
			probability1 = 100
			savingthrow = 16
			savebonus = "-4"
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 176
			target = 2
			parameter1 = 0
			parameter2 = 1
			duration = 12
			probability1 = 100
			savingthrow = 16
			savebonus = "-4"
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 278
			target = 2
			parameter1 = "-4"
			parameter2 = 0
			duration = 12
			probability1 = 100
			savingthrow = 16
			savebonus = "-4"
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 0
			target = 2
			parameter1 = "-4"
			parameter2 = 0
			duration = 12
			probability1 = 100
			savingthrow = 16
			savebonus = "-4"
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 36
			target = 2
			parameter1 = "-4"
			parameter2 = 0
			duration = 12
			probability1 = 100
			savingthrow = 16
			savebonus = "-4"
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 146
			target = 2
			parameter1 = 0
			parameter2 = 1
			timing = 3
			duration = 12
			probability1 = 100
			savingthrow = 16
			savebonus = "-4"
		STR_VAR
			resource = "ja#3m2"
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 206
			target = 2
			parameter1 = 0
			parameter2 = 0
			timing = 3
			duration = 12
			probability1 = 100
			savingthrow = 16
			savebonus = "-4"
		STR_VAR
			resource = "ja#2m2"
		END

CREATE SPL "ja#3m2"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x28
	WRITE_SHORT 0x68 1
	WRITE_LONG 0x6a 0x9a
	WRITE_SHORT 0x72 2
	WRITE_SHORT 0x82 1
	WRITE_SHORT 0x1c 4
	WRITE_BYTE 0x27 11
	WRITE_LONG 0x34 1
	WRITE_SHORT 0x74 4
	WRITE_BYTE 0x7e 1
	SAY NAME1 @4002 SAY NAME2 @4002
	LPF ADD_EFFECT
		INT_VAR
			opcode = 134
			target = 2
			parameter1 = 0
			parameter2 = 0
			timing = 9
			probability1 = 100
			savingthrow = 16
			savebonus = "-4"
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 139
			target = 2
			parameter1 = RESOLVE_STR_REF(@4004)
			parameter2 = 0
			timing = 9
			probability1 = 100
			savingthrow = 16
			savebonus = "-4"
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 174
			target = 2
			parameter1 = 0
			parameter2 = 0
			timing = 9
			probability1 = 100
			savingthrow = 16
			savebonus = "-4"
		STR_VAR
			resource = "MISC_06B"
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 215
			target = 2
			parameter1 = 0
			parameter2 = 0
			timing = 9
			probability1 = 100
			savingthrow = 16
			savebonus = "-4"
		STR_VAR
			resource = "SPFLESHS.VVC"
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 61
			target = 2
			parameter1 = 2021160960
			parameter2 = 1638400
			timing = 9
			probability1 = 100
			savingthrow = 16
			savebonus = "-4"
		END

CREATE ITM "ja#m2w1"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_LONG 0x60 1
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 1
	WRITE_SHORT 0x84 3
	WRITE_BYTE 0x88 10
	WRITE_BYTE 0x8a 1
	WRITE_SHORT 0x8e 3
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
COPY_EXISTING ~ja#m2w1.itm~ ~override~

ACTION_FOR_EACH ~file~ IN
	BASILL
	BASILLSU
	BPBASL01
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~BASILL1~
			REMOVE_CRE_ITEM ~BASILL2~
			ADD_CRE_ITEM ~ja#m2w1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			ADD_MEMORIZED_SPELL ~ja#1m2~ #0 ~innate~ (1)
			ADD_MEMORIZED_SPELL ~ja#2m2~ #0 ~innate~ (1)
			LPF clearProficiencies END
			LPF patchCreature
				INT_VAR
					level1=6
					strength=16
					dexterity=8
					constitution=15
					intelligence=2
					wisdom=8
					charisma=7
					movement=5
					hp=54
					ac=4
					thac0=15
					apr=1
					xpv=1400
					alignment=IDS_OF_SYMBOL (~alignment~ ~NEUTRAL~)
					saveDeath=11
					saveWand=13
					savePolymorph=12
					saveBreath=13
					saveSpell=14
					morale=12
					moraleBreak=4
					moraleRecovery=15
					general=IDS_OF_SYMBOL (~general~ ~MONSTER~)
					race=IDS_OF_SYMBOL (~race~ ~BASILISK~)
					class=IDS_OF_SYMBOL (~class~ ~BASILISK~)
					gender=IDS_OF_SYMBOL (~gender~ ~NIETHER~)
					sex=IDS_OF_SYMBOL (~gender~ ~NIETHER~)
					enforce=1
			END
			DEFINE_ARRAY removeScripts BEGIN LBASILSK END
			DEFINE_ARRAY skipFiles BEGIN BASILLSU END
			LPF patchCreatureScript STR_VAR script=ja#m2 skipFiles removeScripts END
			DEFINE_ARRAY removeScripts BEGIN LBASILSK END
			DEFINE_ARRAY files BEGIN BASILLSU END
			LPF patchCreatureScript STR_VAR script=ja#m2su files removeScripts END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~BASILLSU~) BEGIN 
				LPF patchCreature
					INT_VAR
						hp=54
						thac0=15
						xpv=0
						saveDeath=11
						saveWand=13
						savePolymorph=12
						saveBreath=13
						saveSpell=14
						summon=1
				END
			END
		BUT_ONLY_IF_IT_CHANGES
	END
END