COMPILE ~%MOD_FOLDER%/lib/pnp-monster/bear/ja#m4.baf~
COMPILE ~%MOD_FOLDER%/lib/pnp-monster/bear/ja#m4su.baf~

CREATE ITM "ja#1m4"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 1
	WRITE_BYTE 0x88 3
	WRITE_BYTE 0x8a 1
	WRITE_SHORT 0x8e 3
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
COPY_EXISTING ~ja#1m4.itm~ ~override~
	LPF ADD_EFFECT
		INT_VAR
			opcode = 139
			target = 2
			parameter1 = RESOLVE_STR_REF(@4007)
			probability1 = 10
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 12
			target = 2
			probability1 = 10
			dicenumber = 2
			dicesize = 4
		END

CREATE ITM "ja#2m4"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 1
	WRITE_BYTE 0x88 6
	WRITE_BYTE 0x8a 1
	WRITE_SHORT 0x8e 1
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
COPY_EXISTING ~ja#2m4.itm~ ~override~

ACTION_FOR_EACH ~file~ IN
	BDBEARBL
	BEARBL
	BEARBLSU
	PLYBEAR2
	RSBEARBL
	UBDBEAR
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~B1-6~
			ADD_CRE_ITEM ~ja#1m4~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			ADD_CRE_ITEM ~ja#2m4~ #0 #0 #0 ~UNDROPPABLE~ ~SHIELD~ 
			LPF clearProficiencies END
			LPF patchCreature
				INT_VAR
					level1=3
					strength=15
					dexterity=10
					constitution=15
					intelligence=4
					wisdom=12
					charisma=7
					movement=10
					hp=27
					ac=7
					thac0=17
					apr=2
					xpv=175
					alignment=IDS_OF_SYMBOL (~align~ ~NEUTRAL~)
					saveDeath=13
					saveWand=15
					savePolymorph=14
					saveBreath=16
					saveSpell=16
					morale=9
					moraleBreak=4
					moraleRecovery=15
					general=IDS_OF_SYMBOL (~general~ ~ANIMAL~)
					race=IDS_OF_SYMBOL (~race~ ~BEAR~)
					class=IDS_OF_SYMBOL (~class~ ~BEAR_BLACK~)
					gender=IDS_OF_SYMBOL (~gender~ ~NIETHER~)
					sex=IDS_OF_SYMBOL (~gender~ ~NIETHER~)
					enforce=1
					perfect2weapon=1
			END
			DEFINE_ARRAY removeScripts BEGIN CBEAR BEAR END
			DEFINE_ARRAY skipFiles BEGIN BEARBLSU END
			LPF patchCreatureScript STR_VAR script=ja#m4 skipFiles removeScripts END
			DEFINE_ARRAY removeScripts BEGIN CBEAR BEAR END
			DEFINE_ARRAY files BEGIN BEARBLSU END
			LPF patchCreatureScript STR_VAR script=ja#m4su files removeScripts END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~BEARBLSU~) BEGIN 
				LPF patchCreature
					INT_VAR
						hp=27
						thac0=17
						xpv=0
						saveDeath=13
						saveWand=15
						savePolymorph=14
						saveBreath=16
						saveSpell=16
						summon=1
				END
			END
		BUT_ONLY_IF_IT_CHANGES
	END ELSE BEGIN
		PRINT ~====> CRE %file% not found!~
	END
END