COMPILE ~%MOD_FOLDER%/lib/pnp-monster/bear/ja#m5.baf~
COMPILE ~%MOD_FOLDER%/lib/pnp-monster/bear/ja#m5su.baf~

CREATE ITM "ja#m5w1"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_LONG 0x60 1
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 2
	WRITE_SHORT 0x84 3
	WRITE_BYTE 0x88 6
	WRITE_BYTE 0x8a 1
	WRITE_SHORT 0x8e 3
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
	LPF ADD_EFFECT
		INT_VAR
			opcode = 139
			target = 2
			parameter1 = RESOLVE_STR_REF(@4007)
			parameter2 = 0
			probability1 = 10
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 12
			target = 2
			parameter1 = 0
			parameter2 = 0
			probability1 = 10
			dicenumber = 2
			dicesize = 6
		END

CREATE ITM "ja#m5w2"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_LONG 0x60 1
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 2
	WRITE_SHORT 0x84 3
	WRITE_BYTE 0x88 8
	WRITE_BYTE 0x8a 1
	WRITE_SHORT 0x8e 1
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1

ACTION_FOR_EACH ~file~ IN
	BDBEARBN
	BDGRIZHU
	BEARBR
	BEARBRSU
	PLYBEAR1
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~B1-8~
			ADD_CRE_ITEM ~ja#m5w1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			ADD_CRE_ITEM ~ja#m5w2~ #0 #0 #0 ~UNDROPPABLE~ ~SHIELD~ 
			LPF clearProficiencies END
			LPF patchCreature
				INT_VAR
					level1=5
					strength=19
					dexterity=10
					constitution=16
					intelligence=4
					wisdom=13
					charisma=7
					movement=10
					hp=58
					ac=6
					thac0=15
					apr=3
					xpv=420
					alignment=34
					saveDeath=11
					saveWand=13
					savePolymorph=12
					saveBreath=13
					saveSpell=14
					morale=9
					moraleBreak=4
					moraleRecovery=15
					general=255
					race=103
					class=105
					gender=4
					sex=4
					enforce=1
			END
			DEFINE_ARRAY removeScripts BEGIN CBEAR BEAR END
			DEFINE_ARRAY skipFiles BEGIN BEARBRSU END
			LPF patchCreatureScript STR_VAR script=ja#m5 skipFiles removeScripts END
			DEFINE_ARRAY removeScripts BEGIN CBEAR BEAR END
			DEFINE_ARRAY files BEGIN BEARBRSU END
			LPF patchCreatureScript STR_VAR script=ja#m5su files removeScripts END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~BEARBRSU~) BEGIN 
				LPF patchCreature
					INT_VAR
						hp=50
						thac0=15
						xpv=0
						saveDeath=11
						saveWand=13
						savePolymorph=12
						saveBreath=13
						saveSpell=14
						summon=1
				END
			END
		BUT_ONLY_IF_IT_CHANGES
	END
END