COMPILE ~%MOD_FOLDER%/lib/pnp-monster/bear/ja#m6.baf~
COMPILE ~%MOD_FOLDER%/lib/pnp-monster/bear/ja#m6su.baf~

CREATE ITM "ja#m6w1"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_LONG 0x60 2
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 2
	WRITE_SHORT 0x84 3
	WRITE_BYTE 0x88 8
	WRITE_BYTE 0x8a 1
	WRITE_SHORT 0x8e 3
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
COPY_EXISTING ~ja#m6w1.itm~ ~override~
	LPF ADD_EFFECT
		INT_VAR
			opcode = 139
			target = 2
			parameter1 = RESOLVE_STR_REF(@4007)
			parameter2 = 0
			probability1 = 10
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 12
			target = 2
			parameter1 = 0
			parameter2 = 0
			probability1 = 10
			dicenumber = 2
			dicesize = 6
		END

CREATE ITM "ja#m6w2"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_LONG 0x60 2
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 2
	WRITE_SHORT 0x84 3
	WRITE_BYTE 0x88 12
	WRITE_BYTE 0x8a 1
	WRITE_SHORT 0x8e 1
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
COPY_EXISTING ~ja#m6w2.itm~ ~override~

ACTION_FOR_EACH ~file~ IN
	BD328OSO
	BDBEARCA
	BEARCA
	BEARCASU
	CAVENE
	URSA
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			PATCH_IF NOT "%SOURCE_RES%" STRING_EQUAL_CASE ~BDBEARCA~ BEGIN
				REMOVE_MEMORIZED_SPELLS
			END
			REMOVE_CRE_ITEM ~B1-10~
			REMOVE_CRE_ITEM ~BEARCASU~
			ADD_CRE_ITEM ~ja#m6w1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			ADD_CRE_ITEM ~ja#m6w2~ #0 #0 #0 ~UNDROPPABLE~ ~SHIELD~ 
			LPF clearProficiencies END
			LPF patchCreature
				INT_VAR
					level1=6
					strength=20
					dexterity=10
					constitution=16
					intelligence=4
					wisdom=13
					charisma=7
					movement=10
					hp=68
					ac=6
					thac0=13
					apr=3
					xpv=650
					alignment=34
					saveDeath=11
					saveWand=13
					savePolymorph=12
					saveBreath=13
					saveSpell=14
					morale=9
					moraleBreak=4
					moraleRecovery=15
					general=255
					race=103
					class=106
					gender=4
					sex=4
					enforce=1
			END
			DEFINE_ARRAY removeScripts BEGIN CBEAR BEAR END
			DEFINE_ARRAY skipFiles BEGIN BEARCASU BDBEARCA END
			LPF patchCreatureScript STR_VAR script=ja#m6 skipFiles removeScripts END
			DEFINE_ARRAY removeScripts BEGIN CBEAR BEAR END
			DEFINE_ARRAY files BEGIN BEARCASU END
			LPF patchCreatureScript STR_VAR script=ja#m6su files removeScripts END
			DEFINE_ARRAY files BEGIN BDBEARCA END
			LPF patchCreatureScript STR_VAR script=ja#m6 slot=General files END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~BEARCASU~) BEGIN 
				LPF patchCreature
					INT_VAR
						hp=60
						thac0=15
						xpv=0
						saveDeath=11
						saveWand=13
						savePolymorph=12
						saveBreath=13
						saveSpell=14
						summon=1
				END
			END
		BUT_ONLY_IF_IT_CHANGES
	END
END