COMPILE ~%MOD_FOLDER%/lib/pnp-monster/bear/ja#m8.baf~

COPY_EXISTING "CONECOLD.pro" ~override/ja#1m8.pro~
	READ_SHORT 0x08 type
	PATCH_IF (%type% = 1) BEGIN
		INSERT_BYTES 0x100 0x100
	END
	WRITE_LONG 0x200 80
	WRITE_SHORT 0x204 180
	WRITE_SHORT 0x206 180
ADD_PROJECTILE ~override/ja#1m8.pro~ ~Improved stream of frost~

COPY_EXISTING "FIREBALL.pro" ~override/ja#2m8.pro~
	READ_SHORT 0x08 type
	PATCH_IF (%type% = 1) BEGIN
		INSERT_BYTES 0x100 0x100
	END
	PATCH_IF (%type% != 3) BEGIN
		INSERT_BYTES 0x200 0x100
	END
	WRITE_SHORT 0x08 3
	WRITE_LONG 0x200 64
	WRITE_SHORT 0x204 180
	WRITE_SHORT 0x206 180
ADD_PROJECTILE ~override/ja#2m8.pro~ ~Improved stream of frost~

CREATE SPL "ja#1m8"
	WRITE_SHORT 0x1c 4
	WRITE_BYTE 0x27 10
	WRITE_LONG 0x34 1
	WRITE_LONG 0x64 0x72
	WRITE_SHORT 0x68 1
	WRITE_LONG 0x6a 0x9a
	INSERT_BYTES 0x72 0x28
	WRITE_SHORT 0x72 2
	WRITE_SHORT 0x74 4
	WRITE_BYTE 0x7e 4
	WRITE_SHORT 0x80 10
	WRITE_SHORT 0x82 1
	WRITE_SHORT 0x94 1
	SAY NAME1 @4008 SAY NAME2 @4008
	SAY UNIDENTIFIED_DESC ~Unleash a stream of frost, causing 6d4 points of damage to everything within 10 feet. A save vs. breath weapon is allowed for half damage. Affected creatures are also paralyzed for one turn (saves vs paralyze at -2)~
	WRITE_SHORT 0x98 (IDS_OF_SYMBOL (~projectl~ ~ja#1m8~)) + 1
	LPF ADD_EFFECT
		INT_VAR
			opcode = 12
			target = 2
			parameter1 = 0
			parameter2 = 131072
			timing = 1
			probability1 = 100
			dicenumber = 6
			dicesize = 4
			savingthrow = 2
			special = 256
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 50
			target = 2
			parameter1 = "-2786560"
			parameter2 = 1310720
			timing = 1
			probability1 = 100
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 109
			target = 2
			parameter1 = IDS_OF_SYMBOL (~EA~ ~ANYONE~)
			parameter2 = 2
			duration = 60
			probability1 = 100
			savingthrow = 4
			savebonus = "-2"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 142
			target = 2
			parameter1 = 0
			parameter2 = 13
			duration = 60
			probability1 = 100
			savingthrow = 4
			savebonus = "-2"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 174
			target = 2
			parameter1 = 0
			parameter2 = 0
			timing = 1
			probability1 = 100
			savingthrow = 4
			savebonus = "-2"
		STR_VAR
			resource = "MISC_04A"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 174
			target = 2
			parameter1 = 0
			parameter2 = 0
			timing = 4
			duration = 60
			probability1 = 100
			savingthrow = 4
			savebonus = "-2"
		STR_VAR
			resource = "EFF_E03"
	END

ACTION_FOR_EACH ~file~ IN
	KALDRAN
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~KALDW1~
			REMOVE_CRE_ITEM ~B1-12~
			ADD_CRE_ITEM ~ja#m7w1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			ADD_CRE_ITEM ~ja#m7w2~ #0 #0 #0 ~UNDROPPABLE~ ~SHIELD~ 
			ADD_MEMORIZED_SPELL ~ja#1m8~ #0 ~innate~ (1)
			LPF patchCreature
				INT_VAR
					level1=12
					strength=20
					dexterity=10
					constitution=16
					intelligence=10
					wisdom=13
					charisma=7
					movement=10
					hp=126
					ac=6
					resistCold=100
					thac0=7
					apr=2
					alignment=34
					saveDeath=7
					saveWand=9
					savePolymorph=8
					saveBreath=8
					saveSpell=10
					morale=15
					moraleBreak=4
					moraleRecovery=15
					general=255
					race=103
					class=107
					gender=4
					sex=4
					enforce=1
					perfect2weapon=1
			END
			DEFINE_ARRAY removeScripts BEGIN kaldran dw1ranmo END
			LPF patchCreatureScript STR_VAR script=ja#m8 removeScripts END
		BUT_ONLY_IF_IT_CHANGES
	END
END