COMPILE ~%MOD_FOLDER%/lib/pnp-monster/bear/ja#m7.baf~
COMPILE ~%MOD_FOLDER%/lib/pnp-monster/bear/ja#m7su.baf~

CREATE ITM "ja#m7w1"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_LONG 0x60 3
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 2
	WRITE_SHORT 0x84 3
	WRITE_BYTE 0x88 10
	WRITE_BYTE 0x8a 1
	WRITE_SHORT 0x8e 3
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
COPY_EXISTING ~ja#m7w1.itm~ ~override~
	LPF ADD_EFFECT
		INT_VAR
			opcode = 139
			target = 2
			parameter1 = RESOLVE_STR_REF(@4007)
			parameter2 = 0
			probability1 = 10
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 12
			target = 2
			parameter1 = 0
			parameter2 = 0
			probability1 = 10
			dicenumber = 3
			dicesize = 6
		END

CREATE ITM "ja#m7w2"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_LONG 0x60 3
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 2
	WRITE_SHORT 0x84 3
	WRITE_BYTE 0x88 6
	WRITE_BYTE 0x8a 2
	WRITE_SHORT 0x8e 1
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
COPY_EXISTING ~ja#m7w2.itm~ ~override~

ACTION_FOR_EACH ~file~ IN
	BEARPO
	BEARPO1
	BEARPO2
	BEARPO3
	BEARPOSU
	NTBEARPO
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~B1-12~
			REMOVE_CRE_ITEM ~BEARPOSU~
			ADD_CRE_ITEM ~ja#m7w1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			ADD_CRE_ITEM ~ja#m7w2~ #0 #0 #0 ~UNDROPPABLE~ ~SHIELD~ 
			LPF clearProficiencies END
			LPF patchCreature
				INT_VAR
					level1=8
					strength=20
					dexterity=10
					constitution=16
					intelligence=4
					wisdom=13
					charisma=7
					movement=10
					hp=92
					ac=6
					thac0=11
					apr=3
					xpv=1400
					alignment=34
					saveDeath=10
					saveWand=12
					savePolymorph=11
					saveBreath=12
					saveSpell=13
					morale=9
					moraleBreak=4
					moraleRecovery=15
					general=255
					race=103
					class=107
					gender=4
					sex=4
					enforce=1
			END
			DEFINE_ARRAY removeScripts BEGIN CBEAR BEAR END
			DEFINE_ARRAY skipFiles BEGIN BEARPOSU END
			LPF patchCreatureScript STR_VAR script=ja#m7 skipFiles removeScripts END
			DEFINE_ARRAY removeScripts BEGIN CBEAR BEAR END
			DEFINE_ARRAY files BEGIN BEARPOSU END
			LPF patchCreatureScript STR_VAR script=ja#m7su files removeScripts END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~BEARPOSU~) BEGIN 
				LPF patchCreature
					INT_VAR
						hp=80
						thac0=13
						xpv=0
						saveDeath=10
						saveWand=12
						savePolymorph=11
						saveBreath=12
						saveSpell=13
						summon=1
				END
			END
		BUT_ONLY_IF_IT_CHANGES
	END
END