COMPILE ~%MOD_FOLDER%/lib/pnp-monster/bear/ja#m7.baf~
COMPILE ~%MOD_FOLDER%/lib/pnp-monster/bear/ja#m7su.baf~

CREATE ITM "ja#m7w1"
	WRITE_LONG 0x64 0x72
	WRITE_SHORT 0x68 1
	WRITE_LONG 0x6a 0xaa
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x72 1
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 1
	WRITE_SHORT 0x84 3
	WRITE_SHORT 0x86 4
	WRITE_BYTE 0x88 10
	WRITE_BYTE 0x8a 1
	WRITE_SHORT 0x8e 3
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
	LPF set_enchantment INT_VAR enchantment = 0 END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 12
			target = 2
			parameter1 = 0
			parameter2 = 0
			probability1 = 10
			dicenumber = 3
			dicesize = 6
	END

CREATE ITM "ja#m7w2"
	WRITE_LONG 0x64 0x72
	WRITE_SHORT 0x68 1
	WRITE_LONG 0x6a 0xaa
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x72 1
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 1
	WRITE_SHORT 0x84 3
	WRITE_SHORT 0x86 8
	WRITE_BYTE 0x88 6
	WRITE_BYTE 0x8a 2
	WRITE_SHORT 0x8e 1
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
	LPF set_enchantment INT_VAR enchantment = 0 END

ACTION_FOR_EACH ~file~ IN
	BEARPO
	BEARPO1
	BEARPO2
	BEARPO3
	BEARPOSU
	KALDRAN
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~B1-12~
			REMOVE_CRE_ITEM ~BEARPOSU~
			ADD_CRE_ITEM ~ja#m7w1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			ADD_CRE_ITEM ~ja#m7w2~ #0 #0 #0 ~UNDROPPABLE~ ~SHIELD~ 
			LPF patchCreature
				INT_VAR
					level1=8
					strength=20
					dexterity=10
					constitution=16
					intelligence=4
					wisdom=13
					charisma=7
					movement=10
					hp=92
					ac=6
					thac0=13
					apr=2
					xpv=1400
					alignment=34
					saveDeath=10
					saveWand=12
					savePolymorph=11
					saveBreath=12
					saveSpell=13
					morale=9
					moraleBreak=4
					moraleRecovery=15
					general=255
					race=103
					class=107
					gender=4
					sex=4
					enforce=1
			END
			DEFINE_ARRAY removeScripts BEGIN
				CBEAR
				BEAR
				SHOUT
				WTASIGHT
				WDASIGHT
				wtrunsgt
				DW2MP0GE
				DW2RC2MO
			END
			LPF patchCreatureScript STR_VAR script=ja#m7  removeScripts skipFiles END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~BEARPOSU~) BEGIN 
				DEFINE_ARRAY removeScripts BEGIN
					ja#m7
					SHOUT
					WTASIGHT
					WDASIGHT
					wtrunsgt
					DW2MP0GE
					DW2RC2MO
				END
				LPF patchCreatureScript STR_VAR script=ja#m7su  removeScripts skipFiles END
			END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~KALDRAN~) BEGIN 
				LPF patchCreature
					INT_VAR
						level1=12
						hp=114
						resistCold=100
						thac0=9
						saveDeath=7
						saveWand=9
						savePolymorph=8
						saveBreath=8
						saveSpell=10
						morale=15
						moraleRecovery=30
				END
			END
		BUT_ONLY_IF_IT_CHANGES
	END
END