CREATE ITM "ja#i1"
	WRITE_LONG 0x64 0x72
	WRITE_LONG 0x18 32
	SAY NAME1 ~construct trait~ SAY NAME2 ~construct trait~
	SAY UNIDENTIFIED_DESC ~Immunity to poison, sleep effects, paralysis, stunning, disease, death effects, necromancy effects, mind-affecting spells and abilities (charms, compulsions, phantasms, patterns, and morale effects). Not subject to critical hits, backstab, nonlethal damage, ability damage, ability drain, fatigue, exhaustion, energy drain, flesh to Stone, insect Plague and similar spells. Darkvision out to 60 feet.~
COPY_EXISTING ~ja#i1.itm~ ~override~
	LPF construct_trait END
