LAF ADD_IDS_ENTRY STR_VAR idsFile = "splstate.ids" identifier = "JA_GRAPPLED" END
LAF ADD_IDS_ENTRY STR_VAR idsFile = "splstate.ids" identifier = "JA_GRAPPLING" END
LAF ADD_IDS_ENTRY STR_VAR idsFile = "splstate.ids" identifier = "JA_FLYING" END
LAF ADD_IDS_ENTRY STR_VAR idsFile = "splstate.ids" identifier = "JA_GASEOUSFORM" END

CREATE ITM "ja#i6"
	WRITE_LONG 0x64 0x72
	WRITE_LONG 0x18 32
	WRITE_ASCII 0x3a ~IAMUL01~ #8
	SAY NAME1 ~entangle trait~ SAY NAME2 ~entangle trait~
	SAY UNIDENTIFIED_DESC ~Entangle immunity~
COPY_EXISTING ~ja#i6.itm~ ~override~
	LPF entangle_immunity END

CREATE ITM "ja#i3"
	WRITE_LONG 0x64 0x72
	WRITE_LONG 0x18 32
	WRITE_ASCII 0x3a ~IBOOT01~ #8
	SAY NAME1 ~hover trait~ SAY NAME2 ~hover trait~
	SAY UNIDENTIFIED_DESC ~Hover (flight),This effectively prevents ground-based spells such as Earthquake, Entangle, Grease and Web from affecting the creature.,Furthermore, creatures with this ability can cross lava and acid pools without taking damage by hovering above them~
COPY_EXISTING ~ja#i3.itm~ ~override~
	LPF hover_immunity END

CREATE ITM "ja#i5"
	WRITE_LONG 0x64 0x72
	WRITE_LONG 0x18 33554464
	WRITE_SHORT 0x1c 72
	WRITE_ASCII 0x3a ~IHELM01~ #8
	SAY NAME1 ~criticalHit trait~ SAY NAME2 ~criticalHit trait~
	SAY UNIDENTIFIED_DESC ~Immunity to critical hits~
COPY_EXISTING ~ja#i5.itm~ ~override~
	LPF criticalHit_immunity END

CREATE ITM "ja#i1"
	WRITE_LONG 0x64 0x72
	WRITE_LONG 0x18 33554464
	WRITE_ASCII 0x3a ~IRING01~ #8
	SAY NAME1 ~construct trait~ SAY NAME2 ~construct trait~
	SAY UNIDENTIFIED_DESC ~Construct trait.,Immunity to poison, sleep effects, paralysis, stunning, disease, death effects, necromancy effects, mind-affecting spells and abilities (charms, compulsions, phantasms, patterns, and morale effects).,Not subject to critical hits, backstab, nonlethal damage, ability damage, ability drain, fatigue, exhaustion, energy drain, flesh to Stone, insect Plague and similar spells.,Darkvision out to 60 feet.~
COPY_EXISTING ~ja#i1.itm~ ~override~
	LPF construct_immunity END

CREATE ITM "ja#i2"
	WRITE_LONG 0x64 0x72
	WRITE_LONG 0x18 32
	WRITE_ASCII 0x3a ~IRING01~ #8
	SAY NAME1 ~skeletal trait~ SAY NAME2 ~skeletal trait~
	SAY UNIDENTIFIED_DESC ~Skeletal undead suffer no damage from cold-based attacks. Due to their bony frames, edged and piercing weapons inflict only half damage.~
COPY_EXISTING ~ja#i2.itm~ ~override~
	LPF skeletal_immunity END

CREATE ITM "ja#i4"
	WRITE_LONG 0x64 0x72
	WRITE_LONG 0x18 33554464
	WRITE_ASCII 0x3a ~IRING01~ #8
	SAY NAME1 ~incorporeal trait~ SAY NAME2 ~incorporeal trait~
	SAY UNIDENTIFIED_DESC ~An incorporeal creature has no physical body.,,Immune to backstab and critical hits,Immune to all nonmagical attacks.,Has a 50% resistance to every damages.,Deflection bonus (+3 AC).,Attacks pass through armor (+4 THAC0).,Do not set off traps that are triggered by weight. (not implemented)~
COPY_EXISTING ~ja#i4.itm~ ~override~
	LPF incorporeal_immunity END
