COPY ~%MOD_FOLDER%/lib/pnp-monster/common/grab/rr#cnstr.vvc~ ~override~      // Constrict/Grab/Flaming Whip ability VVC animation
COPY ~%MOD_FOLDER%/lib/pnp-monster/common/grab/rr#cnstr.bam~ ~override~      // Constrict/Grab/Flaming Whip ability BAM graphics

ACTION_IF !FILE_EXISTS_IN_GAME rr#trat.cre BEGIN                            // Invisible Rat that destroys itself after a round, used to Dimension Door away from screen
  COPY ~%MOD_FOLDER%/lib/pnp-monster/common/rat/rr#trat.cre~ ~override~     // Targeting Rat (script aid)
  COMPILE ~%MOD_FOLDER%/lib/pnp-monster/common/rat/rr#trat.baf~             // Targeting Rat AI script
END
