CREATE ITM "ja#1m38"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_LONG 0x18 64
	WRITE_LONG 0x60 1
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 2
	WRITE_BYTE 0x88 4
	WRITE_BYTE 0x8a 2
	WRITE_SHORT 0x8e 6
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
COPY_EXISTING ~ja#1m38.itm~ ~override~
	LPF ADD_ITEM_EQEFFECT
		INT_VAR
			opcode = 0
			target = 1
			parameter1 = 2
			timing = 2
			probability1 = 100
		END
	LPF ADD_ITEM_EQEFFECT
		INT_VAR
			opcode = 146
			target = 1
			parameter2 = 1
			timing = 2
			probability1 = 100
		STR_VAR
			resource = "BDDISPB2"
		END

ACTION_FOR_EACH ~file~ IN
	BDDISPBE
	BDDISPBP
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~BDDISPBE~
			ADD_CRE_ITEM ~ja#1m38~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			LPF clearProficiencies END
			LPF patchCreature
				INT_VAR
					level1=6
					strength=18
					dexterity=15
					constitution=16
					intelligence=4
					wisdom=12
					charisma=8
					movement=13
					hp=60
					ac=4
					thac0=15
					apr=2
					xpv=975
					alignment=IDS_OF_SYMBOL (~align~ ~LAWFUL_EVIL~)
					saveDeath=7
					saveWand=9
					savePolymorph=8
					saveBreath=8
					saveSpell=10
					morale=14
					moraleBreak=4
					moraleRecovery=15
					general=IDS_OF_SYMBOL (~general~ ~MONSTER~)
					race=IDS_OF_SYMBOL (~race~ ~CAT~)
					class=IDS_OF_SYMBOL (~class~ ~CAT~)
					gender=IDS_OF_SYMBOL (~gender~ ~NIETHER~)
					sex=IDS_OF_SYMBOL (~gender~ ~NIETHER~)
					enforce=1
			END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~BDDISPBP~) BEGIN 
				LPF patchCreature
					INT_VAR
						level1=9
						strength=19
						constitution=19
						hp=117
						ac=2
						thac0=11
						xpv=1200
						saveDeath=7
						saveWand=9
						savePolymorph=8
						saveBreath=8
						saveSpell=10
				END
			END
		BUT_ONLY_IF_IT_CHANGES
	END ELSE BEGIN
		PRINT ~====> CRE %file% not found!~
	END
END