CREATE ITM "ja#1m37"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_LONG 0x18 64
	WRITE_LONG 0x60 2
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 2
	WRITE_BYTE 0x88 4
	WRITE_BYTE 0x8a 1
	WRITE_SHORT 0x8e 3
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
COPY_EXISTING ~ja#1m37.itm~ ~override~
	LPF ADD_EFFECT
		INT_VAR
			opcode = 139
			target = 2
			parameter1 = RESOLVE_STR_REF(@4009)
			probability1 = 10
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 12
			target = 2
			parameter1 = 1
			parameter2 = 16777216
			probability1 = 10
			dicenumber = 1
			dicesize = 6
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 12
			target = 2
			parameter1 = 1
			parameter2 = 16777216
			probability1 = 10
			dicenumber = 1
			dicesize = 6
		END

CREATE ITM "ja#2m37"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_LONG 0x18 64
	WRITE_LONG 0x60 2
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 2
	WRITE_BYTE 0x88 6
	WRITE_BYTE 0x8a 2
	WRITE_SHORT 0x8e 1
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
COPY_EXISTING ~ja#2m37.itm~ ~override~

CREATE ITM "ja#3m37"
	WRITE_LONG 0x64 0x72
	WRITE_SHORT 0x1c 10
	WRITE_ASCII 0x3a ~IRING01~ #8
COPY_EXISTING ~ja#3m37.itm~ ~override~
	LPF ADD_ITEM_EQEFFECT
		INT_VAR
			global = 1
			opcode = 20
			target = 1
			parameter2 = 1
			timing = 2
			probability1 = 100
		END
	LPF mindSpells_immunity END
	LPF normalWeapons_immunity END
	LPF extraplanar_immunity END

ACTION_FOR_EACH ~file~ IN
	BDHELCAT
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~BDHELCAT~
			REMOVE_CRE_ITEM ~RINGDEMN~
			REMOVE_CRE_ITEM ~IPSION~
			ADD_CRE_ITEM ~ja#1m37~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			ADD_CRE_ITEM ~ja#2m37~ #0 #0 #0 ~UNDROPPABLE~ ~SHIELD~ 
			ADD_CRE_ITEM ~ja#3m37~ #0 #0 #0 ~UNDROPPABLE~ ~RRING~ 
			LPF clear_proficiencies END
			LPF DELETE_CRE_EFFECT INT_VAR opcode_to_delete=65 END
			LPF DELETE_CRE_EFFECT INT_VAR opcode_to_delete=292 END
			LPF patchCreature
				INT_VAR
					level1=7
					strength=21
					dexterity=21
					constitution=19
					intelligence=10
					wisdom=14
					charisma=10
					movement=12
					hp=91
					ac=6
					resistMagic=20
					thac0=13
					apr=2
					xpv=5000
					alignment=IDS_OF_SYMBOL (~align~ ~LAWFUL_EVIL~)
					saveDeath=7
					saveWand=11
					savePolymorph=10
					saveBreath=13
					saveSpell=12
					morale=13
					moraleBreak=4
					moraleRecovery=15
					general=IDS_OF_SYMBOL (~general~ ~MONSTER~)
					race=IDS_OF_SYMBOL (~race~ ~DEMONIC~)
					class=IDS_OF_SYMBOL (~class~ ~CAT~)
					gender=IDS_OF_SYMBOL (~gender~ ~NIETHER~)
					sex=IDS_OF_SYMBOL (~gender~ ~NIETHER~)
					enforce=1
					perfect2weapon=1
			END
		BUT_ONLY_IF_IT_CHANGES
	END ELSE BEGIN
		PRINT ~====> CRE %file% not found!~
	END
END