CREATE ITM "ja#1m36"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 1
	WRITE_BYTE 0x88 3
	WRITE_BYTE 0x8a 1
	WRITE_SHORT 0x8e 3
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
COPY_EXISTING ~ja#1m36.itm~ ~override~
	LPF ADD_EFFECT
		INT_VAR
			opcode = 139
			target = 2
			parameter1 = RESOLVE_STR_REF(@4009)
			probability1 = 10
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 12
			target = 2
			parameter1 = 1
			parameter2 = 16777216
			probability1 = 10
			dicenumber = 1
			dicesize = 4
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 12
			target = 2
			parameter1 = 1
			parameter2 = 16777216
			probability1 = 10
			dicenumber = 1
			dicesize = 4
		END

CREATE ITM "ja#2m36"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 1
	WRITE_BYTE 0x88 6
	WRITE_BYTE 0x8a 1
	WRITE_SHORT 0x8e 1
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
COPY_EXISTING ~ja#2m36.itm~ ~override~

ACTION_FOR_EACH ~file~ IN
	CATJAGSU
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~CATJAGSU~
			ADD_CRE_ITEM ~ja#1m36~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			ADD_CRE_ITEM ~ja#2m36~ #0 #0 #0 ~UNDROPPABLE~ ~SHIELD~ 
			LPF clear_proficiencies END
			LPF patchCreature
				INT_VAR
					level1=3
					strength=16
					dexterity=19
					constitution=15
					intelligence=4
					wisdom=12
					charisma=6
					movement=12
					hp=27
					ac=6
					thac0=17
					apr=2
					xpv=270
					alignment=IDS_OF_SYMBOL (~align~ ~NEUTRAL~)
					saveDeath=10
					saveWand=14
					savePolymorph=13
					saveBreath=16
					saveSpell=15
					morale=9
					moraleBreak=4
					moraleRecovery=15
					general=IDS_OF_SYMBOL (~general~ ~ANIMAL~)
					race=IDS_OF_SYMBOL (~race~ ~CAT~)
					class=IDS_OF_SYMBOL (~class~ ~CAT~)
					gender=IDS_OF_SYMBOL (~gender~ ~NIETHER~)
					sex=IDS_OF_SYMBOL (~gender~ ~NIETHER~)
					enforce=1
					perfect2weapon=1
			END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~CATJAGSU~) BEGIN 
			END
		BUT_ONLY_IF_IT_CHANGES
	END ELSE BEGIN
		PRINT ~====> CRE %file% not found!~
	END
END