CREATE ITM "ja#m10w1"
	WRITE_LONG 0x64 0x72
	WRITE_SHORT 0x68 1
	WRITE_LONG 0x6a 0xaa
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x72 1
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 1
	WRITE_SHORT 0x84 3
	WRITE_BYTE 0x88 4
	WRITE_BYTE 0x8a 1
	WRITE_SHORT 0x8e 3
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x60 0
	WRITE_LONG 0x98 1
	LPF ADD_EFFECT
		INT_VAR
			opcode = 139
			target = 2
			parameter1 = RESOLVE_STR_REF(@4009)
			parameter2 = 0
			probability1 = 10
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 12
			target = 2
			parameter1 = 1
			parameter2 = 16777216
			probability1 = 10
			dicenumber = 1
			dicesize = 6
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 12
			target = 2
			parameter1 = 1
			parameter2 = 16777216
			probability1 = 10
			dicenumber = 1
			dicesize = 6
	END

CREATE ITM "ja#m10w2"
	WRITE_LONG 0x64 0x72
	WRITE_SHORT 0x68 1
	WRITE_LONG 0x6a 0xaa
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x72 1
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 1
	WRITE_SHORT 0x84 3
	WRITE_BYTE 0x88 10
	WRITE_BYTE 0x8a 1
	WRITE_SHORT 0x8e 1
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x60 0
	WRITE_LONG 0x98 1

ACTION_FOR_EACH ~file~ IN
	BDHELP02
	CATLIOSU
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~CATLIO~
			ADD_CRE_ITEM ~ja#m10w1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			ADD_CRE_ITEM ~ja#m10w2~ #0 #0 #0 ~UNDROPPABLE~ ~SHIELD~ 
			LPF patchCreature
				INT_VAR
					level1=5
					strength=17
					dexterity=15
					constitution=13
					intelligence=4
					wisdom=12
					charisma=8
					movement=10
					hp=40
					ac=5
					thac0=15
					apr=3
					xpv=650
					alignment=34
					saveDeath=11
					saveWand=13
					savePolymorph=12
					saveBreath=13
					saveSpell=14
					morale=9
					moraleBreak=4
					moraleRecovery=15
					general=255
					race=137
					class=175
					gender=4
					sex=4
					enforce=1
					perfect2weapon=1
			END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~CATLIOSU~) BEGIN 
				LPF patchCreature
					INT_VAR
						hp=40
						xpv=0
						saveDeath=11
						saveWand=13
						savePolymorph=12
						saveBreath=13
						saveSpell=14
						summon=1
				END
			END
		BUT_ONLY_IF_IT_CHANGES
	END
END