CREATE ITM "ja#m11w1"
	WRITE_LONG 0x64 0x72
	WRITE_SHORT 0x68 1
	WRITE_LONG 0x6a 0xaa
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x72 1
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 1
	WRITE_SHORT 0x84 3
	WRITE_BYTE 0x88 3
	WRITE_BYTE 0x8a 1
	WRITE_SHORT 0x8e 3
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x60 0
	WRITE_LONG 0x98 1
	LPF ADD_EFFECT
		INT_VAR
			opcode = 139
			target = 2
			parameter1 = RESOLVE_STR_REF(@4009)
			parameter2 = 0
			probability1 = 10
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 12
			target = 2
			parameter1 = 0
			parameter2 = 16777216
			probability1 = 10
			dicenumber = 1
			dicesize = 4
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 12
			target = 2
			parameter1 = 0
			parameter2 = 16777216
			probability1 = 10
			dicenumber = 1
			dicesize = 4
	END

CREATE ITM "ja#m11w2"
	WRITE_LONG 0x64 0x72
	WRITE_SHORT 0x68 1
	WRITE_LONG 0x6a 0xaa
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x72 1
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 1
	WRITE_SHORT 0x84 3
	WRITE_BYTE 0x88 6
	WRITE_BYTE 0x8a 1
	WRITE_SHORT 0x8e 1
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x60 0
	WRITE_LONG 0x98 1

ACTION_FOR_EACH ~file~ IN
	CATLIM01
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~P1-6~
			ADD_CRE_ITEM ~ja#m11w1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			ADD_CRE_ITEM ~ja#m11w2~ #0 #0 #0 ~UNDROPPABLE~ ~SHIELD~ 
			LPF patchCreature
				INT_VAR
					level1=3
					strength=17
					dexterity=15
					constitution=13
					intelligence=4
					wisdom=12
					charisma=8
					movement=10
					hp=24
					ac=6
					thac0=17
					apr=2
					xpv=270
					alignment=34
					saveDeath=13
					saveWand=15
					savePolymorph=14
					saveBreath=16
					saveSpell=16
					morale=9
					moraleBreak=4
					moraleRecovery=15
					general=255
					race=137
					class=175
					gender=4
					sex=4
					enforce=1
					perfect2weapon=1
			END
		BUT_ONLY_IF_IT_CHANGES
	END
END