COMPILE ~%MOD_FOLDER%/lib/pnp-monster/dog/ja#14.baf~

CREATE SPL "ja#1m14"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x28
	WRITE_SHORT 0x68 1
	WRITE_LONG 0x6a 0x9a
	WRITE_SHORT 0x72 1
	WRITE_SHORT 0x82 1
	WRITE_SHORT 0x1c 4
	WRITE_LONG 0x34 1
	WRITE_SHORT 0x74 4
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 30
	SAY NAME1 @4010 SAY NAME2 @4010
	LPF ADD_EFFECT
		INT_VAR
			opcode = 124
			target = 1
			parameter1 = 0
			parameter2 = 0
			probability1 = 100
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 278
			target = 1
			parameter1 = 2
			parameter2 = 0
			duration = 6
			probability1 = 75
		END

CREATE ITM "ja#m14w1"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 1
	WRITE_SHORT 0x84 3
	WRITE_BYTE 0x88 6
	WRITE_BYTE 0x8a 1
	WRITE_SHORT 0x8e 1
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1

ACTION_FOR_EACH ~file~ IN
	DOGBLINK
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~P1-6~
			ADD_CRE_ITEM ~ja#m14w1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			ADD_MEMORIZED_SPELL ~ja#1m14~ #0 ~innate~ (1)
			LPF clearProficiencies END
			LPF patchCreature
				INT_VAR
					level1=4
					strength=12
					dexterity=17
					constitution=15
					intelligence=9
					wisdom=13
					charisma=11
					movement=10
					hp=36
					ac=5
					thac0=17
					apr=1
					xpv=270
					alignment=34
					saveDeath=13
					saveWand=15
					savePolymorph=14
					saveBreath=16
					saveSpell=16
					morale=12
					moraleBreak=4
					moraleRecovery=15
					general=255
					race=105
					class=109
					gender=1
					sex=1
					enforce=1
			END
			DEFINE_ARRAY removeScripts BEGIN PSPIDER END
			LPF patchCreatureScript STR_VAR script=ja#14 removeScripts END
		BUT_ONLY_IF_IT_CHANGES
	END
END