CREATE ITM "ja#2m39"
	WRITE_LONG 0x64 0x72
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~IRING01~ #8
COPY_EXISTING ~ja#2m39.itm~ ~override~
	LPF ADD_ITEM_EQEFFECT
		INT_VAR
			global = 1
			opcode = 193
			target = 1
			parameter2 = 1
			timing = 2
			probability1 = 100
		END
	LPF ADD_ITEM_EQEFFECT
		INT_VAR
			global = 1
			opcode = 365
			target = 1
			parameter2 = 1
			timing = 2
			probability1 = 100
		END
	LPF extraplanar_immunity END

ACTION_FOR_EACH ~file~ IN
	BDSHA01C
	DOGWAWP
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~FIGRING3~
			REMOVE_CRE_ITEM ~IPSION~
			REMOVE_CRE_ITEM ~BDSPIRIM~
			ADD_CRE_ITEM ~ja#2m39~ #0 #0 #0 ~UNDROPPABLE~ ~AMULET~ 
			ADD_CRE_ITEM ~ja#i4~ #0 #0 #0 ~UNDROPPABLE~ ~RRING~ 
			ADD_CRE_ITEM ~ja#i5~ #0 #0 #0 ~UNDROPPABLE~ ~HELMET~ 
			LPF clearProficiencies END
			LPF patchCreature
				INT_VAR
					level1=5
					strength=17
					dexterity=15
					constitution=14
					intelligence=4
					wisdom=14
					charisma=12
					movement=13
					hp=40
					ac="-2"
					thac0=15
					apr=1
					xpv=975
					alignment=IDS_OF_SYMBOL (~align~ ~CHAOTIC_EVIL~)
					saveDeath=11
					saveWand=13
					savePolymorph=12
					saveBreath=13
					saveSpell=14
					morale=19
					moraleBreak=4
					moraleRecovery=15
					general=IDS_OF_SYMBOL (~general~ ~MONSTER~)
					race=IDS_OF_SYMBOL (~race~ ~DOG~)
					class=IDS_OF_SYMBOL (~class~ ~DOG_WAR~)
					gender=IDS_OF_SYMBOL (~gender~ ~MALE~)
					sex=IDS_OF_SYMBOL (~gender~ ~MALE~)
					enforce=1
			END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~BDSHA01C~) BEGIN 
				WRITE_LONG 0x14 0 // xpv
				WRITE_BYTE 0x237 IDS_OF_SYMBOL (~gender~ ~SUMMONED~) // gender
				WRITE_BYTE 0x275 IDS_OF_SYMBOL (~gender~ ~SUMMONED~) // gender
			END
		BUT_ONLY_IF_IT_CHANGES
	END ELSE BEGIN
		PRINT ~====> CRE %file% not found!~
	END
END