CREATE ITM "ja#m13w1"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 1
	WRITE_SHORT 0x84 3
	WRITE_BYTE 0x88 4
	WRITE_BYTE 0x8a 2
	WRITE_SHORT 0x8e 1
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1

ACTION_FOR_EACH ~file~ IN
	BDPRISD1
	BDPRISD2
	DOGWA
	DOGWASU
	DOGWASU
	dw#rndwa
	UBNIMDOG
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~P2-8~
			ADD_CRE_ITEM ~ja#m13w1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			LPF clearProficiencies END
			LPF patchCreature
				INT_VAR
					level1=2
					strength=12
					dexterity=17
					constitution=15
					intelligence=4
					wisdom=13
					charisma=11
					movement=10
					hp=18
					ac=6
					thac0=19
					apr=1
					xpv=65
					alignment=34
					saveDeath=14
					saveWand=16
					savePolymorph=15
					saveBreath=17
					saveSpell=17
					morale=9
					moraleBreak=4
					moraleRecovery=15
					general=255
					race=105
					class=110
					gender=1
					sex=1
					enforce=1
			END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~DOGWASU~) BEGIN 
				LPF patchCreature
					INT_VAR
						hp=18
						thac0=19
						xpv=0
						saveDeath=14
						saveWand=16
						savePolymorph=15
						saveBreath=17
						saveSpell=17
						summon=1
				END
			END
		BUT_ONLY_IF_IT_CHANGES
	END
END