CREATE ITM "ja#m12w1"
	WRITE_LONG 0x64 0x72
	WRITE_SHORT 0x68 1
	WRITE_LONG 0x6a 0xaa
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x72 1
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 1
	WRITE_SHORT 0x84 3
	WRITE_BYTE 0x88 4
	WRITE_BYTE 0x8a 1
	WRITE_SHORT 0x8e 1
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x60 0
	WRITE_LONG 0x98 1

ACTION_FOR_EACH ~file~ IN
	BDBDOG
	BDEADOG
	DOGWI
	DOGWISU
	BDCRUDOG
	BDDOG
	dw#rndwi
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~P1-4~
			ADD_CRE_ITEM ~ja#m12w1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			LPF patchCreature
				INT_VAR
					level1=1
					strength=12
					dexterity=17
					constitution=15
					intelligence=4
					wisdom=13
					charisma=11
					movement=13
					hp=9
					ac=7
					thac0=19
					apr=1
					xpv=35
					alignment=34
					saveDeath=14
					saveWand=16
					savePolymorph=15
					saveBreath=17
					saveSpell=17
					morale=6
					moraleBreak=4
					moraleRecovery=15
					general=255
					race=105
					class=109
					gender=1
					sex=1
					enforce=1
			END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~DOGWISU~) BEGIN 
				LPF patchCreature
					INT_VAR
						hp=9
						xpv=0
						saveDeath=14
						saveWand=16
						savePolymorph=15
						saveBreath=17
						saveSpell=17
						summon=1
				END
			END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~BDDOG~) BEGIN 
				LPF patchCreature
					INT_VAR
						hp=9
						saveDeath=14
						saveWand=16
						savePolymorph=15
						saveBreath=17
						saveSpell=17
						class=155
				END
			END
		BUT_ONLY_IF_IT_CHANGES
	END
END