COMPILE ~%MOD_FOLDER%/lib/pnp-monster/ogre/ja#m29.baf~

ACTION_FOR_EACH ~file~ IN
	OGREBJOR
	OGREHA
	OGREHA1
	OGREHA2
	OGREHA3
	OGREHA4
	OGREHA5
	OGREHA_A
	OGREHA_B
	OGREHA_C
	OGREHA_D
	OGREHA_E
	BDOGRE04
	ARGHAI
	L#CHIEN
	TAZOK
	TAZOK2
	X#CHOP
	X#CRU11
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			LPF clearProficiencies END
			SET_BG2_PROFICIENCY ~PROFICIENCYBASTARDSWORD~ 2
			SET_BG2_PROFICIENCY ~PROFICIENCYTWOHANDEDSWORD~ 2
			LPF ADD_CRE_EFFECT
				INT_VAR
					opcode = 73
					target = 1
					parameter1 = 2
					timing = 2
					probability1 = 100
				END
			LPF patchCreature
				INT_VAR
					level1=2
					strength=17
					dexterity=10
					constitution=14
					intelligence=9
					wisdom=9
					charisma=10
					movement=10
					hp=22
					ac=5
					thac0=17
					apr=1
					xpv=175
					alignment=IDS_OF_SYMBOL (~align~ ~CHAOTIC_EVIL~)
					saveDeath=14
					saveWand=16
					savePolymorph=15
					saveBreath=17
					saveSpell=17
					morale=12
					moraleBreak=4
					moraleRecovery=15
					general=IDS_OF_SYMBOL (~general~ ~GIANTHUMANOID~)
					race=IDS_OF_SYMBOL (~race~ ~OGRE~)
					class=IDS_OF_SYMBOL (~class~ ~OGRE_HALFOGRE~)
					enforce=1
			END
			DEFINE_ARRAY removeScripts BEGIN HALFOGRE BDFIG00 END
			LPF patchCreatureScript STR_VAR script=ja#m29 removeScripts END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~BDOGRE04~) BEGIN 
				LPF patchCreature
					INT_VAR
						level1=5
						strength=18
						exceptionalStrength=100
						hp=46
						thac0=15
						xpv=420
						saveDeath=11
						saveWand=13
						savePolymorph=12
						saveBreath=13
						saveSpell=14
				END
			END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~L#CHIEN~) BEGIN 
				LPF patchCreature
					INT_VAR
						level1=9
						strength=18
						exceptionalStrength=100
						hp=78
						resistFire=50
						resistCold=50
						resistMissile=100
						thac0=11
						xpv=4000
						saveDeath=8
						saveWand=10
						savePolymorph=9
						saveBreath=9
						saveSpell=11
						class=IDS_OF_SYMBOL (~class~ ~FIGHTER~)
				END
				SET_BG2_PROFICIENCY ~PROFICIENCYLONGSWORD~ 4
			END
		BUT_ONLY_IF_IT_CHANGES
	END ELSE BEGIN
		PRINT ~====> CRE %file% not found!~
	END
END