COMPILE ~%MOD_FOLDER%/lib/pnp-monster/ogre/ja#m29.baf~

ACTION_FOR_EACH ~file~ IN
	OGREBJOR
	OGREHA
	OGREHA1
	OGREHA2
	OGREHA3
	OGREHA4
	OGREHA5
	OGREHA_A
	OGREHA_B
	OGREHA_C
	OGREHA_D
	OGREHA_E
	BDOGRE04
	ARGHAI
	L#CHIEN
	TAZOK
	TAZOK2
	X#CHOP
	X#CRU11
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			LPF clearProficiencies END
			SET_BG2_PROFICIENCY ~PROFICIENCYBASTARDSWORD~ 2
			SET_BG2_PROFICIENCY ~PROFICIENCYTWOHANDEDSWORD~ 2
			LPF patchCreature
				INT_VAR
					level1=2
					strength=17
					dexterity=10
					constitution=14
					intelligence=9
					wisdom=9
					charisma=10
					movement=10
					hp=22
					ac=5
					thac0=17
					apr=1
					xpv=175
					alignment=IDS_OF_SYMBOL (~align~ ~CHAOTIC_EVIL~)
					saveDeath=14
					saveWand=16
					savePolymorph=15
					saveBreath=17
					saveSpell=17
					morale=12
					moraleBreak=4
					moraleRecovery=15
					general=IDS_OF_SYMBOL (~general~ ~GIANTHUMANOID~)
					race=IDS_OF_SYMBOL (~race~ ~OGRE~)
					class=IDS_OF_SYMBOL (~class~ ~OGRE_HALFOGRE~)
					enforce=1
			END
			DEFINE_ARRAY removeScripts BEGIN HALFOGRE BDFIG00 END
			LPF patchCreatureScript STR_VAR script=ja#m29 removeScripts END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~BDOGRE04~) OR ("%SOURCE_RES%" STRING_EQUAL_CASE ~ARGHAI~) OR ("%SOURCE_RES%" STRING_EQUAL_CASE ~X#CHOP~) OR ("%SOURCE_RES%" STRING_EQUAL_CASE ~X#CRU11~) BEGIN 
				WRITE_LONG 0x14 520 // xpv
				WRITE_SHORT 0x24 46 // hp
				WRITE_SHORT 0x26 46 // hp
				WRITE_SHORT 0x46 3 // ac
				WRITE_SHORT 0x48 3 // ac
				WRITE_BYTE 0x52 15 // thac0
				WRITE_BYTE 0x54 11 // saveDeath
				WRITE_BYTE 0x55 13 // saveWand
				WRITE_BYTE 0x56 12 // savePolymorph
				WRITE_BYTE 0x57 13 // saveBreath
				WRITE_BYTE 0x58 14 // saveSpell
				WRITE_BYTE 0x234 5 // level1
				WRITE_BYTE 0x238 18 // strength
			END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~ARGHAI~) BEGIN 
				WRITE_BYTE 0x239 100 // exceptionalStrength
			END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~BDOGRE04~) BEGIN 
				WRITE_BYTE 0x239 83 // exceptionalStrength
			END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~X#CHOP~) OR ("%SOURCE_RES%" STRING_EQUAL_CASE ~X#CRU11~) BEGIN 
				WRITE_BYTE 0x238 19 // strength
			END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~TAZOK~) OR ("%SOURCE_RES%" STRING_EQUAL_CASE ~TAZOK2~) OR ("%SOURCE_RES%" STRING_EQUAL_CASE ~L#CHIEN~) BEGIN 
				WRITE_LONG 0x14 4000 // xpv
				WRITE_SHORT 0x24 78 // hp
				WRITE_SHORT 0x26 78 // hp
				WRITE_SHORT 0x46 10 // ac
				WRITE_SHORT 0x48 10 // ac
				WRITE_BYTE 0x52 11 // thac0
				WRITE_BYTE 0x54 8 // saveDeath
				WRITE_BYTE 0x55 10 // saveWand
				WRITE_BYTE 0x56 9 // savePolymorph
				WRITE_BYTE 0x57 9 // saveBreath
				WRITE_BYTE 0x58 11 // saveSpell
				WRITE_BYTE 0x234 9 // level1
				WRITE_BYTE 0x238 18 // strength
				WRITE_BYTE 0x23f 20 // morale
				WRITE_BYTE 0x273 IDS_OF_SYMBOL (~class~ ~FIGHTER~) // class
			END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~TAZOK~) OR ("%SOURCE_RES%" STRING_EQUAL_CASE ~TAZOK2~) BEGIN 
				WRITE_SHORT 0x246 IDS_OF_SYMBOL (~kit~ ~BERSERKER~) // kit
				ADD_MEMORIZED_SPELL ~SPCL321~ #0 ~innate~ (1)
				SET_BG2_PROFICIENCY ~PROFICIENCYTWOHANDEDSWORD~ 5
			END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~TAZOK2~) BEGIN 
				WRITE_SHORT 0x24 94 // hp
				WRITE_SHORT 0x26 94 // hp
				WRITE_BYTE 0x52 9 // thac0
				WRITE_BYTE 0x54 7 // saveDeath
				WRITE_BYTE 0x55 9 // saveWand
				WRITE_BYTE 0x56 8 // savePolymorph
				WRITE_BYTE 0x57 8 // saveBreath
				WRITE_BYTE 0x58 10 // saveSpell
				WRITE_BYTE 0x59 70 // resistFire
				WRITE_BYTE 0x5e 70 // resistFire
				WRITE_BYTE 0x234 11 // level1
			END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~L#CHIEN~) BEGIN 
				WRITE_BYTE 0x59 50 // resistFire
				WRITE_BYTE 0x5e 50 // resistFire
				WRITE_BYTE 0x5a 50 // resistCold
				WRITE_BYTE 0x5f 50 // resistCold
				WRITE_BYTE 0x63 100 // resistMissile
				SET_BG2_PROFICIENCY ~PROFICIENCYLONGSWORD~ 5
			END
		BUT_ONLY_IF_IT_CHANGES
	END ELSE BEGIN
		PRINT ~====> CRE %file% not found!~
	END
END