COMPILE ~%MOD_FOLDER%/lib/pnp-monster/ogre/ja#m29.baf~

CREATE ITM "ja#m29w1"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_LONG 0x18 2
	WRITE_SHORT 0x1c 69
	WRITE_ASCII 0x22 ~S0~ #2
	WRITE_BYTE 0x31 89
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 2
	WRITE_BYTE 0x88 10
	WRITE_BYTE 0x8a 1
	WRITE_SHORT 0x8e 3
	WRITE_SHORT 0x9e 40
	WRITE_SHORT 0xa0 40
	WRITE_SHORT 0xa2 20
	WRITE_LONG 0x98 1
COPY_EXISTING ~ja#m29w1.itm~ ~override~

ACTION_FOR_EACH ~file~ IN
	
	
	
	
	
	
	
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~P2-8~
			ADD_CRE_ITEM ~ja#m29w1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			LPF clearProficiencies END
			SET_BG2_PROFICIENCY ~PROFICIENCYBASTARDSWORD~ 2
			DEFINE_ARRAY notEnforceFiles BEGIN  END
			LPF patchCreature
				INT_VAR
					level1=2
					strength=17
					dexterity=10
					constitution=14
					intelligence=9
					wisdom=9
					charisma=10
					movement=10
					hp=22
					ac=5
					thac0=17
					apr=1
					xpv=270
					alignment=IDS_OF_SYMBOL (~align~ ~CHAOTIC_EVIL~)
					saveDeath=14
					saveWand=16
					savePolymorph=15
					saveBreath=17
					saveSpell=17
					morale=12
					moraleBreak=4
					moraleRecovery=15
					general=IDS_OF_SYMBOL (~general~ ~MONSTER~)
					race=IDS_OF_SYMBOL (~race~ ~OGRE~)
					class=IDS_OF_SYMBOL (~class~ ~OGRE_HALFOGRE~)
					gender=IDS_OF_SYMBOL (~gender~ ~MALE~)
					sex=IDS_OF_SYMBOL (~gender~ ~MALE~)
					enforce=1
				STR_VAR
					notEnforceFiles
			END
			LPF patchCreatureScript STR_VAR script=ja#m29 END
		BUT_ONLY_IF_IT_CHANGES
	END ELSE BEGIN
		PRINT ~====> CRE %file% not found!~
	END
END