COMPILE ~%MOD_FOLDER%/lib/pnp-monster/ogre/ja#m32.baf~

COPY_EXISTING "CONECOLD.pro" ~override/ja#1m32.pro~
	READ_SHORT 0x08 type
	PATCH_IF (%type% = 1) BEGIN
		INSERT_BYTES 0x100 0x100
	END
	WRITE_SHORT 0x204 620
	WRITE_SHORT 0x206 620
ADD_PROJECTILE ~override/ja#1m32.pro~ ~Ogre-Mage Cone of Cold~

CREATE SPL "ja#1m32"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x28
	WRITE_SHORT 0x68 1
	WRITE_LONG 0x6a 0x9a
	WRITE_SHORT 0x72 1
	WRITE_SHORT 0x82 1
	WRITE_SHORT 0x1c 1
	WRITE_BYTE 0x27 10
	WRITE_LONG 0x34 5
	WRITE_SHORT 0x74 2
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 10
	WRITE_SHORT 0x84 1
	SAY NAME1 26492 SAY NAME2 26492
	WRITE_SHORT 0x98 (IDS_OF_SYMBOL (~projectl~ ~ja#1m32~)) + 1
	LPF ADD_EFFECT
		INT_VAR
			opcode = 12
			target = 2
			parameter2 = 131072
			probability1 = 100
			dicenumber = 8
			dicesize = 8
			savingthrow = 16777217
			savebonus = "-4"
			special = 256
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 165
			target = 2
			duration = 1
			probability1 = 100
		END

CREATE ITM "ja#1m32"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_LONG 0x18 66
	WRITE_SHORT 0x1c 30
	WRITE_ASCII 0x22 ~S3~ #2
	WRITE_BYTE 0x31 94
	WRITE_LONG 0x60 1
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 2
	WRITE_BYTE 0x88 12
	WRITE_BYTE 0x8a 1
	WRITE_SHORT 0x8e 3
	WRITE_SHORT 0x9e 50
	WRITE_SHORT 0xa0 50
	WRITE_SHORT 0xa2 0
	WRITE_LONG 0x98 1
COPY_EXISTING ~ja#1m32.itm~ ~override~

ACTION_FOR_EACH ~file~ IN
	BDOGRE03
	BDWAVE16
	BPOGMA01
	OGREMA
	OGREMA02
	OGREMA03
	OGREMASU
	OGREMA_A
	OGREMA_B
	OGREMA_C
	OGREMA_D
	OGREMBA
	OGRMBA
	UBOGMA01
	UBOGMA02
	NTFOREOG
	BDOGRE05
	BDMURS
	BDMURS2
	DROTH
	DWSST2
	KAHRK
	KROTAN
	NTKROTAN
	WIGENTLE
	WIOGMA01
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~REGHP1~
			REMOVE_CRE_ITEM ~BDOGRE03~
			ADD_CRE_ITEM ~ja#1m32~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			ADD_CRE_ITEM ~ja#i3~ #0 #0 #0 ~UNDROPPABLE~ ~BOOTS~ 
			ADD_MEMORIZED_SPELL ~SPWI206~ #1 ~wizard~ (1)
			ADD_MEMORIZED_SPELL ~SPWI228~ #1 ~wizard~ (1)
			ADD_MEMORIZED_SPELL ~SPWI104~ #0 ~wizard~ (1)
			ADD_MEMORIZED_SPELL ~SPWI116~ #0 ~wizard~ (1)
			ADD_MEMORIZED_SPELL ~ja#1m32~ #4 ~innate~ (1)
			LPF clearProficiencies END
			SET_BG2_PROFICIENCY ~PROFICIENCYKATANA~ 2
			LPF ADD_CRE_EFFECT
				INT_VAR
					opcode = 98
					target = 2
					parameter1 = 6
					parameter2 = 3
					probability1 = 100
				END
			LPF patchCreature
				INT_VAR
					level1=5
					strength=18
					exceptionalStrength=100
					dexterity=10
					constitution=17
					intelligence=16
					wisdom=14
					charisma=17
					movement=13
					hp=55
					ac=4
					thac0=15
					apr=1
					xpv=650
					alignment=IDS_OF_SYMBOL (~align~ ~LAWFUL_EVIL~)
					saveDeath=11
					saveWand=13
					savePolymorph=12
					saveBreath=13
					saveSpell=14
					morale=14
					moraleBreak=4
					moraleRecovery=15
					general=IDS_OF_SYMBOL (~general~ ~GIANTHUMANOID~)
					race=IDS_OF_SYMBOL (~race~ ~OGRE~)
					class=IDS_OF_SYMBOL (~class~ ~OGRE_MAGE~)
					gender=IDS_OF_SYMBOL (~gender~ ~MALE~)
					sex=IDS_OF_SYMBOL (~gender~ ~MALE~)
					enforce=1
			END
			LPF patchCreatureScript STR_VAR script=ja#m32 END
		BUT_ONLY_IF_IT_CHANGES
	END ELSE BEGIN
		PRINT ~====> CRE %file% not found!~
	END
END