COMPILE ~%MOD_FOLDER%/lib/pnp-monster/ogre/ja#m30.baf~

CREATE ITM "ja#1m30"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_LONG 0x18 64
	WRITE_LONG 0x60 1
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 2
	WRITE_BYTE 0x88 10
	WRITE_BYTE 0x8a 1
	WRITE_SHORT 0x8e 2
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
COPY_EXISTING ~ja#1m30.itm~ ~override~

CREATE ITM "ja#2m30"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_LONG 0x18 64
	WRITE_LONG 0x60 1
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 2
	WRITE_BYTE 0x88 6
	WRITE_BYTE 0x8a 2
	WRITE_SHORT 0x8e 2
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
COPY_EXISTING ~ja#2m30.itm~ ~override~

CREATE ITM "ja#3m30"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_LONG 0x18 64
	WRITE_LONG 0x60 1
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 2
	WRITE_BYTE 0x88 6
	WRITE_BYTE 0x8a 2
	WRITE_SHORT 0x8e 2
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
COPY_EXISTING ~ja#3m30.itm~ ~override~

ACTION_FOR_EACH ~file~ IN
	AC#FP2O1
	AC#FP2O2
	BDOGRE01
	BDOGRE1D
	BDOGREF
	BDOGREM
	BPOGRE01
	BSOGRED
	AC#FP2OT
	AC#FPOG4
	AC#WRIM1
	ACQ13002
	BDCCOGR1
	BDSOGR1
	BDSOGR2
	GORF
	HACK
	LARZE
	KROTAN
	NTKROTAN
	NTOGREDA
	NTWELT
	WELT
	OOPAH
	OOPAH2
	SEWERF4
	OGRE
	OGRE02
	OGRE03
	OGRE04
	OGRE05
	OGRECO
	OGRED
	OGRES
	OGRESU
	OGREUNSH
	OGRE_A
	OGRE_B
	OGRE_C
	OGRE_D
	OGRE_E
	PLYOGRE
	WIOGRE01
	X3HOGRE
	X3HOGRE2
	X3HOGRED
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~OGRE1~
			REMOVE_CRE_ITEM ~B1-2~
			REMOVE_CRE_ITEM ~B3-12~
			REMOVE_CRE_ITEM ~B2-16~
			PATCH_IF (NOT "%SOURCE_RES%" STRING_EQUAL_CASE ~AC#FP2OT~) BEGIN 
				ADD_CRE_ITEM ~ja#1m30~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			END
			LPF clearProficiencies END
			SET_BG2_PROFICIENCY ~PROFICIENCYTWOHANDEDSWORD~ 2
			LPF ADD_CRE_EFFECT
				INT_VAR
					opcode = 73
					target = 1
					parameter1 = 2
					timing = 2
					probability1 = 100
				END
			DEFINE_ARRAY notEnforceFiles BEGIN AC#FP2OT END
			LPF patchCreature
				INT_VAR
					level1=4
					strength=18
					dexterity=8
					constitution=16
					intelligence=8
					wisdom=7
					charisma=7
					movement=8
					hp=40
					ac=5
					thac0=17
					apr=1
					xpv=270
					alignment=IDS_OF_SYMBOL (~align~ ~CHAOTIC_EVIL~)
					saveDeath=13
					saveWand=15
					savePolymorph=14
					saveBreath=16
					saveSpell=16
					morale=12
					moraleBreak=4
					moraleRecovery=15
					general=IDS_OF_SYMBOL (~general~ ~GIANTHUMANOID~)
					race=IDS_OF_SYMBOL (~race~ ~OGRE~)
					class=IDS_OF_SYMBOL (~class~ ~OGRE~)
					enforce=1
				STR_VAR
					notEnforceFiles
			END
			DEFINE_ARRAY removeScripts BEGIN BDSUM00 OGRE END
			DEFINE_ARRAY skipFiles BEGIN X3HOGRE2 END
			LPF patchCreatureScript STR_VAR script=ja#m30 skipFiles removeScripts END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~OOPAH~) OR ("%SOURCE_RES%" STRING_EQUAL_CASE ~WELT~) BEGIN 
				DEFINE_ARRAY notEnforceFiles BEGIN AC#FP2OT END
				LPF patchCreature
					INT_VAR
						hp=40
						thac0=17
						saveDeath=13
						saveWand=15
						savePolymorph=14
						saveBreath=16
						saveSpell=16
						class=IDS_OF_SYMBOL (~class~ ~INNOCENT~)
					STR_VAR
						notEnforceFiles
				END
			END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~OOPAH~) OR ("%SOURCE_RES%" STRING_EQUAL_CASE ~OOPAH2~) BEGIN 
				DEFINE_ARRAY notEnforceFiles BEGIN AC#FP2OT END
				LPF patchCreature
					INT_VAR
						level1=5
						hp=50
						thac0=15
						saveDeath=11
						saveWand=13
						savePolymorph=12
						saveBreath=13
						saveSpell=14
					STR_VAR
						notEnforceFiles
				END
			END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~SEWERF4~) OR ("%SOURCE_RES%" STRING_EQUAL_CASE ~BDOGREM~) OR ("%SOURCE_RES%" STRING_EQUAL_CASE ~ACQ13002~) OR ("%SOURCE_RES%" STRING_EQUAL_CASE ~BDCCOGR1~) OR ("%SOURCE_RES%" STRING_EQUAL_CASE ~NTOGREDA~) BEGIN 
				DEFINE_ARRAY notEnforceFiles BEGIN AC#FP2OT END
				LPF patchCreature
					INT_VAR
						level1=7
						strength=18
						exceptionalStrength=100
						hp=70
						ac=3
						thac0=13
						xpv=650
						saveDeath=10
						saveWand=12
						savePolymorph=11
						saveBreath=12
						saveSpell=13
					STR_VAR
						notEnforceFiles
				END
				ADD_CRE_ITEM ~ja#2m30~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~AC#WRIM1~) BEGIN 
				DEFINE_ARRAY notEnforceFiles BEGIN AC#FP2OT END
				LPF patchCreature
					INT_VAR
						level1=7
						strength=18
						exceptionalStrength=100
						hp=70
						ac=2
						thac0=13
						xpv=975
						saveDeath=10
						saveWand=12
						savePolymorph=11
						saveBreath=12
						saveSpell=13
					STR_VAR
						notEnforceFiles
				END
				ADD_CRE_ITEM ~ja#3m30~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~AC#WRIM1~) BEGIN 
				DEFINE_ARRAY notEnforceFiles BEGIN AC#FP2OT END
				LPF patchCreature
					INT_VAR
						level1=10
						hp=98
						thac0=11
						saveDeath=8
						saveWand=10
						savePolymorph=9
						saveBreath=9
						saveSpell=11
					STR_VAR
						notEnforceFiles
				END
			END
		BUT_ONLY_IF_IT_CHANGES
	END ELSE BEGIN
		PRINT ~====> CRE %file% not found!~
	END
END