COMPILE ~%MOD_FOLDER%/lib/pnp-monster/ogre/ja#m28.baf~

CREATE ITM "ja#m28w1"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 1
	WRITE_BYTE 0x88 6
	WRITE_BYTE 0x8a 1
	WRITE_SHORT 0x8e 2
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
COPY_EXISTING ~ja#m28w1.itm~ ~override~

ACTION_FOR_EACH ~file~ IN
	BDKORDEO
	OGREGR
	OGREGR1
	OGREGR2
	OGREGR3
	OGREGR4
	OGREGR_A
	OGREGR_B
	OGREGR_C
	OGREGR_D
	OGRELESU
	OGREMIRI
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~P2-8~
			ADD_CRE_ITEM ~ja#m28w1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			LPF clearProficiencies END
			LPF patchCreature
				INT_VAR
					level1=2
					strength=18
					dexterity=9
					constitution=14
					intelligence=6
					wisdom=7
					charisma=7
					movement=10
					hp=20
					ac=6
					thac0=17
					apr=2
					xpv=175
					alignment=IDS_OF_SYMBOL (~align~ ~CHAOTIC_EVIL~)
					saveDeath=14
					saveWand=16
					savePolymorph=15
					saveBreath=17
					saveSpell=17
					morale=10
					moraleBreak=4
					moraleRecovery=15
					general=IDS_OF_SYMBOL (~general~ ~MONSTER~)
					race=IDS_OF_SYMBOL (~race~ ~OGRE~)
					class=IDS_OF_SYMBOL (~class~ ~OGRE_OGRILLON~)
					gender=IDS_OF_SYMBOL (~gender~ ~MALE~)
					sex=IDS_OF_SYMBOL (~gender~ ~MALE~)
					enforce=1
			END
			LPF patchCreatureScript STR_VAR script=ja#m28 END
		BUT_ONLY_IF_IT_CHANGES
	END ELSE BEGIN
		PRINT ~====> CRE %file% not found!~
	END
END