COMPILE ~%MOD_FOLDER%/lib/pnp-monster/ogre/ja#m28.baf~
COMPILE ~%MOD_FOLDER%/lib/pnp-monster/ogre/ja#m28su.baf~

CREATE ITM "ja#1m28"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 1
	WRITE_BYTE 0x88 6
	WRITE_BYTE 0x8a 1
	WRITE_SHORT 0x8e 2
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
COPY_EXISTING ~ja#1m28.itm~ ~override~

ACTION_FOR_EACH ~file~ IN
	BDKORDEO
	GNARL
	HAIRTO
	OGREGR
	OGREGR1
	OGREGR2
	OGREGR3
	OGREGR4
	OGREGR_A
	OGREGR_B
	OGREGR_C
	OGREGR_D
	OGRELESU
	OGREMIRI
	SEWERF1
	UBSNOGOL
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~B1-8~
			REMOVE_CRE_ITEM ~SW1H01~
			ADD_CRE_ITEM ~ja#1m28~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			LPF clearProficiencies END
			DEFINE_ARRAY notEnforceFiles BEGIN  END
			LPF patchCreature
				INT_VAR
					level1=2
					strength=18
					exceptionalStrength=50
					dexterity=9
					constitution=14
					intelligence=6
					wisdom=7
					charisma=7
					movement=10
					hp=20
					ac=6
					thac0=17
					apr=2
					xpv=175
					alignment=IDS_OF_SYMBOL (~align~ ~CHAOTIC_EVIL~)
					saveDeath=14
					saveWand=16
					savePolymorph=15
					saveBreath=17
					saveSpell=17
					morale=10
					moraleBreak=4
					moraleRecovery=15
					general=IDS_OF_SYMBOL (~general~ ~GIANTHUMANOID~)
					race=IDS_OF_SYMBOL (~race~ ~OGRE~)
					class=IDS_OF_SYMBOL (~class~ ~OGRE_OGRILLON~)
					enforce=1
				STR_VAR
					notEnforceFiles
			END
			DEFINE_ARRAY removeScripts BEGIN ORGRILLON DW1MELGE BDSUM00 END
			DEFINE_ARRAY skipFiles BEGIN OGRELESU END
			LPF patchCreatureScript STR_VAR script=ja#m28 skipFiles removeScripts END
			DEFINE_ARRAY removeScripts BEGIN ORGRILLON DW1MELGE BDSUM00 END
			DEFINE_ARRAY files BEGIN OGRELESU END
			LPF patchCreatureScript STR_VAR script=ja#m28su files removeScripts END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~OGRELESU~) BEGIN 
			DEFINE_ARRAY notEnforceFiles BEGIN  END
				LPF patchCreature
					INT_VAR
						level1=3
						hp=28
						thac0=17
						xpv=0
						saveDeath=13
						saveWand=15
						savePolymorph=14
						saveBreath=16
						saveSpell=16
						summon=1
					STR_VAR
						notEnforceFiles
				END
			END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~GNARL~) OR ("%SOURCE_RES%" STRING_EQUAL_CASE ~HAIRTO~) BEGIN 
			DEFINE_ARRAY notEnforceFiles BEGIN  END
				LPF patchCreature
					INT_VAR
						level1=5
						exceptionalStrength=95
						constitution=15
						hp=45
						thac0=15
						xpv=420
						saveDeath=11
						saveWand=13
						savePolymorph=12
						saveBreath=13
						saveSpell=14
					STR_VAR
						notEnforceFiles
				END
			END
		BUT_ONLY_IF_IT_CHANGES
	END ELSE BEGIN
		PRINT ~====> CRE %file% not found!~
	END
END