COMPILE ~%MOD_FOLDER%/lib/pnp-monster/ogre/ja#m40.baf~

CREATE ITM "ja#1m40"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_LONG 0x18 64
	WRITE_LONG 0x60 1
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 2
	WRITE_BYTE 0x88 10
	WRITE_BYTE 0x8a 1
	WRITE_SHORT 0x8e 2
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
COPY_EXISTING ~ja#1m40.itm~ ~override~

ACTION_FOR_EACH ~file~ IN
	BDOGRE05
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~BLUN01~
			ADD_CRE_ITEM ~ja#1m40~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			LPF clearProficiencies END
			SET_BG2_PROFICIENCY ~PROFICIENCYTWOHANDEDSWORD~ 2
			LPF patchCreature
				INT_VAR
					level1=5
					level2=5
					strength=18
					dexterity=8
					constitution=16
					intelligence=12
					wisdom=13
					charisma=7
					movement=8
					hp=43
					ac=5
					thac0=15
					apr=1
					xpv=270
					alignment=IDS_OF_SYMBOL (~align~ ~CHAOTIC_EVIL~)
					saveDeath=11
					saveWand=13
					savePolymorph=12
					saveBreath=13
					saveSpell=14
					morale=12
					moraleBreak=4
					moraleRecovery=15
					general=IDS_OF_SYMBOL (~general~ ~GIANTHUMANOID~)
					race=IDS_OF_SYMBOL (~race~ ~OGRE~)
					class=IDS_OF_SYMBOL (~class~ ~FIGHTER_CLERIC~)
					enforce=1
			END
			DEFINE_ARRAY removeScripts BEGIN BDSHM00 END
			LPF patchCreatureScript STR_VAR script=ja#m40 removeScripts END
		BUT_ONLY_IF_IT_CHANGES
	END ELSE BEGIN
		PRINT ~====> CRE %file% not found!~
	END
END