COMPILE ~%MOD_FOLDER%/lib/pnp-monster/golem/ja#m26.baf~

CREATE SPL "ja#1m25"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x28
	WRITE_SHORT 0x68 1
	WRITE_LONG 0x6a 0x9a
	WRITE_SHORT 0x72 1
	WRITE_SHORT 0x82 1
	WRITE_SHORT 0x1c 4
	WRITE_LONG 0x34 1
	WRITE_SHORT 0x74 4
	WRITE_BYTE 0x7e 1
	SAY NAME1 @4013 SAY NAME2 @4013
	LPF GET_2DA_ENTRY_OF INT_VAR col_match = 0 STR_VAR file = ~msectype.2da~ entry_match = ~K1#SLOW~ RET row col END
	PATCH_IF row != "-1" BEGIN
		LPF ADD_EFFECT
			INT_VAR
				opcode = 221
				target = 2
				parameter1 = 9
				parameter2 = row
				duration = 18
				probability1 = 100
			END
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 40
			target = 2
			duration = 18
			probability1 = 100
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 142
			target = 2
			parameter2 = 38
			duration = 18
			probability1 = 100
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 141
			target = 2
			parameter2 = 4
			timing = 1
			probability1 = 100
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 61
			target = 2
			parameter1 = 2017213440
			parameter2 = 1638400
			timing = 1
			probability1 = 100
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 139
			target = 2
			parameter1 = 14023
			timing = 1
			probability1 = 100
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 174
			target = 2
			timing = 1
			probability1 = 100
		STR_VAR
			resource = "EFF_M28"
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 174
			target = 2
			timing = 4
			duration = 18
			probability1 = 100
		STR_VAR
			resource = "EFF_M29"
		END

CREATE ITM "ja#m26w1"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_LONG 0x18 64
	WRITE_LONG 0x60 4
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 2
	WRITE_BYTE 0x88 10
	WRITE_BYTE 0x8a 4
	WRITE_SHORT 0x8e 2
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
COPY_EXISTING ~ja#m26w1.itm~ ~override~

ACTION_FOR_EACH ~file~ IN
	
	
	
	
	
	
	
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~~
			ADD_CRE_ITEM ~ja#m26w1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			ADD_CRE_ITEM ~ja#i1~ #0 #0 #0 ~UNDROPPABLE~ ~HELMET~ 
			ADD_MEMORIZED_SPELL ~ja#1m25~ #0 ~innate~ (1)
			LPF clearProficiencies END
			LPF patchCreature
				INT_VAR
					level1=18
					strength=24
					dexterity=9
					constitution=20
					intelligence=3
					wisdom=11
					charisma=1
					movement=5
					hp=174
					ac=3
					resistFire=125
					resistMagic=100
					thac0=3
					apr=1
					xpv=13000
					alignment=IDS_OF_SYMBOL (~align~ ~NEUTRAL~)
					saveDeath=3
					saveWand=5
					savePolymorph=4
					saveBreath=4
					saveSpell=6
					morale=20
					moraleBreak=4
					moraleRecovery=15
					general=IDS_OF_SYMBOL (~general~ ~GIANTHUMANOID~)
					race=IDS_OF_SYMBOL (~race~ ~GOLEM~)
					class=IDS_OF_SYMBOL (~class~ ~GOLEM_IRON~)
					gender=IDS_OF_SYMBOL (~gender~ ~NIETHER~)
					sex=IDS_OF_SYMBOL (~gender~ ~NIETHER~)
					enforce=1
			END
			DEFINE_ARRAY removeScripts BEGIN  END
			LPF patchCreatureScript STR_VAR script=ja#m26 removeScripts END
		BUT_ONLY_IF_IT_CHANGES
	END ELSE BEGIN
		PRINT ~====> CRE %file% not found!~
	END
END