// Init
IF
	Global("JA#INIT","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("JA#INIT","LOCALS",1)
		SetGlobal("JA#COMBAT","LOCALS",0)
		SetGlobalTimer("JA#REST","LOCALS",2400)
END

// Rest (reset everything and heal if applicable)
IF
	Global("JA#INIT","LOCALS",1)
	GlobalTimerExpired("JA#REST","LOCALS")
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA#INIT","LOCALS",0)
		Rest()
		ApplySpell(Myself,RESTORE_FULL_HEALTH)
END

// Turn hostile if attacked
IF
	Allegiance(Myself,NEUTRAL)
	OR(4)
		AttackedBy([GOODCUTOFF],DEFAULT)
		SpellCastOnMe([GOODCUTOFF],0)
		TookDamage()
		Heard([EVILCUTOFF.0.GOLEM],99)
THEN
	RESPONSE #100
		Enemy()
END

// Detect combat
IF
	Global("JA#COMBAT","LOCALS",0)
	Allegiance(Myself,EVILCUTOFF)
	See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
END

// Detect combat
IF
	Global("JA#COMBAT","LOCALS",0)
	Allegiance(Myself,GOODCUTOFF)
	See([EVILCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
END

// Shouts every 3 rounds
IF
	Global("JA#COMBAT","LOCALS",1)
	!GlobalTimerNotExpired("JA#HELP","LOCALS")
THEN
	RESPONSE #100
		Shout(99)
		SetGlobalTimer("JA#HELP","LOCALS",18)
END

// React to shouts
IF
	Global("JA#COMBAT","LOCALS",0)
	Heard([EVILCUTOFF.0.GOLEM],99)
	InMyArea([EVILCUTOFF.0.GOLEM])
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
		MoveToObject(LastHeardBy(Myself))
END

IF
	Global("JA#COMBAT","LOCALS",1)
	Heard([EVILCUTOFF.0.GOLEM],99)
	InMyArea([EVILCUTOFF.0.GOLEM])
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		MoveToObject(LastHeardBy(Myself))
END

// Do nothing if...
IF
	OR(4)
		Global("JA#COMBAT","LOCALS",0)
		!Allegiance(Myself,EVILCUTOFF)
		StateCheck(Myself,STATE_IMMOBILE)
		StateCheck(Myself,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		NoAction()
END

IF
	!InActiveArea(Myself)
	!Range(NearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		NoAction()
END

// Slow
IF
	!GlobalTimerNotExpired("Slow","LOCALS")
	HaveSpell(WIZARD_SLOW)
	!StateCheck(NearestEnemyOf(Myself),STATE_SLOWED)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	Range(NearestEnemyOf(Myself),10)
	!General(NearestEnemyOf(Myself),WEAPON)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
	!CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(NearestEnemyOf(Myself),STATE_REALLY_DEAD)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetGlobalTimer("Slow","LOCALS",12)
		ReallyForceSpell(Myself,WIZARD_SLOW)
END

IF
	!GlobalTimerNotExpired("Slow","LOCALS")
	HaveSpell(WIZARD_SLOW)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLOWED)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	Range(SecondNearestEnemyOf(Myself),10)
	!General(SecondNearestEnemyOf(Myself),WEAPON)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_INVISIBLE)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_REALLY_DEAD)
	See(SecondNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetGlobalTimer("Slow","LOCALS",12)
		ReallyForceSpell(Myself,WIZARD_SLOW)
END

IF
	!GlobalTimerNotExpired("Slow","LOCALS")
	HaveSpell(WIZARD_SLOW)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLOWED)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	Range(ThirdNearestEnemyOf(Myself),10)
	!General(ThirdNearestEnemyOf(Myself),WEAPON)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_INVISIBLE)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_REALLY_DEAD)
	See(ThirdNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetGlobalTimer("Slow","LOCALS",12)
		ReallyForceSpell(Myself,WIZARD_SLOW)
END

IF
	!GlobalTimerNotExpired("Slow","LOCALS")
	HaveSpell(WIZARD_SLOW)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_SLOWED)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	Range(FourthNearestEnemyOf(Myself),10)
	!General(FourthNearestEnemyOf(Myself),WEAPON)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_INVISIBLE)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
	See(FourthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetGlobalTimer("Slow","LOCALS",12)
		ReallyForceSpell(Myself,WIZARD_SLOW)
END

IF
	!GlobalTimerNotExpired("Slow","LOCALS")
	HaveSpell(WIZARD_SLOW)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_SLOWED)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	Range(FifthNearestEnemyOf(Myself),10)
	!General(FifthNearestEnemyOf(Myself),WEAPON)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_INVISIBLE)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
	See(FifthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetGlobalTimer("Slow","LOCALS",12)
		ReallyForceSpell(Myself,WIZARD_SLOW)
END

// Attack NoCheck enemy
IF
	OR(5)
		General(NearestEnemyOf(Myself),WEAPON)
		StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NearestEnemyOf(Myself))
	OR(5)
		General(SecondNearestEnemyOf(Myself),WEAPON)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SecondNearestEnemyOf(Myself))
	OR(5)
		General(ThirdNearestEnemyOf(Myself),WEAPON)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(ThirdNearestEnemyOf(Myself))
	OR(5)
		General(FourthNearestEnemyOf(Myself),WEAPON)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FourthNearestEnemyOf(Myself))
	OR(5)
		General(FifthNearestEnemyOf(Myself),WEAPON)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FifthNearestEnemyOf(Myself))
	OR(5)
		General(SixthNearestEnemyOf(Myself),WEAPON)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SixthNearestEnemyOf(Myself))
	OR(5)
		General(SeventhNearestEnemyOf(Myself),WEAPON)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(SeventhNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SeventhNearestEnemyOf(Myself))
	OR(5)
		General(EighthNearestEnemyOf(Myself),WEAPON)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(EighthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(EighthNearestEnemyOf(Myself))
	OR(5)
		General(NinthNearestEnemyOf(Myself),WEAPON)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(NinthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NinthNearestEnemyOf(Myself))
	OR(5)
		General(TenthNearestEnemyOf(Myself),WEAPON)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(TenthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(TenthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Continue()
END

IF
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

// Attack Sleep enemy
IF
	OR(5)
		!StateCheck(Player1,STATE_SLEEPING)
		StateCheck(Player1,STATE_INVISIBLE)
		CheckStatGT(Player1,0,SANCTUARY)
		StateCheck(Player1,STATE_REALLY_DEAD)
		!See(Player1)
	OR(5)
		!StateCheck(Player2,STATE_SLEEPING)
		StateCheck(Player2,STATE_INVISIBLE)
		CheckStatGT(Player2,0,SANCTUARY)
		StateCheck(Player2,STATE_REALLY_DEAD)
		!See(Player2)
	OR(5)
		!StateCheck(Player3,STATE_SLEEPING)
		StateCheck(Player3,STATE_INVISIBLE)
		CheckStatGT(Player3,0,SANCTUARY)
		StateCheck(Player3,STATE_REALLY_DEAD)
		!See(Player3)
	OR(5)
		!StateCheck(Player4,STATE_SLEEPING)
		StateCheck(Player4,STATE_INVISIBLE)
		CheckStatGT(Player4,0,SANCTUARY)
		StateCheck(Player4,STATE_REALLY_DEAD)
		!See(Player4)
	OR(5)
		!StateCheck(Player5,STATE_SLEEPING)
		StateCheck(Player5,STATE_INVISIBLE)
		CheckStatGT(Player5,0,SANCTUARY)
		StateCheck(Player5,STATE_REALLY_DEAD)
		!See(Player5)
	OR(5)
		!StateCheck(Player6,STATE_SLEEPING)
		StateCheck(Player6,STATE_INVISIBLE)
		CheckStatGT(Player6,0,SANCTUARY)
		StateCheck(Player6,STATE_REALLY_DEAD)
		!See(Player6)
THEN
	RESPONSE #100
		Continue()
END

IF
	StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

// Track players if allegiance is not GOODCUTOFF
IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player1)
	Range(Player1,150)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStatGT(Player1,0,SANCTUARY)
	!StateCheck(Player1,STATE_CHARMED)
	!StateCheck(Player1,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player2)
	Range(Player2,150)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStatGT(Player2,0,SANCTUARY)
	!StateCheck(Player2,STATE_CHARMED)
	!StateCheck(Player2,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player3)
	Range(Player3,150)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStatGT(Player3,0,SANCTUARY)
	!StateCheck(Player3,STATE_CHARMED)
	!StateCheck(Player3,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player4)
	Range(Player4,150)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStatGT(Player4,0,SANCTUARY)
	!StateCheck(Player4,STATE_CHARMED)
	!StateCheck(Player4,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player5)
	Range(Player5,150)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStatGT(Player5,0,SANCTUARY)
	!StateCheck(Player5,STATE_CHARMED)
	!StateCheck(Player5,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player6)
	Range(Player6,150)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStatGT(Player6,0,SANCTUARY)
	!StateCheck(Player6,STATE_CHARMED)
	!StateCheck(Player6,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

// Track last seen enemy if allegiance is GOODCUTOFF
IF
	Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(LastSeenBy(Myself))
	Range(LastSeenBy(Myself),150)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

// Random walking (in combat) 
IF
	Global("JA#COMBAT","LOCALS",1)
	ActionListEmpty()
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		RandomWalk()
		Wait(2)
END

