INCLUDE "%MOD_FOLDER%/lib/pnp-monster/golem/23.tpa" // Flesh Golem
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/golem/24.tpa" // Clay Golem
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/golem/25.tpa" // Stone Golem
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/golem/26.tpa" // Iron Golem
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/golem/27.tpa" // Bone Golem
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/golem/33.tpa" // Juggernaut Golem
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/golem/67.tpa" // Snow Golem
