COPY ~%MOD_FOLDER%/spl/rr#telwe.spl~ ~override/rr#ddoor.spl~            // Dimension Door (renewable)
  SAY NAME1 #12082 SAY NAME2 #12082
  LPF SPELL_TO_INNATE INT_VAR ctime=1 renew=1 END

COPY ~%MOD_FOLDER%/spl/rr#telwe.spl~ ~override/rr#ddor2.spl~            // Dimension Door (non-renewable, for Nymphs)
  SAY NAME1 #12082 SAY NAME2 #12082
  LPF SPELL_TO_INNATE INT_VAR ctime=1 END

COPY ~%MOD_FOLDER%/spl/rr#telwx.spl~ ~override/rr#ddorx.spl~            // Dimension Door (special version, breaks targeting via 1 second invisibility)
  SAY NAME1 #12082 SAY NAME2 #12082
  LPF SPELL_TO_INNATE INT_VAR ctime=1 END

COPY ~%MOD_FOLDER%/spl/fey/rr#fafrn.spl~ ~override~                     // Animal Friendship (renewable)
  SAY NAME1 @1900 SAY NAME2 @1900

COPY ~%MOD_FOLDER%/spl/fey/rr#fbbea.spl~ ~override~                     // Blinding Beauty (part 1)
  SAY NAME1 @1901 SAY NAME2 @1901
  READ_LONG  0x64 ab_off
  READ_SHORT 0x68 ab_num
  FOR(i=0; i<ab_num; i+=1) BEGIN
    WRITE_SHORT (ab_off+i*0x28+0x26) %fl#sight%                         // use new projectile
  END

COPY ~%MOD_FOLDER%/spl/fey/rr#fbbe2.spl~ ~override~                     // Blinding Beauty (part 2)
COPY ~%MOD_FOLDER%/eff/fey/rr#fbbea.eff~ ~override~                     // Blinding Beauty EFF (for targeting only humanoids)

COPY ~%MOD_FOLDER%/spl/fey/rr#fcsng.spl~ ~override~                     // Charming Song (part 1)
  SAY NAME1 @1902 SAY NAME2 @1902
  READ_LONG  0x64 ab_off
  READ_SHORT 0x68 ab_num
  FOR(i=0; i<ab_num; i+=1) BEGIN
    WRITE_SHORT (ab_off+i*0x28+0x26) %rr#fcsng%                         // use new projectile
  END

COPY ~%MOD_FOLDER%/spl/fey/rr#fcsn2.spl~ ~override~                     // Charming Song (part 2)
COPY ~%MOD_FOLDER%/eff/fey/rr#fcsng.eff~ ~override~                     // Charming Song EFF 1 (for targeting only humanoids)
COPY ~%MOD_FOLDER%/eff/fey/rr#fcsn2.eff~ ~override~                     // Charming Song EFF 2 (for elven and half-elven charm immunity)
  SAY 0x1C @1903                                                        // Resists charm effect

// Items and spells which cause Deafness should grant immunity to the Sirine's Charming Song
ACTION_FOR_EACH ~file~ IN
    ~spwi223~  // Deafness
    ~rr#bhl5a~ // Resonating Weapon (RR)
BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~%file%.spl~ BEGIN
    COPY_EXISTING ~%file%.spl~ ~override~
      PATCH_IF (%SOURCE_SIZE% > 0x71) THEN BEGIN  // file size sanity check (filters out 0 byte files i.e. ALLOW_MISSING)
        LPF add_conditional_immunity INT_VAR opcode = 80 stringref = 4742 STR_VAR spell = rr#fcsng END
      END
    BUT_ONLY_IF_IT_CHANGES
  END
END

COPY ~%MOD_FOLDER%/spl/fey/rr#fdsnr.spl~ ~override~       // Detect Snares and Pits (renewable)
  SAY NAME1 @1904 SAY NAME2 @1904

COPY ~%MOD_FOLDER%/vvc/rr#mmswf.vvc~ ~override~           // Fog Cloud animation
COPY ~%MOD_FOLDER%/spl/fey/rr#fcld.spl~ ~override~        // Fog Cloud

COPY ~%MOD_FOLDER%/spl/fey/rr#fdsnr.spl~ ~override~       // Detect Snares and Pits (renewable)
  SAY NAME1 @1904 SAY NAME2 @1904

COPY ~%MOD_FOLDER%/spl/fey/rr#ftrnq.spl~ ~override~       // Touch of Tranquility (spell)
  SAY NAME1 @1905 SAY NAME2 @1905

COPY ~%MOD_FOLDER%/spl/fey/rr#fiinv.spl~ ~override~       // Improved Invisibility shell spell (use Casting Level 11th)
COPY_EXISTING ~SPWI405.SPL~  ~override/rr#wi405.spl~      // Clone Improved Invisibility into an innate ability (used by Sirine)
  LPF SPELL_TO_INNATE INT_VAR ctime=1 END

COPY ~%MOD_FOLDER%/spl/fey/rr#pjell.spl~ ~override~       // Polymorph Mustard Jelly (Sirine)
  ADD_PROJECTILE ~%MOD_FOLDER%/pro/rr#ftvap.pro~          // New projectile for Toxic Vapors (small area cloud)

COPY ~%MOD_FOLDER%/spl/fey/rr#ftvap.spl~ ~override~       // Mustard Jelly Toxic Vapors
  SAY NAME1 @1906 SAY NAME2 @1906
  READ_LONG  0x64 ab_off
  READ_SHORT 0x68 ab_num
  FOR(i=0; i<ab_num; i+=1) BEGIN
    WRITE_SHORT (ab_off+i*0x28+0x26) %rr#ftvap%           // use new projectile
  END
  FOR (i = LONG_AT 0x6a; i < SOURCE_SIZE; i += 0x30) BEGIN
    READ_BYTE  i + 0xc timing
    WRITE_LONG i + 0xe timing = 1 ? 0 : 12                // 2 rounds for non-instant effects
  END

COPY ~%MOD_FOLDER%/cre/fey/rr#pjell.cre~ ~override~       // Mustard Jelly (PnP style)
COPY ~%MOD_FOLDER%/itm/fey/rr#pjell.itm~ ~override~       // Mustard Jelly attack (PnP style)
COPY ~%MOD_FOLDER%/itm/fey/rr#fsiri.itm~ ~override~       // Sirine's Boots (movement rate increase, destroyed when polymorphed)
