// Dimension Door
CREATE SPL "spwi402"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x28
	WRITE_SHORT 0x68 1
	WRITE_LONG 0x6a 0x9a
	WRITE_SHORT 0x72 1
	WRITE_SHORT 0x82 1
	WRITE_LONG 0x18 2048
	WRITE_ASCII 0x3a ~SPWI402C~ #8
	WRITE_ASCII 0x76 ~SPWI402B~ #8
	WRITE_SHORT 0x22 10
	WRITE_SHORT 0x1c 1
	WRITE_BYTE 0x25 8
	WRITE_BYTE 0x27 13
	WRITE_LONG 0x34 4
	WRITE_ASCII 0x10 ~CAS_M08~ #8
	WRITE_SHORT 0x74 2
	WRITE_BYTE 0x7e 4
	WRITE_SHORT 0x80 900
	WRITE_SHORT 0x84 1
	WRITE_SHORT 0x98 1
	WRITE_LONG 0x8 12082
	WRITE_LONG 0xc 12082
	WRITE_LONG 0x50 RESOLVE_STR_REF(@1891)
	LPF ADD_EFFECT INT_VAR opcode=141 target=1 power=4 resist_dispel=1 probability1=100 timing=1 parameter2=38 END
	LPF ADD_EFFECT INT_VAR opcode=174	target=1 power=4 resist_dispel=1 probability1=100 timing=1 STR_VAR resource="EFF_M09"	END
	LPF ADD_EFFECT INT_VAR opcode=215 target=1 power=4 resist_dispel=1 probability1=100 timing=1 parameter2=2 duration=1 STR_VAR resource="SPDIMNDR" END
	LPF ADD_EFFECT INT_VAR opcode=124	target=1 power=4 resist_dispel=1 probability1=100 timing=4 duration=1 END
	LPF ADD_EFFECT INT_VAR opcode=20  target=1 power=4 resist_dispel=1 probability1=100 timing=3 duration=1 END

LAF hide_spell INT_VAR hide=0 STR_VAR ids="WIZARD_DIMENSION_DOOR" END
LAF hide_spell INT_VAR hide=1 silent=1 STR_VAR ids="WIZARD_DIMENSION_JUMP" END

ACTION_FOR_EACH ~file~ IN
	scrl1v    // Spell Revisions
	d0scrldd  // D0 Tweaks
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.itm~ BEGIN
		COPY_EXISTING ~%file%.itm~ ~override~
      PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
        WRITE_LONG 0xc 12082
        WRITE_LONG 0x34 500
        WRITE_ASCII 0x3a ~SPWI402A~ #8
        WRITE_ASCII 0x76 ~SPWI402A~ #8
        WRITE_ASCII 0xae ~SPWI402A~ #8
        SAY DESC @1891
        LPF ALTER_EFFECT INT_VAR silent=1 match_opcode=147 STR_VAR resource=~SPWI402~ END
        LPF ALTER_EFFECT INT_VAR silent=1 match_opcode=148 STR_VAR resource=~SPWI402~ END
      END
		BUT_ONLY_IF_IT_CHANGES
	END
END

// COPY_EXISTING_REGEXP GLOB ~^.+\.sto$~ ~override~                                   // parses through all stores in the game (even those added by mods)
//   PATCH_IF (%SOURCE_SIZE% > 0x9b) THEN BEGIN                                       // file size sanity check (filters out 0 byte files i.e. ALLOW_MISSING)
//     READ_LONG 0x08 "itemtype" ELSE 0                                               // check store type
//     PATCH_IF "%itemtype%" != 5 BEGIN                                               // if the store isn't a container
//       ADD_STORE_ITEM ~rr#scr1v~ AFTER ~SCRL1U~ #1 #0 #0 ~IDENTIFIED~ #2            // Add 2x Dimension Door scroll
//     END
//   END
// IF "_?SCRL1U" //confusion
// UNLESS "d0scrldd\|BGSCRL1V\|_?SCRL1V_?" //DD from d0Tweaks, BGT, Tutu and EET
// BUT_ONLY_IF_IT_CHANGES
