ACTION_FOR_EACH i IN 1 2 3 4 BEGIN
	COPY ~%MOD_FOLDER%/cre/ja#trean.cre~ ~override/ja#trea%i%.cre~
		SET ref = 1930 + i
		WRITE_LONG 0x8 RESOLVE_STR_REF((AT ref))
		WRITE_LONG 0xc RESOLVE_STR_REF((AT ref))
END

INCLUDE "%MOD_FOLDER%/lib/pnp-monster/plant/treant.tpa"

ACTION_FOR_EACH cre IN ~ja#dryad~ ~ja#trea1~ ~ja#trea2~ ~ja#trea3~ ~ja#trea4~ BEGIN
	CREATE EFF %cre%
		WRITE_LONG 0x10 67
		WRITE_LONG 0x14 2
		WRITE_LONG 0x24 1
		WRITE_SHORT 0x2c 100
		WRITE_ASCII 0x30 ~%cre%~ #8
END

APPEND ~splprot.2da~ ~JA_NOT_OUTDOOR_CHECK%TAB%0x106%TAB%1%TAB%9~ UNLESS ~JA_NOT_OUTDOOR_CHECK~

COPY_EXISTING ~sppr410.spl~ ~override~
  SAY DESC @1895 SAY UNIDENTIFIED_DESC @1895
  LPF DELETE_SPELL_HEADER INT_VAR header_type="-1" END
COPY_EXISTING ~sppr410.spl~ ~override~
  LPF GET_2DA_ENTRY_OF INT_VAR col_match=0 STR_VAR file=~splprot~ entry_match=~JA_NOT_OUTDOOR_CHECK~ RET JA_NOT_OUTDOOR_CHECK=row END
	PATCH_DEFINE_ASSOCIATIVE_ARRAY table BEGIN
		~1~ => ~1~
		~2~ => ~13~
		~3~ => ~20~
	END
	PHP_EACH table AS i => required_level BEGIN
		SPRINT resource ~ja#trea%i%~ 
		LPF ADD_SPELL_HEADER INT_VAR type=1 target=4 required_level location=2 speed=9 range=20 projectile=0 STR_VAR icon=~sppr410B~ END  
		LPF ADD_EFFECT INT_VAR header=i opcode=324 target=1 duration=1 parameter2=JA_NOT_OUTDOOR_CHECK STR_VAR resource=~sppr410~ END
		LPF ADD_EFFECT INT_VAR header=i opcode=177 target=1 power=4 parameter1=IDS_OF_SYMBOL (~EA~ ~ANYONE~) parameter2=2 resist_dispel=2 duration=120 probability1=100 STR_VAR resource END
	END
