COPY ~%MOD_FOLDER%/cre/ja#trean.cre~ ~override/ja#trea1.cre~      // Treant 8hd
  WRITE_LONG 0x8 RESOLVE_STR_REF(@1931)
  WRITE_LONG 0xc RESOLVE_STR_REF(@1931)
COPY ~%MOD_FOLDER%/cre/ja#trean.cre~ ~override/ja#trea2.cre~      // Treant 10hd
  WRITE_LONG 0x8 RESOLVE_STR_REF(@1932)
  WRITE_LONG 0xc RESOLVE_STR_REF(@1932)
COPY ~%MOD_FOLDER%/cre/ja#trean.cre~ ~override/ja#trea3.cre~      // Treant 12hd
  WRITE_LONG 0x8 RESOLVE_STR_REF(@1933)
  WRITE_LONG 0xc RESOLVE_STR_REF(@1933)

INCLUDE "%MOD_FOLDER%/lib/pnp-monster/plant/treant.tpa"

CREATE EFF "ja#dryad"
	WRITE_LONG 0x10 67
	WRITE_LONG 0x14 2
	WRITE_LONG 0x24 1
	WRITE_SHORT 0x2c 100
	WRITE_ASCII 0x30 ~ja#dryad~ #8

CREATE EFF "ja#trea1"
	WRITE_LONG 0x10 67
	WRITE_LONG 0x14 2
	WRITE_LONG 0x24 1
	WRITE_SHORT 0x2c 100
	WRITE_ASCII 0x30 ~ja#trea1~ #8

CREATE EFF "ja#trea2"
	WRITE_LONG 0x10 67
	WRITE_LONG 0x14 2
	WRITE_LONG 0x24 1
	WRITE_SHORT 0x2c 100
	WRITE_ASCII 0x30 ~ja#trea2~ #8

CREATE EFF "ja#trea3"
	WRITE_LONG 0x10 67
	WRITE_LONG 0x14 2
	WRITE_LONG 0x24 1
	WRITE_SHORT 0x2c 100
	WRITE_ASCII 0x30 ~ja#trea3~ #8

APPEND ~splprot.2da~ ~JA_NOT_OUTDOOR_CHECK%TAB%0x106%TAB%1%TAB%9~ UNLESS ~JA_NOT_OUTDOOR_CHECK~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~JA_NOT_OUTDOOR_CHECK~ BEGIN
	    SET JA_NOT_OUTDOOR_CHECK = %row%
      SET row=rows
	  END
	END

COPY_EXISTING ~sppr410.spl~ ~override~
  SAY DESC @1895 SAY UNIDENTIFIED_DESC @1895
  LPF DELETE_SPELL_HEADER INT_VAR header_type="-1" END
COPY_EXISTING ~sppr410.spl~ ~override~
  SET speed=9
  SET duration=120
  // level 1
  LPF ADD_SPELL_HEADER INT_VAR type=1 target=4 required_level=1 location=2 speed range=20 projectile=0 STR_VAR icon=~sppr410B~ END  
	LPF ADD_EFFECT INT_VAR header=1 opcode=324 target=1 duration=1 parameter2=JA_NOT_OUTDOOR_CHECK STR_VAR resource=~sppr410~ END
  LPF ADD_EFFECT INT_VAR header=1 opcode=177 target=1 parameter1=IDS_OF_SYMBOL (~EA~ ~ANYONE~) parameter2=2 resist_dispel=2 duration probability1=100 STR_VAR resource=~ja#dryad~ END
  LPF ADD_EFFECT INT_VAR header=1 opcode=177 target=1 parameter1=IDS_OF_SYMBOL (~EA~ ~ANYONE~) parameter2=2 resist_dispel=2 duration probability1=75 STR_VAR resource=~ja#dryad~ END
  LPF ADD_EFFECT INT_VAR header=1 opcode=177 target=1 parameter1=IDS_OF_SYMBOL (~EA~ ~ANYONE~) parameter2=2 resist_dispel=2 duration probability1=50 STR_VAR resource=~ja#dryad~ END
  LPF ADD_EFFECT INT_VAR header=1 opcode=177 target=1 parameter1=IDS_OF_SYMBOL (~EA~ ~ANYONE~) parameter2=2 resist_dispel=2 duration probability1=25 STR_VAR resource=~ja#dryad~ END
  // level 13
  LPF ADD_SPELL_HEADER INT_VAR type=1 target=4 required_level=13 location=2 speed range=20 projectile=0 STR_VAR icon=~sppr410B~ END  
	LPF ADD_EFFECT INT_VAR header=2 opcode=324 target=1 duration=1 parameter2=JA_NOT_OUTDOOR_CHECK STR_VAR resource=~sppr410~ END
	LPF ADD_EFFECT INT_VAR header=2 opcode=177 target=1 power=4 parameter1=IDS_OF_SYMBOL (~EA~ ~ANYONE~) parameter2=2 resist_dispel=2 duration probability1=100 STR_VAR resource=~ja#trea2~ END
  // level 20
  LPF ADD_SPELL_HEADER INT_VAR type=1 target=4 required_level=20 location=2 speed range=20 projectile=0 STR_VAR icon=~sppr410B~ END  
	LPF ADD_EFFECT INT_VAR header=3 opcode=324 target=1 duration=1 parameter2=JA_NOT_OUTDOOR_CHECK STR_VAR resource=~sppr410~ END
	LPF ADD_EFFECT INT_VAR header=3 opcode=177 target=1 power=4 parameter1=IDS_OF_SYMBOL (~EA~ ~ANYONE~) parameter2=2 resist_dispel=2 duration probability1=100 STR_VAR resource=~ja#trea3~ END


