export enum AnimationIdentifiers {
    FIRE_RING = "FIRE_RING",
    FIRE_RING_BRIGHT = "FIRE_RING_BRIGHT",
    CHUNKS = "CHUNKS",
    EXPLODING_ARM = "EXPLODING_ARM",
    EXPLODING_HEAD = "EXPLODING_HEAD",
    EXPLODING_FOOT = "EXPLODING_FOOT",
    EXPLODING_TORSO = "EXPLODING_TORSO",
    EXPLODING_LEG = "EXPLODING_LEG",
    SMOKE_PUFF_LARGE = "SMOKE_PUFF_LARGE",
    SMOKE_PUFF_SMALL = "SMOKE_PUFF_SMALL",
    TRAP_SKULL = "TRAP_SKULL",
    TRAP_GLYPH = "TRAP_GLYPH",
    CLOUD_TRAVEL = "CLOUD_TRAVEL",
    CLOUD_STATIC = "CLOUD_STATIC",
    STORM_TRAVEL = "STORM_TRAVEL",
    STORM_STATIC = "STORM_STATIC",
    GREASE_TRAVEL = "GREASE_TRAVEL",
    GREASE_STATIC = "GREASE_STATIC",
    WEB_TRAVEL = "WEB_TRAVEL",
    WEB_STATIC = "WEB_STATIC",
    WYVERN_BIG = "WYVERN_BIG",
    WYVERN_WHITE_BIG = "WYVERN_WHITE_BIG",
    WYRMLING_ALBINO = "WYRMLING_ALBINO",
    TANARRI = "TANARRI",
    DRAGON_WHITE = "DRAGON_WHITE",
    FIEND_BLUE = "FIEND_BLUE",
    FIEND_GREEN = "FIEND_GREEN",
    FIEND_RED = "FIEND_RED",
    DRAGON_GREEN_IWD = "DRAGON_GREEN_IWD",
    DRAGON_RED = "DRAGON_RED",
    DRAGON_BLACK = "DRAGON_BLACK",
    DRAGON_SILVER = "DRAGON_SILVER",
    DRAGON_GREEN = "DRAGON_GREEN",
    DRAGON_AQUA = "DRAGON_AQUA",
    DRAGON_BLUE = "DRAGON_BLUE",
    DRAGON_BROWN = "DRAGON_BROWN",
    DRAGON_MULTICOLOR = "DRAGON_MULTICOLOR",
    DRAGON_PURPLE = "DRAGON_PURPLE",
    DEMOGORGON = "DEMOGORGON",
    SIRINE = "SIRINE",
    VOLO = "VOLO",
    OGRE_MAGE = "OGRE_MAGE",
    DEATH_KNIGHT = "DEATH_KNIGHT",
    ANKHEG = "ANKHEG",
    STATIC_NOBLE_MAN_CHAIR = "STATIC_NOBLE_MAN_CHAIR",
    NULL_ANIMATION = "NULL_ANIMATION",
    STATIC_NOBLE_MAN_MATTE = "STATIC_NOBLE_MAN_MATTE",
    STATIC_NOBLE_WOMAN_CHAIR = "STATIC_NOBLE_WOMAN_CHAIR",
    STATIC_NOBLE_WOMAN_MATTE = "STATIC_NOBLE_WOMAN_MATTE",
    STATIC_PEASANT_MAN_CHAIR = "STATIC_PEASANT_MAN_CHAIR",
    STATIC_PEASANT_MAN_STOOL = "STATIC_PEASANT_MAN_STOOL",
    STATIC_PEASANT_MAN_MATTE = "STATIC_PEASANT_MAN_MATTE",
    STATIC_PEASANT_WOMAN_CHAIR = "STATIC_PEASANT_WOMAN_CHAIR",
    STATIC_PEASANT_WOMAN_MATTE = "STATIC_PEASANT_WOMAN_MATTE",
    STATIC_HUMANCLERIC_MAN_CHAIR = "STATIC_HUMANCLERIC_MAN_CHAIR",
    STATIC_SPIDER_WOMAN = "STATIC_SPIDER_WOMAN",
    SLEEPING_MAN_HUMAN = "SLEEPING_MAN_HUMAN",
    SLEEPING_WOMAN_HUMAN = "SLEEPING_WOMAN_HUMAN",
    SLEEPING_FAT_MAN_HUMAN = "SLEEPING_FAT_MAN_HUMAN",
    SLEEPING_DWARF = "SLEEPING_DWARF",
    SLEEPING_MAN_ELF = "SLEEPING_MAN_ELF",
    SLEEPING_WOMAN_ELF = "SLEEPING_WOMAN_ELF",
    SLEEPING_MAN_HALFLING = "SLEEPING_MAN_HALFLING",
    CLERIC_MALE_HUMAN_LOW = "CLERIC_MALE_HUMAN_LOW",
    CLERIC_MALE_ELF_LOW = "CLERIC_MALE_ELF_LOW",
    CLERIC_MALE_DWARF_LOW = "CLERIC_MALE_DWARF_LOW",
    CLERIC_MALE_HALFLING_LOW = "CLERIC_MALE_HALFLING_LOW",
    CLERIC_FEMALE_HUMAN_LOW = "CLERIC_FEMALE_HUMAN_LOW",
    CLERIC_FEMALE_ELF_LOW = "CLERIC_FEMALE_ELF_LOW",
    CLERIC_FEMALE_DWARF_LOW = "CLERIC_FEMALE_DWARF_LOW",
    CLERIC_FEMALE_HALFLING_LOW = "CLERIC_FEMALE_HALFLING_LOW",
    FIGHTER_MALE_HUMAN_LOW = "FIGHTER_MALE_HUMAN_LOW",
    FIGHTER_MALE_ELF_LOW = "FIGHTER_MALE_ELF_LOW",
    FIGHTER_MALE_DWARF_LOW = "FIGHTER_MALE_DWARF_LOW",
    FIGHTER_MALE_HALFLING_LOW = "FIGHTER_MALE_HALFLING_LOW",
    FIGHTER_FEMALE_HUMAN_LOW = "FIGHTER_FEMALE_HUMAN_LOW",
    FIGHTER_FEMALE_ELF_LOW = "FIGHTER_FEMALE_ELF_LOW",
    FIGHTER_FEMALE_DWARF_LOW = "FIGHTER_FEMALE_DWARF_LOW",
    FIGHTER_FEMALE_HALFLING_LOW = "FIGHTER_FEMALE_HALFLING_LOW",
    MAGE_MALE_HUMAN_LOW = "MAGE_MALE_HUMAN_LOW",
    MAGE_MALE_ELF_LOW = "MAGE_MALE_ELF_LOW",
    MAGE_MALE_DWARF_LOW = "MAGE_MALE_DWARF_LOW",
    MAGE_FEMALE_HUMAN_LOW = "MAGE_FEMALE_HUMAN_LOW",
    MAGE_FEMALE_ELF_LOW = "MAGE_FEMALE_ELF_LOW",
    MAGE_FEMALE_DWARF_LOW = "MAGE_FEMALE_DWARF_LOW",
    THIEF_MALE_HUMAN_LOW = "THIEF_MALE_HUMAN_LOW",
    THIEF_MALE_ELF_LOW = "THIEF_MALE_ELF_LOW",
    THIEF_MALE_DWARF_LOW = "THIEF_MALE_DWARF_LOW",
    THIEF_MALE_HALFLING_LOW = "THIEF_MALE_HALFLING_LOW",
    THIEF_FEMALE_HUMAN_LOW = "THIEF_FEMALE_HUMAN_LOW",
    THIEF_FEMALE_ELF_LOW = "THIEF_FEMALE_ELF_LOW",
    THIEF_FEMALE_DWARF_LOW = "THIEF_FEMALE_DWARF_LOW",
    THIEF_FEMALE_HALFLING_LOW = "THIEF_FEMALE_HALFLING_LOW",
    CLERIC_MALE_HUMAN = "CLERIC_MALE_HUMAN",
    CLERIC_MALE_ELF = "CLERIC_MALE_ELF",
    CLERIC_MALE_DWARF = "CLERIC_MALE_DWARF",
    CLERIC_MALE_HALFLING = "CLERIC_MALE_HALFLING",
    CLERIC_MALE_GNOME = "CLERIC_MALE_GNOME",
    CLERIC_MALE_HALFORC = "CLERIC_MALE_HALFORC",
    CLERIC_FEMALE_HUMAN = "CLERIC_FEMALE_HUMAN",
    CLERIC_FEMALE_ELF = "CLERIC_FEMALE_ELF",
    CLERIC_FEMALE_DWARF = "CLERIC_FEMALE_DWARF",
    CLERIC_FEMALE_HALFLING = "CLERIC_FEMALE_HALFLING",
    CLERIC_FEMALE_GNOME = "CLERIC_FEMALE_GNOME",
    CLERIC_FEMALE_HALFORC = "CLERIC_FEMALE_HALFORC",
    FIGHTER_MALE_HUMAN = "FIGHTER_MALE_HUMAN",
    FIGHTER_MALE_ELF = "FIGHTER_MALE_ELF",
    FIGHTER_MALE_DWARF = "FIGHTER_MALE_DWARF",
    FIGHTER_MALE_HALFLING = "FIGHTER_MALE_HALFLING",
    FIGHTER_MALE_GNOME = "FIGHTER_MALE_GNOME",
    FIGHTER_MALE_HALFORC = "FIGHTER_MALE_HALFORC",
    FIGHTER_FEMALE_HUMAN = "FIGHTER_FEMALE_HUMAN",
    FIGHTER_FEMALE_ELF = "FIGHTER_FEMALE_ELF",
    FIGHTER_FEMALE_DWARF = "FIGHTER_FEMALE_DWARF",
    FIGHTER_FEMALE_HALFLING = "FIGHTER_FEMALE_HALFLING",
    FIGHTER_FEMALE_GNOME = "FIGHTER_FEMALE_GNOME",
    FIGHTER_FEMALE_HALFORC = "FIGHTER_FEMALE_HALFORC",
    MAGE_MALE_HUMAN = "MAGE_MALE_HUMAN",
    MAGE_MALE_ELF = "MAGE_MALE_ELF",
    MAGE_MALE_DWARF = "MAGE_MALE_DWARF",
    MAGE_MALE_GNOME = "MAGE_MALE_GNOME",
    MAGE_MALE_HALFORC = "MAGE_MALE_HALFORC",
    MAGE_FEMALE_HUMAN = "MAGE_FEMALE_HUMAN",
    MAGE_FEMALE_ELF = "MAGE_FEMALE_ELF",
    MAGE_FEMALE_DWARF = "MAGE_FEMALE_DWARF",
    MAGE_FEMALE_GNOME = "MAGE_FEMALE_GNOME",
    MAGE_FEMALE_HALFORC = "MAGE_FEMALE_HALFORC",
    THIEF_MALE_HUMAN = "THIEF_MALE_HUMAN",
    THIEF_MALE_ELF = "THIEF_MALE_ELF",
    THIEF_MALE_DWARF = "THIEF_MALE_DWARF",
    THIEF_MALE_HALFLING = "THIEF_MALE_HALFLING",
    THIEF_MALE_GNOME = "THIEF_MALE_GNOME",
    THIEF_MALE_HALFORC = "THIEF_MALE_HALFORC",
    THIEF_FEMALE_HUMAN = "THIEF_FEMALE_HUMAN",
    THIEF_FEMALE_ELF = "THIEF_FEMALE_ELF",
    THIEF_FEMALE_DWARF = "THIEF_FEMALE_DWARF",
    THIEF_FEMALE_HALFLING = "THIEF_FEMALE_HALFLING",
    THIEF_FEMALE_GNOME = "THIEF_FEMALE_GNOME",
    THIEF_FEMALE_HALFORC = "THIEF_FEMALE_HALFORC",
    DRIZZT = "DRIZZT",
    ELMINSTER = "ELMINSTER",
    MONK = "MONK",
    SKELETON = "SKELETON",
    SAREVOK = "SAREVOK",
    DOOM_GUARD = "DOOM_GUARD",
    DOOM_GUARD_LARGER = "DOOM_GUARD_LARGER",
    MONK_MALE_HUMAN = "MONK_MALE_HUMAN",
    MONK_FEMALE_HUMAN = "MONK_FEMALE_HUMAN",
    FIGHTER_FEMALE_HUMAN_BG1 = "FIGHTER_FEMALE_HUMAN_BG1",
    HALF_OGRE = "HALF_OGRE",
    OGRILLON = "OGRILLON",
    BASILISK = "BASILISK",
    BASILISK_GREATER = "BASILISK_GREATER",
    BEAR_BLACK = "BEAR_BLACK",
    BEAR_BROWN = "BEAR_BROWN",
    BEAR_CAVE = "BEAR_CAVE",
    BEAR_POLAR = "BEAR_POLAR",
    ELEMENTAL_EARTH = "ELEMENTAL_EARTH",
    ELEMENTAL_EARTH_SMALL = "ELEMENTAL_EARTH_SMALL",
    SHAMBLING_MOUND = "SHAMBLING_MOUND",
    ELEMENTAL_FIRE = "ELEMENTAL_FIRE",
    ELEMENTAL_FIRE_SMALL = "ELEMENTAL_FIRE_SMALL",
    ELEMENTAL_FIRE_PURPLE = "ELEMENTAL_FIRE_PURPLE",
    ELEMENTAL_FIRE_SMALL_PURPLE = "ELEMENTAL_FIRE_SMALL_PURPLE",
    BURNING_MAN = "BURNING_MAN",
    ELEMENTAL_AIR = "ELEMENTAL_AIR",
    ELEMENTAL_AIR_SMALL = "ELEMENTAL_AIR_SMALL",
    DOG_WILD = "DOG_WILD",
    DOG_WAR = "DOG_WAR",
    DOG_MOON = "DOG_MOON",
    DOPPLEGANGER = "DOPPLEGANGER",
    DOPPLEGANGER_GREATER = "DOPPLEGANGER_GREATER",
    ETTERCAP = "ETTERCAP",
    MAUREZHI = "MAUREZHI",
    MYRLOCHAR = "MYRLOCHAR",
    DOG_GRAY = "DOG_GRAY",
    SPIDER_WATER = "SPIDER_WATER",
    GHOUL = "GHOUL",
    REVENANT = "REVENANT",
    GHAST = "GHAST",
    SHADOW = "SHADOW",
    GIBBERLING = "GIBBERLING",
    GIBBERLING_BROOD = "GIBBERLING_BROOD",
    BLACK_PUDDING = "BLACK_PUDDING",
    SLIME_GREEN = "SLIME_GREEN",
    SLIME_OLIVE = "SLIME_OLIVE",
    SLIME_MUSTARD = "SLIME_MUSTARD",
    SLIME_OCHRE = "SLIME_OCHRE",
    GRAY_OOZE = "GRAY_OOZE",
    SPIDER_GIANT = "SPIDER_GIANT",
    SPIDER_HUGE = "SPIDER_HUGE",
    SPIDER_PHASE = "SPIDER_PHASE",
    SPIDER_SWORD = "SPIDER_SWORD",
    SPIDER_WRAITH = "SPIDER_WRAITH",
    WOLF = "WOLF",
    WOLF_WORG = "WOLF_WORG",
    WOLF_DIRE = "WOLF_DIRE",
    WOLF_WINTER = "WOLF_WINTER",
    WOLF_VAMPIRIC = "WOLF_VAMPIRIC",
    WOLF_DREAD = "WOLF_DREAD",
    WOLF_SHADOW = "WOLF_SHADOW",
    KOBOLD_XVART = "KOBOLD_XVART",
    KOBOLD_TASLOI = "KOBOLD_TASLOI",
    ZOMBIE = "ZOMBIE",
    SLAVE_FIGHTER = "SLAVE_FIGHTER",
    CHICKEN_BROWN = "CHICKEN_BROWN",
    CHICKEN_WHITE = "CHICKEN_WHITE",
    HARLOT_FIGHTER = "HARLOT_FIGHTER",
    NOBLEMAN_FIGHTER = "NOBLEMAN_FIGHTER",
    NOBLEWOMAN_FIGHTER = "NOBLEWOMAN_FIGHTER",
    PEASANT_MAN_FIGHTER = "PEASANT_MAN_FIGHTER",
    PEASANT_WOMAN_FIGHTER = "PEASANT_WOMAN_FIGHTER",
    WEREWOLF = "WEREWOLF",
    WEREWOLF_GREATER = "WEREWOLF_GREATER",
    TROLL = "TROLL",
    MINDFLAYER = "MINDFLAYER",
    BEHOLDER = "BEHOLDER",
    IMP = "IMP",
    GOLEM_IRON = "GOLEM_IRON",
    DJINNI = "DJINNI",
    DJINNI_LEGS = "DJINNI_LEGS",
    GOLEM_CLAY = "GOLEM_CLAY",
    OTYUGH = "OTYUGH",
    SAHUAGIN = "SAHUAGIN",
    GREATCAT_PANTHER = "GREATCAT_PANTHER",
    GREATCAT_LEOPARD = "GREATCAT_LEOPARD",
    KUO_TOA = "KUO-TOA",
    LICH = "LICH",
    DEMILICH = "DEMILICH",
    TROLL_SMALL = "TROLL_SMALL",
    RAKSHASA = "RAKSHASA",
    UMBER_HULK = "UMBER_HULK",
    VAMPIRE = "VAMPIRE",
    SNAKE = "SNAKE",
    GITHYANKI = "GITHYANKI",
    BEHOLDER_SMALL = "BEHOLDER_SMALL",
    MOOSE = "MOOSE",
    RABBIT = "RABBIT",
    DEER = "DEER",
    DANCING_SWORD = "DANCING_SWORD",
    GROUNDHOG = "GROUNDHOG",
    PHEASANT = "PHEASANT",
    VAMPIRE_FEMALE = "VAMPIRE_FEMALE",
    SAHUAGIN_LARGE = "SAHUAGIN_LARGE",
    PIRATE = "PIRATE",
    DROW = "DROW",
    KUO_TOA_LARGE = "KUO-TOA_LARGE",
    DROW_FEMALE = "DROW_FEMALE",
    SAILOR_MAN = "SAILOR_MAN",
    MDK2_MAX = "MDK2_MAX",
    AMNIAN_SOLDIER = "AMNIAN_SOLDIER",
    WYVERN_FAMILIAR = "WYVERN_FAMILIAR",
    RAVER = "RAVER",
    SPIDER_SMALL = "SPIDER_SMALL",
    BODHI = "BODHI",
    ELLESIME = "ELLESIME",
    SLAYER = "SLAYER",
    MDK2_KURT = "MDK2_KURT",
    MDK2_DOCTOR = "MDK2_DOCTOR",
    MIST_CREATURE = "MIST_CREATURE",
    SHADOW_THIEF = "SHADOW_THIEF",
    JON_IRENICUS = "JON_IRENICUS",
    WIZARD_EYE = "WIZARD_EYE",
    BLOB_MIST_CREATURE = "BLOB_MIST_CREATURE",
    IRENICUS_ROBED = "IRENICUS_ROBED",
    SOLAR = "SOLAR",
    DEVA_MONADIC = "DEVA_MONADIC",
    MELISSAN = "MELISSAN",
    GIANT_FIRE = "GIANT_FIRE",
    GIANT_YAGA_SHURA = "GIANT_YAGA-SHURA",
    GOLEM_MINI = "GOLEM_MINI",
    EFREETI_NOBLE = "EFREETI_NOBLE",
    RED_WIZARD = "RED_WIZARD",
    YOCHLOL = "YOCHLOL",
    ELLESIME_WHITE = "ELLESIME_WHITE",
    LAGOON_CREATURE = "LAGOON_CREATURE",
    DEATH_TYRANT = "DEATH_TYRANT",
    GIANT_FIRE_2 = "GIANT_FIRE_2",
    SOLAR_FALLEN = "SOLAR_FALLEN",
    DEVA_MONADIC_FALLEN = "DEVA_MONADIC_FALLEN",
    DEVA_ASTRAL = "DEVA_ASTRAL",
    DEVA_ASTRAL_FALLEN = "DEVA_ASTRAL_FALLEN",
    PLANETAR = "PLANETAR",
    PLANETAR_FALLEN = "PLANETAR_FALLEN",
    DEVA_MOVANIC = "DEVA_MOVANIC",
    DEVA_MOVANIC_FALLEN = "DEVA_MOVANIC_FALLEN",
    NISHRUU = "NISHRUU",
    HAKEASHAR = "HAKEASHAR",
    SAILOR_GREEN = "SAILOR_GREEN",
    SAILOR_RED = "SAILOR_RED",
    SAILOR_DARK = "SAILOR_DARK",
    CRUSADER_SOLDIER = "CRUSADER_SOLDIER",
    WILL_O_WISP = "WILL_O_WISP",
    WILL_O_WISP_SMALL = "WILL_O_WISP_SMALL",
    ABISHAI_BLACK = "ABISHAI_BLACK",
    ABISHAI_GREEN = "ABISHAI_GREEN",
    ABISHAI_RED = "ABISHAI_RED",
    ABISHAI_BLUE = "ABISHAI_BLUE",
    HAG_NIGHT = "HAG_NIGHT",
    HAG_GREEN = "HAG_GREEN",
    HAG_SEA = "HAG_SEA",
    HAG_ANNIS = "HAG_ANNIS",
    SNAKE_WATER = "SNAKE_WATER",
    DRAGON_RED_JUVENILE = "DRAGON_RED_JUVENILE",
    DRAGON_GREEN_JUVENILE = "DRAGON_GREEN_JUVENILE",
    GNOLL = "GNOLL",
    HOBGOBLIN = "HOBGOBLIN",
    KOBOLD = "KOBOLD",
    OGRE = "OGRE",
    WYVERN = "WYVERN",
    CARRION_CRAWLER = "CARRION_CRAWLER",
    WYVERN_WHITE = "WYVERN_WHITE",
    MEGALOCENTIPEDE = "MEGALOCENTIPEDE",
    TUNNEL_WORM = "TUNNEL_WORM",
    COW = "COW",
    HORSE = "HORSE",
    STATIC_BEGGAR_MAN = "STATIC_BEGGAR_MAN",
    STATIC_HARLOT_WOMAN = "STATIC_HARLOT_WOMAN",
    STATIC_BOY = "STATIC_BOY",
    STATIC_GIRL = "STATIC_GIRL",
    STATIC_FAT_MAN = "STATIC_FAT_MAN",
    STATIC_FAT_WOMAN = "STATIC_FAT_WOMAN",
    STATIC_PEASANT_MAN = "STATIC_PEASANT_MAN",
    STATIC_PEASANT_WOMAN = "STATIC_PEASANT_WOMAN",
    STATIC_NOBLE_MAN = "STATIC_NOBLE_MAN",
    STATIC_NOBLE_WOMAN = "STATIC_NOBLE_WOMAN",
    STATIC_SLAVE = "STATIC_SLAVE",
    BAT_INSIDE = "BAT_INSIDE",
    CAT = "CAT",
    CHICKEN = "CHICKEN",
    RAT = "RAT",
    SQUIRREL = "SQUIRREL",
    BAT_OUTSIDE = "BAT_OUTSIDE",
    BEGGAR_MAN = "BEGGAR_MAN",
    HARLOT_WOMAN = "HARLOT_WOMAN",
    BOY = "BOY",
    GIRL = "GIRL",
    FAT_MAN = "FAT_MAN",
    FAT_WOMAN = "FAT_WOMAN",
    PEASANT_MAN = "PEASANT_MAN",
    PEASANT_WOMAN = "PEASANT_WOMAN",
    NOBLE_MAN = "NOBLE_MAN",
    NOBLE_WOMAN = "NOBLE_WOMAN",
    SLAVE = "SLAVE",
    KEG1 = "KEG1",
    KEG2 = "KEG2",
    KEG3 = "KEG3",
    RAT_OUTSIDE = "RAT_OUTSIDE",
    EAGLE = "EAGLE",
    SEAGULL = "SEAGULL",
    VULTURE = "VULTURE",
    BIRD = "BIRD",
    BIRD_INSIDE = "BIRD_INSIDE",
    CYCLOPS = "CYCLOPS",
    ETTIN = "ETTIN",
    DONOT_USE = "DONOT_USE",
    HISTACHII = "HISTACHII",
    LICH_BLACK = "LICH_BLACK",
    LICH_WHITE = "LICH_WHITE",
    MINOTAUR = "MINOTAUR",
    MUMMY = "MUMMY",
    MARILITH = "MARILITH",
    TROLL_ICE = "TROLL_ICE",
    TROLL_BLUE = "TROLL_BLUE",
    TROLL_SNOW = "TROLL_SNOW",
    UMBER_HULK_ELDER = "UMBER_HULK_ELDER",
    CORNUGON = "CORNUGON",
    GOLEM_ICE = "GOLEM_ICE",
    GLABREZU = "GLABREZU",
    WAILING_VIRGIN = "WAILING_VIRGIN",
    BEETLE_BORING = "BEETLE_BORING",
    BEETLE_FIRE = "BEETLE_FIRE",
    BEETLE_BOMBARDIER = "BEETLE_BOMBARDIER",
    BEETLE_RHINOCEROS = "BEETLE_RHINOCEROS",
    ANIMATED_PLATE_BRONZE = "ANIMATED_PLATE_BRONZE",
    ANIMATED_PLATE_DARK = "ANIMATED_PLATE_DARK",
    ANIMATED_PLATE_GREEN = "ANIMATED_PLATE_GREEN",
    ARUNDEL = "ARUNDEL",
    BARBARIAN_WARRIOR_TAN = "BARBARIAN_WARRIOR_TAN",
    BARBARIAN_WARRIOR_RED = "BARBARIAN_WARRIOR_RED",
    BARBARIAN_WARRIOR_BROWN = "BARBARIAN_WARRIOR_BROWN",
    BARBARIAN_SHAMAN_HAMMER = "BARBARIAN_SHAMAN_HAMMER",
    BARBARIAN_SHAMAN_STAFF = "BARBARIAN_SHAMAN_STAFF",
    BARBARIAN_SHAMAN_CLUB = "BARBARIAN_SHAMAN_CLUB",
    BARBARIAN_ICASARACHT = "BARBARIAN_ICASARACHT",
    ELEMENTAL_EARTH_IWD = "ELEMENTAL_EARTH_IWD",
    ELEMENTAL_FIRE_IWD = "ELEMENTAL_FIRE_IWD",
    ELEMENTAL_WATER = "ELEMENTAL_WATER",
    GIANT_FIRE_IWD = "GIANT_FIRE_IWD",
    GIANT_FROST = "GIANT_FROST",
    GOLEM_IRON_IWD = "GOLEM_IRON_IWD",
    GIANT_VERBEEG = "GIANT_VERBEEG",
    HARPY = "HARPY",
    REMORHAZ = "REMORHAZ",
    TROLL_SCRAG = "TROLL_SCRAG",
    SEER = "SEER",
    BELHIFET = "BELHIFET",
    BELHIFET_PRIEST = "BELHIFET_PRIEST",
    HEPHERNAAN = "HEPHERNAAN",
    SVIRFNEBLIN_PALE_AXE = "SVIRFNEBLIN_PALE_AXE",
    SVIRFNEBLIN_PALE_NOAXE = "SVIRFNEBLIN_PALE_NOAXE",
    UMBER_HULK_VODYANOI = "UMBER_HULK_VODYANOI",
    MARILITH_IWD = "MARILITH_IWD",
    TUNDRA_YETI = "TUNDRA_YETI",
    WIGHT_BARROW = "WIGHT_BARROW",
    DROWNED_DEAD = "DROWNED_DEAD",
    CREEPING_DOOM = "CREEPING_DOOM",
    SAHUAGIN_IWD = "SAHUAGIN_IWD",
    SAHUAGIN_LARGE_IWD = "SAHUAGIN_LARGE_IWD",
    SVIRFNEBLIN_DARK_AXE = "SVIRFNEBLIN_DARK_AXE",
    SVIRFNEBLIN_DARK_NOAXE = "SVIRFNEBLIN_DARK_NOAXE",
    BOAR_ARCTIC = "BOAR_ARCTIC",
    BUGBEAR_CAPTAIN = "BUGBEAR_CAPTAIN",
    BUGBEAR = "BUGBEAR",
    CHIMERA = "CHIMERA",
    HALFDRAGON_BLACK = "HALFDRAGON_BLACK",
    HALFDRAGON_RED = "HALFDRAGON_RED",
    TREANT_DARK = "TREANT_DARK",
    ELEMENTAL_WATER_SMALL = "ELEMENTAL_WATER_SMALL",
    FEYR_GREATER = "FEYR_GREATER",
    FEYR = "FEYR",
    GIANT_FOMORIAN = "GIANT_FOMORIAN",
    GOBLIN_CAPTAIN = "GOBLIN_CAPTAIN",
    GOBLIN_SHAMAN = "GOBLIN_SHAMAN",
    GOBLIN_WORG = "GOBLIN_WORG",
    GOBLIN_WORG_CAPTAIN = "GOBLIN_WORG_CAPTAIN",
    HOOK_HORROR = "HOOK_HORROR",
    ISAIR = "ISAIR",
    LEMURE = "LEMURE",
    MADAE = "MADAE",
    MALARITE = "MALARITE",
    OROG_SHAMAN = "OROG_SHAMAN",
    ORC_AXE_UNDEAD = "ORC_AXE_UNDEAD",
    ORC_SHAMAN_UNDEAD = "ORC_SHAMAN_UNDEAD",
    SHENRICAL = "SHENRICAL",
    WEREBADGER = "WEREBADGER",
    WERERAT = "WERERAT",
    BOAR_WILD = "BOAR_WILD",
    WORG = "WORG",
    YUAN_TI_HALF = "YUAN-TI_HALF",
    DRIDER_FEMALE = "DRIDER_FEMALE",
    DRIDER_MALE = "DRIDER_MALE",
    INVISIBLE_SMALL = "INVISIBLE_SMALL",
    INVISIBLE_MEDIUM = "INVISIBLE_MEDIUM",
    INVISIBLE_LARGE = "INVISIBLE_LARGE",
    INVISIBLE_GIANT = "INVISIBLE_GIANT",
    GOBLIN_WORG_ELITE = "GOBLIN_WORG_ELITE",
    GOBLIN_WORG_SHAMAN = "GOBLIN_WORG_SHAMAN",
    TROLL_SPECTRAL = "TROLL_SPECTRAL",
    ABISHAI_WHITE = "ABISHAI_WHITE",
    DRAGON_WHITE_YOUNG = "DRAGON_WHITE_YOUNG",
    DRAGON_SILVER_YOUNG = "DRAGON_SILVER_YOUNG",
    DRAGON_GREEN_YOUNG = "DRAGON_GREEN_YOUNG",
    DROWNED_DEAD_RED = "DROWNED_DEAD_RED",
    HALFDRAGON_GREEN = "HALFDRAGON_GREEN",
    BUGBEAR_SHAMAN = "BUGBEAR_SHAMAN",
    ETTIN_GHOST = "ETTIN_GHOST",
    GIANT_HILL = "GIANT_HILL",
    BONEBAT = "BONEBAT",
    GHOST = "GHOST",
    GHOUL_GREATER = "GHOUL_GREATER",
    GHAST_GREATER = "GHAST_GREATER",
    GOBLIN_AXE = "GOBLIN_AXE",
    GOBLIN_BOW = "GOBLIN_BOW",
    GOBLIN_ELITE_AXE = "GOBLIN_ELITE_AXE",
    GOBLIN_ELITE_BOW = "GOBLIN_ELITE_BOW",
    MKHIIN = "MKHIIN",
    MKHIIN_BOW = "MKHIIN_BOW",
    MKHIIN_STAFF = "MKHIIN_STAFF",
    MKHIIN_ARMOR_AXE = "MKHIIN_ARMOR_AXE",
    MKHIIN_ARMOR_BOW = "MKHIIN_ARMOR_BOW",
    LIZARD_MAN_ELITE = "LIZARD_MAN_ELITE",
    LIZARD_MAN = "LIZARD_MAN",
    LIZARD_KING = "LIZARD_KING",
    MYCONID_RED = "MYCONID_RED",
    MYCONID_BLUE = "MYCONID_BLUE",
    OROG = "OROG",
    OROG_ELITE = "OROG_ELITE",
    OROG_CHIEFTAIN = "OROG_CHIEFTAIN",
    ORC_MELEE = "ORC_MELEE",
    ORC_RANGE = "ORC_RANGE",
    ORC_ELITE_MELEE = "ORC_ELITE_MELEE",
    ORC_ELITE_RANGE = "ORC_ELITE_RANGE",
    ORC_SHAMAN = "ORC_SHAMAN",
    SALAMANDER_FIRE = "SALAMANDER_FIRE",
    SALAMANDER_FROST = "SALAMANDER_FROST",
    SHRIEKER = "SHRIEKER",
    SHADOW_SMALL = "SHADOW_SMALL",
    SHADOW_LARGE = "SHADOW_LARGE",
    SKELETON_MONSTER = "SKELETON_MONSTER",
    SKELETON_WARRIOR = "SKELETON_WARRIOR",
    SKELETON_FIEND = "SKELETON_FIEND",
    WIGHT_GRAY = "WIGHT_GRAY",
    WIGHT_GREEN = "WIGHT_GREEN",
    WIGHT_YELLOW = "WIGHT_YELLOW",
    YUAN_TI = "YUAN-TI",
    YUAN_TI_ELITE = "YUAN-TI_ELITE",
    YUAN_TI_PRIEST = "YUAN-TI_PRIEST",
    ZOMBIE_YELLOW = "ZOMBIE_YELLOW",
    ZOMBIE_BLUE = "ZOMBIE_BLUE",
    WATER_WEIRD = "WATER_WEIRD",
    BOLT_OF_GLORY = "BOLT_OF_GLORY",
    SUN_SOULRAY = "SUN_SOULRAY",
}

export const animationIds = [
    { id: "0x0000", value: "FIRE_RING" },
    { id: "0x0001", value: "FIRE_RING_BRIGHT" },
    { id: "0x0100", value: "CHUNKS" },
    { id: "0x0200", value: "EXPLODING_ARM" },
    { id: "0x0210", value: "EXPLODING_HEAD" },
    { id: "0x0220", value: "EXPLODING_FOOT" },
    { id: "0x0230", value: "EXPLODING_TORSO" },
    { id: "0x0240", value: "EXPLODING_LEG" },
    { id: "0x0300", value: "SMOKE_PUFF_LARGE" },
    { id: "0x0301", value: "SMOKE_PUFF_SMALL" },
    { id: "0x0400", value: "TRAP_SKULL" },
    { id: "0x0410", value: "TRAP_GLYPH" },
    { id: "0x0500", value: "CLOUD_TRAVEL" },
    { id: "0x0510", value: "CLOUD_STATIC" },
    { id: "0x0600", value: "STORM_TRAVEL" },
    { id: "0x0610", value: "STORM_STATIC" },
    { id: "0x0700", value: "GREASE_TRAVEL" },
    { id: "0x0710", value: "GREASE_STATIC" },
    { id: "0x0800", value: "WEB_TRAVEL" },
    { id: "0x0810", value: "WEB_STATIC" },
    { id: "0x1000", value: "WYVERN_BIG" },
    { id: "0x1003", value: "WYVERN_WHITE_BIG" },
    { id: "0x1004", value: "WYRMLING_ALBINO" },
    { id: "0x1100", value: "TANARRI" },
    { id: "0x1101", value: "DRAGON_WHITE" },
    { id: "0x1102", value: "FIEND_BLUE" },
    { id: "0x1103", value: "FIEND_GREEN" },
    { id: "0x1104", value: "FIEND_RED" },
    { id: "0x1105", value: "DRAGON_GREEN_IWD" },
    { id: "0x1200", value: "DRAGON_RED" },
    { id: "0x1201", value: "DRAGON_BLACK" },
    { id: "0x1202", value: "DRAGON_SILVER" },
    { id: "0x1203", value: "DRAGON_GREEN" },
    { id: "0x1204", value: "DRAGON_AQUA" },
    { id: "0x1205", value: "DRAGON_BLUE" },
    { id: "0x1206", value: "DRAGON_BROWN" },
    { id: "0x1207", value: "DRAGON_MULTICOLOR" },
    { id: "0x1208", value: "DRAGON_PURPLE" },
    { id: "0x1300", value: "DEMOGORGON" },
    { id: "0x2000", value: "SIRINE" },
    { id: "0x2100", value: "VOLO" },
    { id: "0x2200", value: "OGRE_MAGE" },
    { id: "0x2300", value: "DEATH_KNIGHT" },
    { id: "0x3000", value: "ANKHEG" },
    { id: "0x4000", value: "STATIC_NOBLE_MAN_CHAIR" },
    { id: "0x4001", value: "NULL_ANIMATION" },
    { id: "0x4002", value: "STATIC_NOBLE_MAN_MATTE" },
    { id: "0x4010", value: "STATIC_NOBLE_WOMAN_CHAIR" },
    { id: "0x4012", value: "STATIC_NOBLE_WOMAN_MATTE" },
    { id: "0x4100", value: "STATIC_PEASANT_MAN_CHAIR" },
    { id: "0x4101", value: "STATIC_PEASANT_MAN_STOOL" },
    { id: "0x4102", value: "STATIC_PEASANT_MAN_MATTE" },
    { id: "0x4110", value: "STATIC_PEASANT_WOMAN_CHAIR" },
    { id: "0x4112", value: "STATIC_PEASANT_WOMAN_MATTE" },
    { id: "0x4200", value: "STATIC_HUMANCLERIC_MAN_CHAIR" },
    { id: "0x4300", value: "STATIC_SPIDER_WOMAN" },
    { id: "0x4400", value: "SLEEPING_MAN_HUMAN" },
    { id: "0x4410", value: "SLEEPING_WOMAN_HUMAN" },
    { id: "0x4500", value: "SLEEPING_FAT_MAN_HUMAN" },
    { id: "0x4600", value: "SLEEPING_DWARF" },
    { id: "0x4700", value: "SLEEPING_MAN_ELF" },
    { id: "0x4710", value: "SLEEPING_WOMAN_ELF" },
    { id: "0x4800", value: "SLEEPING_MAN_HALFLING" },
    { id: "0x5000", value: "CLERIC_MALE_HUMAN_LOW" },
    { id: "0x5001", value: "CLERIC_MALE_ELF_LOW" },
    { id: "0x5002", value: "CLERIC_MALE_DWARF_LOW" },
    { id: "0x5003", value: "CLERIC_MALE_HALFLING_LOW" },
    { id: "0x5010", value: "CLERIC_FEMALE_HUMAN_LOW" },
    { id: "0x5011", value: "CLERIC_FEMALE_ELF_LOW" },
    { id: "0x5012", value: "CLERIC_FEMALE_DWARF_LOW" },
    { id: "0x5013", value: "CLERIC_FEMALE_HALFLING_LOW" },
    { id: "0x5100", value: "FIGHTER_MALE_HUMAN_LOW" },
    { id: "0x5101", value: "FIGHTER_MALE_ELF_LOW" },
    { id: "0x5102", value: "FIGHTER_MALE_DWARF_LOW" },
    { id: "0x5103", value: "FIGHTER_MALE_HALFLING_LOW" },
    { id: "0x5110", value: "FIGHTER_FEMALE_HUMAN_LOW" },
    { id: "0x5111", value: "FIGHTER_FEMALE_ELF_LOW" },
    { id: "0x5112", value: "FIGHTER_FEMALE_DWARF_LOW" },
    { id: "0x5113", value: "FIGHTER_FEMALE_HALFLING_LOW" },
    { id: "0x5200", value: "MAGE_MALE_HUMAN_LOW" },
    { id: "0x5201", value: "MAGE_MALE_ELF_LOW" },
    { id: "0x5202", value: "MAGE_MALE_DWARF_LOW" },
    { id: "0x5210", value: "MAGE_FEMALE_HUMAN_LOW" },
    { id: "0x5211", value: "MAGE_FEMALE_ELF_LOW" },
    { id: "0x5212", value: "MAGE_FEMALE_DWARF_LOW" },
    { id: "0x5300", value: "THIEF_MALE_HUMAN_LOW" },
    { id: "0x5301", value: "THIEF_MALE_ELF_LOW" },
    { id: "0x5302", value: "THIEF_MALE_DWARF_LOW" },
    { id: "0x5303", value: "THIEF_MALE_HALFLING_LOW" },
    { id: "0x5310", value: "THIEF_FEMALE_HUMAN_LOW" },
    { id: "0x5311", value: "THIEF_FEMALE_ELF_LOW" },
    { id: "0x5312", value: "THIEF_FEMALE_DWARF_LOW" },
    { id: "0x5313", value: "THIEF_FEMALE_HALFLING_LOW" },
    { id: "0x6000", value: "CLERIC_MALE_HUMAN" },
    { id: "0x6001", value: "CLERIC_MALE_ELF" },
    { id: "0x6002", value: "CLERIC_MALE_DWARF" },
    { id: "0x6003", value: "CLERIC_MALE_HALFLING" },
    { id: "0x6004", value: "CLERIC_MALE_GNOME" },
    { id: "0x6005", value: "CLERIC_MALE_HALFORC" },
    { id: "0x6010", value: "CLERIC_FEMALE_HUMAN" },
    { id: "0x6011", value: "CLERIC_FEMALE_ELF" },
    { id: "0x6012", value: "CLERIC_FEMALE_DWARF" },
    { id: "0x6013", value: "CLERIC_FEMALE_HALFLING" },
    { id: "0x6014", value: "CLERIC_FEMALE_GNOME" },
    { id: "0x6015", value: "CLERIC_FEMALE_HALFORC" },
    { id: "0x6100", value: "FIGHTER_MALE_HUMAN" },
    { id: "0x6101", value: "FIGHTER_MALE_ELF" },
    { id: "0x6102", value: "FIGHTER_MALE_DWARF" },
    { id: "0x6103", value: "FIGHTER_MALE_HALFLING" },
    { id: "0x6104", value: "FIGHTER_MALE_GNOME" },
    { id: "0x6105", value: "FIGHTER_MALE_HALFORC" },
    { id: "0x6110", value: "FIGHTER_FEMALE_HUMAN" },
    { id: "0x6111", value: "FIGHTER_FEMALE_ELF" },
    { id: "0x6112", value: "FIGHTER_FEMALE_DWARF" },
    { id: "0x6113", value: "FIGHTER_FEMALE_HALFLING" },
    { id: "0x6114", value: "FIGHTER_FEMALE_GNOME" },
    { id: "0x6115", value: "FIGHTER_FEMALE_HALFORC" },
    { id: "0x6200", value: "MAGE_MALE_HUMAN" },
    { id: "0x6201", value: "MAGE_MALE_ELF" },
    { id: "0x6202", value: "MAGE_MALE_DWARF" },
    { id: "0x6204", value: "MAGE_MALE_GNOME" },
    { id: "0x6205", value: "MAGE_MALE_HALFORC" },
    { id: "0x6210", value: "MAGE_FEMALE_HUMAN" },
    { id: "0x6211", value: "MAGE_FEMALE_ELF" },
    { id: "0x6212", value: "MAGE_FEMALE_DWARF" },
    { id: "0x6214", value: "MAGE_FEMALE_GNOME" },
    { id: "0x6215", value: "MAGE_FEMALE_HALFORC" },
    { id: "0x6300", value: "THIEF_MALE_HUMAN" },
    { id: "0x6301", value: "THIEF_MALE_ELF" },
    { id: "0x6302", value: "THIEF_MALE_DWARF" },
    { id: "0x6303", value: "THIEF_MALE_HALFLING" },
    { id: "0x6304", value: "THIEF_MALE_GNOME" },
    { id: "0x6305", value: "THIEF_MALE_HALFORC" },
    { id: "0x6310", value: "THIEF_FEMALE_HUMAN" },
    { id: "0x6311", value: "THIEF_FEMALE_ELF" },
    { id: "0x6312", value: "THIEF_FEMALE_DWARF" },
    { id: "0x6313", value: "THIEF_FEMALE_HALFLING" },
    { id: "0x6314", value: "THIEF_FEMALE_GNOME" },
    { id: "0x6315", value: "THIEF_FEMALE_HALFORC" },
    { id: "0x6400", value: "DRIZZT" },
    { id: "0x6401", value: "ELMINSTER" },
    { id: "0x6402", value: "MONK" },
    { id: "0x6403", value: "SKELETON" },
    { id: "0x6404", value: "SAREVOK" },
    { id: "0x6405", value: "DOOM_GUARD" },
    { id: "0x6406", value: "DOOM_GUARD_LARGER" },
    { id: "0x6500", value: "MONK_MALE_HUMAN" },
    { id: "0x6510", value: "MONK_FEMALE_HUMAN" },
    { id: "0x6621", value: "FIGHTER_FEMALE_HUMAN_BG1" },
    { id: "0x7000", value: "HALF_OGRE" },
    { id: "0x7001", value: "OGRILLON" },
    { id: "0x7100", value: "BASILISK" },
    { id: "0x7101", value: "BASILISK_GREATER" },
    { id: "0x7200", value: "BEAR_BLACK" },
    { id: "0x7201", value: "BEAR_BROWN" },
    { id: "0x7202", value: "BEAR_CAVE" },
    { id: "0x7203", value: "BEAR_POLAR" },
    { id: "0x7300", value: "ELEMENTAL_EARTH" },
    { id: "0x7301", value: "ELEMENTAL_EARTH_SMALL" },
    { id: "0x7302", value: "SHAMBLING_MOUND" },
    { id: "0x7310", value: "ELEMENTAL_FIRE" },
    { id: "0x7311", value: "ELEMENTAL_FIRE_SMALL" },
    { id: "0x7312", value: "ELEMENTAL_FIRE_PURPLE" },
    { id: "0x7313", value: "ELEMENTAL_FIRE_SMALL_PURPLE" },
    { id: "0x7314", value: "BURNING_MAN" },
    { id: "0x7320", value: "ELEMENTAL_AIR" },
    { id: "0x7321", value: "ELEMENTAL_AIR_SMALL" },
    { id: "0x7400", value: "DOG_WILD" },
    { id: "0x7401", value: "DOG_WAR" },
    { id: "0x7402", value: "DOG_MOON" },
    { id: "0x7500", value: "DOPPLEGANGER" },
    { id: "0x7501", value: "DOPPLEGANGER_GREATER" },
    { id: "0x7600", value: "ETTERCAP" },
    { id: "0x7601", value: "MAUREZHI" },
    { id: "0x7602", value: "MYRLOCHAR" },
    { id: "0x7603", value: "DOG_GRAY" },
    { id: "0x7604", value: "SPIDER_WATER" },
    { id: "0x7700", value: "GHOUL" },
    { id: "0x7701", value: "REVENANT" },
    { id: "0x7702", value: "GHAST" },
    { id: "0x7703", value: "SHADOW" },
    { id: "0x7800", value: "GIBBERLING" },
    { id: "0x7801", value: "GIBBERLING_BROOD" },
    { id: "0x7802", value: "BLACK_PUDDING" },
    { id: "0x7900", value: "SLIME_GREEN" },
    { id: "0x7901", value: "SLIME_OLIVE" },
    { id: "0x7902", value: "SLIME_MUSTARD" },
    { id: "0x7903", value: "SLIME_OCHRE" },
    { id: "0x7904", value: "GRAY_OOZE" },
    { id: "0x7A00", value: "SPIDER_GIANT" },
    { id: "0x7A01", value: "SPIDER_HUGE" },
    { id: "0x7A02", value: "SPIDER_PHASE" },
    { id: "0x7A03", value: "SPIDER_SWORD" },
    { id: "0x7A04", value: "SPIDER_WRAITH" },
    { id: "0x7B00", value: "WOLF" },
    { id: "0x7B01", value: "WOLF_WORG" },
    { id: "0x7B02", value: "WOLF_DIRE" },
    { id: "0x7B03", value: "WOLF_WINTER" },
    { id: "0x7B04", value: "WOLF_VAMPIRIC" },
    { id: "0x7B05", value: "WOLF_DREAD" },
    { id: "0x7B06", value: "WOLF_SHADOW" },
    { id: "0x7C00", value: "KOBOLD_XVART" },
    { id: "0x7C01", value: "KOBOLD_TASLOI" },
    { id: "0x7D00", value: "ZOMBIE" },
    { id: "0x7D01", value: "SLAVE_FIGHTER" },
    { id: "0x7D02", value: "CHICKEN_BROWN" },
    { id: "0x7D03", value: "CHICKEN_WHITE" },
    { id: "0x7D04", value: "HARLOT_FIGHTER" },
    { id: "0x7D05", value: "NOBLEMAN_FIGHTER" },
    { id: "0x7D06", value: "NOBLEWOMAN_FIGHTER" },
    { id: "0x7D07", value: "PEASANT_MAN_FIGHTER" },
    { id: "0x7D08", value: "PEASANT_WOMAN_FIGHTER" },
    { id: "0x7E00", value: "WEREWOLF" },
    { id: "0x7E01", value: "WEREWOLF_GREATER" },
    { id: "0x7F00", value: "TROLL" },
    { id: "0x7F01", value: "MINDFLAYER" },
    { id: "0x7F02", value: "BEHOLDER" },
    { id: "0x7F03", value: "IMP" },
    { id: "0x7F04", value: "GOLEM_IRON" },
    { id: "0x7F05", value: "DJINNI" },
    { id: "0x7F06", value: "DJINNI_LEGS" },
    { id: "0x7F07", value: "GOLEM_CLAY" },
    { id: "0x7F08", value: "OTYUGH" },
    { id: "0x7F09", value: "SAHUAGIN" },
    { id: "0x7F0A", value: "GREATCAT_PANTHER" },
    { id: "0x7F0B", value: "GREATCAT_LEOPARD" },
    { id: "0x7F0C", value: "KUO-TOA" },
    { id: "0x7F0D", value: "LICH" },
    { id: "0x7F0E", value: "DEMILICH" },
    { id: "0x7F0F", value: "TROLL_SMALL" },
    { id: "0x7F10", value: "RAKSHASA" },
    { id: "0x7F11", value: "UMBER_HULK" },
    { id: "0x7F12", value: "VAMPIRE" },
    { id: "0x7F13", value: "SNAKE" },
    { id: "0x7F14", value: "GITHYANKI" },
    { id: "0x7F15", value: "BEHOLDER_SMALL" },
    { id: "0x7F16", value: "MOOSE" },
    { id: "0x7F17", value: "RABBIT" },
    { id: "0x7F18", value: "DEER" },
    { id: "0x7F19", value: "DANCING_SWORD" },
    { id: "0x7F20", value: "GROUNDHOG" },
    { id: "0x7F21", value: "PHEASANT" },
    { id: "0x7F22", value: "VAMPIRE_FEMALE" },
    { id: "0x7F23", value: "SAHUAGIN_LARGE" },
    { id: "0x7F24", value: "PIRATE" },
    { id: "0x7F27", value: "DROW" },
    { id: "0x7F28", value: "KUO-TOA_LARGE" },
    { id: "0x7F29", value: "DROW_FEMALE" },
    { id: "0x7F2A", value: "SAILOR_MAN" },
    { id: "0x7F2B", value: "MDK2_MAX" },
    { id: "0x7F2C", value: "AMNIAN_SOLDIER" },
    { id: "0x7F2D", value: "WYVERN_FAMILIAR" },
    { id: "0x7F2E", value: "RAVER" },
    { id: "0x7F2F", value: "SPIDER_SMALL" },
    { id: "0x7F30", value: "BODHI" },
    { id: "0x7F31", value: "ELLESIME" },
    { id: "0x7F32", value: "SLAYER" },
    { id: "0x7F33", value: "MDK2_KURT" },
    { id: "0x7F34", value: "MDK2_DOCTOR" },
    { id: "0x7F35", value: "MIST_CREATURE" },
    { id: "0x7F36", value: "SHADOW_THIEF" },
    { id: "0x7F37", value: "JON_IRENICUS" },
    { id: "0x7F38", value: "WIZARD_EYE" },
    { id: "0x7F39", value: "BLOB_MIST_CREATURE" },
    { id: "0x7F3A", value: "IRENICUS_ROBED" },
    { id: "0x7F3B", value: "SOLAR" },
    { id: "0x7F3C", value: "DEVA_MONADIC" },
    { id: "0x7F3D", value: "MELISSAN" },
    { id: "0x7F3E", value: "GIANT_FIRE" },
    { id: "0x7F3F", value: "GIANT_YAGA-SHURA" },
    { id: "0x7F40", value: "GOLEM_MINI" },
    { id: "0x7F41", value: "EFREETI_NOBLE" },
    { id: "0x7F42", value: "RED_WIZARD" },
    { id: "0x7F43", value: "YOCHLOL" },
    { id: "0x7F44", value: "ELLESIME_WHITE" },
    { id: "0x7F45", value: "LAGOON_CREATURE" },
    { id: "0x7F46", value: "DEATH_TYRANT" },
    { id: "0x7F47", value: "GIANT_FIRE_2" },
    { id: "0x7F48", value: "SOLAR_FALLEN" },
    { id: "0x7F49", value: "DEVA_MONADIC_FALLEN" },
    { id: "0x7F4A", value: "DEVA_ASTRAL" },
    { id: "0x7F4B", value: "DEVA_ASTRAL_FALLEN" },
    { id: "0x7F4C", value: "PLANETAR" },
    { id: "0x7F4D", value: "PLANETAR_FALLEN" },
    { id: "0x7F4E", value: "DEVA_MOVANIC" },
    { id: "0x7F4F", value: "DEVA_MOVANIC_FALLEN" },
    { id: "0x7F50", value: "NISHRUU" },
    { id: "0x7F51", value: "HAKEASHAR" },
    { id: "0x7F52", value: "SAILOR_GREEN" },
    { id: "0x7F53", value: "SAILOR_RED" },
    { id: "0x7F54", value: "SAILOR_DARK" },
    { id: "0x7F55", value: "CRUSADER_SOLDIER" },
    { id: "0x7F56", value: "WILL_O_WISP" },
    { id: "0x7F57", value: "WILL_O_WISP_SMALL" },
    { id: "0x7F58", value: "ABISHAI_BLACK" },
    { id: "0x7F59", value: "ABISHAI_GREEN" },
    { id: "0x7F5A", value: "ABISHAI_RED" },
    { id: "0x7F5B", value: "ABISHAI_BLUE" },
    { id: "0x7F5C", value: "HAG_NIGHT" },
    { id: "0x7F5D", value: "HAG_GREEN" },
    { id: "0x7F5E", value: "HAG_SEA" },
    { id: "0x7F5F", value: "HAG_ANNIS" },
    { id: "0x7F60", value: "SNAKE_WATER" },
    { id: "0x7F61", value: "DRAGON_RED_JUVENILE" },
    { id: "0x7F62", value: "DRAGON_GREEN_JUVENILE" },
    { id: "0x8000", value: "GNOLL" },
    { id: "0x8100", value: "HOBGOBLIN" },
    { id: "0x8200", value: "KOBOLD" },
    { id: "0x9000", value: "OGRE" },
    { id: "0xA000", value: "WYVERN" },
    { id: "0xA100", value: "CARRION_CRAWLER" },
    { id: "0xA200", value: "WYVERN_WHITE" },
    { id: "0xA201", value: "MEGALOCENTIPEDE" },
    { id: "0xA202", value: "TUNNEL_WORM" },
    { id: "0xB000", value: "COW" },
    { id: "0xB100", value: "HORSE" },
    { id: "0xB200", value: "STATIC_BEGGAR_MAN" },
    { id: "0xB210", value: "STATIC_HARLOT_WOMAN" },
    { id: "0xB300", value: "STATIC_BOY" },
    { id: "0xB310", value: "STATIC_GIRL" },
    { id: "0xB400", value: "STATIC_FAT_MAN" },
    { id: "0xB410", value: "STATIC_FAT_WOMAN" },
    { id: "0xB500", value: "STATIC_PEASANT_MAN" },
    { id: "0xB510", value: "STATIC_PEASANT_WOMAN" },
    { id: "0xB600", value: "STATIC_NOBLE_MAN" },
    { id: "0xB610", value: "STATIC_NOBLE_WOMAN" },
    { id: "0xB700", value: "STATIC_SLAVE" },
    { id: "0xC000", value: "BAT_INSIDE" },
    { id: "0xC100", value: "CAT" },
    { id: "0xC200", value: "CHICKEN" },
    { id: "0xC300", value: "RAT" },
    { id: "0xC400", value: "SQUIRREL" },
    { id: "0xC500", value: "BAT_OUTSIDE" },
    { id: "0xC600", value: "BEGGAR_MAN" },
    { id: "0xC610", value: "HARLOT_WOMAN" },
    { id: "0xC700", value: "BOY" },
    { id: "0xC710", value: "GIRL" },
    { id: "0xC800", value: "FAT_MAN" },
    { id: "0xC810", value: "FAT_WOMAN" },
    { id: "0xC900", value: "PEASANT_MAN" },
    { id: "0xC910", value: "PEASANT_WOMAN" },
    { id: "0xCA00", value: "NOBLE_MAN" },
    { id: "0xCA10", value: "NOBLE_WOMAN" },
    { id: "0xCB00", value: "SLAVE" },
    { id: "0xCC00", value: "KEG1" },
    { id: "0xCC01", value: "KEG2" },
    { id: "0xCC02", value: "KEG3" },
    { id: "0xCC04", value: "RAT_OUTSIDE" },
    { id: "0xD000", value: "EAGLE" },
    { id: "0xD100", value: "SEAGULL" },
    { id: "0xD200", value: "VULTURE" },
    { id: "0xD300", value: "BIRD" },
    { id: "0xD400", value: "BIRD_INSIDE" },
    { id: "0xE000", value: "CYCLOPS" },
    { id: "0xE010", value: "ETTIN" },
    { id: "0xE020", value: "DONOT_USE" },
    { id: "0xE040", value: "HISTACHII" },
    { id: "0xE050", value: "LICH_BLACK" },
    { id: "0xE060", value: "LICH_WHITE" },
    { id: "0xE070", value: "MINOTAUR" },
    { id: "0xE080", value: "MUMMY" },
    { id: "0xE090", value: "MARILITH" },
    { id: "0xE0A0", value: "TROLL_ICE" },
    { id: "0xE0B0", value: "TROLL_BLUE" },
    { id: "0xE0C0", value: "TROLL_SNOW" },
    { id: "0xE0D0", value: "UMBER_HULK_ELDER" },
    { id: "0xE0E0", value: "CORNUGON" },
    { id: "0xE0F0", value: "GOLEM_ICE" },
    { id: "0xE0F1", value: "GLABREZU" },
    { id: "0xE0F2", value: "WAILING_VIRGIN" },
    { id: "0xE200", value: "BEETLE_BORING" },
    { id: "0xE210", value: "BEETLE_FIRE" },
    { id: "0xE220", value: "BEETLE_BOMBARDIER" },
    { id: "0xE230", value: "BEETLE_RHINOCEROS" },
    { id: "0xE240", value: "ANIMATED_PLATE_BRONZE" },
    { id: "0xE241", value: "ANIMATED_PLATE_DARK" },
    { id: "0xE242", value: "ANIMATED_PLATE_GREEN" },
    { id: "0xE243", value: "ARUNDEL" },
    { id: "0xE244", value: "BARBARIAN_WARRIOR_TAN" },
    { id: "0xE245", value: "BARBARIAN_WARRIOR_RED" },
    { id: "0xE246", value: "BARBARIAN_WARRIOR_BROWN" },
    { id: "0xE247", value: "BARBARIAN_SHAMAN_HAMMER" },
    { id: "0xE248", value: "BARBARIAN_SHAMAN_STAFF" },
    { id: "0xE249", value: "BARBARIAN_SHAMAN_CLUB" },
    { id: "0xE24A", value: "BARBARIAN_ICASARACHT" },
    { id: "0xE24B", value: "ELEMENTAL_EARTH_IWD" },
    { id: "0xE24C", value: "ELEMENTAL_FIRE_IWD" },
    { id: "0xE24D", value: "ELEMENTAL_WATER" },
    { id: "0xE24E", value: "GIANT_FIRE_IWD" },
    { id: "0xE24F", value: "GIANT_FROST" },
    { id: "0xE250", value: "GOLEM_IRON_IWD" },
    { id: "0xE251", value: "GIANT_VERBEEG" },
    { id: "0xE252", value: "HARPY" },
    { id: "0xE253", value: "REMORHAZ" },
    { id: "0xE254", value: "TROLL_SCRAG" },
    { id: "0xE255", value: "SEER" },
    { id: "0xE256", value: "BELHIFET" },
    { id: "0xE257", value: "BELHIFET_PRIEST" },
    { id: "0xE258", value: "HEPHERNAAN" },
    { id: "0xE259", value: "SVIRFNEBLIN_PALE_AXE" },
    { id: "0xE25A", value: "SVIRFNEBLIN_PALE_NOAXE" },
    { id: "0xE25B", value: "UMBER_HULK_VODYANOI" },
    { id: "0xE25C", value: "MARILITH_IWD" },
    { id: "0xE25D", value: "TUNDRA_YETI" },
    { id: "0xE25E", value: "WIGHT_BARROW" },
    { id: "0xE25F", value: "DROWNED_DEAD" },
    { id: "0xE260", value: "CREEPING_DOOM" },
    { id: "0xE261", value: "SAHUAGIN_IWD" },
    { id: "0xE262", value: "SAHUAGIN_LARGE_IWD" },
    { id: "0xE263", value: "SVIRFNEBLIN_DARK_AXE" },
    { id: "0xE264", value: "SVIRFNEBLIN_DARK_NOAXE" },
    { id: "0xE265", value: "BOAR_ARCTIC" },
    { id: "0xE266", value: "BUGBEAR_CAPTAIN" },
    { id: "0xE267", value: "BUGBEAR" },
    { id: "0xE268", value: "CHIMERA" },
    { id: "0xE269", value: "HALFDRAGON_BLACK" },
    { id: "0xE26A", value: "HALFDRAGON_RED" },
    { id: "0xE26B", value: "TREANT_DARK" },
    { id: "0xE26C", value: "ELEMENTAL_WATER_SMALL" },
    { id: "0xE26D", value: "FEYR_GREATER" },
    { id: "0xE26E", value: "FEYR" },
    { id: "0xE26F", value: "GIANT_FOMORIAN" },
    { id: "0xE270", value: "GOBLIN_CAPTAIN" },
    { id: "0xE271", value: "GOBLIN_SHAMAN" },
    { id: "0xE272", value: "GOBLIN_WORG" },
    { id: "0xE273", value: "GOBLIN_WORG_CAPTAIN" },
    { id: "0xE274", value: "HOOK_HORROR" },
    { id: "0xE275", value: "ISAIR" },
    { id: "0xE276", value: "LEMURE" },
    { id: "0xE277", value: "MADAE" },
    { id: "0xE278", value: "MALARITE" },
    { id: "0xE279", value: "OROG_SHAMAN" },
    { id: "0xE27A", value: "ORC_AXE_UNDEAD" },
    { id: "0xE27B", value: "ORC_SHAMAN_UNDEAD" },
    { id: "0xE27C", value: "SHENRICAL" },
    { id: "0xE27D", value: "WEREBADGER" },
    { id: "0xE27E", value: "WERERAT" },
    { id: "0xE27F", value: "BOAR_WILD" },
    { id: "0xE280", value: "WORG" },
    { id: "0xE281", value: "YUAN-TI_HALF" },
    { id: "0xE282", value: "DRIDER_FEMALE" },
    { id: "0xE283", value: "DRIDER_MALE" },
    { id: "0xE284", value: "INVISIBLE_SMALL" },
    { id: "0xE285", value: "INVISIBLE_MEDIUM" },
    { id: "0xE286", value: "INVISIBLE_LARGE" },
    { id: "0xE287", value: "INVISIBLE_GIANT" },
    { id: "0xE288", value: "GOBLIN_WORG_ELITE" },
    { id: "0xE289", value: "GOBLIN_WORG_SHAMAN" },
    { id: "0xE28A", value: "TROLL_SPECTRAL" },
    { id: "0xE28B", value: "ABISHAI_WHITE" },
    { id: "0xE28C", value: "DRAGON_WHITE_YOUNG" },
    { id: "0xE28D", value: "DRAGON_SILVER_YOUNG" },
    { id: "0xE28E", value: "DRAGON_GREEN_YOUNG" },
    { id: "0xE28F", value: "DROWNED_DEAD_RED" },
    { id: "0xE290", value: "HALFDRAGON_GREEN" },
    { id: "0xE291", value: "BUGBEAR_SHAMAN" },
    { id: "0xE292", value: "ETTIN_GHOST" },
    { id: "0xE293", value: "GIANT_HILL" },
    { id: "0xE294", value: "BONEBAT" },
    { id: "0xE300", value: "GHOST" },
    { id: "0xE310", value: "GHOUL_GREATER" },
    { id: "0xE320", value: "GHAST_GREATER" },
    { id: "0xE400", value: "GOBLIN_AXE" },
    { id: "0xE410", value: "GOBLIN_BOW" },
    { id: "0xE420", value: "GOBLIN_ELITE_AXE" },
    { id: "0xE430", value: "GOBLIN_ELITE_BOW" },
    { id: "0xE440", value: "MKHIIN" },
    { id: "0xE441", value: "MKHIIN_BOW" },
    { id: "0xE442", value: "MKHIIN_STAFF" },
    { id: "0xE443", value: "MKHIIN_ARMOR_AXE" },
    { id: "0xE444", value: "MKHIIN_ARMOR_BOW" },
    { id: "0xE500", value: "LIZARD_MAN_ELITE" },
    { id: "0xE510", value: "LIZARD_MAN" },
    { id: "0xE520", value: "LIZARD_KING" },
    { id: "0xE600", value: "MYCONID_RED" },
    { id: "0xE610", value: "MYCONID_BLUE" },
    { id: "0xE700", value: "OROG" },
    { id: "0xE710", value: "OROG_ELITE" },
    { id: "0xE720", value: "OROG_CHIEFTAIN" },
    { id: "0xE800", value: "ORC_MELEE" },
    { id: "0xE810", value: "ORC_RANGE" },
    { id: "0xE820", value: "ORC_ELITE_MELEE" },
    { id: "0xE830", value: "ORC_ELITE_RANGE" },
    { id: "0xE840", value: "ORC_SHAMAN" },
    { id: "0xE900", value: "SALAMANDER_FIRE" },
    { id: "0xE910", value: "SALAMANDER_FROST" },
    { id: "0xEA00", value: "SHRIEKER" },
    { id: "0xEA10", value: "SHADOW_SMALL" },
    { id: "0xEA20", value: "SHADOW_LARGE" },
    { id: "0xEB00", value: "SKELETON_MONSTER" },
    { id: "0xEB10", value: "SKELETON_WARRIOR" },
    { id: "0xEB20", value: "SKELETON_FIEND" },
    { id: "0xEC00", value: "WIGHT_GRAY" },
    { id: "0xEC10", value: "WIGHT_GREEN" },
    { id: "0xEC20", value: "WIGHT_YELLOW" },
    { id: "0xED00", value: "YUAN-TI" },
    { id: "0xED10", value: "YUAN-TI_ELITE" },
    { id: "0xED20", value: "YUAN-TI_PRIEST" },
    { id: "0xEE00", value: "ZOMBIE_YELLOW" },
    { id: "0xEE10", value: "ZOMBIE_BLUE" },
    { id: "0xEF10", value: "WATER_WEIRD" },
    { id: "0x0101", value: "BOLT_OF_GLORY" },
    { id: "0x0102", value: "SUN_SOULRAY" }
];