export enum GeneralIdentifiers {
    HUMANOID = 'HUMANOID',
    ANIMAL = 'ANIMAL',
    DEAD = 'DEAD',
    UNDEAD = 'UNDEAD',
    GIANTHUMANOID = 'GIANTHUMANOID',
    FROZEN = 'FROZEN',
    PLANT = 'PLANT',
    MONSTER = 'MONSTER',
    WEAPON = 'WEAPON',
    ARMOR = 'ARMOR',
    AMULET = 'AMULET',
    BELT = 'BELT',
    BOOTS = 'BOOTS',
    AMMO = 'AMMO',
    GENERAL_ITEM = 'GENERAL_ITEM',
    HELMET = 'HELMET',
    KEY = 'KEY',
    POTION = 'POTION',
    RING = 'RING',
    SCROLL = 'SCROLL',
    SHIELD = 'SHIELD',
    GLOVES = 'GLOVES'
}

export const generalIds = [
    { id: '0', value: 'GENERAL_ITEM' },
    { id: '1', value: 'HUMANOID' },
    { id: '2', value: 'ANIMAL' },
    { id: '3', value: 'DEAD' },
    { id: '4', value: 'UNDEAD' },
    { id: '5', value: 'GIANTHUMANOID' },
    { id: '6', value: 'FROZEN' },
    { id: '7', value: 'PLANT' },
    { id: '255', value: 'MONSTER' },
    { id: '101', value: 'WEAPON' },
    { id: '102', value: 'ARMOR' },
    { id: '103', value: 'AMULET' },
    { id: '104', value: 'BELT' },
    { id: '105', value: 'BOOTS' },
    { id: '106', value: 'AMMO' },
    { id: '107', value: 'HELMET' },
    { id: '108', value: 'KEY' },
    { id: '109', value: 'POTION' },
    { id: '110', value: 'RING' },
    { id: '111', value: 'SCROLL' },
    { id: '112', value: 'SHIELD' },
    { id: '113', value: 'GLOVES' },
];