// Spectre
ACTION_FOR_EACH file IN
                spectr01 //regular (also ranger stronghold mission)
//				sahspc01
				cbmalr6b //CtB
BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME "%file%.cre" BEGIN
    COPY_EXISTING "%file%.cre" override
      LPF FJ_CRE_VALIDITY END
      PATCH_INCLUDE "%MOD_FOLDER%/lib/fj_cre_validity.tpp"
      PATCH_IF valid BEGIN
        PATCH_INCLUDE "%MOD_FOLDER%/lib/fj_cre_reindex.tpp"
        REPLACE_CRE_ITEM "%ring95%" #0 #0 #0 none lring //Standard undead immunities
        REPLACE_CRE_ITEM immune1 #0 #0 #0 none rring
        REPLACE_CRE_ITEM fl#spect #0 #0 #0 none weapon1 EQUIP
        LPF patchCreature
          INT_VAR
            xpv = 3000
            hp = 59 //7d8+3
            ac = 2
            thac0 = 13
            apr = 1
            saveDeath = 7
            saveWand = 9
            savePolymorph = 8
            saveBreath = 9
            saveSpell = 8
            level1 = 7
            level2 = 0
            level3 = 0
            resistMagic = 0
            resistFire = 0
            resistCold = 100
            resistElectricity = 0
            resistAcid = 0
            resistSlashing = 0
            resistCrushing = 0
            resistPiercing = 0
            resistMissile = 0
            strength = 13
            strengthx = 0
            intelligence = 14
            wisdom = 11
            dexterity = 10
            constitution = 9
            charisma = 10
            morale = 15
            alignment = 0x13 //LE
            general = 4 //undead
            
            enforce = 1
        END
        LPF patchCreatureScript
          STR_VAR
            newscript = fl#higmc
            script01 = wtasight
            script02 = bpmag14m
            script03 = bpwtsigt
			script04 = DW2MC2GE
			script05 = DW2MS4GE
			skipfile01 = cbmalr6b
        END
        // LPF hover_immunities END
        // LPF cold_spell_immunities END
      END
    BUT_ONLY
  END
END

COPY_EXISTING b1-8.itm "override/fl#spect.itm"
  LPF set_enchantment INT_VAR enchantment = 2 END
  LPF hover_immunities END
  LPF cold_spell_immunities END
  DEFINE_ARRAY wigh_opcode BEGIN 216 139 141 END //drain 2 levels
  DEFINE_ARRAY wigh_p1 BEGIN 2 40968 0 END
  DEFINE_ARRAY wigh_p2 BEGIN 0 0 1 END
  PHP_EACH wigh_opcode AS int => opcode BEGIN
    LPF ADD_ITEM_EFFECT
      INT_VAR
        type = 1

        opcode
        target = 2
        parameter1 = $wigh_p1("%int%")
        parameter2 = $wigh_p2("%int%")
        timing = 1
     END
   END
