ACTION_FOR_EACH ~file~ IN
  _ANKHEG
  _ANKHEGG
  _ANKHEGQ
  ANKHEG
  ANKHEGF
  ANKHEGG
  ANKHEGQ
  ANKHEG01
  bdankh01    // 10hd, 1400xp
  bdankheg
  bdankhsu    // summoned
  BDNEO 
  BPANKHE1
BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
    COPY_EXISTING ~%file%.cre~ ~override~
      LPF FJ_CRE_VALIDITY END
      REMOVE_KNOWN_SPELLS
      REMOVE_MEMORIZED_SPELLS
      DEFINE_ARRAY notEnforceFiles BEGIN END
      LPF patchCreature   
        INT_VAR 
          level1=8
          strength=21
          dexterity=10
          constitution=17
          intelligence=1
          wisdom=13
          charisma=6
          movement=12
          hp=64
          ac=2
          thac0=13
          apr=1
          xpv=975
          alignment=34       // True Neutral
          saveDeath=10
          saveWand=12
          savePolymorph=11
          saveBreath=12
          saveSpell=13
          morale=9
          moraleBreak=4
          moraleRecovery=15
          general=255        // MONSTER
          race=101           // ANKHEG
          class=101          // ANKHEG
          gender=4
          sex=4
          enforce=1
      END
      DEFINE_ARRAY removeScripts BEGIN 
        ANKHEG
        SHOUT         // generic shout script
        WTASIGHT      // generic AI script
        wtrunsgt      // generic AI script
        DW2MP0GE      // Stratagems Melee script
        DW2RC2MO      // Stratagems Melee script
      END
      DEFINE_ARRAY skipFiles BEGIN 
      END
      LPF patchCreatureScript STR_VAR script=ja#m1 removeScripts skipFiles END
    BUT_ONLY_IF_IT_CHANGES
  END
END
