// Summons are destroyed on death
IF
	Die()
THEN
	RESPONSE #100
		DestroySelf()
END

// Random walk on panic
IF
	StateCheck(Myself,STATE_PANIC)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

// Detect combat
IF
	Global("JA#COMBAT","LOCALS",0)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
		Shout(98)
END

// React to shouts
IF
	Global("JA#COMBAT","LOCALS",0)
	Heard(LastSummonerOf(Myself),98)
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
END

// Summon follow summoner
IF
	Global("JA#COMBAT","LOCALS",0)
	!StateCheck(Myself,STATE_BLIND)
	ActionListEmpty()
	!See(NearestEnemyOf(Myself))
	!See(LastSummonerOf(Myself))
	HPGT(LastSummonerOf(Myself),0)
	Range(LastSummonerOf(Myself),150)
THEN
	RESPONSE #100
		MoveToObject(LastSummonerOf(Myself))
END

// Do nothing if combat is not started
IF
	Global("JA#COMBAT","LOCALS",0)
	ActionListEmpty()
THEN
	RESPONSE #100
		NoAction()
END

// Acidic Enzymes
IF
	HPPercentLT(Myself,50)
	HaveSpellRES("ja#2m1")
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	OR(7)
		!Range([PC.0.0.MAGE],30)
		General([PC.0.0.MAGE],WEAPON)
		CheckStatGT([PC.0.0.MAGE],0,SANCTUARY)
		StateCheck([PC.0.0.MAGE],STATE_CHARMED)
		StateCheck([PC.0.0.MAGE],STATE_REALLY_DEAD)
		!See([PC.0.0.MAGE])
		StateCheck([PC.0.0.MAGE],STATE_INVISIBLE)
	OR(7)
		!Range([PC.0.0.MAGE_THIEF],30)
		General([PC.0.0.MAGE_THIEF],WEAPON)
		CheckStatGT([PC.0.0.MAGE_THIEF],0,SANCTUARY)
		StateCheck([PC.0.0.MAGE_THIEF],STATE_CHARMED)
		StateCheck([PC.0.0.MAGE_THIEF],STATE_REALLY_DEAD)
		!See([PC.0.0.MAGE_THIEF])
		StateCheck([PC.0.0.MAGE_THIEF],STATE_INVISIBLE)
	OR(7)
		!Range([PC.0.0.MAGE_ALL],30)
		General([PC.0.0.MAGE_ALL],WEAPON)
		CheckStatGT([PC.0.0.MAGE_ALL],0,SANCTUARY)
		StateCheck([PC.0.0.MAGE_ALL],STATE_CHARMED)
		StateCheck([PC.0.0.MAGE_ALL],STATE_REALLY_DEAD)
		!See([PC.0.0.MAGE_ALL])
		StateCheck([PC.0.0.MAGE_ALL],STATE_INVISIBLE)
	OR(7)
		!Range([PC.0.0.THIEF],30)
		General([PC.0.0.THIEF],WEAPON)
		CheckStatGT([PC.0.0.THIEF],0,SANCTUARY)
		StateCheck([PC.0.0.THIEF],STATE_CHARMED)
		StateCheck([PC.0.0.THIEF],STATE_REALLY_DEAD)
		!See([PC.0.0.THIEF])
		StateCheck([PC.0.0.THIEF],STATE_INVISIBLE)
	OR(7)
		!Range([PC.0.0.BARD],30)
		General([PC.0.0.BARD],WEAPON)
		CheckStatGT([PC.0.0.BARD],0,SANCTUARY)
		StateCheck([PC.0.0.BARD],STATE_CHARMED)
		StateCheck([PC.0.0.BARD],STATE_REALLY_DEAD)
		!See([PC.0.0.BARD])
		StateCheck([PC.0.0.BARD],STATE_INVISIBLE)
	OR(7)
		!Range([PC.0.0.THIEF_ALL],30)
		General([PC.0.0.THIEF_ALL],WEAPON)
		CheckStatGT([PC.0.0.THIEF_ALL],0,SANCTUARY)
		StateCheck([PC.0.0.THIEF_ALL],STATE_CHARMED)
		StateCheck([PC.0.0.THIEF_ALL],STATE_REALLY_DEAD)
		!See([PC.0.0.THIEF_ALL])
		StateCheck([PC.0.0.THIEF_ALL],STATE_INVISIBLE)
	OR(7)
		!Range([PC.0.0.CLERIC],30)
		General([PC.0.0.CLERIC],WEAPON)
		CheckStatGT([PC.0.0.CLERIC],0,SANCTUARY)
		StateCheck([PC.0.0.CLERIC],STATE_CHARMED)
		StateCheck([PC.0.0.CLERIC],STATE_REALLY_DEAD)
		!See([PC.0.0.CLERIC])
		StateCheck([PC.0.0.CLERIC],STATE_INVISIBLE)
	OR(7)
		!Range([PC],30)
		General([PC],WEAPON)
		CheckStatGT([PC],0,SANCTUARY)
		StateCheck([PC],STATE_CHARMED)
		StateCheck([PC],STATE_REALLY_DEAD)
		!See([PC])
		StateCheck([PC],STATE_INVISIBLE)
	OR(7)
		!Range(SecondNearest([PC]),30)
		General(SecondNearest([PC]),WEAPON)
		CheckStatGT(SecondNearest([PC]),0,SANCTUARY)
		StateCheck(SecondNearest([PC]),STATE_CHARMED)
		StateCheck(SecondNearest([PC]),STATE_REALLY_DEAD)
		!See(SecondNearest([PC]))
		StateCheck(SecondNearest([PC]),STATE_INVISIBLE)
	OR(7)
		!Range(ThirdNearest([PC]),30)
		General(ThirdNearest([PC]),WEAPON)
		CheckStatGT(ThirdNearest([PC]),0,SANCTUARY)
		StateCheck(ThirdNearest([PC]),STATE_CHARMED)
		StateCheck(ThirdNearest([PC]),STATE_REALLY_DEAD)
		!See(ThirdNearest([PC]))
		StateCheck(ThirdNearest([PC]),STATE_INVISIBLE)
THEN
	RESPONSE #100
		Continue()
END

IF
	HPPercentLT(Myself,50)
	HaveSpellRES("ja#2m1")
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	Range(LastSeenBy(Myself),30)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SelectWeaponAbility(SLOT_WEAPON1,0)
		AttackOneRound(LastSeenBy(Myself))
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

// Attack GRABBED enemy
IF
	OR(7)
		!CheckSpellState(NearestEnemyOf(Myself),JA_GRAPPLE)
		General(NearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(NearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NearestEnemyOf(Myself))
		StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
	OR(7)
		!CheckSpellState(SecondNearestEnemyOf(Myself),JA_GRAPPLE)
		General(SecondNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SecondNearestEnemyOf(Myself))
		StateCheck(SecondNearestEnemyOf(Myself),STATE_INVISIBLE)
	OR(7)
		!CheckSpellState(ThirdNearestEnemyOf(Myself),JA_GRAPPLE)
		General(ThirdNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(ThirdNearestEnemyOf(Myself))
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_INVISIBLE)
	OR(7)
		!CheckSpellState(FourthNearestEnemyOf(Myself),JA_GRAPPLE)
		General(FourthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FourthNearestEnemyOf(Myself))
		StateCheck(FourthNearestEnemyOf(Myself),STATE_INVISIBLE)
	OR(7)
		!CheckSpellState(FifthNearestEnemyOf(Myself),JA_GRAPPLE)
		General(FifthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FifthNearestEnemyOf(Myself))
		StateCheck(FifthNearestEnemyOf(Myself),STATE_INVISIBLE)
	OR(7)
		!CheckSpellState(SixthNearestEnemyOf(Myself),JA_GRAPPLE)
		General(SixthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SixthNearestEnemyOf(Myself))
		StateCheck(SixthNearestEnemyOf(Myself),STATE_INVISIBLE)
	OR(7)
		!CheckSpellState(SeventhNearestEnemyOf(Myself),JA_GRAPPLE)
		General(SeventhNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SeventhNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SeventhNearestEnemyOf(Myself))
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_INVISIBLE)
	OR(7)
		!CheckSpellState(EighthNearestEnemyOf(Myself),JA_GRAPPLE)
		General(EighthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(EighthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(EighthNearestEnemyOf(Myself))
		StateCheck(EighthNearestEnemyOf(Myself),STATE_INVISIBLE)
	OR(7)
		!CheckSpellState(NinthNearestEnemyOf(Myself),JA_GRAPPLE)
		General(NinthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NinthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NinthNearestEnemyOf(Myself))
		StateCheck(NinthNearestEnemyOf(Myself),STATE_INVISIBLE)
	OR(7)
		!CheckSpellState(TenthNearestEnemyOf(Myself),JA_GRAPPLE)
		General(TenthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(TenthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(TenthNearestEnemyOf(Myself))
		StateCheck(TenthNearestEnemyOf(Myself),STATE_INVISIBLE)
THEN
	RESPONSE #100
		Continue()
END

IF
	CheckSpellState(LastSeenBy(Myself),JA_GRAPPLE)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SelectWeaponAbility(SLOT_WEAPON,0)
		AttackOneRound(LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

// Attack NEAREST enemy
IF
	OR(6)
		General(NearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(NearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NearestEnemyOf(Myself))
		StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
	OR(6)
		General(SecondNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SecondNearestEnemyOf(Myself))
		StateCheck(SecondNearestEnemyOf(Myself),STATE_INVISIBLE)
	OR(6)
		General(ThirdNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(ThirdNearestEnemyOf(Myself))
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_INVISIBLE)
	OR(6)
		General(FourthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FourthNearestEnemyOf(Myself))
		StateCheck(FourthNearestEnemyOf(Myself),STATE_INVISIBLE)
	OR(6)
		General(FifthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FifthNearestEnemyOf(Myself))
		StateCheck(FifthNearestEnemyOf(Myself),STATE_INVISIBLE)
	OR(6)
		General(SixthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SixthNearestEnemyOf(Myself))
		StateCheck(SixthNearestEnemyOf(Myself),STATE_INVISIBLE)
	OR(6)
		General(SeventhNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SeventhNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SeventhNearestEnemyOf(Myself))
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_INVISIBLE)
	OR(6)
		General(EighthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(EighthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(EighthNearestEnemyOf(Myself))
		StateCheck(EighthNearestEnemyOf(Myself),STATE_INVISIBLE)
	OR(6)
		General(NinthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NinthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NinthNearestEnemyOf(Myself))
		StateCheck(NinthNearestEnemyOf(Myself),STATE_INVISIBLE)
	OR(6)
		General(TenthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(TenthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(TenthNearestEnemyOf(Myself))
		StateCheck(TenthNearestEnemyOf(Myself),STATE_INVISIBLE)
THEN
	RESPONSE #100
		Continue()
END

IF
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SelectWeaponAbility(SLOT_WEAPON,0)
		AttackOneRound(LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

// Attack SLEEP enemy
IF
	OR(7)
		!Allegiance(Myself,ENEMY)
		!StateCheck(Player1,STATE_SLEEPING)
		CheckStatGT(Player1,0,SANCTUARY)
		StateCheck(Player1,STATE_CHARMED)
		StateCheck(Player1,STATE_REALLY_DEAD)
		!See(Player1)
		StateCheck(Player1,STATE_INVISIBLE)
	OR(7)
		!Allegiance(Myself,ENEMY)
		!StateCheck(Player2,STATE_SLEEPING)
		CheckStatGT(Player2,0,SANCTUARY)
		StateCheck(Player2,STATE_CHARMED)
		StateCheck(Player2,STATE_REALLY_DEAD)
		!See(Player2)
		StateCheck(Player2,STATE_INVISIBLE)
	OR(7)
		!Allegiance(Myself,ENEMY)
		!StateCheck(Player3,STATE_SLEEPING)
		CheckStatGT(Player3,0,SANCTUARY)
		StateCheck(Player3,STATE_CHARMED)
		StateCheck(Player3,STATE_REALLY_DEAD)
		!See(Player3)
		StateCheck(Player3,STATE_INVISIBLE)
	OR(7)
		!Allegiance(Myself,ENEMY)
		!StateCheck(Player4,STATE_SLEEPING)
		CheckStatGT(Player4,0,SANCTUARY)
		StateCheck(Player4,STATE_CHARMED)
		StateCheck(Player4,STATE_REALLY_DEAD)
		!See(Player4)
		StateCheck(Player4,STATE_INVISIBLE)
	OR(7)
		!Allegiance(Myself,ENEMY)
		!StateCheck(Player5,STATE_SLEEPING)
		CheckStatGT(Player5,0,SANCTUARY)
		StateCheck(Player5,STATE_CHARMED)
		StateCheck(Player5,STATE_REALLY_DEAD)
		!See(Player5)
		StateCheck(Player5,STATE_INVISIBLE)
	OR(7)
		!Allegiance(Myself,ENEMY)
		!StateCheck(Player6,STATE_SLEEPING)
		CheckStatGT(Player6,0,SANCTUARY)
		StateCheck(Player6,STATE_CHARMED)
		StateCheck(Player6,STATE_REALLY_DEAD)
		!See(Player6)
		StateCheck(Player6,STATE_INVISIBLE)
THEN
	RESPONSE #100
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SelectWeaponAbility(SLOT_WEAPON,0)
		AttackOneRound(LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

// Track players if allegiance is not GOODCUTOFF
IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player1,150)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStatGT(Player1,0,SANCTUARY)
	!StateCheck(Player1,STATE_CHARMED)
	!StateCheck(Player1,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player2,150)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStatGT(Player2,0,SANCTUARY)
	!StateCheck(Player2,STATE_CHARMED)
	!StateCheck(Player2,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player2)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player3,150)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStatGT(Player3,0,SANCTUARY)
	!StateCheck(Player3,STATE_CHARMED)
	!StateCheck(Player3,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player3)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player4,150)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStatGT(Player4,0,SANCTUARY)
	!StateCheck(Player4,STATE_CHARMED)
	!StateCheck(Player4,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player4)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player5,150)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStatGT(Player5,0,SANCTUARY)
	!StateCheck(Player5,STATE_CHARMED)
	!StateCheck(Player5,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player5)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player6,150)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStatGT(Player6,0,SANCTUARY)
	!StateCheck(Player6,STATE_CHARMED)
	!StateCheck(Player6,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player6)
END

// Track last seen enemy if allegiance is GOODCUTOFF
IF
	Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(LastSeenBy(Myself),150)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

