// Init
IF
	Global("JA#INIT","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("JA#INIT","LOCALS",1)
		SetGlobal("JA#COMBAT","LOCALS",0)
		SetGlobalTimer("JA#REST","LOCALS",2400)
END

// Rest (reset everything and heal if applicable)
IF
	Global("JA#INIT","LOCALS",1)
	GlobalTimerExpired("JA#REST","LOCALS")
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA#INIT","LOCALS",0)
		Rest()
END

// Turn hostile if attacked
IF
	Allegiance(Myself,NEUTRAL)
	OR(4)
		AttackedBy([GOODCUTOFF],DEFAULT)
		SpellCastOnMe([GOODCUTOFF],0)
		TookDamage()
		Heard([EVILCUTOFF.0.ANKHEG],99)
THEN
	RESPONSE #100
		Enemy()
END

// Detect combat
IF
	Global("JA#COMBAT","LOCALS",0)
	Allegiance(Myself,EVILCUTOFF)
	See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
END

// Detect combat
IF
	Global("JA#COMBAT","LOCALS",0)
	Allegiance(Myself,GOODCUTOFF)
	See([EVILCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
END

// Shouts every 3 rounds
IF
	Global("JA#COMBAT","LOCALS",1)
	!GlobalTimerNotExpired("JA#HELP","LOCALS")
THEN
	RESPONSE #100
		Shout(99)
		SetGlobalTimer("JA#HELP","LOCALS",18)
END

// React to shouts
IF
	Global("JA#COMBAT","LOCALS",0)
	Heard([EVILCUTOFF.0.ANKHEG],99)
	InMyArea([EVILCUTOFF.0.ANKHEG])
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
		MoveToObject(LastHeardBy(Myself))
END

IF
	Global("JA#COMBAT","LOCALS",1)
	Heard([EVILCUTOFF.0.ANKHEG],99)
	InMyArea([EVILCUTOFF.0.ANKHEG])
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		MoveToObject(LastHeardBy(Myself))
END

// Do nothing if...
IF
	OR(4)
		Global("JA#COMBAT","LOCALS",0)
		!Allegiance(Myself,EVILCUTOFF)
		StateCheck(Myself,STATE_IMMOBILE)
		StateCheck(Myself,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		NoAction()
END

IF
	!InActiveArea(Myself)
	!Range(NearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		NoAction()
END

// Random walk on panic
IF
	StateCheck(Myself,STATE_PANIC)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

// Acidic Enzymes
IF
	HPPercentLT(Myself,50)
	HaveSpellRES("ja#2m1")
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	Range([PC.0.0.MAGE],30)
	!General([PC.0.0.MAGE],WEAPON)
	!StateCheck([PC.0.0.MAGE],STATE_INVISIBLE)
	!CheckStatGT([PC.0.0.MAGE],0,SANCTUARY)
	!StateCheck([PC.0.0.MAGE],STATE_CHARMED)
	!StateCheck([PC.0.0.MAGE],STATE_REALLY_DEAD)
	See([PC.0.0.MAGE])
	RandomNumGT(1000,100)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HPPercentLT(Myself,50)
	HaveSpellRES("ja#2m1")
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	Range([PC.0.0.MAGE_THIEF],30)
	!General([PC.0.0.MAGE_THIEF],WEAPON)
	!StateCheck([PC.0.0.MAGE_THIEF],STATE_INVISIBLE)
	!CheckStatGT([PC.0.0.MAGE_THIEF],0,SANCTUARY)
	!StateCheck([PC.0.0.MAGE_THIEF],STATE_CHARMED)
	!StateCheck([PC.0.0.MAGE_THIEF],STATE_REALLY_DEAD)
	See([PC.0.0.MAGE_THIEF])
	RandomNumGT(1000,111)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HPPercentLT(Myself,50)
	HaveSpellRES("ja#2m1")
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	Range([PC.0.0.MAGE_ALL],30)
	!General([PC.0.0.MAGE_ALL],WEAPON)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_INVISIBLE)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,SANCTUARY)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_CHARMED)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_REALLY_DEAD)
	See([PC.0.0.MAGE_ALL])
	RandomNumGT(1000,125)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HPPercentLT(Myself,50)
	HaveSpellRES("ja#2m1")
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	Range([PC.0.0.THIEF],30)
	!General([PC.0.0.THIEF],WEAPON)
	!StateCheck([PC.0.0.THIEF],STATE_INVISIBLE)
	!CheckStatGT([PC.0.0.THIEF],0,SANCTUARY)
	!StateCheck([PC.0.0.THIEF],STATE_CHARMED)
	!StateCheck([PC.0.0.THIEF],STATE_REALLY_DEAD)
	See([PC.0.0.THIEF])
	RandomNumGT(1000,143)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HPPercentLT(Myself,50)
	HaveSpellRES("ja#2m1")
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	Range([PC.0.0.BARD],30)
	!General([PC.0.0.BARD],WEAPON)
	!StateCheck([PC.0.0.BARD],STATE_INVISIBLE)
	!CheckStatGT([PC.0.0.BARD],0,SANCTUARY)
	!StateCheck([PC.0.0.BARD],STATE_CHARMED)
	!StateCheck([PC.0.0.BARD],STATE_REALLY_DEAD)
	See([PC.0.0.BARD])
	RandomNumGT(1000,167)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HPPercentLT(Myself,50)
	HaveSpellRES("ja#2m1")
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	Range([PC.0.0.THIEF_ALL],30)
	!General([PC.0.0.THIEF_ALL],WEAPON)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_INVISIBLE)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,SANCTUARY)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_CHARMED)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_REALLY_DEAD)
	See([PC.0.0.THIEF_ALL])
	RandomNumGT(1000,200)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HPPercentLT(Myself,50)
	HaveSpellRES("ja#2m1")
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	Range([PC.0.0.CLERIC],30)
	!General([PC.0.0.CLERIC],WEAPON)
	!StateCheck([PC.0.0.CLERIC],STATE_INVISIBLE)
	!CheckStatGT([PC.0.0.CLERIC],0,SANCTUARY)
	!StateCheck([PC.0.0.CLERIC],STATE_CHARMED)
	!StateCheck([PC.0.0.CLERIC],STATE_REALLY_DEAD)
	See([PC.0.0.CLERIC])
	RandomNumGT(1000,250)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HPPercentLT(Myself,50)
	HaveSpellRES("ja#2m1")
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	Range([PC],30)
	!General([PC],WEAPON)
	!StateCheck([PC],STATE_INVISIBLE)
	!CheckStatGT([PC],0,SANCTUARY)
	!StateCheck([PC],STATE_CHARMED)
	!StateCheck([PC],STATE_REALLY_DEAD)
	See([PC])
	RandomNumGT(1000,333)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HPPercentLT(Myself,50)
	HaveSpellRES("ja#2m1")
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	Range(SecondNearest([PC]),30)
	!General(SecondNearest([PC]),WEAPON)
	!StateCheck(SecondNearest([PC]),STATE_INVISIBLE)
	!CheckStatGT(SecondNearest([PC]),0,SANCTUARY)
	!StateCheck(SecondNearest([PC]),STATE_CHARMED)
	!StateCheck(SecondNearest([PC]),STATE_REALLY_DEAD)
	See(SecondNearest([PC]))
	RandomNumGT(1000,500)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HPPercentLT(Myself,50)
	HaveSpellRES("ja#2m1")
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	Range(ThirdNearest([PC]),30)
	!General(ThirdNearest([PC]),WEAPON)
	!StateCheck(ThirdNearest([PC]),STATE_INVISIBLE)
	!CheckStatGT(ThirdNearest([PC]),0,SANCTUARY)
	!StateCheck(ThirdNearest([PC]),STATE_CHARMED)
	!StateCheck(ThirdNearest([PC]),STATE_REALLY_DEAD)
	See(ThirdNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

// Attack Grabbed enemy
IF
	OR(7)
		!CheckSpellState(NearestEnemyOf(Myself),JA_GRAPPLED)
		General(NearestEnemyOf(Myself),WEAPON)
		StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(NearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NearestEnemyOf(Myself))
	OR(7)
		!CheckSpellState(SecondNearestEnemyOf(Myself),JA_GRAPPLED)
		General(SecondNearestEnemyOf(Myself),WEAPON)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SecondNearestEnemyOf(Myself))
	OR(7)
		!CheckSpellState(ThirdNearestEnemyOf(Myself),JA_GRAPPLED)
		General(ThirdNearestEnemyOf(Myself),WEAPON)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(ThirdNearestEnemyOf(Myself))
	OR(7)
		!CheckSpellState(FourthNearestEnemyOf(Myself),JA_GRAPPLED)
		General(FourthNearestEnemyOf(Myself),WEAPON)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FourthNearestEnemyOf(Myself))
	OR(7)
		!CheckSpellState(FifthNearestEnemyOf(Myself),JA_GRAPPLED)
		General(FifthNearestEnemyOf(Myself),WEAPON)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FifthNearestEnemyOf(Myself))
	OR(7)
		!CheckSpellState(SixthNearestEnemyOf(Myself),JA_GRAPPLED)
		General(SixthNearestEnemyOf(Myself),WEAPON)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SixthNearestEnemyOf(Myself))
	OR(7)
		!CheckSpellState(SeventhNearestEnemyOf(Myself),JA_GRAPPLED)
		General(SeventhNearestEnemyOf(Myself),WEAPON)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(SeventhNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SeventhNearestEnemyOf(Myself))
	OR(7)
		!CheckSpellState(EighthNearestEnemyOf(Myself),JA_GRAPPLED)
		General(EighthNearestEnemyOf(Myself),WEAPON)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(EighthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(EighthNearestEnemyOf(Myself))
	OR(7)
		!CheckSpellState(NinthNearestEnemyOf(Myself),JA_GRAPPLED)
		General(NinthNearestEnemyOf(Myself),WEAPON)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(NinthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NinthNearestEnemyOf(Myself))
	OR(7)
		!CheckSpellState(TenthNearestEnemyOf(Myself),JA_GRAPPLED)
		General(TenthNearestEnemyOf(Myself),WEAPON)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(TenthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(TenthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Continue()
END

IF
	CheckSpellState(LastSeenBy(Myself),JA_GRAPPLED)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SelectWeaponAbility(SLOT_WEAPON,0)
		AttackOneRound(LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

// Attack NoCheck enemy
IF
	OR(6)
		General(NearestEnemyOf(Myself),WEAPON)
		StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(NearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NearestEnemyOf(Myself))
	OR(6)
		General(SecondNearestEnemyOf(Myself),WEAPON)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SecondNearestEnemyOf(Myself))
	OR(6)
		General(ThirdNearestEnemyOf(Myself),WEAPON)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(ThirdNearestEnemyOf(Myself))
	OR(6)
		General(FourthNearestEnemyOf(Myself),WEAPON)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FourthNearestEnemyOf(Myself))
	OR(6)
		General(FifthNearestEnemyOf(Myself),WEAPON)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FifthNearestEnemyOf(Myself))
	OR(6)
		General(SixthNearestEnemyOf(Myself),WEAPON)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SixthNearestEnemyOf(Myself))
	OR(6)
		General(SeventhNearestEnemyOf(Myself),WEAPON)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(SeventhNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SeventhNearestEnemyOf(Myself))
	OR(6)
		General(EighthNearestEnemyOf(Myself),WEAPON)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(EighthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(EighthNearestEnemyOf(Myself))
	OR(6)
		General(NinthNearestEnemyOf(Myself),WEAPON)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(NinthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NinthNearestEnemyOf(Myself))
	OR(6)
		General(TenthNearestEnemyOf(Myself),WEAPON)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_INVISIBLE)
		CheckStatGT(TenthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_CHARMED)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(TenthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Continue()
END

IF
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SelectWeaponAbility(SLOT_WEAPON,0)
		AttackOneRound(LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

// Attack Sleep enemy
IF
	OR(6)
		!StateCheck(Player1,STATE_SLEEPING)
		StateCheck(Player1,STATE_INVISIBLE)
		CheckStatGT(Player1,0,SANCTUARY)
		StateCheck(Player1,STATE_CHARMED)
		StateCheck(Player1,STATE_REALLY_DEAD)
		!See(Player1)
	OR(6)
		!StateCheck(Player2,STATE_SLEEPING)
		StateCheck(Player2,STATE_INVISIBLE)
		CheckStatGT(Player2,0,SANCTUARY)
		StateCheck(Player2,STATE_CHARMED)
		StateCheck(Player2,STATE_REALLY_DEAD)
		!See(Player2)
	OR(6)
		!StateCheck(Player3,STATE_SLEEPING)
		StateCheck(Player3,STATE_INVISIBLE)
		CheckStatGT(Player3,0,SANCTUARY)
		StateCheck(Player3,STATE_CHARMED)
		StateCheck(Player3,STATE_REALLY_DEAD)
		!See(Player3)
	OR(6)
		!StateCheck(Player4,STATE_SLEEPING)
		StateCheck(Player4,STATE_INVISIBLE)
		CheckStatGT(Player4,0,SANCTUARY)
		StateCheck(Player4,STATE_CHARMED)
		StateCheck(Player4,STATE_REALLY_DEAD)
		!See(Player4)
	OR(6)
		!StateCheck(Player5,STATE_SLEEPING)
		StateCheck(Player5,STATE_INVISIBLE)
		CheckStatGT(Player5,0,SANCTUARY)
		StateCheck(Player5,STATE_CHARMED)
		StateCheck(Player5,STATE_REALLY_DEAD)
		!See(Player5)
	OR(6)
		!StateCheck(Player6,STATE_SLEEPING)
		StateCheck(Player6,STATE_INVISIBLE)
		CheckStatGT(Player6,0,SANCTUARY)
		StateCheck(Player6,STATE_CHARMED)
		StateCheck(Player6,STATE_REALLY_DEAD)
		!See(Player6)
THEN
	RESPONSE #100
		Continue()
END

IF
	StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SelectWeaponAbility(SLOT_WEAPON,0)
		AttackOneRound(LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

// Track players if allegiance is not GOODCUTOFF
IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player1,150)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStatGT(Player1,0,SANCTUARY)
	!StateCheck(Player1,STATE_CHARMED)
	!StateCheck(Player1,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player2,150)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStatGT(Player2,0,SANCTUARY)
	!StateCheck(Player2,STATE_CHARMED)
	!StateCheck(Player2,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player2)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player3,150)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStatGT(Player3,0,SANCTUARY)
	!StateCheck(Player3,STATE_CHARMED)
	!StateCheck(Player3,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player3)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player4,150)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStatGT(Player4,0,SANCTUARY)
	!StateCheck(Player4,STATE_CHARMED)
	!StateCheck(Player4,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player4)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player5,150)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStatGT(Player5,0,SANCTUARY)
	!StateCheck(Player5,STATE_CHARMED)
	!StateCheck(Player5,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player5)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player6,150)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStatGT(Player6,0,SANCTUARY)
	!StateCheck(Player6,STATE_CHARMED)
	!StateCheck(Player6,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player6)
END

// Track last seen enemy if allegiance is GOODCUTOFF
IF
	Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(LastSeenBy(Myself),150)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

// Random walking (in combat) 
IF
	Global("JA#COMBAT","LOCALS",1)
	ActionListEmpty()
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		RandomWalk()
		Wait(2)
END

