COMPILE ~%MOD_FOLDER%/lib/pnp-monster/ankheg/ja#m1.baf~
COMPILE ~%MOD_FOLDER%/lib/pnp-monster/ankheg/ja#m1su.baf~

CREATE SPL "ja#1m1"
	WRITE_SHORT 0x1c 4
	WRITE_BYTE 0x27 10
	WRITE_LONG 0x34 1
	WRITE_LONG 0x64 0x72
	WRITE_SHORT 0x68 1
	WRITE_LONG 0x6a 0x9a
	INSERT_BYTES 0x72 0x28
	WRITE_SHORT 0x72 1
	WRITE_SHORT 0x74 4
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 5
	WRITE_SHORT 0x82 1
	WRITE_SHORT 0x94 1
	SAY NAME1 @4001 SAY NAME2 @4001
	SAY UNIDENTIFIED_DESC ~The ankheg can secret acidic digestive enzymes to cause an additional 1d4 points of damage per round until the victim is dissolved (truncated to 4 rounds).~
	LPF ADD_EFFECT
		INT_VAR
			opcode = 12
			target = 2
			parameter1 = 0
			parameter2 = 65536
			probability1 = 100
			dicenumber = 1
			dicesize = 4
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 12
			target = 2
			parameter1 = 0
			parameter2 = 65536
			timing = 4
			duration = 6
			probability1 = 100
			dicenumber = 1
			dicesize = 4
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 12
			target = 2
			parameter1 = 0
			parameter2 = 65536
			timing = 4
			duration = 12
			probability1 = 100
			dicenumber = 1
			dicesize = 4
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 12
			target = 2
			parameter1 = 0
			parameter2 = 65536
			timing = 4
			duration = 18
			probability1 = 100
			dicenumber = 1
			dicesize = 4
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 142
			target = 2
			parameter1 = 0
			parameter2 = 102
			duration = 24
			probability1 = 100
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 206
			target = 2
			parameter1 = 0
			parameter2 = 0
			duration = 24
			probability1 = 100
		STR_VAR
			resource = "ja#1m1"
	END

CREATE SPL "ja#2m1"
	WRITE_SHORT 0x1c 4
	WRITE_BYTE 0x27 10
	WRITE_LONG 0x34 1
	WRITE_LONG 0x64 0x72
	WRITE_SHORT 0x68 1
	WRITE_LONG 0x6a 0x9a
	INSERT_BYTES 0x72 0x28
	WRITE_SHORT 0x72 2
	WRITE_SHORT 0x74 4
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 30
	WRITE_SHORT 0x82 1
	WRITE_SHORT 0x84 3
	WRITE_SHORT 0x94 1
	SAY NAME1 @4000 SAY NAME2 @4000
	SAY UNIDENTIFIED_DESC ~The ankheg can squirt a stream of acidic enzymes once every six hours to a distance of 30 feet. A victim struck by the stream of acidic enzymes suffers 8d4 points of damage (half damage if the victim rolls a successful saving throw vs. poison). It uses this attack technique only when desperate.~
	WRITE_SHORT 0x98 (IDS_OF_SYMBOL (~projectl~ ~acidblob~)) + 1
	LPF ADD_EFFECT
		INT_VAR
			opcode = 12
			target = 2
			parameter1 = 0
			parameter2 = 65536
			probability1 = 100
			dicenumber = 8
			dicesize = 4
			savingthrow = 4
			special = 256
	END

CREATE SPL "ja#3m1"
	WRITE_SHORT 0x1c 4
	WRITE_LONG 0x34 1
	WRITE_LONG 0x64 0x72
	WRITE_SHORT 0x68 1
	WRITE_LONG 0x6a 0x9a
	INSERT_BYTES 0x72 0x28
	WRITE_SHORT 0x72 1
	WRITE_SHORT 0x74 4
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 5
	WRITE_SHORT 0x82 1
	WRITE_SHORT 0x94 1
	SAY NAME1 @3000 SAY NAME2 @3000
	LPF ADD_EFFECT
		INT_VAR
			opcode = 177
			target = 2
			parameter1 = (IDS_OF_SYMBOL (~RACE~ ~146~))
			parameter2 = 4
			duration = 1
			probability1 = 100
		STR_VAR
			resource = "ja#3m1"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 177
			target = 2
			parameter1 = (IDS_OF_SYMBOL (~RACE~ ~140~))
			parameter2 = 4
			duration = 1
			probability1 = 100
		STR_VAR
			resource = "ja#3m1"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 177
			target = 2
			parameter1 = (IDS_OF_SYMBOL (~RACE~ ~136~))
			parameter2 = 4
			duration = 1
			probability1 = 100
		STR_VAR
			resource = "ja#3m1"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 177
			target = 2
			parameter1 = (IDS_OF_SYMBOL (~RACE~ ~132~))
			parameter2 = 4
			duration = 1
			probability1 = 100
		STR_VAR
			resource = "ja#3m1"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 177
			target = 2
			parameter1 = (IDS_OF_SYMBOL (~RACE~ ~119~))
			parameter2 = 4
			duration = 1
			probability1 = 100
		STR_VAR
			resource = "ja#3m1"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 177
			target = 2
			parameter1 = (IDS_OF_SYMBOL (~RACE~ ~175~))
			parameter2 = 4
			duration = 1
			probability1 = 100
		STR_VAR
			resource = "ja#3m1"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 177
			target = 2
			parameter1 = (IDS_OF_SYMBOL (~RACE~ ~133~))
			parameter2 = 4
			duration = 1
			probability1 = 100
		STR_VAR
			resource = "ja#3m1"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 177
			target = 2
			parameter1 = (IDS_OF_SYMBOL (~RACE~ ~181~))
			parameter2 = 4
			duration = 1
			probability1 = 100
		STR_VAR
			resource = "ja#3m1"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 177
			target = 2
			parameter1 = (IDS_OF_SYMBOL (~RACE~ ~134~))
			parameter2 = 4
			duration = 1
			probability1 = 100
		STR_VAR
			resource = "ja#3m1"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 177
			target = 2
			parameter1 = (IDS_OF_SYMBOL (~RACE~ ~118~))
			parameter2 = 4
			duration = 1
			probability1 = 100
		STR_VAR
			resource = "ja#3m1"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 177
			target = 2
			parameter1 = (IDS_OF_SYMBOL (~RACE~ ~101~))
			parameter2 = 4
			duration = 1
			probability1 = 100
		STR_VAR
			resource = "ja#3m1"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 177
			target = 2
			parameter1 = (IDS_OF_SYMBOL (~RACE~ ~145~))
			parameter2 = 4
			duration = 1
			probability1 = 100
		STR_VAR
			resource = "ja#3m1"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 177
			target = 2
			parameter1 = (IDS_OF_SYMBOL (~RACE~ ~199~))
			parameter2 = 4
			duration = 1
			probability1 = 100
		STR_VAR
			resource = "ja#3m1"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 177
			target = 2
			parameter1 = (IDS_OF_SYMBOL (~RACE~ ~142~))
			parameter2 = 4
			duration = 1
			probability1 = 100
		STR_VAR
			resource = "ja#3m1"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 177
			target = 2
			parameter1 = (IDS_OF_SYMBOL (~RACE~ ~162~))
			parameter2 = 4
			duration = 1
			probability1 = 100
		STR_VAR
			resource = "ja#3m1"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 177
			target = 2
			parameter1 = (IDS_OF_SYMBOL (~RACE~ ~184~))
			parameter2 = 4
			duration = 1
			probability1 = 100
		STR_VAR
			resource = "ja#3m1"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 177
			target = 2
			parameter1 = (IDS_OF_SYMBOL (~CLASS~ ~221~))
			parameter2 = 5
			duration = 1
			probability1 = 100
		STR_VAR
			resource = "ja#3m1"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 177
			target = 2
			parameter1 = (IDS_OF_SYMBOL (~CLASS~ ~222~))
			parameter2 = 5
			duration = 1
			probability1 = 100
		STR_VAR
			resource = "ja#3m1"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 177
			target = 2
			parameter1 = (IDS_OF_SYMBOL (~CLASS~ ~141~))
			parameter2 = 5
			duration = 1
			probability1 = 100
		STR_VAR
			resource = "ja#3m1"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 177
			target = 2
			parameter1 = (IDS_OF_SYMBOL (~CLASS~ ~106~))
			parameter2 = 5
			duration = 1
			probability1 = 100
		STR_VAR
			resource = "ja#3m1"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 177
			target = 2
			parameter1 = (IDS_OF_SYMBOL (~CLASS~ ~107~))
			parameter2 = 5
			duration = 1
			probability1 = 100
		STR_VAR
			resource = "ja#3m1"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 177
			target = 2
			parameter1 = (IDS_OF_SYMBOL (~CLASS~ ~139~))
			parameter2 = 5
			duration = 1
			probability1 = 100
		STR_VAR
			resource = "ja#3m1"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 177
			target = 2
			parameter1 = (IDS_OF_SYMBOL (~CLASS~ ~140~))
			parameter2 = 5
			duration = 1
			probability1 = 100
		STR_VAR
			resource = "ja#3m1"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 328
			target = 2
			parameter1 = 0
			parameter2 = (IDS_OF_SYMBOL (~splstate~ ~JA_GRAPPLE~))
			duration = 18
			probability1 = 100
			special = 1
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 139
			target = 2
			parameter1 = RESOLVE_STR_REF(@3001)
			parameter2 = 0
			timing = 1
			probability1 = 100
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 176
			target = 2
			parameter1 = 0
			parameter2 = 1
			duration = 18
			probability1 = 100
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 174
			target = 2
			parameter1 = 0
			parameter2 = 0
			timing = 1
			probability1 = 100
		STR_VAR
			resource = "CRE_P01"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 174
			target = 2
			parameter1 = 0
			parameter2 = 0
			timing = 4
			duration = 18
			probability1 = 100
		STR_VAR
			resource = "EFF_M22A"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 215
			target = 2
			parameter1 = 0
			parameter2 = 1
			duration = 18
			probability1 = 100
		STR_VAR
			resource = "rr#cnstr"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 142
			target = 2
			parameter1 = 0
			parameter2 = 144
			duration = 18
			probability1 = 100
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 15
			target = 2
			parameter1 = 8
			parameter2 = 1
			duration = 18
			probability1 = 100
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 206
			target = 2
			parameter1 = 0
			parameter2 = 0
			probability1 = 100
		STR_VAR
			resource = "ja#3m1"
	END

CREATE EFF "ja#3m1"
	WRITE_LONG 0x10 206
	WRITE_LONG 0x14 2
	WRITE_LONG 0x24 0
	WRITE_LONG 0x28 1
	WRITE_SHORT 0x2c 100
	WRITE_ASCII 0x30 ~ja#3m1~ #8

CREATE ITM "ja#m1w1"
	WRITE_LONG 0x64 0x72
	WRITE_SHORT 0x68 1
	WRITE_LONG 0x6a 0xaa
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x72 1
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 1
	WRITE_SHORT 0x84 3
	WRITE_BYTE 0x88 6
	WRITE_BYTE 0x8a 3
	WRITE_SHORT 0x8e 2
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
	LPF set_enchantment INT_VAR enchantment = 0 END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 146
			target = 2
			parameter1 = 0
			parameter2 = 1
			probability1 = 100
		STR_VAR
			resource = "ja#1m1"
	END

CREATE ITM "ja#m1w2"
	WRITE_LONG 0x64 0x72
	WRITE_SHORT 0x68 1
	WRITE_LONG 0x6a 0xaa
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x72 2
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 30
	WRITE_SHORT 0x84 3
	WRITE_SHORT 0x86 20
	WRITE_SHORT 0x9c (IDS_OF_SYMBOL (~projectl~ ~acidblob~)) + 1
	WRITE_SHORT 0x38 1
	WRITE_SHORT 0xa4 1
	LPF set_enchantment INT_VAR enchantment = 0 END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 146
			target = 2
			parameter1 = 0
			parameter2 = 1
			probability1 = 100
		STR_VAR
			resource = "ja#2m1"
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 172
			target = 1
			parameter1 = 0
			parameter2 = 0
			probability1 = 100
		STR_VAR
			resource = "ja#2m1"
	END

ACTION_FOR_EACH ~file~ IN
	ANKHEG
	ANKHEGF
	ANKHEGG
	ANKHEGQ
	ANKHEG01
	bdankh01
	bdankheg
	bdankhsu
	BDNEO
	BPANKHE1
	wiankhe1
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~ANKHEG1~
			REMOVE_CRE_ITEM ~ANKHEG2~
			ADD_CRE_ITEM ~ja#m1w1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			ADD_CRE_ITEM ~ja#m1w2~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON2~ 
			ADD_MEMORIZED_SPELL ~ja#1m1~ #0 ~innate~ (1)
			ADD_MEMORIZED_SPELL ~ja#2m1~ #0 ~innate~ (1)
			ADD_MEMORIZED_SPELL ~ja#3m1~ #0 ~innate~ (1)
			LPF patchCreature
				INT_VAR
					level1=8
					strength=21
					dexterity=10
					constitution=17
					intelligence=1
					wisdom=13
					charisma=6
					movement=12
					hp=64
					ac=2
					thac0=13
					apr=1
					xpv=975
					alignment=34
					saveDeath=10
					saveWand=12
					savePolymorph=11
					saveBreath=12
					saveSpell=13
					morale=9
					moraleBreak=4
					moraleRecovery=15
					general=255
					race=101
					class=101
					gender=4
					sex=4
					enforce=1
			END
			DEFINE_ARRAY removeScripts BEGIN
				ANKHEG
				SHOUT
				WTASIGHT
				wtrunsgt
				DW2MP0GE
				DW2RC2MO
			END
			LPF patchCreatureScript STR_VAR script=ja#m1 removeScripts skipFiles END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~bdankh01~) BEGIN 
				LPF patchCreature
					INT_VAR
						level1=10
						hp=80
						thac0=11
						xpv=1400
						saveDeath=8
						saveWand=10
						savePolymorph=9
						saveBreath=9
						saveSpell=11
				END
			END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~bdankhsu~) BEGIN 
				DEFINE_ARRAY removeScripts BEGIN
					ja#m1
					ANKHEG
					SHOUT
					WTASIGHT
					wtrunsgt
					DW2MP0GE
					DW2RC2MO
				END
				LPF patchCreatureScript STR_VAR script=ja#m1su removeScripts skipFiles END
			END
		BUT_ONLY_IF_IT_CHANGES
	END
END