import { StringReferenceEnum } from "../config/stringRef";
import { RawCreature } from "../src/model/raw/creature";

export const ANKHEG: RawCreature = {
  name: "Ankheg",
  bafFile: "lib/pnp-monster/ankheg/ja#m1",
  tpaFile: "lib/pnp-monster/ankheg/main",
  tracking: true,
  combatWalk: true,
  data: {
    level1: 8,
    strength: 17,
    dexterity: 11,
    constitution: 13,
    intelligence: 1,
    wisdom: 13,
    charisma: 6,
    movement: 6,
    ac: 2,
    apr: 1,
    xpv: 975,
    alignment: "NEUTRAL",
    morale: 9,
    moraleBreak: 4,
    moraleRecovery: 15,
    general: "MONSTER",
    race: "ANKHEG",
    class: "ANKHEG",
    gender: "NIETHER",
    size: "Huge",
  },
  additionalData: {
    removeScripts: ["ANKHEG"],
    removeItems: ["ANKHEG1", "ANKHEG2"],
  },
  abilities: [
    {
      name: "Acidic Enzymes",
      disableInterrupt: true,
      target: { name: "PCsPreferringWeak", random: true },
      triggers: [
        { name: "HPPercentLT", params: ["Myself", 50] },
        { name: "HaveSpellRES", params: ["ja#2m1"] },
      ],
      actions: [
        { name: "SelectWeaponAbility", params: ["SLOT_WEAPON1", 0] },
        { name: "AttackOneRound", params: ["LastSeenBy"] },
      ],
      range: 30,
    },
  ],
  items: [
    {
      file: "ja#m1w1",
      equippedSlot: "WEAPON1",
      type: "Melee",
      diceThrown: 3,
      diceSize: 6,
      damageType: "Crushing",
      speed: 3,
      abilityFlags: ["AddStrengthBonus"],
      effects: [
        {
          opcode: "CastSpell",
          resource: "ja#1m1",
          type: "CastInstantlyAtCasterLevel",
        },
      ],
    },
    {
      file: "ja#m1w2",
      equippedSlot: "WEAPON2",
      type: "Ranged",
      range: 30,
      speed: 3,
      bonusToHit: 20,
      projectile: "acidblob",
      effects: [
        {
          opcode: "CastSpell",
          type: "CastInstantlyAtCasterLevel",
          resource: "ja#2m1",
        },
        { opcode: "RemoveSpell", target: "Self", resource: "ja#2m1" },
      ],
    },
  ],
  attack: {
    actions: [{ weaponSlot: "SLOT_WEAPON", disableInterrupt: true }],
    grab: {
      file: "ja#3m1",
      probability: 100,
      saveBonus: -4,
      weaponFile: "ja#m1w1",
      duration: 18,
    },
  },
  spells: [
    {
      name: "Acidic digestive enzymes",
      file: "ja#1m1",
      memorizedCount: 1,
      stringRef: StringReferenceEnum.AcidicDigestiveEnzymes,
      description: [
        "The ankheg can secret acidic digestive enzymes to cause an additional 1d4 points of damage per round until the victim is dissolved (truncated to 4 rounds).",
      ],
      secondaryType: "OffensiveDamage",
      type: "Melee",
      range: 5,
      effects: [
        {
          opcode: "ProtectionFromSpell",
          resource: "ja#1m1",
          duration: 24,
          timing: "InstantLimited",
        },
        { opcode: "DisplayPortraitIcon", icon: "Acid", duration: 24 },
        { opcode: "Damage", type: "Acid", diceThrown: 1, diceSize: 4 },
        {
          opcode: "Damage",
          timing: "DelayPermanent",
          duration: 6,
          type: "Acid",
          diceThrown: 1,
          diceSize: 4,
        },
        {
          opcode: "Damage",
          timing: "DelayPermanent",
          duration: 12,
          type: "Acid",
          diceThrown: 1,
          diceSize: 4,
        },
        {
          opcode: "Damage",
          timing: "DelayPermanent",
          duration: 18,
          type: "Acid",
          diceThrown: 1,
          diceSize: 4,
        },
      ],
    },
    {
      name: "Stream of acidic enzymes",
      file: "ja#2m1",
      memorizedCount: 1,
      stringRef: StringReferenceEnum.StreamOfAcidicEnzymes,
      description: [
        "The ankheg can squirt a stream of acidic enzymes once every six hours to a distance of 30 feet.",
        "A victim struck by the stream of acidic enzymes suffers 8d4 points of damage (half damage if the victim rolls a successful saving throw vs. poison).",
        "It uses this attack technique only when desperate.",
      ],
      secondaryType: "OffensiveDamage",
      type: "Ranged",
      range: 30,
      speed: 3,
      projectile: "acidblob",
      effects: [
        {
          opcode: "Damage",
          type: "Acid",
          diceThrown: 8,
          diceSize: 4,
          saveTypes: ["ParalyzePoisonDeath"],
          flags: ["SaveForHalf"],
        },
      ],
    },
  ],
  files: [
    "ANKHEG",
    "ANKHEGF",
    "ANKHEGG",
    "ANKHEGQ",
    "ANKHEG01",
    "bdankh01",
    "bdankheg",
    "bdankhsu",
    "BDNEO",
    "BPANKHE1",
    "wiankhe1",
  ],
  adjustments: [
    { files: ["bdankh01"], data: { level1: 10, xpv: 1400 } },
    { files: ["bdankhsu"], summon: true },
  ],
};
