import { RawCreature } from "../src/model/raw/creature";

export const BASILISK_LESSER: RawCreature = {
  name: "Lesser Basilisk",
  bafFile: "lib/pnp-monster/basilisk/ja#m2",
  tpaFile: "lib/pnp-monster/basilisk/lesser",
  tracking: true,
  combatWalk: true,
  data: {
    level1: 6,
    bonusHp: 1,
    strength: 16,
    dexterity: 8,
    constitution: 15,
    intelligence: 2,
    wisdom: 8,
    charisma: 7,
    movement: 6,
    ac: 4,
    apr: 1,
    xpv: 1400,
    alignment: "NEUTRAL",
    morale: 12,
    moraleBreak: 4,
    moraleRecovery: 15,
    general: "MONSTER",
    race: "BASILISK",
    class: "BASILISK",
    gender: "NIETHER",
    size: "Medium",
  },
  additionalData: {
    removeItems: ["BASILL1", "BASILL2"],
    removeScripts: ["LBASILSK"],
  },
  abilities: [
    {
      name: "Petrification",
      target: {
        name: "NearestEnemies",
        random: true,
        triggers: [
          {
            name: "CheckStatGT",
            params: ["{Target}", "0", "HELD"],
            negation: true,
          },
          {
            name: "StateCheck",
            params: ["{Target}", "STATE_SLOWED"],
            negation: true,
          },
        ],
      },
      actions: [{ name: "ForceSpellRES", params: ["ja#1m2", "LastSeenBy"] }],
      range: 30,
    },
  ],
  items: [
    {
      file: "ja#m2w1",
      equippedSlot: "WEAPON1",
      type: "Melee",
      diceThrown: 1,
      diceSize: 10,
      damageType: "Slashing",
      speed: 3,
      abilityFlags: ["AddStrengthBonus"],
    },
  ],
  projectiles: [
    {
      file: "ja#1m2",
      copyFromFile: "gaze",
      description: "Basilisk petrifying gaze",
      type: "AreaOfEffect",
      triggerRadius: 255,
      areaOfEffect: 255,
      coneWidth: 60,
      areaProjectileFlags: ["AffectOnlyEnemies", "Coneshaped"],
      fragmentAnimation: "NULL_ANIMATION",
      explosionEffect: "NONE",
    },
  ],
  spells: [
    {
      name: "Petrification (2e)",
      file: "ja#1m2",
      memorizedCount: 1,
      stringRef: 4002,
      description: [
        "Any creature, that can see and within 30 feet of the basilisk, must save vs petrify at -4. On a failed save, the creature is petrified until freed by the greater restoration spell or other magic.",
      ],
      secondaryType: "Disabling",
      type: "Ranged",
      projectile: "ja#1m2",
      range: 30,
      effects: [
        {
          opcode: "Petrification",
          saveTypes: ["PetrifyPolymorph"],
          saveBonus: -4,
        },
        {
          opcode: "DisplayString",
          stringRef: 4004,
          saveTypes: ["PetrifyPolymorph"],
          saveBonus: -4,
        },
        {
          opcode: "PlaySound",
          resource: "MISC_06B",
          saveTypes: ["PetrifyPolymorph"],
          saveBonus: -4,
        },
        {
          opcode: "PlayVisualEffect",
          playWhere: "OverTargetUnattached",
          resource: "SPFLESHS.VVC",
          saveTypes: ["PetrifyPolymorph"],
          saveBonus: -4,
        },
        {
          opcode: "CreatureRGBColorFade",
          color: { blue: 120, red: 120, green: 120 },
          fadeSpeed: 25,
          saveTypes: ["PetrifyPolymorph"],
          saveBonus: -4,
        },
      ],
    },
    {
      name: "Petrification (5e)",
      file: "ja#2m2",
      memorizedCount: 1,
      stringRef: 4002,
      description: [
        "Any creature, that can see and within 30 feet of the basilisk, must save vs petrify at -4.",
        "On a failed save, the creature magically begins to turn to stone and is restrained.",
        "It must repeat the saving throw at the end of its next turn. On a success, the effect ends. On a failure, the creature is petrified until freed by the greater restoration spell or other magic.",
      ],
      secondaryType: "Disabling",
      type: "Ranged",
      projectile: "ja#2m2",
      range: 30,
      effects: [
        {
          opcode: "DisplayString",
          stringRef: 4005,
          saveTypes: ["PetrifyPolymorph"],
          saveBonus: -4,
        },
        {
          opcode: "RestrainedEffects",
          duration: 12,
          saveTypes: ["PetrifyPolymorph"],
          saveBonus: -4,
        },
        {
          opcode: "CastSpell",
          timing: "DelayLimited",
          duration: 12,
          type: "CastInstantlyAtCasterLevel",
          resource: "ja#3m2",
          saveTypes: ["PetrifyPolymorph"],
          saveBonus: -4,
        },
        {
          opcode: "ProtectionFromSpell",
          timing: "DelayLimited",
          duration: 12,
          resource: "ja#2m2",
          saveTypes: ["PetrifyPolymorph"],
          saveBonus: -4,
        },
      ],
    },
    {
      name: "Petrification (5e, technical)",
      stringRef: 4002,
      file: "ja#3m2",
      secondaryType: "Disabling",
      type: "Ranged",
      effects: [
        {
          opcode: "Petrification",
          timing: "InstantPermanent",
          saveTypes: ["PetrifyPolymorph"],
          saveBonus: -4,
        },
        {
          opcode: "DisplayString",
          stringRef: 4004,
          timing: "InstantPermanent",
          saveTypes: ["PetrifyPolymorph"],
          saveBonus: -4,
        },
        {
          opcode: "PlaySound",
          resource: "MISC_06B",
          timing: "InstantPermanent",
          saveTypes: ["PetrifyPolymorph"],
          saveBonus: -4,
        },
        {
          opcode: "PlayVisualEffect",
          playWhere: "OverTargetUnattached",
          resource: "SPFLESHS.VVC",
          timing: "InstantPermanent",
          saveTypes: ["PetrifyPolymorph"],
          saveBonus: -4,
        },
        {
          opcode: "CreatureRGBColorFade",
          color: { blue: 120, red: 120, green: 120 },
          fadeSpeed: 25,
          timing: "InstantPermanent",
          saveTypes: ["PetrifyPolymorph"],
          saveBonus: -4,
        },
      ],
    },
  ],
  files: ["BASILL", "BASILLSU", "BPBASL01"],
  adjustments: [{ files: ["BASILLSU"], summon: true }],
};
