import { StringReferenceEnum } from "../config/stringRef";
import { RawCreature } from "../src/model/raw/creature";

export const BEAR_POLAR_KALDRAN: RawCreature = {
  name: "Polar Bear Kaldran",
  bafFile: "lib/pnp-monster/bear/ja#m8",
  tpaFile: "lib/pnp-monster/bear/kaldran",
  tracking: true,
  combatWalk: true,
  attack: { dualWielding: true },
  data: {
    level1: 12,
    bonusHp: 8,
    specialBonusHp: 12,
    strength: 20,
    dexterity: 10,
    constitution: 16,
    intelligence: 10,
    wisdom: 13,
    charisma: 7,
    movement: 12,
    ac: 6,
    apr: 3,
    resistCold: 100,
    alignment: "NEUTRAL",
    morale: 15,
    moraleBreak: 4,
    moraleRecovery: 15,
    general: "MONSTER",
    race: "BEAR",
    class: "BEAR_POLAR",
    gender: "NIETHER",
    size: "Huge",
  },
  additionalData: {
    removeItems: ["KALDW1", "B1-12"],
    removeScripts: ["kaldran", "dw1ranmo"],
    itemSlots: [
      { file: "ja#m7w1", slot: "WEAPON1" },
      { file: "ja#m7w2", slot: "SHIELD" },
    ],
  },
  customCode: [
    {
      location: "init",
      type: "insertAfter",
      statements: [
        {
          triggers: [
            { name: "Global", params: ["Kaldran", "GLOBAL", 0] },
            { name: "See", params: ["NearestEnemyOf"] },
            { name: "See", params: ["PC"] },
          ],
          responses: [
            {
              weight: 100,
              actions: [
                { name: "SetGlobal", params: ["Kaldran", "GLOBAL", 1] },
              ],
            },
          ],
        },
      ],
    },
  ],
  projectiles: [
    {
      file: "ja#1m8",
      copyFromFile: "CONECOLD",
      description: "Improved stream of frost",
      triggerRadius: 180,
      areaOfEffect: 180,
      areaProjectileFlags: ["AffectOnlyEnemies", "UseSecondaryProjectile"],
      coneWidth: 0,
    },
    {
      file: "ja#2m8",
      copyFromFile: "FIREBALL",
      description: "Improved stream of frost",
      type: "AreaOfEffect",
      triggerRadius: 180,
      areaOfEffect: 180,
      areaProjectileFlags: ["AffectOnlyEnemies"],
      coneWidth: 0,
    },
  ],
  abilities: [
    {
      name: "Improved stream of frost",
      target: { name: "NearestEnemies", limit: 3 },
      range: 10,
      triggers: [{ name: "HaveSpellRES", params: ["ja#1m8"] }],
      timer: { name: "StreamOfFrost", value: 18 },
      actions: [{ name: "ForceSpellRES", params: ["ja#1m8", "Myself"] }],
    },
  ],
  spells: [
    {
      name: "Improved stream of frost",
      file: "ja#1m8",
      memorizedCount: 1,
      stringRef: StringReferenceEnum.ImprovedStreamOfFrost,
      description: [
        "Unleash a stream of frost, causing 6d4 points of damage to everything within 10 feet. A save vs. breath weapon is allowed for half damage. Affected creatures are also paralyzed for one turn (saves vs paralyze at -2)",
      ],
      target: "AnyPointWithinRange",
      secondaryType: "OffensiveDamage",
      type: "Ranged",
      projectile: "ja#1m8",
      range: 10,
      effects: [
        {
          opcode: "Damage",
          timing: "InstantPermanentUntilDeath",
          amount: 0,
          damageMode: "Normal",
          type: "Cold",
          diceThrown: 6,
          diceSize: 4,
          saveTypes: ["Breath"],
          flags: ["SaveForHalf"],
        },
        {
          opcode: "CharacterColorPulse",
          timing: "InstantPermanentUntilDeath",
          color: { blue: 255, green: 213, red: 123 },
          location: "ArmorGreyBeltAmulet",
          cycleSpeed: 20,
        },
        {
          opcode: "Paralyze",
          timing: "InstantLimited",
          idsFile: "EA",
          idsEntry: "ANYONE",
          duration: 60,
          saveTypes: ["ParalyzePoisonDeath"],
          saveBonus: -2,
        },
        {
          opcode: "DisplayPortraitIcon",
          timing: "InstantLimited",
          icon: "Held",
          duration: 60,
          saveTypes: ["ParalyzePoisonDeath"],
          saveBonus: -2,
        },
        {
          opcode: "PlaySound",
          timing: "InstantPermanentUntilDeath",
          resource: "MISC_04A",
          saveTypes: ["ParalyzePoisonDeath"],
          saveBonus: -2,
        },
        {
          opcode: "PlaySound",
          timing: "DelayPermanent",
          resource: "EFF_E03",
          duration: 60,
          saveTypes: ["ParalyzePoisonDeath"],
          saveBonus: -2,
        },
      ],
    },
  ],
  files: ["KALDRAN"],
};
