import { RawCreature } from "../src/model/raw/creature";

export const GOLEM_FLESH: RawCreature = {
  name: "Flesh Golem",
  bafFile: "lib/pnp-monster/golem/ja#m23",
  tpaFile: "lib/pnp-monster/golem/flesh",
  tracking: true,
  combatWalk: true,
  restHeal: true,
  data: {
    level1: 9,
    bonusHp: 0,
    strength: 19,
    dexterity: 9,
    constitution: 18,
    intelligence: 3,
    wisdom: 10,
    charisma: 5,
    movement: 8,
    ac: 9,
    apr: 2,
    xpv: 2000,
    alignment: "NEUTRAL",
    morale: 20,
    moraleBreak: 4,
    moraleRecovery: 15,
    general: "GIANTHUMANOID",
    race: "GOLEM",
    class: "GOLEM_FLESH",
    gender: "NIETHER",
    size: "Large",
    modAnimation: "A7!GOLEM_FLESH_PST",
    resistMagic: 100,
    resistFire: 100,
    resistCold: 100,
    resistElectricity: 125,
  },
  additionalData: {
    immunities: ["construct"],
    removeScripts: ["dw1melmo"],
    removeItems: ["GOLFLE"],
  },
  items: [
    {
      file: "ja#m23w1",
      equippedSlot: "WEAPON1",
      type: "Melee",
      diceThrown: 2,
      diceSize: 8,
      damageType: "Crushing",
      speed: 3,
      abilityFlags: ["AddStrengthBonus"],
    },
  ],
  files: ["BPGOFL01", "FGOLEM", "GOLEMF", "GOLEMF2", "TOMEGOL1"],
};
