CREATE ITM "ja#1m19"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_LONG 0x18 64
	WRITE_LONG 0x60 1
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 2
	WRITE_BYTE 0x88 4
	WRITE_BYTE 0x8a 2
	WRITE_SHORT 0x8e 1
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
COPY_EXISTING ~ja#1m19.itm~ ~override~

ACTION_FOR_EACH ~file~ IN
	BDWOLFDI
	P#WOLF02
	WOLFDI
	WOLFDISU
	UBNIMWLF
	SHAWOL01
	RUFIE
	L#FAIEN3
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~P1-8~
			REMOVE_CRE_ITEM ~P2-8~
			REMOVE_CRE_ITEM ~IMMUNE1~
			REMOVE_CRE_ITEM ~RING95~
			ADD_CRE_ITEM ~ja#1m19~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			LPF clearProficiencies END
			DEFINE_ARRAY notEnforceFiles BEGIN  END
			LPF patchCreature
				INT_VAR
					level1=4
					strength=17
					dexterity=15
					constitution=15
					intelligence=4
					wisdom=12
					charisma=7
					movement=15
					hp=36
					ac=6
					thac0=15
					apr=1
					xpv=175
					alignment=IDS_OF_SYMBOL (~align~ ~NEUTRAL~)
					saveDeath=13
					saveWand=15
					savePolymorph=14
					saveBreath=16
					saveSpell=16
					morale=10
					moraleBreak=4
					moraleRecovery=15
					general=IDS_OF_SYMBOL (~general~ ~ANIMAL~)
					race=IDS_OF_SYMBOL (~race~ ~WOLF~)
					class=IDS_OF_SYMBOL (~class~ ~WOLF_DIRE~)
					gender=IDS_OF_SYMBOL (~gender~ ~MALE~)
					sex=IDS_OF_SYMBOL (~gender~ ~MALE~)
					enforce=1
				STR_VAR
					notEnforceFiles
			END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~WOLFDISU~) BEGIN 
			DEFINE_ARRAY notEnforceFiles BEGIN  END
				LPF patchCreature
					INT_VAR
						hp=36
						thac0=17
						xpv=0
						saveDeath=13
						saveWand=15
						savePolymorph=14
						saveBreath=16
						saveSpell=16
						summon=1
					STR_VAR
						notEnforceFiles
				END
			END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~SHAWOL01~) BEGIN 
			DEFINE_ARRAY notEnforceFiles BEGIN  END
				LPF patchCreature
					INT_VAR
						strength=18
						hp=36
						thac0=17
						xpv=450
						saveDeath=13
						saveWand=15
						savePolymorph=14
						saveBreath=16
						saveSpell=16
					STR_VAR
						notEnforceFiles
				END
				ADD_CRE_ITEM ~ja#i4~ #0 #0 #0 ~UNDROPPABLE~ ~RRING~ 
				ADD_CRE_ITEM ~ja#i5~ #0 #0 #0 ~UNDROPPABLE~ ~HELMET~ 
			END
		BUT_ONLY_IF_IT_CHANGES
	END ELSE BEGIN
		PRINT ~====> CRE %file% not found!~
	END
END