COMPILE ~%MOD_FOLDER%/lib/pnp-monster/wolf/ja#m22.baf~

	// Dread wolf down state
CREATE SPL "ja#1m22"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x28
	WRITE_SHORT 0x68 1
	WRITE_LONG 0x6a 0x9a
	WRITE_SHORT 0x72 1
	WRITE_SHORT 0x82 1
	WRITE_SHORT 0x1c 4
	WRITE_LONG 0x34 1
	WRITE_SHORT 0x74 4
	WRITE_BYTE 0x7e 1
	WRITE_LONG 0x8 RESOLVE_STR_REF(~Dread wolf down state~)
	LPF ADD_EFFECT
		INT_VAR
			opcode = 112
			target = 1
			timing = 1
			probability1 = 100
		STR_VAR
			resource = "ja#2m22"
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 4
			target = 1
			timing = 1
			probability1 = 100
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 75
			target = 1
			timing = 1
			probability1 = 100
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 242
			target = 1
			timing = 1
			probability1 = 100
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 81
			target = 1
			timing = 1
			probability1 = 100
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 79
			target = 1
			timing = 1
			probability1 = 100
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 77
			target = 1
			timing = 1
			probability1 = 100
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 11
			target = 1
			timing = 1
			probability1 = 100
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 2
			target = 1
			timing = 1
			probability1 = 100
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 46
			target = 1
			timing = 1
			probability1 = 100
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 162
			target = 1
			timing = 1
			probability1 = 100
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 161
			target = 1
			timing = 1
			probability1 = 100
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 143
			target = 1
			parameter1 = IDS_OF_SYMBOL (~slots~ ~SLOT_RING_LEFT~)
			duration = 12
			probability1 = 100
		STR_VAR
			resource = "ja#3m22"
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 39
			target = 1
			parameter2 = 1
			duration = 12
			probability1 = 100
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 17
			target = 1
			parameter1 = 1
			parameter2 = 1
			timing = 1
			probability1 = 100
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 143
			target = 1
			parameter1 = IDS_OF_SYMBOL (~slots~ ~SLOT_RING_LEFT~)
			timing = 4
			duration = 12
			probability1 = 100
		STR_VAR
			resource = "ja#2m22"
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 17
			target = 1
			parameter1 = 6
			parameter2 = 1
			timing = 4
			duration = 12
			probability1 = 100
		END

CREATE ITM "ja#1m22"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_LONG 0x18 64
	WRITE_LONG 0x60 1
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 1
	WRITE_BYTE 0x88 10
	WRITE_BYTE 0x8a 1
	WRITE_SHORT 0x8e 1
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
COPY_EXISTING ~ja#1m22.itm~ ~override~
	LPF ADD_EFFECT
		INT_VAR
			opcode = 78
			target = 2
			parameter1 = 300
			parameter2 = 3
			duration = 90000
			probability1 = 100
			special = 7
		END

CREATE ITM "ja#2m22"
	WRITE_LONG 0x64 0x72
	SAY NAME1 ~Dread wolf resistances~ SAY NAME2 ~Dread wolf resistances~
	SAY UNIDENTIFIED_DESC ~A dread wolf regenerates like a troll, regaining 3 hp per round after the first combat round.
Only acid, fire, or total dismemberment will inflict permanent damage.
It is immune to charm, hold, and cold-based spells.
Electricity-based spells cause only half damage.~
	WRITE_SHORT 0x1c 10
	WRITE_ASCII 0x3a ~IRING01~ #8
COPY_EXISTING ~ja#2m22.itm~ ~override~
	LPF ADD_ITEM_EQEFFECT
		INT_VAR
			opcode = 98
			target = 1
			parameter1 = 2
			parameter2 = 3
			timing = 2
			probability1 = 100
			special = 87
		END
	LPF ADD_ITEM_EQEFFECT
		INT_VAR
			opcode = 208
			target = 1
			parameter1 = 1
			timing = 2
			probability1 = 100
		END
	LPF ADD_ITEM_EQEFFECT
		INT_VAR
			opcode = 232
			target = 1
			parameter2 = 19
			timing = 2
			probability1 = 100
			special = 6
		STR_VAR
			resource = "ja#1m22"
		END
	LPF coldSpells_immunity END
	LPF charm_immunity END
	LPF hold_immunity END

CREATE ITM "ja#3m22"
	WRITE_LONG 0x64 0x72
	SAY NAME1 ~Dread wolf down resistances~ SAY NAME2 ~Dread wolf down resistances~
	SAY UNIDENTIFIED_DESC ~A down dread wolf is immune to everything but fire and acid.~
	WRITE_SHORT 0x1c 10
	WRITE_ASCII 0x3a ~IRING01~ #8
COPY_EXISTING ~ja#3m22.itm~ ~override~
	LPF ADD_ITEM_EQEFFECT
		INT_VAR
			opcode = 29
			target = 1
			parameter1 = 100
			parameter2 = 1
			timing = 2
			probability1 = 100
		END
	LPF ADD_ITEM_EQEFFECT
		INT_VAR
			opcode = 31
			target = 1
			parameter1 = 100
			parameter2 = 1
			timing = 2
			probability1 = 100
		END
	LPF poison_immunity END
	LPF disease_immunity END
	LPF cold_immunity END
	LPF physical_immunity END

ACTION_FOR_EACH ~file~ IN
	BDWOLFDR
	D5WOLFD1
	DW#REWO
	P#WOLF03
	P#WOLF05
	PLYWOLF
	WOLFD1
	WOLFDR
	L#HALWO
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~P1-10~
			REMOVE_CRE_ITEM ~RING95~
			REMOVE_CRE_ITEM ~TROLLIMM~
			REMOVE_CRE_ITEM ~BDWOLFD1~
			REMOVE_CRE_ITEM ~BDWOLFDR~
			ADD_CRE_ITEM ~ja#1m22~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			ADD_CRE_ITEM ~ja#2m22~ #0 #0 #0 ~UNDROPPABLE~ ~LRING~ 
			LPF clearProficiencies END
			LPF patchCreature
				INT_VAR
					level1=4
					strength=18
					dexterity=13
					constitution=14
					intelligence=9
					wisdom=12
					charisma=8
					movement=15
					hp=46
					ac=6
					resistCold=100
					resistElectricity=50
					thac0=15
					apr=1
					xpv=650
					alignment=IDS_OF_SYMBOL (~align~ ~NEUTRAL_EVIL~)
					saveDeath=13
					saveWand=15
					savePolymorph=14
					saveBreath=16
					saveSpell=16
					morale=18
					moraleBreak=4
					moraleRecovery=15
					general=IDS_OF_SYMBOL (~general~ ~ANIMAL~)
					race=IDS_OF_SYMBOL (~race~ ~WOLF~)
					class=IDS_OF_SYMBOL (~class~ ~WOLF_DREAD~)
					gender=IDS_OF_SYMBOL (~gender~ ~MALE~)
					sex=IDS_OF_SYMBOL (~gender~ ~MALE~)
					enforce=1
			END
			LPF patchCreatureScript STR_VAR script=ja#m22 END
		BUT_ONLY_IF_IT_CHANGES
	END ELSE BEGIN
		PRINT ~====> CRE %file% not found!~
	END
END