COMPILE ~%MOD_FOLDER%/lib/pnp-monster/wolf/ja#22.baf~

CREATE ITM "ja#m22w1"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_LONG 0x60 1
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 1
	WRITE_SHORT 0x84 3
	WRITE_BYTE 0x88 10
	WRITE_BYTE 0x8a 1
	WRITE_SHORT 0x8e 1
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
COPY_EXISTING ~ja#m22w1.itm~ ~override~
	LPF ADD_EFFECT
		INT_VAR
			opcode = 78
			target = 2
			parameter1 = 300
			parameter2 = 3
			duration = 90000
			probability1 = 100
			special = 7
		END

CREATE ITM "ja#m22a1"
	WRITE_LONG 0x64 0x72
	SAY NAME1 ~Dread wolf resistances~ SAY NAME2 ~Dread wolf resistances~
	SAY UNIDENTIFIED_DESC ~A dread wolf regenerates like a troll, regaining 3 hp per round after the first combat round.
Only acid, fire, or total dismemberment will inflict permanent damage.
It is immune to charm, hold, and cold-based spells.
Electricity-based spells cause only half damage.~
	WRITE_SHORT 0x1c 10
	WRITE_ASCII 0x3a ~IRING01~ #8
	WRITE_LONG 0x60 1
COPY_EXISTING ~ja#m22a1.itm~ ~override~
	LPF ADD_ITEM_EQEFFECT
		INT_VAR
			opcode = 98
			target = 1
			parameter1 = 2
			parameter2 = 3
			timing = 2
			probability1 = 100
			special = 87
		END
	LPF ADD_ITEM_EQEFFECT
		INT_VAR
			opcode = 232
			target = 1
			parameter1 = 0
			parameter2 = 20
			timing = 2
			probability1 = 100
			special = 12
		STR_VAR
			resource = "TROLLREG"
		END
	LPF coldSpells_immunity END
	LPF charm_immunity END
	LPF hold_immunity END
	LPF sleep_immunity END
	LPF fear_immunity END

ACTION_FOR_EACH ~file~ IN
	BDWOLFDR
	D5WOLFD1
	dw#rewo
	P#WOLF03
	P#WOLF05
	PLYWOLF
	WOLFD1
	WOLFDR
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~P1-10~
			REMOVE_CRE_ITEM ~RING95~
			REMOVE_CRE_ITEM ~TROLLIMM~
			REMOVE_CRE_ITEM ~BDWOLFD1~
			REMOVE_CRE_ITEM ~BDWOLFDR~
			ADD_CRE_ITEM ~MONHP1~ #0 #0 #0 ~UNDROPPABLE~ ~AMULET~ 
			ADD_CRE_ITEM ~TROLLREG~ #0 #0 #0 ~UNDROPPABLE~ ~LRING~ 
			ADD_CRE_ITEM ~ja#m22w1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			LPF clearProficiencies END
			LPF patchCreature
				INT_VAR
					level1=4
					strength=18
					dexterity=13
					constitution=14
					intelligence=9
					wisdom=12
					charisma=8
					movement=15
					hp=20
					ac=6
					resistCold=100
					resistElectricity=50
					thac0=15
					apr=1
					xpv=650
					alignment=35
					saveDeath=13
					saveWand=15
					savePolymorph=14
					saveBreath=16
					saveSpell=16
					morale=18
					moraleBreak=4
					moraleRecovery=15
					general=2
					race=117
					class=148
					gender=1
					sex=1
					enforce=1
			END
			LPF patchCreatureScript STR_VAR script=ja#22 END
		BUT_ONLY_IF_IT_CHANGES
	END
END