CREATE ITM "ja#1m18"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 1
	WRITE_BYTE 0x88 4
	WRITE_BYTE 0x8a 2
	WRITE_SHORT 0x8e 1
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
COPY_EXISTING ~ja#1m18.itm~ ~override~

ACTION_FOR_EACH ~file~ IN
	WOLFCH
	BDWORG
	WORG
	WORGAR
	WORGSU
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~P1-6~
			ADD_CRE_ITEM ~ja#1m18~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			LPF clearProficiencies END
			LPF patchCreature
				INT_VAR
					level1=3
					strength=16
					dexterity=13
					constitution=13
					intelligence=7
					wisdom=11
					charisma=8
					movement=14
					hp=27
					ac=6
					thac0=17
					apr=1
					xpv=120
					alignment=IDS_OF_SYMBOL (~align~ ~NEUTRAL_EVIL~)
					saveDeath=10
					saveWand=14
					savePolymorph=13
					saveBreath=16
					saveSpell=15
					morale=11
					moraleBreak=4
					moraleRecovery=15
					general=IDS_OF_SYMBOL (~general~ ~ANIMAL~)
					race=IDS_OF_SYMBOL (~race~ ~WOLF~)
					class=IDS_OF_SYMBOL (~class~ ~WOLF_WORG~)
					gender=IDS_OF_SYMBOL (~gender~ ~MALE~)
					sex=IDS_OF_SYMBOL (~gender~ ~MALE~)
					enforce=1
			END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~WORGSU~) BEGIN 
			END
		BUT_ONLY_IF_IT_CHANGES
	END ELSE BEGIN
		PRINT ~====> CRE %file% not found!~
	END
END