COMPILE ~%MOD_FOLDER%/lib/pnp-monster/carrion/ja#m9.baf~
COMPILE ~%MOD_FOLDER%/lib/pnp-monster/carrion/ja#m9su.baf~

CREATE ITM "ja#m9w1"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 2
	WRITE_SHORT 0x84 3
	WRITE_BYTE 0x88 2
	WRITE_BYTE 0x8a 1
	WRITE_SHORT 0x8e 1
	WRITE_SHORT 0x9e 34
	WRITE_SHORT 0xa0 33
	WRITE_SHORT 0xa2 33
	WRITE_LONG 0x98 1
COPY_EXISTING ~ja#m9w1.itm~ ~override~
	LPF ADD_EFFECT
		INT_VAR
			opcode = 109
			target = 2
			parameter1 = IDS_OF_SYMBOL (~EA~ ~ANYONE~)
			parameter2 = 2
			duration = 42
			probability1 = 100
			savingthrow = 4
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 142
			target = 2
			parameter1 = 0
			parameter2 = 13
			duration = 42
			probability1 = 100
			savingthrow = 4
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 174
			target = 2
			parameter1 = 0
			parameter2 = 0
			timing = 1
			probability1 = 100
			savingthrow = 4
		STR_VAR
			resource = "EFF_P11"
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 174
			target = 2
			parameter1 = 0
			parameter2 = 0
			timing = 4
			duration = 42
			probability1 = 100
			savingthrow = 4
		STR_VAR
			resource = "EFF_E05"
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 50
			target = 2
			parameter1 = 3757824
			parameter2 = 1638400
			timing = 1
			probability1 = 100
			savingthrow = 4
		END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 141
			target = 2
			parameter1 = 0
			parameter2 = 1
			timing = 1
			probability1 = 100
			savingthrow = 4
		END

ACTION_FOR_EACH ~file~ IN
	BDCCRAW1
	BPCRCW01
	CARRIO
	CRYPTCRA
	BDCRAWMU
	BDMCARRI
	CARRIOSU
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~CARRIO1~
			ADD_CRE_ITEM ~ja#m9w1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			LPF clearProficiencies END
			LPF patchCreature
				INT_VAR
					level1=3
					strength=14
					dexterity=13
					constitution=16
					intelligence=1
					wisdom=12
					charisma=5
					movement=5
					hp=30
					ac=3
					thac0=17
					apr=4
					doubleApr=1
					xpv=420
					alignment=34
					saveDeath=13
					saveWand=15
					savePolymorph=14
					saveBreath=16
					saveSpell=16
					morale=10
					moraleBreak=4
					moraleRecovery=15
					general=255
					race=104
					class=108
					gender=4
					sex=4
					enforce=1
			END
			DEFINE_ARRAY removeScripts BEGIN ccrawler END
			DEFINE_ARRAY skipFiles BEGIN CARRIOSU BDCCRAW1 END
			LPF patchCreatureScript STR_VAR script=ja#m9 skipFiles removeScripts END
			DEFINE_ARRAY removeScripts BEGIN ccrawler END
			DEFINE_ARRAY files BEGIN CARRIOSU END
			LPF patchCreatureScript STR_VAR script=ja#m9su files removeScripts END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~CARRIOSU~) BEGIN 
				LPF patchCreature
					INT_VAR
						hp=30
						thac0=17
						xpv=0
						saveDeath=13
						saveWand=15
						savePolymorph=14
						saveBreath=16
						saveSpell=16
						summon=1
				END
			END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~CRYPTCRA~) BEGIN 
				LPF patchCreature
					INT_VAR
						level1=6
						hp=60
						thac0=9
						xpv=650
						saveDeath=11
						saveWand=13
						savePolymorph=12
						saveBreath=13
						saveSpell=14
				END
			END
		BUT_ONLY_IF_IT_CHANGES
	END
END