export const GLOBAL_CONFIG = {
  files: {
    coreMonsters: "lib/pnp-monster/common/core.tpa",
    spellResources: "lib/common/spell-resources.tpa",
    spellFunctions: "lib/common/spell-functions.tpa",
    immunities: "lib/common/immunities.tpa",
  },
  constitutionAffectHitPoint: true,
  bafConstants: {
    combatStarted: "JA#COMBAT",
    disableSpellcasting: "JA#DISABLE_SPELLCASTING",
    initGlobal: "JA#INIT",
    restTimer: "JA#REST",
    helpTimer: "JA#HELP",
    roundTimer: "JA#ROUND",
    noOpenDoor: "RR#NOPND",
    dialog: "JA#DIALOG",
    monsterShoutId: 99,
    summonerShoutId: 98,
    trackingRange: 150,
    meleeRange: 4,
  },
  tpaConstants: {
    genericScriptsToRemove: [
      "BDANIMN",
      "BDENRAGE",
      "BDENSHTV",
      "BDFIG00",
      "BDGRSHTV",
      "BDNONIN",
      "BDSUM00",
      "BPASIGHT",
      "BPSIGHT",
      "DVMELEE",
      "DW#GPSHM",
      "DW#GPSHT",
      "DW#PRSHT",
      "dw1ranmo",
      "dw1melmo",
      "DW2MP0GE",
      "DW2RC2MO",
      "GENSHT01",
      "HUNTER",
      "initdlg",
      "SHOUT",
      "WTASIGHT",
      "WDASIGHT",
      "wtrunsgt",
    ],
  },
  tokens: {
    target: "{Target}",
  },
};
