export const GLOBAL_CONFIG = {
  files: {
    coreMonsters: "lib/pnp-monster/common/core.tpa",
    spellResources: "lib/common/spell-resources.tpa",
    spellFunctions: "lib/common/spell-functions.tpa",
    immunities: "lib/common/immunities.tpa",
  },
  constitutionAffectHitPoint: true,
  bafConstants: {
    combatStarted: "JA#COMBAT",
    disableSpellcasting: "JA#DISABLE_SPELLCASTING",
    initGlobal: "JA#INIT",
    restTimer: "JA#REST",
    helpTimer: "JA#HELP",
    roundTimer: "JA#ROUND",
    noOpenDoor: "RR#NOPND",
    dialog: "JA#DIALOG",
    monsterShoutId: 99,
    summonerShoutId: 98,
    trackingRange: 150,
    meleeRange: 4,
  },
  tpaConstants: {
    genericScriptsToRemove: [
      "BDANIMN",
      "BDENRAGE",
      "BDENSHTV",
      "BDFIG00",
      "BDFIGH01",
      "BDFIGH42",
      "BDFIGH43",
      "BDFMAG01",
      "BDFMAG23",
      "BDGRSHTV",
      "BDNONIN",
      "BDSHM00",
      // "BDSHOUT",
      "BDSUM00",
      "BPASIGHT",
      "BPSIGHT",
      "DVMELEE",
      "DW#MG29",
      "DW#MG56",
      "DW#MG78",
      "DW#MG84",
      "DW#MG99",
      "DW#MG101",
      "DW#MG102",
      "DW#MG103",
      "DW#MG104",
      "DW#MG105",
      "DW#MG106",
      "DW#MG107",
      "DW#MG108",
      "DW#MG131",
      "DW#MG132",
      "DW#MG137",
      "DW#MG139",
      "DW#GPSHM",
      "DW#GPSHT",
      "dw1melbe",
      "DW1MELGE",
      "DW#PRSHT",
      "DW1RANGE",
      "dw1ranmo",
      "dw1melmo",
      "DW2MP0GE",
      "DW2RC2MO",
      "GENSHT01",
      "HUNTER",
      "initdlg",
      "SHOUT",
      "TUTU_SCR",
      "WTASIGHT",
      "WDASIGHT",
      "wtrunsgt",
    ],
  },
};
