export const SPELLS = {
  // Wizard
  Blur: "SPWI201",
  CharmPerson: "SPWI104",
  Cloudkill: "SPWI502",
  ColorSpray: "SPWI105",
  ConeOfCold: "SPWI503",
  Darkness15Radius: "SPWI228",
  DetectInvisibility: "SPWI203",
  DireCharm: "SPWI316",
  DimensionDoor: "SPWI402",
  Domination: "SPWI506",
  Feeblemind: "SPWI509",
  Fireburst: "SPWI523",
  FleshToStone: "SPWI604",
  Haste: "SPWI305",
  Horror: "SPWI205",
  ImprovedInvisibility: "SPWI405",
  Invisibility: "SPWI206",
  MagicMissiles: "SPWI112",
  MelfAcidArrow: "SPWI211",
  MinorGlobeOfInvulnerability: "SPWI406",
  MirrorImages: "SPWI212",
  PolymorphSelf: "SPWI416",
  PowerWordSleep: "SPWI220",
  ShapeshiftMustardJelly: "SPWI496",
  Sleep: "SPWI116",
  Slow: "SPWI312",
  StinkingCloud: "SPWI213",
  Stoneskin: "SPWI408",
  Web: "SPWI215",
  // Priest
  AnimalSummoning4: "SPPR402",
  Barkskin: "SPPR202",
  Bless: "SPPR101",
  BlindingBeauty: "SPPR704",
  CallLightning: "SPPR302",
  CallWoodlandBeeings: "SPPR410",
  Chant: "SPPR203",
  CharmPersonOrAnimal: "SPPR204",
  CloakOfFear: "SPPR416C",
  Command: "SPPR102",
  CureLightWounds: "SPPR103",
  Entangle: "SPPR105",
  FindTraps: "SPPR205",
  GlyphOfWarding: "SPPR304",
  HoldPerson: "SPPR208",
  HoldPersonOrAnimal: "SPPR305",
  MiscastMagic: "SPPR310",
  ResistFear: "SPPR108",
  RigidThinking: "SPPR311",
  Silence: "SPPR211",
  SummonInsects: "SPPR319",
  // Innates
  MephitColorSpray: "SPIN937",
  SpiderSingleTargetWeb: "BDSPIDGA",
  VortexWeb: "SPIN575",
  // Class
  BerserkerRage: "SPCL321",
  BarbarianRage: "SPCL152",
  OffensiveSpin: "SPCL521",
};

export const ATWEAKS_SPELLS = {
  // CauseDisease: "FL#CSDIS",
  // PitFiendDisease: "RR#DPDIS",
  // GhoulLordDisease: "fl#glor2",
  // MummyDisease: "fl#mum",
  // GreaterMummyDisease: "fl#gmum",
  // ZombieSeaDisease: "fl#zomsd",
  // SporeExplosionDisease: "rr#gassp",
  // BoaliskDisease: "rr#bogaz",
  // Bleeding: "RR#BLEED",
  // Fear1: "fl#cnefr",
  // Fear2: "fl#shafi",
  // Fear3: "fl#tchfr",
  // CauseFear: "rr#dcfea",
  // AuraOfFear1: "rr#dcfa1",
  // AuraOfFear2: "rr#dcfa2",
  // BlastOfFear: "rr#dmfea",
  // CloakOfFear: "rr#scare",
  // SymbolFear: "rr#wi811",
  // Confusion: "RR#WI401",
  // MagicMissile: "RR#WI112",
  // PitFiendFireball: "RR#WI304",
  // BurningHand: "RR#WI103",
  // SunfireBlazingGloryBuckler: "RR#WI523",
  // FireStorm: "RR#PR705",
  // FlameFan: "RR#MFIFF",
  // FlameJet: "RR#MFIFJ",
  // HeatAura: "RR#MFIHA",
  // HeatEmission: "RR#MMAHE",
  // ImixHeatEmission: "rr#eimhe",
  // ImixFireball: "rr#eimfb",
  // ZaamanRulFireball: "rr#ezafb",
  // Burn: "rr#eburn",
  // Engulf: "rr#englf",
  // WallOfFire: "RR#GWOF1",
  // FireBreath: "rr#gfbth",
  // IceStorm: "RR#WI404",
  // ConeOfCold: "RR#WI503",
  // WallOfIce: "rr#icew",
  // Freeze: "rr#efrzn",
  // IceStorn: "rr#ehyis",
  // LightningBolt: "RR#WI308",
  // CureLightWounds: "fl#bp101",
  // TempleMassCure: "RR#PR514",
  // MarilithCauseSeriousWounds: "RR#DCSW",
  // CauseSeriousWounds: "rr#csw",
  // CauseCriticalWounds: "rr#ccw",
  // Harm: "rr#harm",
  // Cloudkill: "RR#WI502",
  // WallOfFog: "RR#MMSWF",
  // FogCloud: "RR#FCLD",
  // ToxicVapors: "RR#FTVAP",
  // OozeStinkingCloud: "RR#MOZSC",
  // SolidFog: "RR#ECHSF",
  // StinkingCloud: "RR#WI213",
  // WebTangle: "rr#spweb",
  // WraithWeb: "rr#spwr2",
  // Web: "rr#wi215",
  // ShamblerEntangle: "RR#SMENT",
  // HamadryadEntangle: "RR#FENTG",
  // Earthquake: "rr#equa",
  // RockToMud: "rr#r2mud",
  // SpeakWithPlants: "rr#fspkp",
  // DimensionDoorInfinite: "rr#ddoor",
  // DimensionDoorPriest: "rr#ddoo2",
  // DryadCharmPerson: "rr#fchrm",
  // AnimalFriendship: "rr#fafrn",
  // DetectSnaresAndPits: "rr#fdsnr",
  // BlindingBeauty: "rr#fbbea",
  // BlindingBeautyTechnical: "rr#fbbe2",
  // ColorSpray: "fl#clrsp",
  // ColorSprayRadiant: "rr#mracs",
  // CharmingSong: "rr#fcsng",
  // CharmingSongTechnical: "rr#fcsn2",
  // TouchOfTranquility: "rr#ftrnq",
};
