export type StringReferenceGroup =
  | "poison"
  | "disease"
  | "bleed"
  | "held"
  | "stun"
  | "levelDrain"
  | "sleep"
  | "charm"
  | "panic"
  | "rigidThinking"
  | "confusion"
  | "petrified"
  | "polymorph"
  | "death";
