COMPILE ~%MOD_FOLDER%/lib/pnp-monster/horror/ja#m15.baf~

CREATE ITM "ja#m15w1"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_LONG 0x18 66
	WRITE_SHORT 0x1c 57
	WRITE_ASCII 0x22 ~S2~ #2
	WRITE_BYTE 0x31 93
	WRITE_LONG 0x60 1
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 2
	WRITE_SHORT 0x84 10
	WRITE_BYTE 0x88 6
	WRITE_BYTE 0x8a 2
	WRITE_SHORT 0x8e 3
	WRITE_SHORT 0x9e 40
	WRITE_SHORT 0xa0 40
	WRITE_SHORT 0xa2 20
	WRITE_LONG 0x98 1
COPY_EXISTING ~ja#m15w1.itm~ ~override~
	LPF ADD_EFFECT
		INT_VAR
			opcode = 12
			target = 2
			parameter2 = 524288
			probability1 = 100
			dicenumber = 1
			dicesize = 6
		END
	LPF ADD_ITEM_EQEFFECT
		INT_VAR
			opcode = 7
			target = 1
			parameter1 = 67
			parameter2 = 21
			timing = 2
			probability1 = 100
		END
	LPF ADD_ITEM_EQEFFECT
		INT_VAR
			opcode = 7
			target = 1
			parameter1 = 67
			parameter2 = 20
			timing = 2
			probability1 = 100
		END
	LPF ADD_ITEM_EQEFFECT
		INT_VAR
			opcode = 7
			target = 1
			parameter1 = 12
			parameter2 = 16
			timing = 2
			probability1 = 100
		END
	LPF ADD_ITEM_EQEFFECT
		INT_VAR
			opcode = 8
			target = 1
			parameter1 = 16384
			parameter2 = 16
			timing = 2
			duration = 3
			probability1 = 100
		END
	LPF ADD_ITEM_EQEFFECT
		INT_VAR
			opcode = 8
			target = 1
			parameter1 = 16384
			parameter2 = 21
			timing = 2
			duration = 3
			probability1 = 100
		END
	LPF ADD_ITEM_EQEFFECT
		INT_VAR
			opcode = 8
			target = 1
			parameter2 = 20
			timing = 2
			duration = 3
			probability1 = 100
		END

CREATE ITM "ja#m15a1"
	WRITE_LONG 0x64 0x72
	WRITE_SHORT 0x1c 2
	WRITE_ASCII 0x22 ~4A~ #2
	WRITE_LONG 0x60 1
COPY_EXISTING ~ja#m15a1.itm~ ~override~
	LPF ADD_ITEM_EQEFFECT
		INT_VAR
			opcode = 7
			target = 1
			parameter1 = 98
			parameter2 = 5
			timing = 2
			probability1 = 100
		END
	LPF ADD_ITEM_EQEFFECT
		INT_VAR
			opcode = 7
			target = 1
			parameter1 = 29
			parameter2 = 4
			timing = 2
			probability1 = 100
		END
	LPF ADD_ITEM_EQEFFECT
		INT_VAR
			opcode = 7
			target = 1
			parameter1 = 87
			timing = 2
			probability1 = 100
		END

COPY_EXISTING ~ja#i1.ITM~  ~override/ja#m15a2.ITM~
	WRITE_SHORT 0x1c 7
	WRITE_ASCII 0x22 ~H5~ #2
	WRITE_LONG 0x60 1
	LPF ADD_ITEM_EQEFFECT
		INT_VAR
			opcode = 7
			target = 1
			parameter1 = 27
			parameter2 = 53
			timing = 2
			probability1 = 100
		END
	LPF ADD_ITEM_EQEFFECT
		INT_VAR
			opcode = 7
			target = 1
			parameter1 = 27
			parameter2 = 52
			timing = 2
			probability1 = 100
		END
	LPF ADD_ITEM_EQEFFECT
		INT_VAR
			opcode = 7
			target = 1
			parameter1 = 27
			parameter2 = 48
			timing = 2
			probability1 = 100
		END

CREATE ITM "ja#m15a3"
	WRITE_LONG 0x64 0x72
	WRITE_SHORT 0x1c 10
	WRITE_ASCII 0x3a ~IRING01~ #8
	WRITE_LONG 0x60 1
COPY_EXISTING ~ja#m15a3.itm~ ~override~
	LPF fireballSpell_immunity END
	LPF lightningBoltSpell_immunity END
	LPF flameArrowSpell_immunity END
	LPF magicMissile_immunity END

ACTION_FOR_EACH ~file~ IN
	HELMHO
	GLOWTEST
	BATTHO
	dw#davho
	DOOMSA
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~HELM08~
			REMOVE_CRE_ITEM ~SHLD18~
			REMOVE_CRE_ITEM ~RING95~
			REMOVE_CRE_ITEM ~BLUN08~
			REMOVE_CRE_ITEM ~FBLADE~
			REMOVE_CRE_ITEM ~PLAT07~
			REMOVE_CRE_ITEM ~HELM13~
			ADD_CRE_ITEM ~ja#m15w1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			ADD_CRE_ITEM ~ja#m15a1~ #0 #0 #0 ~UNDROPPABLE~ ~ARMOR~ 
			ADD_CRE_ITEM ~ja#m15a2~ #0 #0 #0 ~UNDROPPABLE~ ~HELMET~ 
			ADD_CRE_ITEM ~ja#m15a3~ #0 #0 #0 ~UNDROPPABLE~ ~RRING~ 
			ADD_CRE_ITEM ~ja#i3~ #0 #0 #0 ~UNDROPPABLE~ ~BOOTS~ 
			LPF clearProficiencies END
			SET_BG2_PROFICIENCY ~PROFICIENCYTWOHANDEDSWORD~ 2
			LPF seeInvisible_immunity END
			LPF patchCreature
				INT_VAR
					level1=4
					strength=18
					dexterity=13
					constitution=9
					intelligence=14
					wisdom=10
					charisma=10
					movement=10
					hp=52
					ac=2
					thac0=15
					apr=1
					xpv=2000
					alignment=IDS_OF_SYMBOL (~align~ ~NEUTRAL~)
					saveDeath=13
					saveWand=15
					savePolymorph=14
					saveBreath=16
					saveSpell=16
					morale=20
					moraleBreak=4
					moraleRecovery=15
					general=IDS_OF_SYMBOL (~general~ ~MONSTER~)
					race=IDS_OF_SYMBOL (~race~ ~GOLEM~)
					class=IDS_OF_SYMBOL (~class~ ~FIGHTER~)
					gender=IDS_OF_SYMBOL (~gender~ ~NIETHER~)
					sex=IDS_OF_SYMBOL (~gender~ ~NIETHER~)
					animation=IDS_OF_SYMBOL (~animation~ ~FIGHTER_MALE_HUMAN~)
					metalColor=63
					minorColor=63
					majorColor=63
					skinColor=63
					leatherColor=63
					armorColor=63
					hairColor=63
					enforce=1
			END
			DEFINE_ARRAY removeScripts BEGIN dw1melmo END
			LPF patchCreatureScript STR_VAR script=ja#m15 removeScripts END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~BATTHO~) OR ("%SOURCE_RES%" STRING_EQUAL_CASE ~dw#davho~) OR ("%SOURCE_RES%" STRING_EQUAL_CASE ~DOOMSA~) BEGIN 
				LPF patchCreature
					INT_VAR
						level1=8
						level2=3
						strength=20
						hp=84
						thac0=11
						xpv=4000
						alignment=IDS_OF_SYMBOL (~align~ ~LAWFUL_EVIL~)
						saveDeath=10
						saveWand=12
						savePolymorph=11
						saveBreath=12
						saveSpell=13
						class=IDS_OF_SYMBOL (~class~ ~FIGHTER_MAGE~)
				END
				ADD_MEMORIZED_SPELL ~SPWI112~ #0 ~wizard~ (1)
				ADD_MEMORIZED_SPELL ~SPWI402~ #3 ~wizard~ (1)
			END
			PATCH_IF ("%SOURCE_RES%" STRING_EQUAL_CASE ~DOOMSA~) BEGIN 
				ADD_CRE_ITEM ~ja#i4~ #0 #0 #0 ~UNDROPPABLE~ ~LRING~ 
			END
		BUT_ONLY_IF_IT_CHANGES
	END
END