COMPILE ~%MOD_FOLDER%/lib/pnp-monster/horror/ja#m15.baf~

CREATE ITM "ja#m15w1"
	WRITE_LONG 0x64 0x72
	WRITE_SHORT 0x68 1
	WRITE_LONG 0x6a 0xaa
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x18 66
	WRITE_ASCII 0x22 ~S2~ #2
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 2
	WRITE_SHORT 0x84 10
	WRITE_BYTE 0x88 6
	WRITE_BYTE 0x8a 2
	WRITE_SHORT 0x8e 3
	WRITE_SHORT 0x9e 40
	WRITE_SHORT 0xa0 40
	WRITE_SHORT 0xa2 20
	WRITE_LONG 0x60 1
	WRITE_LONG 0x98 1

ACTION_FOR_EACH ~file~ IN
	HELMHO
	GLOWTEST
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~HELM08~
			REMOVE_CRE_ITEM ~SHLD18~
			REMOVE_CRE_ITEM ~RING95~
			REMOVE_CRE_ITEM ~BLUN08~
			ADD_CRE_ITEM ~ja#m15w1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			LPF patchCreature
				INT_VAR
					level1=6
					strength=18
					dexterity=13
					constitution=16
					intelligence=14
					wisdom=10
					charisma=10
					movement=10
					hp=60
					ac=2
					thac0=12
					apr=1
					xpv=2000
					alignment=34
					saveDeath=11
					saveWand=13
					savePolymorph=12
					saveBreath=13
					saveSpell=14
					morale=20
					moraleBreak=4
					moraleRecovery=15
					general=255
					race=144
					class=182
					gender=4
					sex=4
					enforce=1
			END
			LPF patchCreatureScript STR_VAR script=ja#m15 END
		BUT_ONLY_IF_IT_CHANGES
	END
END