COMPILE ~%MOD_FOLDER%/lib/pnp-monster/horror/ja#m15.baf~

CREATE SPL "ja#1m1"
	WRITE_SHORT 0x1c 4
	WRITE_BYTE 0x27 10
	WRITE_LONG 0x34 1
	WRITE_LONG 0x64 0x72
	WRITE_SHORT 0x68 1
	WRITE_LONG 0x6a 0x9a
	INSERT_BYTES 0x72 0x28
	WRITE_SHORT 0x72 1
	WRITE_SHORT 0x74 4
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 5
	WRITE_SHORT 0x82 1
	WRITE_SHORT 0x94 1
	SAY NAME1 @4001 SAY NAME2 @4001
	SAY UNIDENTIFIED_DESC ~The ankheg can secret acidic digestive enzymes to cause an additional 1d4 points of damage per round until the victim is dissolved (truncated to 4 rounds).~
	LPF ADD_EFFECT
		INT_VAR
			opcode = 12
			target = 2
			parameter1 = 0
			parameter2 = 65536
			probability1 = 100
			dicenumber = 1
			dicesize = 4
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 12
			target = 2
			parameter1 = 0
			parameter2 = 65536
			timing = 4
			duration = 6
			probability1 = 100
			dicenumber = 1
			dicesize = 4
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 12
			target = 2
			parameter1 = 0
			parameter2 = 65536
			timing = 4
			duration = 12
			probability1 = 100
			dicenumber = 1
			dicesize = 4
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 12
			target = 2
			parameter1 = 0
			parameter2 = 65536
			timing = 4
			duration = 18
			probability1 = 100
			dicenumber = 1
			dicesize = 4
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 142
			target = 2
			parameter1 = 0
			parameter2 = 102
			duration = 24
			probability1 = 100
	END
	LPF ADD_EFFECT
		INT_VAR
			opcode = 206
			target = 2
			parameter1 = 0
			parameter2 = 0
			duration = 24
			probability1 = 100
		STR_VAR
			resource = "ja#1m1"
	END

CREATE SPL "ja#2m1"
	WRITE_SHORT 0x1c 4
	WRITE_BYTE 0x27 10
	WRITE_LONG 0x34 1
	WRITE_LONG 0x64 0x72
	WRITE_SHORT 0x68 1
	WRITE_LONG 0x6a 0x9a
	INSERT_BYTES 0x72 0x28
	WRITE_SHORT 0x72 2
	WRITE_SHORT 0x74 4
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 30
	WRITE_SHORT 0x82 1
	WRITE_SHORT 0x84 3
	WRITE_SHORT 0x94 1
	SAY NAME1 @4000 SAY NAME2 @4000
	SAY UNIDENTIFIED_DESC ~The ankheg can squirt a stream of acidic enzymes once every six hours to a distance of 30 feet. A victim struck by the stream of acidic enzymes suffers 8d4 points of damage (half damage if the victim rolls a successful saving throw vs. poison). It uses this attack technique only when desperate.~
	WRITE_SHORT 0x98 (IDS_OF_SYMBOL (~projectl~ ~acidblob~)) + 1
	LPF ADD_EFFECT
		INT_VAR
			opcode = 12
			target = 2
			parameter1 = 0
			parameter2 = 65536
			probability1 = 100
			dicenumber = 8
			dicesize = 4
			savingthrow = 4
			special = 256
	END

CREATE ITM "ja#m15w1"
	WRITE_LONG 0x64 0x72
	WRITE_SHORT 0x68 1
	WRITE_LONG 0x6a 0xaa
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x18 66
	WRITE_ASCII 0x22 ~S2~ #2
	WRITE_SHORT 0x74 1
	WRITE_BYTE 0x7e 1
	WRITE_SHORT 0x80 2
	WRITE_SHORT 0x84 10
	WRITE_BYTE 0x88 6
	WRITE_BYTE 0x8a 2
	WRITE_SHORT 0x8e 3
	WRITE_SHORT 0x9e 40
	WRITE_SHORT 0xa0 40
	WRITE_SHORT 0xa2 20
	WRITE_LONG 0x60 1
	WRITE_LONG 0x98 1

ACTION_FOR_EACH ~file~ IN
	HELMHO
	GLOWTEST
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.cre~ BEGIN
		COPY_EXISTING ~%file%.cre~ ~override~
			LPF FJ_CRE_VALIDITY END
			REMOVE_KNOWN_SPELLS
			REMOVE_MEMORIZED_SPELLS
			REMOVE_CRE_ITEM ~HELM08~
			REMOVE_CRE_ITEM ~SHLD18~
			REMOVE_CRE_ITEM ~RING95~
			REMOVE_CRE_ITEM ~BLUN08~
			ADD_CRE_ITEM ~ja#m15w1~ #0 #0 #0 ~UNDROPPABLE~ ~WEAPON1~ EQUIP
			ADD_MEMORIZED_SPELL ~ja#1m1~ #0 ~innate~ (1)
			ADD_MEMORIZED_SPELL ~ja#2m1~ #0 ~innate~ (1)
			LPF patchCreature
				INT_VAR
					level1=6
					strength=18
					dexterity=13
					constitution=16
					intelligence=14
					wisdom=10
					charisma=10
					movement=10
					hp=60
					ac=2
					thac0=12
					apr=1
					xpv=2000
					alignment=34
					saveDeath=11
					saveWand=13
					savePolymorph=12
					saveBreath=13
					saveSpell=14
					morale=20
					moraleBreak=4
					moraleRecovery=15
					general=255
					race=144
					class=182
					gender=4
					sex=4
					enforce=1
			END
			LPF patchCreatureScript STR_VAR script=ja#m15 END
		BUT_ONLY_IF_IT_CHANGES
	END
END