IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_CHAOS)  // SPPR709.SPL (Chaos)
  !StateCheck(SixthNearest([PC]),STATE_INVISIBLE)
  !CheckStatGT(SixthNearest([PC]),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(SixthNearest([PC]),DO_NOT_TARGET_SPELLS)
  See(SixthNearest([PC]))
  !StateCheck(SixthNearest([PC]),STATE_DISABLED)
  OR(3)
      TriggerOverride(SixthNearest([PC]),Range(NearestAllyOf(Myself),15))
      NumInParty(1)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  OR(2)
      !TriggerOverride(SixthNearest([PC]),StateCheck(NearestAllyOf(Myself),STATE_DISABLED))
      !TriggerOverride(SixthNearest([PC]),StateCheck(SecondNearestAllyOf(Myself),STATE_DISABLED))
  OR(2)
      !TriggerOverride(SixthNearest([PC]),StateCheck(NearestAllyOf(Myself),STATE_DISABLED))
      TriggerOverride(SixthNearest([PC]),Range(SecondNearestAllyOf(Myself),15))
  !StateCheck(SixthNearest([PC]),STATE_CONFUSED)
  !CheckSpellState(SixthNearest([PC]),CHAOTIC_COMMANDS)
  !General(SixthNearest([PC]),UNDEAD)
  !CheckSpellState(SixthNearest([PC]),EXALTATION)
  OR(2)
      !CheckSpellState(SixthNearest([PC]),CONFUSION_IMMUNITY_SEEN)
      !CheckSpellState(SixthNearest([PC]),CONFUSION_IMMUNITY)
  OR(2)
      !CheckStatGT(SixthNearest([PC]),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance(SixthNearest([PC]),ENEMY)
  !Class(SixthNearest([PC]),SKELETON_WARRIOR)
  CheckStatGT(SixthNearest([PC]),0,SAVEVSSPELL)
THEN
  RESPONSE #200
      ApplySpellRES("dw#mgsee",Myself)  // Armor
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(SixthNearest([PC]),CLERIC_CHAOS)  // SPPR709.SPL (Chaos)
  RESPONSE #100
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_CHAOS)  // SPPR709.SPL (Chaos)
  !StateCheck(FifthNearest([PC]),STATE_INVISIBLE)
  !CheckStatGT(FifthNearest([PC]),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(FifthNearest([PC]),DO_NOT_TARGET_SPELLS)
  See(FifthNearest([PC]))
  !StateCheck(FifthNearest([PC]),STATE_DISABLED)
  OR(3)
      TriggerOverride(FifthNearest([PC]),Range(NearestAllyOf(Myself),15))
      NumInParty(1)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  OR(2)
      !TriggerOverride(FifthNearest([PC]),StateCheck(NearestAllyOf(Myself),STATE_DISABLED))
      !TriggerOverride(FifthNearest([PC]),StateCheck(SecondNearestAllyOf(Myself),STATE_DISABLED))
  OR(2)
      !TriggerOverride(FifthNearest([PC]),StateCheck(NearestAllyOf(Myself),STATE_DISABLED))
      TriggerOverride(FifthNearest([PC]),Range(SecondNearestAllyOf(Myself),15))
  !StateCheck(FifthNearest([PC]),STATE_CONFUSED)
  !CheckSpellState(FifthNearest([PC]),CHAOTIC_COMMANDS)
  !General(FifthNearest([PC]),UNDEAD)
  !CheckSpellState(FifthNearest([PC]),EXALTATION)
  OR(2)
      !CheckSpellState(FifthNearest([PC]),CONFUSION_IMMUNITY_SEEN)
      !CheckSpellState(FifthNearest([PC]),CONFUSION_IMMUNITY)
  OR(2)
      !CheckStatGT(FifthNearest([PC]),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance(FifthNearest([PC]),ENEMY)
  !Class(FifthNearest([PC]),SKELETON_WARRIOR)
  CheckStatGT(FifthNearest([PC]),0,SAVEVSSPELL)
THEN
  RESPONSE #200
      ApplySpellRES("dw#mgsee",Myself)  // Armor
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(FifthNearest([PC]),CLERIC_CHAOS)  // SPPR709.SPL (Chaos)
  RESPONSE #100
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_CHAOS)  // SPPR709.SPL (Chaos)
  !StateCheck(FourthNearest([PC]),STATE_INVISIBLE)
  !CheckStatGT(FourthNearest([PC]),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(FourthNearest([PC]),DO_NOT_TARGET_SPELLS)
  See(FourthNearest([PC]))
  !StateCheck(FourthNearest([PC]),STATE_DISABLED)
  OR(3)
      TriggerOverride(FourthNearest([PC]),Range(NearestAllyOf(Myself),15))
      NumInParty(1)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  OR(2)
      !TriggerOverride(FourthNearest([PC]),StateCheck(NearestAllyOf(Myself),STATE_DISABLED))
      !TriggerOverride(FourthNearest([PC]),StateCheck(SecondNearestAllyOf(Myself),STATE_DISABLED))
  OR(2)
      !TriggerOverride(FourthNearest([PC]),StateCheck(NearestAllyOf(Myself),STATE_DISABLED))
      TriggerOverride(FourthNearest([PC]),Range(SecondNearestAllyOf(Myself),15))
  !StateCheck(FourthNearest([PC]),STATE_CONFUSED)
  !CheckSpellState(FourthNearest([PC]),CHAOTIC_COMMANDS)
  !General(FourthNearest([PC]),UNDEAD)
  !CheckSpellState(FourthNearest([PC]),EXALTATION)
  OR(2)
      !CheckSpellState(FourthNearest([PC]),CONFUSION_IMMUNITY_SEEN)
      !CheckSpellState(FourthNearest([PC]),CONFUSION_IMMUNITY)
  OR(2)
      !CheckStatGT(FourthNearest([PC]),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance(FourthNearest([PC]),ENEMY)
  !Class(FourthNearest([PC]),SKELETON_WARRIOR)
  CheckStatGT(FourthNearest([PC]),0,SAVEVSSPELL)
THEN
  RESPONSE #200
      ApplySpellRES("dw#mgsee",Myself)  // Armor
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(FourthNearest([PC]),CLERIC_CHAOS)  // SPPR709.SPL (Chaos)
  RESPONSE #100
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_CHAOS)  // SPPR709.SPL (Chaos)
  !StateCheck(ThirdNearest([PC]),STATE_INVISIBLE)
  !CheckStatGT(ThirdNearest([PC]),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(ThirdNearest([PC]),DO_NOT_TARGET_SPELLS)
  See(ThirdNearest([PC]))
  !StateCheck(ThirdNearest([PC]),STATE_DISABLED)
  OR(3)
      TriggerOverride(ThirdNearest([PC]),Range(NearestAllyOf(Myself),15))
      NumInParty(1)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  OR(2)
      !TriggerOverride(ThirdNearest([PC]),StateCheck(NearestAllyOf(Myself),STATE_DISABLED))
      !TriggerOverride(ThirdNearest([PC]),StateCheck(SecondNearestAllyOf(Myself),STATE_DISABLED))
  OR(2)
      !TriggerOverride(ThirdNearest([PC]),StateCheck(NearestAllyOf(Myself),STATE_DISABLED))
      TriggerOverride(ThirdNearest([PC]),Range(SecondNearestAllyOf(Myself),15))
  !StateCheck(ThirdNearest([PC]),STATE_CONFUSED)
  !CheckSpellState(ThirdNearest([PC]),CHAOTIC_COMMANDS)
  !General(ThirdNearest([PC]),UNDEAD)
  !CheckSpellState(ThirdNearest([PC]),EXALTATION)
  OR(2)
      !CheckSpellState(ThirdNearest([PC]),CONFUSION_IMMUNITY_SEEN)
      !CheckSpellState(ThirdNearest([PC]),CONFUSION_IMMUNITY)
  OR(2)
      !CheckStatGT(ThirdNearest([PC]),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance(ThirdNearest([PC]),ENEMY)
  !Class(ThirdNearest([PC]),SKELETON_WARRIOR)
  CheckStatGT(ThirdNearest([PC]),0,SAVEVSSPELL)
THEN
  RESPONSE #200
      ApplySpellRES("dw#mgsee",Myself)  // Armor
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(ThirdNearest([PC]),CLERIC_CHAOS)  // SPPR709.SPL (Chaos)
  RESPONSE #100
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_CHAOS)  // SPPR709.SPL (Chaos)
  !StateCheck(SecondNearest([PC]),STATE_INVISIBLE)
  !CheckStatGT(SecondNearest([PC]),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(SecondNearest([PC]),DO_NOT_TARGET_SPELLS)
  See(SecondNearest([PC]))
  !StateCheck(SecondNearest([PC]),STATE_DISABLED)
  OR(3)
      TriggerOverride(SecondNearest([PC]),Range(NearestAllyOf(Myself),15))
      NumInParty(1)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  OR(2)
      !TriggerOverride(SecondNearest([PC]),StateCheck(NearestAllyOf(Myself),STATE_DISABLED))
      !TriggerOverride(SecondNearest([PC]),StateCheck(SecondNearestAllyOf(Myself),STATE_DISABLED))
  OR(2)
      !TriggerOverride(SecondNearest([PC]),StateCheck(NearestAllyOf(Myself),STATE_DISABLED))
      TriggerOverride(SecondNearest([PC]),Range(SecondNearestAllyOf(Myself),15))
  !StateCheck(SecondNearest([PC]),STATE_CONFUSED)
  !CheckSpellState(SecondNearest([PC]),CHAOTIC_COMMANDS)
  !General(SecondNearest([PC]),UNDEAD)
  !CheckSpellState(SecondNearest([PC]),EXALTATION)
  OR(2)
      !CheckSpellState(SecondNearest([PC]),CONFUSION_IMMUNITY_SEEN)
      !CheckSpellState(SecondNearest([PC]),CONFUSION_IMMUNITY)
  OR(2)
      !CheckStatGT(SecondNearest([PC]),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance(SecondNearest([PC]),ENEMY)
  !Class(SecondNearest([PC]),SKELETON_WARRIOR)
  CheckStatGT(SecondNearest([PC]),0,SAVEVSSPELL)
THEN
  RESPONSE #200
      ApplySpellRES("dw#mgsee",Myself)  // Armor
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(SecondNearest([PC]),CLERIC_CHAOS)  // SPPR709.SPL (Chaos)
  RESPONSE #100
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_CHAOS)  // SPPR709.SPL (Chaos)
  !StateCheck([PC],STATE_INVISIBLE)
  !CheckStatGT([PC],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC],DO_NOT_TARGET_SPELLS)
  See([PC])
  !StateCheck([PC],STATE_DISABLED)
  OR(3)
      TriggerOverride([PC],Range(NearestAllyOf(Myself),15))
      NumInParty(1)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  OR(2)
      !TriggerOverride([PC],StateCheck(NearestAllyOf(Myself),STATE_DISABLED))
      !TriggerOverride([PC],StateCheck(SecondNearestAllyOf(Myself),STATE_DISABLED))
  OR(2)
      !TriggerOverride([PC],StateCheck(NearestAllyOf(Myself),STATE_DISABLED))
      TriggerOverride([PC],Range(SecondNearestAllyOf(Myself),15))
  !StateCheck([PC],STATE_CONFUSED)
  !CheckSpellState([PC],CHAOTIC_COMMANDS)
  !General([PC],UNDEAD)
  !CheckSpellState([PC],EXALTATION)
  OR(2)
      !CheckSpellState([PC],CONFUSION_IMMUNITY_SEEN)
      !CheckSpellState([PC],CONFUSION_IMMUNITY)
  OR(2)
      !CheckStatGT([PC],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance([PC],ENEMY)
  !Class([PC],SKELETON_WARRIOR)
  CheckStatGT([PC],0,SAVEVSSPELL)
THEN
  RESPONSE #200
      ApplySpellRES("dw#mgsee",Myself)  // Armor
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell([PC],CLERIC_CHAOS)  // SPPR709.SPL (Chaos)
  RESPONSE #100
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_CHAOS)  // SPPR709.SPL (Chaos)
  !StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(NearestEnemyOf(Myself),DO_NOT_TARGET_SPELLS)
  See(NearestEnemyOf(Myself))
  ActionListEmpty()
  !Allegiance(Myself,ENEMY)
  !StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
  OR(3)
      TriggerOverride(NearestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
      NumInParty(1)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  OR(2)
      !TriggerOverride(NearestEnemyOf(Myself),StateCheck(NearestAllyOf(Myself),STATE_DISABLED))
      !TriggerOverride(NearestEnemyOf(Myself),StateCheck(SecondNearestAllyOf(Myself),STATE_DISABLED))
  OR(2)
      !TriggerOverride(NearestEnemyOf(Myself),StateCheck(NearestAllyOf(Myself),STATE_DISABLED))
      TriggerOverride(NearestEnemyOf(Myself),Range(SecondNearestAllyOf(Myself),15))
  !StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
  !CheckSpellState(NearestEnemyOf(Myself),CHAOTIC_COMMANDS)
  !General(NearestEnemyOf(Myself),UNDEAD)
  !CheckSpellState(NearestEnemyOf(Myself),EXALTATION)
  OR(2)
      !CheckSpellState(NearestEnemyOf(Myself),CONFUSION_IMMUNITY_SEEN)
      !CheckSpellState(NearestEnemyOf(Myself),CONFUSION_IMMUNITY)
  OR(2)
      !CheckStatGT(NearestEnemyOf(Myself),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !Class(NearestEnemyOf(Myself),SKELETON_WARRIOR)
  CheckStatGT(NearestEnemyOf(Myself),0,SAVEVSSPELL)
THEN
  RESPONSE #200
      ApplySpellRES("dw#mgsee",Myself)  // Armor
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(NearestEnemyOf(Myself),CLERIC_CHAOS)  // SPPR709.SPL (Chaos)
  RESPONSE #100
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_CHAOS)  // SPPR709.SPL (Chaos)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_INVISIBLE)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(SecondNearestEnemyOf(Myself),DO_NOT_TARGET_SPELLS)
  See(SecondNearestEnemyOf(Myself))
  ActionListEmpty()
  !Allegiance(Myself,ENEMY)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
  OR(3)
      TriggerOverride(SecondNearestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
      NumInParty(1)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  OR(2)
      !TriggerOverride(SecondNearestEnemyOf(Myself),StateCheck(NearestAllyOf(Myself),STATE_DISABLED))
      !TriggerOverride(SecondNearestEnemyOf(Myself),StateCheck(SecondNearestAllyOf(Myself),STATE_DISABLED))
  OR(2)
      !TriggerOverride(SecondNearestEnemyOf(Myself),StateCheck(NearestAllyOf(Myself),STATE_DISABLED))
      TriggerOverride(SecondNearestEnemyOf(Myself),Range(SecondNearestAllyOf(Myself),15))
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
  !CheckSpellState(SecondNearestEnemyOf(Myself),CHAOTIC_COMMANDS)
  !General(SecondNearestEnemyOf(Myself),UNDEAD)
  !CheckSpellState(SecondNearestEnemyOf(Myself),EXALTATION)
  OR(2)
      !CheckSpellState(SecondNearestEnemyOf(Myself),CONFUSION_IMMUNITY_SEEN)
      !CheckSpellState(SecondNearestEnemyOf(Myself),CONFUSION_IMMUNITY)
  OR(2)
      !CheckStatGT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !Class(SecondNearestEnemyOf(Myself),SKELETON_WARRIOR)
  CheckStatGT(SecondNearestEnemyOf(Myself),0,SAVEVSSPELL)
THEN
  RESPONSE #200
      ApplySpellRES("dw#mgsee",Myself)  // Armor
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(SecondNearestEnemyOf(Myself),CLERIC_CHAOS)  // SPPR709.SPL (Chaos)
  RESPONSE #100
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_CHAOS)  // SPPR709.SPL (Chaos)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_INVISIBLE)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),DO_NOT_TARGET_SPELLS)
  See(ThirdNearestEnemyOf(Myself))
  ActionListEmpty()
  !Allegiance(Myself,ENEMY)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
  OR(3)
      TriggerOverride(ThirdNearestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
      NumInParty(1)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  OR(2)
      !TriggerOverride(ThirdNearestEnemyOf(Myself),StateCheck(NearestAllyOf(Myself),STATE_DISABLED))
      !TriggerOverride(ThirdNearestEnemyOf(Myself),StateCheck(SecondNearestAllyOf(Myself),STATE_DISABLED))
  OR(2)
      !TriggerOverride(ThirdNearestEnemyOf(Myself),StateCheck(NearestAllyOf(Myself),STATE_DISABLED))
      TriggerOverride(ThirdNearestEnemyOf(Myself),Range(SecondNearestAllyOf(Myself),15))
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),CHAOTIC_COMMANDS)
  !General(ThirdNearestEnemyOf(Myself),UNDEAD)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),EXALTATION)
  OR(2)
      !CheckSpellState(ThirdNearestEnemyOf(Myself),CONFUSION_IMMUNITY_SEEN)
      !CheckSpellState(ThirdNearestEnemyOf(Myself),CONFUSION_IMMUNITY)
  OR(2)
      !CheckStatGT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !Class(ThirdNearestEnemyOf(Myself),SKELETON_WARRIOR)
  CheckStatGT(ThirdNearestEnemyOf(Myself),0,SAVEVSSPELL)
THEN
  RESPONSE #200
      ApplySpellRES("dw#mgsee",Myself)  // Armor
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(ThirdNearestEnemyOf(Myself),CLERIC_CHAOS)  // SPPR709.SPL (Chaos)
  RESPONSE #100
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
  !StateCheck([PC.0.0.FIGHTER],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC.0.0.FIGHTER],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC.0.0.FIGHTER],DO_NOT_TARGET_SPELLS)
  See([PC.0.0.FIGHTER])
  !StateCheck([PC.0.0.FIGHTER],STATE_DISABLED)
  !CheckStatGT([PC.0.0.FIGHTER],0,HELD)
  !Kit([PC.0.0.FIGHTER],CAVALIER)
  !Kit([PC.0.0.FIGHTER],INQUISITOR)
  !Race([PC.0.0.FIGHTER],ELF)
  !CheckSpellState([PC.0.0.FIGHTER],CHAOTIC_COMMANDS)
  !General([PC.0.0.FIGHTER],UNDEAD)
  !CheckSpellState([PC.0.0.FIGHTER],ALLIED_AND_SAME_ALIGNMENT_RIGHTEOUS_WRATH_OF_THE_FAITHFUL)
  OR(2)
      !CheckSpellState([PC.0.0.FIGHTER],CHARM_IMMUNITY_SEEN)
      !CheckSpellState([PC.0.0.FIGHTER],CHARM_IMMUNITY)
  !CheckStatGT([PC.0.0.FIGHTER],0,MINORGLOBE)
  OR(2)
      !CheckStatGT([PC.0.0.FIGHTER],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.FIGHTER],ENEMY)
  CheckStatGT([PC.0.0.FIGHTER],4,SAVEVSSPELL)
THEN
  RESPONSE #50
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell([PC.0.0.FIGHTER],CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
  RESPONSE #50
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
  !StateCheck([PC.0.0.RANGER],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC.0.0.RANGER],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC.0.0.RANGER],DO_NOT_TARGET_SPELLS)
  See([PC.0.0.RANGER])
  !StateCheck([PC.0.0.RANGER],STATE_DISABLED)
  !CheckStatGT([PC.0.0.RANGER],0,HELD)
  !Kit([PC.0.0.RANGER],CAVALIER)
  !Kit([PC.0.0.RANGER],INQUISITOR)
  !Race([PC.0.0.RANGER],ELF)
  !CheckSpellState([PC.0.0.RANGER],CHAOTIC_COMMANDS)
  !General([PC.0.0.RANGER],UNDEAD)
  !CheckSpellState([PC.0.0.RANGER],ALLIED_AND_SAME_ALIGNMENT_RIGHTEOUS_WRATH_OF_THE_FAITHFUL)
  OR(2)
      !CheckSpellState([PC.0.0.RANGER],CHARM_IMMUNITY_SEEN)
      !CheckSpellState([PC.0.0.RANGER],CHARM_IMMUNITY)
  !CheckStatGT([PC.0.0.RANGER],0,MINORGLOBE)
  OR(2)
      !CheckStatGT([PC.0.0.RANGER],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.RANGER],ENEMY)
  CheckStatGT([PC.0.0.RANGER],4,SAVEVSSPELL)
THEN
  RESPONSE #50
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell([PC.0.0.RANGER],CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
  RESPONSE #50
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
  !StateCheck([PC.0.0.PALADIN],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC.0.0.PALADIN],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC.0.0.PALADIN],DO_NOT_TARGET_SPELLS)
  See([PC.0.0.PALADIN])
  !StateCheck([PC.0.0.PALADIN],STATE_DISABLED)
  !CheckStatGT([PC.0.0.PALADIN],0,HELD)
  !Kit([PC.0.0.PALADIN],CAVALIER)
  !Kit([PC.0.0.PALADIN],INQUISITOR)
  !Race([PC.0.0.PALADIN],ELF)
  !CheckSpellState([PC.0.0.PALADIN],CHAOTIC_COMMANDS)
  !General([PC.0.0.PALADIN],UNDEAD)
  !CheckSpellState([PC.0.0.PALADIN],ALLIED_AND_SAME_ALIGNMENT_RIGHTEOUS_WRATH_OF_THE_FAITHFUL)
  OR(2)
      !CheckSpellState([PC.0.0.PALADIN],CHARM_IMMUNITY_SEEN)
      !CheckSpellState([PC.0.0.PALADIN],CHARM_IMMUNITY)
  !CheckStatGT([PC.0.0.PALADIN],0,MINORGLOBE)
  OR(2)
      !CheckStatGT([PC.0.0.PALADIN],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.PALADIN],ENEMY)
  CheckStatGT([PC.0.0.PALADIN],4,SAVEVSSPELL)
THEN
  RESPONSE #50
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell([PC.0.0.PALADIN],CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
  RESPONSE #50
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
  !StateCheck([PC.0.0.FIGHTER_THIEF],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC.0.0.FIGHTER_THIEF],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC.0.0.FIGHTER_THIEF],DO_NOT_TARGET_SPELLS)
  See([PC.0.0.FIGHTER_THIEF])
  !StateCheck([PC.0.0.FIGHTER_THIEF],STATE_DISABLED)
  !CheckStatGT([PC.0.0.FIGHTER_THIEF],0,HELD)
  !Kit([PC.0.0.FIGHTER_THIEF],CAVALIER)
  !Kit([PC.0.0.FIGHTER_THIEF],INQUISITOR)
  !Race([PC.0.0.FIGHTER_THIEF],ELF)
  !CheckSpellState([PC.0.0.FIGHTER_THIEF],CHAOTIC_COMMANDS)
  !General([PC.0.0.FIGHTER_THIEF],UNDEAD)
  !CheckSpellState([PC.0.0.FIGHTER_THIEF],ALLIED_AND_SAME_ALIGNMENT_RIGHTEOUS_WRATH_OF_THE_FAITHFUL)
  OR(2)
      !CheckSpellState([PC.0.0.FIGHTER_THIEF],CHARM_IMMUNITY_SEEN)
      !CheckSpellState([PC.0.0.FIGHTER_THIEF],CHARM_IMMUNITY)
  !CheckStatGT([PC.0.0.FIGHTER_THIEF],0,MINORGLOBE)
  OR(2)
      !CheckStatGT([PC.0.0.FIGHTER_THIEF],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.FIGHTER_THIEF],ENEMY)
  CheckStatGT([PC.0.0.FIGHTER_THIEF],4,SAVEVSSPELL)
THEN
  RESPONSE #50
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell([PC.0.0.FIGHTER_THIEF],CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
  RESPONSE #50
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
  !StateCheck([PC.0.0.BARD],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC.0.0.BARD],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC.0.0.BARD],DO_NOT_TARGET_SPELLS)
  See([PC.0.0.BARD])
  !StateCheck([PC.0.0.BARD],STATE_DISABLED)
  !CheckStatGT([PC.0.0.BARD],0,HELD)
  !Kit([PC.0.0.BARD],CAVALIER)
  !Kit([PC.0.0.BARD],INQUISITOR)
  !Race([PC.0.0.BARD],ELF)
  !CheckSpellState([PC.0.0.BARD],CHAOTIC_COMMANDS)
  !General([PC.0.0.BARD],UNDEAD)
  !CheckSpellState([PC.0.0.BARD],ALLIED_AND_SAME_ALIGNMENT_RIGHTEOUS_WRATH_OF_THE_FAITHFUL)
  OR(2)
      !CheckSpellState([PC.0.0.BARD],CHARM_IMMUNITY_SEEN)
      !CheckSpellState([PC.0.0.BARD],CHARM_IMMUNITY)
  !CheckStatGT([PC.0.0.BARD],0,MINORGLOBE)
  OR(2)
      !CheckStatGT([PC.0.0.BARD],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.BARD],ENEMY)
  CheckStatGT([PC.0.0.BARD],4,SAVEVSSPELL)
THEN
  RESPONSE #50
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell([PC.0.0.BARD],CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
  RESPONSE #50
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
  !StateCheck([PC.0.0.THIEF],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC.0.0.THIEF],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC.0.0.THIEF],DO_NOT_TARGET_SPELLS)
  See([PC.0.0.THIEF])
  !StateCheck([PC.0.0.THIEF],STATE_DISABLED)
  !CheckStatGT([PC.0.0.THIEF],0,HELD)
  !Kit([PC.0.0.THIEF],CAVALIER)
  !Kit([PC.0.0.THIEF],INQUISITOR)
  !Race([PC.0.0.THIEF],ELF)
  !CheckSpellState([PC.0.0.THIEF],CHAOTIC_COMMANDS)
  !General([PC.0.0.THIEF],UNDEAD)
  !CheckSpellState([PC.0.0.THIEF],ALLIED_AND_SAME_ALIGNMENT_RIGHTEOUS_WRATH_OF_THE_FAITHFUL)
  OR(2)
      !CheckSpellState([PC.0.0.THIEF],CHARM_IMMUNITY_SEEN)
      !CheckSpellState([PC.0.0.THIEF],CHARM_IMMUNITY)
  !CheckStatGT([PC.0.0.THIEF],0,MINORGLOBE)
  OR(2)
      !CheckStatGT([PC.0.0.THIEF],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.THIEF],ENEMY)
  CheckStatGT([PC.0.0.THIEF],4,SAVEVSSPELL)
THEN
  RESPONSE #50
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell([PC.0.0.THIEF],CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
  RESPONSE #50
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
  !StateCheck([PC],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC],DO_NOT_TARGET_SPELLS)
  See([PC])
  !StateCheck([PC],STATE_DISABLED)
  !CheckStatGT([PC],0,HELD)
  !Kit([PC],CAVALIER)
  !Kit([PC],INQUISITOR)
  !Race([PC],ELF)
  !CheckSpellState([PC],CHAOTIC_COMMANDS)
  !General([PC],UNDEAD)
  !CheckSpellState([PC],ALLIED_AND_SAME_ALIGNMENT_RIGHTEOUS_WRATH_OF_THE_FAITHFUL)
  OR(2)
      !CheckSpellState([PC],CHARM_IMMUNITY_SEEN)
      !CheckSpellState([PC],CHARM_IMMUNITY)
  !CheckStatGT([PC],0,MINORGLOBE)
  OR(2)
      !CheckStatGT([PC],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance([PC],ENEMY)
  CheckStatGT([PC],4,SAVEVSSPELL)
THEN
  RESPONSE #50
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell([PC],CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
  RESPONSE #50
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
  !StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
  !CheckStatGT(SecondNearest([PC]),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(SecondNearest([PC]),DO_NOT_TARGET_SPELLS)
  See(SecondNearest([PC]))
  !StateCheck(SecondNearest([PC]),STATE_DISABLED)
  !CheckStatGT(SecondNearest([PC]),0,HELD)
  !Kit(SecondNearest([PC]),CAVALIER)
  !Kit(SecondNearest([PC]),INQUISITOR)
  !Race(SecondNearest([PC]),ELF)
  !CheckSpellState(SecondNearest([PC]),CHAOTIC_COMMANDS)
  !General(SecondNearest([PC]),UNDEAD)
  !CheckSpellState(SecondNearest([PC]),ALLIED_AND_SAME_ALIGNMENT_RIGHTEOUS_WRATH_OF_THE_FAITHFUL)
  OR(2)
      !CheckSpellState(SecondNearest([PC]),CHARM_IMMUNITY_SEEN)
      !CheckSpellState(SecondNearest([PC]),CHARM_IMMUNITY)
  !CheckStatGT(SecondNearest([PC]),0,MINORGLOBE)
  OR(2)
      !CheckStatGT(SecondNearest([PC]),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance(SecondNearest([PC]),ENEMY)
  CheckStatGT(SecondNearest([PC]),4,SAVEVSSPELL)
THEN
  RESPONSE #50
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(SecondNearest([PC]),CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
  RESPONSE #50
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
  !StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
  !CheckStatGT(ThirdNearest([PC]),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(ThirdNearest([PC]),DO_NOT_TARGET_SPELLS)
  See(ThirdNearest([PC]))
  !StateCheck(ThirdNearest([PC]),STATE_DISABLED)
  !CheckStatGT(ThirdNearest([PC]),0,HELD)
  !Kit(ThirdNearest([PC]),CAVALIER)
  !Kit(ThirdNearest([PC]),INQUISITOR)
  !Race(ThirdNearest([PC]),ELF)
  !CheckSpellState(ThirdNearest([PC]),CHAOTIC_COMMANDS)
  !General(ThirdNearest([PC]),UNDEAD)
  !CheckSpellState(ThirdNearest([PC]),ALLIED_AND_SAME_ALIGNMENT_RIGHTEOUS_WRATH_OF_THE_FAITHFUL)
  OR(2)
      !CheckSpellState(ThirdNearest([PC]),CHARM_IMMUNITY_SEEN)
      !CheckSpellState(ThirdNearest([PC]),CHARM_IMMUNITY)
  !CheckStatGT(ThirdNearest([PC]),0,MINORGLOBE)
  OR(2)
      !CheckStatGT(ThirdNearest([PC]),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance(ThirdNearest([PC]),ENEMY)
  CheckStatGT(ThirdNearest([PC]),4,SAVEVSSPELL)
THEN
  RESPONSE #50
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(ThirdNearest([PC]),CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
  RESPONSE #50
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(NearestEnemyOf(Myself),DO_NOT_TARGET_SPELLS)
  See(NearestEnemyOf(Myself))
  ActionListEmpty()
  !Allegiance(Myself,ENEMY)
  !StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
  !CheckStatGT(NearestEnemyOf(Myself),0,HELD)
  !Kit(NearestEnemyOf(Myself),CAVALIER)
  !Kit(NearestEnemyOf(Myself),INQUISITOR)
  !Race(NearestEnemyOf(Myself),ELF)
  !CheckSpellState(NearestEnemyOf(Myself),CHAOTIC_COMMANDS)
  !General(NearestEnemyOf(Myself),UNDEAD)
  !CheckSpellState(NearestEnemyOf(Myself),ALLIED_AND_SAME_ALIGNMENT_RIGHTEOUS_WRATH_OF_THE_FAITHFUL)
  OR(2)
      !CheckSpellState(NearestEnemyOf(Myself),CHARM_IMMUNITY_SEEN)
      !CheckSpellState(NearestEnemyOf(Myself),CHARM_IMMUNITY)
  !CheckStatGT(NearestEnemyOf(Myself),0,MINORGLOBE)
  OR(2)
      !CheckStatGT(NearestEnemyOf(Myself),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  CheckStatGT(NearestEnemyOf(Myself),4,SAVEVSSPELL)
THEN
  RESPONSE #50
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(NearestEnemyOf(Myself),CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
  RESPONSE #50
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(SecondNearestEnemyOf(Myself),DO_NOT_TARGET_SPELLS)
  See(SecondNearestEnemyOf(Myself))
  ActionListEmpty()
  !Allegiance(Myself,ENEMY)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
  !Kit(SecondNearestEnemyOf(Myself),CAVALIER)
  !Kit(SecondNearestEnemyOf(Myself),INQUISITOR)
  !Race(SecondNearestEnemyOf(Myself),ELF)
  !CheckSpellState(SecondNearestEnemyOf(Myself),CHAOTIC_COMMANDS)
  !General(SecondNearestEnemyOf(Myself),UNDEAD)
  !CheckSpellState(SecondNearestEnemyOf(Myself),ALLIED_AND_SAME_ALIGNMENT_RIGHTEOUS_WRATH_OF_THE_FAITHFUL)
  OR(2)
      !CheckSpellState(SecondNearestEnemyOf(Myself),CHARM_IMMUNITY_SEEN)
      !CheckSpellState(SecondNearestEnemyOf(Myself),CHARM_IMMUNITY)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  OR(2)
      !CheckStatGT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  CheckStatGT(SecondNearestEnemyOf(Myself),4,SAVEVSSPELL)
THEN
  RESPONSE #50
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(SecondNearestEnemyOf(Myself),CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
  RESPONSE #50
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),DO_NOT_TARGET_SPELLS)
  See(ThirdNearestEnemyOf(Myself))
  ActionListEmpty()
  !Allegiance(Myself,ENEMY)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
  !Kit(ThirdNearestEnemyOf(Myself),CAVALIER)
  !Kit(ThirdNearestEnemyOf(Myself),INQUISITOR)
  !Race(ThirdNearestEnemyOf(Myself),ELF)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),CHAOTIC_COMMANDS)
  !General(ThirdNearestEnemyOf(Myself),UNDEAD)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),ALLIED_AND_SAME_ALIGNMENT_RIGHTEOUS_WRATH_OF_THE_FAITHFUL)
  OR(2)
      !CheckSpellState(ThirdNearestEnemyOf(Myself),CHARM_IMMUNITY_SEEN)
      !CheckSpellState(ThirdNearestEnemyOf(Myself),CHARM_IMMUNITY)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  OR(2)
      !CheckStatGT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  CheckStatGT(ThirdNearestEnemyOf(Myself),4,SAVEVSSPELL)
THEN
  RESPONSE #50
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(ThirdNearestEnemyOf(Myself),CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
  RESPONSE #50
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_CALL_LIGHTNING)  // SPPR302.SPL (Call Lightning)
  !StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
  !CheckStatGT(ThirdNearest([PC]),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(ThirdNearest([PC]),DO_NOT_TARGET_SPELLS)
  !StateCheck(ThirdNearest([PC]),STATE_DISABLED)
  !CheckStatGT(ThirdNearest([PC]),0,HELD)
  OR(2)
      !CheckStatGT(ThirdNearest([PC]),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT(ThirdNearest([PC]),50,RESISTELECTRICITY)
  !CheckStatGT(ThirdNearest([PC]),0,MINORGLOBE)
  Allegiance(Myself,ENEMY)
  !Allegiance(ThirdNearest([PC]),ENEMY)
  AreaType(OUTDOOR)
  See(ThirdNearest([PC]))
  False()
THEN
  RESPONSE #100
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_CALL_LIGHTNING)  // SPPR302.SPL (Call Lightning)
  !StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
  !CheckStatGT(SecondNearest([PC]),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(SecondNearest([PC]),DO_NOT_TARGET_SPELLS)
  !StateCheck(SecondNearest([PC]),STATE_DISABLED)
  !CheckStatGT(SecondNearest([PC]),0,HELD)
  OR(2)
      !CheckStatGT(SecondNearest([PC]),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT(SecondNearest([PC]),50,RESISTELECTRICITY)
  !CheckStatGT(SecondNearest([PC]),0,MINORGLOBE)
  Allegiance(Myself,ENEMY)
  !Allegiance(SecondNearest([PC]),ENEMY)
  AreaType(OUTDOOR)
  See(SecondNearest([PC]))
  False()
THEN
  RESPONSE #100
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_CALL_LIGHTNING)  // SPPR302.SPL (Call Lightning)
  !StateCheck([PC],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC],DO_NOT_TARGET_SPELLS)
  !StateCheck([PC],STATE_DISABLED)
  !CheckStatGT([PC],0,HELD)
  OR(2)
      !CheckStatGT([PC],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC],50,RESISTELECTRICITY)
  !CheckStatGT([PC],0,MINORGLOBE)
  Allegiance(Myself,ENEMY)
  !Allegiance([PC],ENEMY)
  AreaType(OUTDOOR)
  See([PC])
  False()
THEN
  RESPONSE #100
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_CALL_LIGHTNING)  // SPPR302.SPL (Call Lightning)
  !StateCheck([PC.0.0.CLERIC],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC.0.0.CLERIC],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC.0.0.CLERIC],DO_NOT_TARGET_SPELLS)
  !StateCheck([PC.0.0.CLERIC],STATE_DISABLED)
  !CheckStatGT([PC.0.0.CLERIC],0,HELD)
  OR(2)
      !CheckStatGT([PC.0.0.CLERIC],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC.0.0.CLERIC],50,RESISTELECTRICITY)
  !CheckStatGT([PC.0.0.CLERIC],0,MINORGLOBE)
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.CLERIC],ENEMY)
  AreaType(OUTDOOR)
  See([PC.0.0.CLERIC])
  False()
THEN
  RESPONSE #100
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_CALL_LIGHTNING)  // SPPR302.SPL (Call Lightning)
  !StateCheck([PC.0.0.THIEF_ALL],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC.0.0.THIEF_ALL],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC.0.0.THIEF_ALL],DO_NOT_TARGET_SPELLS)
  !StateCheck([PC.0.0.THIEF_ALL],STATE_DISABLED)
  !CheckStatGT([PC.0.0.THIEF_ALL],0,HELD)
  OR(2)
      !CheckStatGT([PC.0.0.THIEF_ALL],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC.0.0.THIEF_ALL],50,RESISTELECTRICITY)
  !CheckStatGT([PC.0.0.THIEF_ALL],0,MINORGLOBE)
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.THIEF_ALL],ENEMY)
  AreaType(OUTDOOR)
  See([PC.0.0.THIEF_ALL])
  False()
THEN
  RESPONSE #100
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_CALL_LIGHTNING)  // SPPR302.SPL (Call Lightning)
  !StateCheck([PC.0.0.BARD],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC.0.0.BARD],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC.0.0.BARD],DO_NOT_TARGET_SPELLS)
  !StateCheck([PC.0.0.BARD],STATE_DISABLED)
  !CheckStatGT([PC.0.0.BARD],0,HELD)
  OR(2)
      !CheckStatGT([PC.0.0.BARD],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC.0.0.BARD],50,RESISTELECTRICITY)
  !CheckStatGT([PC.0.0.BARD],0,MINORGLOBE)
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.BARD],ENEMY)
  AreaType(OUTDOOR)
  See([PC.0.0.BARD])
  False()
THEN
  RESPONSE #100
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_CALL_LIGHTNING)  // SPPR302.SPL (Call Lightning)
  !StateCheck([PC.0.0.THIEF],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC.0.0.THIEF],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC.0.0.THIEF],DO_NOT_TARGET_SPELLS)
  !StateCheck([PC.0.0.THIEF],STATE_DISABLED)
  !CheckStatGT([PC.0.0.THIEF],0,HELD)
  OR(2)
      !CheckStatGT([PC.0.0.THIEF],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC.0.0.THIEF],50,RESISTELECTRICITY)
  !CheckStatGT([PC.0.0.THIEF],0,MINORGLOBE)
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.THIEF],ENEMY)
  AreaType(OUTDOOR)
  See([PC.0.0.THIEF])
  False()
THEN
  RESPONSE #100
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_CALL_LIGHTNING)  // SPPR302.SPL (Call Lightning)
  !StateCheck([PC.0.0.LONG_BOW],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC.0.0.LONG_BOW],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC.0.0.LONG_BOW],DO_NOT_TARGET_SPELLS)
  !StateCheck([PC.0.0.LONG_BOW],STATE_DISABLED)
  !CheckStatGT([PC.0.0.LONG_BOW],0,HELD)
  OR(2)
      !CheckStatGT([PC.0.0.LONG_BOW],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC.0.0.LONG_BOW],50,RESISTELECTRICITY)
  !CheckStatGT([PC.0.0.LONG_BOW],0,MINORGLOBE)
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.LONG_BOW],ENEMY)
  AreaType(OUTDOOR)
  See([PC.0.0.LONG_BOW])
  False()
THEN
  RESPONSE #100
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_CALL_LIGHTNING)  // SPPR302.SPL (Call Lightning)
  !StateCheck([PC.0.0.MAGE_THIEF],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC.0.0.MAGE_THIEF],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC.0.0.MAGE_THIEF],DO_NOT_TARGET_SPELLS)
  !StateCheck([PC.0.0.MAGE_THIEF],STATE_DISABLED)
  !CheckStatGT([PC.0.0.MAGE_THIEF],0,HELD)
  OR(2)
      !CheckStatGT([PC.0.0.MAGE_THIEF],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC.0.0.MAGE_THIEF],50,RESISTELECTRICITY)
  !CheckStatGT([PC.0.0.MAGE_THIEF],0,MINORGLOBE)
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.MAGE_THIEF],ENEMY)
  AreaType(OUTDOOR)
  See([PC.0.0.MAGE_THIEF])
  False()
THEN
  RESPONSE #100
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_CALL_LIGHTNING)  // SPPR302.SPL (Call Lightning)
  !StateCheck([PC.0.0.MAGE],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC.0.0.MAGE],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC.0.0.MAGE],DO_NOT_TARGET_SPELLS)
  !StateCheck([PC.0.0.MAGE],STATE_DISABLED)
  !CheckStatGT([PC.0.0.MAGE],0,HELD)
  OR(2)
      !CheckStatGT([PC.0.0.MAGE],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC.0.0.MAGE],50,RESISTELECTRICITY)
  !CheckStatGT([PC.0.0.MAGE],0,MINORGLOBE)
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.MAGE],ENEMY)
  AreaType(OUTDOOR)
  See([PC.0.0.MAGE])
  False()
THEN
  RESPONSE #100
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_CALL_LIGHTNING)  // SPPR302.SPL (Call Lightning)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(LastSeenBy(Myself),DO_NOT_TARGET_SPELLS)
  !StateCheck(LastSeenBy(Myself),STATE_DISABLED)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  OR(2)
      !CheckStatGT(LastSeenBy(Myself),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT(LastSeenBy(Myself),50,RESISTELECTRICITY)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  AreaType(OUTDOOR)
  See(LastSeenBy(Myself))
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(LastSeenBy(Myself),CLERIC_CALL_LIGHTNING)  // SPPR302.SPL (Call Lightning)
  RESPONSE #30
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_CALL_LIGHTNING)  // SPPR302.SPL (Call Lightning)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(NearestEnemyOf(Myself),DO_NOT_TARGET_SPELLS)
  See(NearestEnemyOf(Myself))
  ActionListEmpty()
  !StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
  !CheckStatGT(NearestEnemyOf(Myself),0,HELD)
  OR(2)
      !CheckStatGT(NearestEnemyOf(Myself),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT(NearestEnemyOf(Myself),50,RESISTELECTRICITY)
  !CheckStatGT(NearestEnemyOf(Myself),0,MINORGLOBE)
  !Allegiance(Myself,ENEMY)
  AreaType(OUTDOOR)
THEN
  RESPONSE #50
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(NearestEnemyOf(Myself),CLERIC_CALL_LIGHTNING)  // SPPR302.SPL (Call Lightning)
  RESPONSE #50
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_CALL_LIGHTNING)  // SPPR302.SPL (Call Lightning)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(SecondNearestEnemyOf(Myself),DO_NOT_TARGET_SPELLS)
  See(SecondNearestEnemyOf(Myself))
  ActionListEmpty()
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
  OR(2)
      !CheckStatGT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT(SecondNearestEnemyOf(Myself),50,RESISTELECTRICITY)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  !Allegiance(Myself,ENEMY)
  AreaType(OUTDOOR)
THEN
  RESPONSE #50
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(SecondNearestEnemyOf(Myself),CLERIC_CALL_LIGHTNING)  // SPPR302.SPL (Call Lightning)
  RESPONSE #50
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_CALL_LIGHTNING)  // SPPR302.SPL (Call Lightning)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),DO_NOT_TARGET_SPELLS)
  See(ThirdNearestEnemyOf(Myself))
  ActionListEmpty()
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
  OR(2)
      !CheckStatGT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT(ThirdNearestEnemyOf(Myself),50,RESISTELECTRICITY)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  !Allegiance(Myself,ENEMY)
  AreaType(OUTDOOR)
THEN
  RESPONSE #50
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(ThirdNearestEnemyOf(Myself),CLERIC_CALL_LIGHTNING)  // SPPR302.SPL (Call Lightning)
  RESPONSE #50
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_CAUSE_SERIOUS_WOUNDS)  // SPPR414.SPL (Cause Critical Wounds)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  See(NearestEnemyOf(Myself))
  OR(2)
      ActionListEmpty()
      Allegiance(Myself,ENEMY)
  Range(NearestEnemyOf(Myself),10)
  !CheckStat(NearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
  !CheckStatGT(NearestEnemyOf(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(NearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStatGT(NearestEnemyOf(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
  OR(2)
      !CheckStatGT(NearestEnemyOf(Myself),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !HasItemEquiped("plat16",NearestEnemyOf(Myself))
  !CheckStatGT(NearestEnemyOf(Myself),30,MAGICDAMAGERESISTANCE)
THEN
  RESPONSE #50
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(Myself,CLERIC_CAUSE_SERIOUS_WOUNDS)  // SPPR414.SPL (Cause Critical Wounds)
  RESPONSE #50
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_CAUSE_SERIOUS_WOUNDS)  // SPPR414.SPL (Cause Critical Wounds)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  See(SecondNearestEnemyOf(Myself))
  OR(2)
      ActionListEmpty()
      Allegiance(Myself,ENEMY)
  Range(SecondNearestEnemyOf(Myself),10)
  !CheckStat(SecondNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
  OR(2)
      !CheckStatGT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !HasItemEquiped("plat16",SecondNearestEnemyOf(Myself))
  !CheckStatGT(SecondNearestEnemyOf(Myself),30,MAGICDAMAGERESISTANCE)
THEN
  RESPONSE #50
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(Myself,CLERIC_CAUSE_SERIOUS_WOUNDS)  // SPPR414.SPL (Cause Critical Wounds)
  RESPONSE #50
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_CAUSE_SERIOUS_WOUNDS)  // SPPR414.SPL (Cause Critical Wounds)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  See(ThirdNearestEnemyOf(Myself))
  OR(2)
      ActionListEmpty()
      Allegiance(Myself,ENEMY)
  Range(ThirdNearestEnemyOf(Myself),10)
  !CheckStat(ThirdNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
  OR(2)
      !CheckStatGT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !HasItemEquiped("plat16",ThirdNearestEnemyOf(Myself))
  !CheckStatGT(ThirdNearestEnemyOf(Myself),30,MAGICDAMAGERESISTANCE)
THEN
  RESPONSE #50
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(Myself,CLERIC_CAUSE_SERIOUS_WOUNDS)  // SPPR414.SPL (Cause Critical Wounds)
  RESPONSE #50
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  !StateCheck([PC.0.0.FIGHTER],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC.0.0.FIGHTER],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC.0.0.FIGHTER],DO_NOT_TARGET_SPELLS)
  See([PC.0.0.FIGHTER])
  !StateCheck([PC.0.0.FIGHTER],STATE_DISABLED)
  !CheckStatGT([PC.0.0.FIGHTER],0,HELD)
  !Kit([PC.0.0.FIGHTER],UNDEADHUNTER)
  !Kit([PC.0.0.FIGHTER],INQUISITOR)
  !CheckStatGT([PC.0.0.FIGHTER],0,CLERIC_FREE_ACTION)
  OR(2)
      !CheckSpellState([PC.0.0.FIGHTER],HOLD_IMMUNITY_SEEN)
      !CheckSpellState([PC.0.0.FIGHTER],HOLD_IMMUNITY)
  OR(2)
      !CheckStatGT([PC.0.0.FIGHTER],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.FIGHTER],ENEMY)
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell([PC.0.0.FIGHTER],WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  RESPONSE #30
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  !StateCheck([PC.0.0.RANGER],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC.0.0.RANGER],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC.0.0.RANGER],DO_NOT_TARGET_SPELLS)
  See([PC.0.0.RANGER])
  !StateCheck([PC.0.0.RANGER],STATE_DISABLED)
  !CheckStatGT([PC.0.0.RANGER],0,HELD)
  !Kit([PC.0.0.RANGER],UNDEADHUNTER)
  !Kit([PC.0.0.RANGER],INQUISITOR)
  !CheckStatGT([PC.0.0.RANGER],0,CLERIC_FREE_ACTION)
  OR(2)
      !CheckSpellState([PC.0.0.RANGER],HOLD_IMMUNITY_SEEN)
      !CheckSpellState([PC.0.0.RANGER],HOLD_IMMUNITY)
  OR(2)
      !CheckStatGT([PC.0.0.RANGER],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.RANGER],ENEMY)
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell([PC.0.0.RANGER],WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  RESPONSE #30
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  !StateCheck([PC.0.0.PALADIN],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC.0.0.PALADIN],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC.0.0.PALADIN],DO_NOT_TARGET_SPELLS)
  See([PC.0.0.PALADIN])
  !StateCheck([PC.0.0.PALADIN],STATE_DISABLED)
  !CheckStatGT([PC.0.0.PALADIN],0,HELD)
  !Kit([PC.0.0.PALADIN],UNDEADHUNTER)
  !Kit([PC.0.0.PALADIN],INQUISITOR)
  !CheckStatGT([PC.0.0.PALADIN],0,CLERIC_FREE_ACTION)
  OR(2)
      !CheckSpellState([PC.0.0.PALADIN],HOLD_IMMUNITY_SEEN)
      !CheckSpellState([PC.0.0.PALADIN],HOLD_IMMUNITY)
  OR(2)
      !CheckStatGT([PC.0.0.PALADIN],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.PALADIN],ENEMY)
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell([PC.0.0.PALADIN],WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  RESPONSE #30
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  !StateCheck([PC.0.0.FIGHTER_THIEF],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC.0.0.FIGHTER_THIEF],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC.0.0.FIGHTER_THIEF],DO_NOT_TARGET_SPELLS)
  See([PC.0.0.FIGHTER_THIEF])
  !StateCheck([PC.0.0.FIGHTER_THIEF],STATE_DISABLED)
  !CheckStatGT([PC.0.0.FIGHTER_THIEF],0,HELD)
  !Kit([PC.0.0.FIGHTER_THIEF],UNDEADHUNTER)
  !Kit([PC.0.0.FIGHTER_THIEF],INQUISITOR)
  !CheckStatGT([PC.0.0.FIGHTER_THIEF],0,CLERIC_FREE_ACTION)
  OR(2)
      !CheckSpellState([PC.0.0.FIGHTER_THIEF],HOLD_IMMUNITY_SEEN)
      !CheckSpellState([PC.0.0.FIGHTER_THIEF],HOLD_IMMUNITY)
  OR(2)
      !CheckStatGT([PC.0.0.FIGHTER_THIEF],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.FIGHTER_THIEF],ENEMY)
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell([PC.0.0.FIGHTER_THIEF],WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  RESPONSE #30
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  !StateCheck([PC.0.0.BARD],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC.0.0.BARD],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC.0.0.BARD],DO_NOT_TARGET_SPELLS)
  See([PC.0.0.BARD])
  !StateCheck([PC.0.0.BARD],STATE_DISABLED)
  !CheckStatGT([PC.0.0.BARD],0,HELD)
  !Kit([PC.0.0.BARD],UNDEADHUNTER)
  !Kit([PC.0.0.BARD],INQUISITOR)
  !CheckStatGT([PC.0.0.BARD],0,CLERIC_FREE_ACTION)
  OR(2)
      !CheckSpellState([PC.0.0.BARD],HOLD_IMMUNITY_SEEN)
      !CheckSpellState([PC.0.0.BARD],HOLD_IMMUNITY)
  OR(2)
      !CheckStatGT([PC.0.0.BARD],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.BARD],ENEMY)
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell([PC.0.0.BARD],WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  RESPONSE #30
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  !StateCheck([PC.0.0.THIEF],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC.0.0.THIEF],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC.0.0.THIEF],DO_NOT_TARGET_SPELLS)
  See([PC.0.0.THIEF])
  !StateCheck([PC.0.0.THIEF],STATE_DISABLED)
  !CheckStatGT([PC.0.0.THIEF],0,HELD)
  !Kit([PC.0.0.THIEF],UNDEADHUNTER)
  !Kit([PC.0.0.THIEF],INQUISITOR)
  !CheckStatGT([PC.0.0.THIEF],0,CLERIC_FREE_ACTION)
  OR(2)
      !CheckSpellState([PC.0.0.THIEF],HOLD_IMMUNITY_SEEN)
      !CheckSpellState([PC.0.0.THIEF],HOLD_IMMUNITY)
  OR(2)
      !CheckStatGT([PC.0.0.THIEF],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.THIEF],ENEMY)
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell([PC.0.0.THIEF],WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  RESPONSE #30
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  !StateCheck([PC],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC],DO_NOT_TARGET_SPELLS)
  See([PC])
  !StateCheck([PC],STATE_DISABLED)
  !CheckStatGT([PC],0,HELD)
  !Kit([PC],UNDEADHUNTER)
  !Kit([PC],INQUISITOR)
  !CheckStatGT([PC],0,CLERIC_FREE_ACTION)
  OR(2)
      !CheckSpellState([PC],HOLD_IMMUNITY_SEEN)
      !CheckSpellState([PC],HOLD_IMMUNITY)
  OR(2)
      !CheckStatGT([PC],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance([PC],ENEMY)
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell([PC],WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  RESPONSE #30
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  !StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
  !CheckStatGT(SecondNearest([PC]),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(SecondNearest([PC]),DO_NOT_TARGET_SPELLS)
  See(SecondNearest([PC]))
  !StateCheck(SecondNearest([PC]),STATE_DISABLED)
  !CheckStatGT(SecondNearest([PC]),0,HELD)
  !Kit(SecondNearest([PC]),UNDEADHUNTER)
  !Kit(SecondNearest([PC]),INQUISITOR)
  !CheckStatGT(SecondNearest([PC]),0,CLERIC_FREE_ACTION)
  OR(2)
      !CheckSpellState(SecondNearest([PC]),HOLD_IMMUNITY_SEEN)
      !CheckSpellState(SecondNearest([PC]),HOLD_IMMUNITY)
  OR(2)
      !CheckStatGT(SecondNearest([PC]),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance(SecondNearest([PC]),ENEMY)
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(SecondNearest([PC]),WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  RESPONSE #30
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  !StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
  !CheckStatGT(ThirdNearest([PC]),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(ThirdNearest([PC]),DO_NOT_TARGET_SPELLS)
  See(ThirdNearest([PC]))
  !StateCheck(ThirdNearest([PC]),STATE_DISABLED)
  !CheckStatGT(ThirdNearest([PC]),0,HELD)
  !Kit(ThirdNearest([PC]),UNDEADHUNTER)
  !Kit(ThirdNearest([PC]),INQUISITOR)
  !CheckStatGT(ThirdNearest([PC]),0,CLERIC_FREE_ACTION)
  OR(2)
      !CheckSpellState(ThirdNearest([PC]),HOLD_IMMUNITY_SEEN)
      !CheckSpellState(ThirdNearest([PC]),HOLD_IMMUNITY)
  OR(2)
      !CheckStatGT(ThirdNearest([PC]),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance(ThirdNearest([PC]),ENEMY)
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(ThirdNearest([PC]),WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  RESPONSE #30
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_MISCAST_MAGIC)  // SPPR310.SPL (Miscast Magic)
  !StateCheck([PC.0.0.LONG_BOW],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC.0.0.LONG_BOW],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC.0.0.LONG_BOW],DO_NOT_TARGET_SPELLS)
  See([PC.0.0.LONG_BOW])
  !CheckStatGT([PC.0.0.LONG_BOW],0,WIZARD_SPELL_TURNING)
  !CheckStatGT([PC.0.0.LONG_BOW],0,WIZARD_SPELL_TRAP)
  !CheckStatGT([PC.0.0.LONG_BOW],0,CLERIC_SHIELD_OF_THE_ARCHONS)
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.LONG_BOW],ENEMY)
  !StateCheck([PC.0.0.LONG_BOW],STATE_DISABLED)
  !CheckStatGT([PC.0.0.LONG_BOW],0,HELD)
  !CheckStatGT([PC.0.0.LONG_BOW],0,MINORGLOBE)
  !CheckStatGT([PC.0.0.LONG_BOW],80,SPELLFAILUREPRIEST)
THEN
  RESPONSE #100
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell([PC.0.0.LONG_BOW],CLERIC_MISCAST_MAGIC)  // SPPR310.SPL (Miscast Magic)
  RESPONSE #100
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_MISCAST_MAGIC)  // SPPR310.SPL (Miscast Magic)
  !StateCheck([PC.0.0.CLERIC_ALL],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC.0.0.CLERIC_ALL],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC.0.0.CLERIC_ALL],DO_NOT_TARGET_SPELLS)
  See([PC.0.0.CLERIC_ALL])
  !CheckStatGT([PC.0.0.CLERIC_ALL],0,WIZARD_SPELL_TURNING)
  !CheckStatGT([PC.0.0.CLERIC_ALL],0,WIZARD_SPELL_TRAP)
  !CheckStatGT([PC.0.0.CLERIC_ALL],0,CLERIC_SHIELD_OF_THE_ARCHONS)
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.CLERIC_ALL],ENEMY)
  !StateCheck([PC.0.0.CLERIC_ALL],STATE_DISABLED)
  !CheckStatGT([PC.0.0.CLERIC_ALL],0,HELD)
  !CheckStatGT([PC.0.0.CLERIC_ALL],0,MINORGLOBE)
  !CheckStatGT([PC.0.0.CLERIC_ALL],80,SPELLFAILUREPRIEST)
THEN
  RESPONSE #100
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell([PC.0.0.CLERIC_ALL],CLERIC_MISCAST_MAGIC)  // SPPR310.SPL (Miscast Magic)
  RESPONSE #100
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_MISCAST_MAGIC)  // SPPR310.SPL (Miscast Magic)
  !StateCheck([PC.0.0.DRUID_ALL],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC.0.0.DRUID_ALL],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC.0.0.DRUID_ALL],DO_NOT_TARGET_SPELLS)
  See([PC.0.0.DRUID_ALL])
  !CheckStatGT([PC.0.0.DRUID_ALL],0,WIZARD_SPELL_TURNING)
  !CheckStatGT([PC.0.0.DRUID_ALL],0,WIZARD_SPELL_TRAP)
  !CheckStatGT([PC.0.0.DRUID_ALL],0,CLERIC_SHIELD_OF_THE_ARCHONS)
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.DRUID_ALL],ENEMY)
  !StateCheck([PC.0.0.DRUID_ALL],STATE_DISABLED)
  !CheckStatGT([PC.0.0.DRUID_ALL],0,HELD)
  !CheckStatGT([PC.0.0.DRUID_ALL],0,MINORGLOBE)
  !CheckStatGT([PC.0.0.DRUID_ALL],80,SPELLFAILUREPRIEST)
THEN
  RESPONSE #100
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell([PC.0.0.DRUID_ALL],CLERIC_MISCAST_MAGIC)  // SPPR310.SPL (Miscast Magic)
  RESPONSE #100
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_MISCAST_MAGIC)  // SPPR310.SPL (Miscast Magic)
  !StateCheck([PC.0.0.BARD],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC.0.0.BARD],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC.0.0.BARD],DO_NOT_TARGET_SPELLS)
  See([PC.0.0.BARD])
  !CheckStatGT([PC.0.0.BARD],0,WIZARD_SPELL_TURNING)
  !CheckStatGT([PC.0.0.BARD],0,WIZARD_SPELL_TRAP)
  !CheckStatGT([PC.0.0.BARD],0,CLERIC_SHIELD_OF_THE_ARCHONS)
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.BARD],ENEMY)
  !StateCheck([PC.0.0.BARD],STATE_DISABLED)
  !CheckStatGT([PC.0.0.BARD],0,HELD)
  !CheckStatGT([PC.0.0.BARD],0,MINORGLOBE)
  !CheckStatGT([PC.0.0.BARD],80,SPELLFAILUREPRIEST)
THEN
  RESPONSE #100
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell([PC.0.0.BARD],CLERIC_MISCAST_MAGIC)  // SPPR310.SPL (Miscast Magic)
  RESPONSE #100
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  !StateCheck([PC.0.0.FIGHTER],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC.0.0.FIGHTER],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC.0.0.FIGHTER],DO_NOT_TARGET_SPELLS)
  See([PC.0.0.FIGHTER])
  !StateCheck([PC.0.0.FIGHTER],STATE_DISABLED)
  !CheckStatGT([PC.0.0.FIGHTER],0,HELD)
  !Kit([PC.0.0.FIGHTER],UNDEADHUNTER)
  !Kit([PC.0.0.FIGHTER],INQUISITOR)
  !CheckStatGT([PC.0.0.FIGHTER],0,CLERIC_FREE_ACTION)
  OR(2)
      !CheckSpellState([PC.0.0.FIGHTER],HOLD_IMMUNITY_SEEN)
      !CheckSpellState([PC.0.0.FIGHTER],HOLD_IMMUNITY)
  OR(2)
      !CheckStatGT([PC.0.0.FIGHTER],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.FIGHTER],ENEMY)
  !CheckStatGT([PC.0.0.FIGHTER],0,MINORGLOBE)
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell([PC.0.0.FIGHTER],CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  RESPONSE #30
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  !StateCheck([PC.0.0.RANGER],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC.0.0.RANGER],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC.0.0.RANGER],DO_NOT_TARGET_SPELLS)
  See([PC.0.0.RANGER])
  !StateCheck([PC.0.0.RANGER],STATE_DISABLED)
  !CheckStatGT([PC.0.0.RANGER],0,HELD)
  !Kit([PC.0.0.RANGER],UNDEADHUNTER)
  !Kit([PC.0.0.RANGER],INQUISITOR)
  !CheckStatGT([PC.0.0.RANGER],0,CLERIC_FREE_ACTION)
  OR(2)
      !CheckSpellState([PC.0.0.RANGER],HOLD_IMMUNITY_SEEN)
      !CheckSpellState([PC.0.0.RANGER],HOLD_IMMUNITY)
  OR(2)
      !CheckStatGT([PC.0.0.RANGER],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.RANGER],ENEMY)
  !CheckStatGT([PC.0.0.RANGER],0,MINORGLOBE)
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell([PC.0.0.RANGER],CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  RESPONSE #30
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  !StateCheck([PC.0.0.PALADIN],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC.0.0.PALADIN],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC.0.0.PALADIN],DO_NOT_TARGET_SPELLS)
  See([PC.0.0.PALADIN])
  !StateCheck([PC.0.0.PALADIN],STATE_DISABLED)
  !CheckStatGT([PC.0.0.PALADIN],0,HELD)
  !Kit([PC.0.0.PALADIN],UNDEADHUNTER)
  !Kit([PC.0.0.PALADIN],INQUISITOR)
  !CheckStatGT([PC.0.0.PALADIN],0,CLERIC_FREE_ACTION)
  OR(2)
      !CheckSpellState([PC.0.0.PALADIN],HOLD_IMMUNITY_SEEN)
      !CheckSpellState([PC.0.0.PALADIN],HOLD_IMMUNITY)
  OR(2)
      !CheckStatGT([PC.0.0.PALADIN],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.PALADIN],ENEMY)
  !CheckStatGT([PC.0.0.PALADIN],0,MINORGLOBE)
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell([PC.0.0.PALADIN],CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  RESPONSE #30
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  !StateCheck([PC.0.0.FIGHTER_THIEF],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC.0.0.FIGHTER_THIEF],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC.0.0.FIGHTER_THIEF],DO_NOT_TARGET_SPELLS)
  See([PC.0.0.FIGHTER_THIEF])
  !StateCheck([PC.0.0.FIGHTER_THIEF],STATE_DISABLED)
  !CheckStatGT([PC.0.0.FIGHTER_THIEF],0,HELD)
  !Kit([PC.0.0.FIGHTER_THIEF],UNDEADHUNTER)
  !Kit([PC.0.0.FIGHTER_THIEF],INQUISITOR)
  !CheckStatGT([PC.0.0.FIGHTER_THIEF],0,CLERIC_FREE_ACTION)
  OR(2)
      !CheckSpellState([PC.0.0.FIGHTER_THIEF],HOLD_IMMUNITY_SEEN)
      !CheckSpellState([PC.0.0.FIGHTER_THIEF],HOLD_IMMUNITY)
  OR(2)
      !CheckStatGT([PC.0.0.FIGHTER_THIEF],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.FIGHTER_THIEF],ENEMY)
  !CheckStatGT([PC.0.0.FIGHTER_THIEF],0,MINORGLOBE)
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell([PC.0.0.FIGHTER_THIEF],CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  RESPONSE #30
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  !StateCheck([PC.0.0.BARD],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC.0.0.BARD],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC.0.0.BARD],DO_NOT_TARGET_SPELLS)
  See([PC.0.0.BARD])
  !StateCheck([PC.0.0.BARD],STATE_DISABLED)
  !CheckStatGT([PC.0.0.BARD],0,HELD)
  !Kit([PC.0.0.BARD],UNDEADHUNTER)
  !Kit([PC.0.0.BARD],INQUISITOR)
  !CheckStatGT([PC.0.0.BARD],0,CLERIC_FREE_ACTION)
  OR(2)
      !CheckSpellState([PC.0.0.BARD],HOLD_IMMUNITY_SEEN)
      !CheckSpellState([PC.0.0.BARD],HOLD_IMMUNITY)
  OR(2)
      !CheckStatGT([PC.0.0.BARD],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.BARD],ENEMY)
  !CheckStatGT([PC.0.0.BARD],0,MINORGLOBE)
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell([PC.0.0.BARD],CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  RESPONSE #30
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  !StateCheck([PC.0.0.THIEF],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC.0.0.THIEF],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC.0.0.THIEF],DO_NOT_TARGET_SPELLS)
  See([PC.0.0.THIEF])
  !StateCheck([PC.0.0.THIEF],STATE_DISABLED)
  !CheckStatGT([PC.0.0.THIEF],0,HELD)
  !Kit([PC.0.0.THIEF],UNDEADHUNTER)
  !Kit([PC.0.0.THIEF],INQUISITOR)
  !CheckStatGT([PC.0.0.THIEF],0,CLERIC_FREE_ACTION)
  OR(2)
      !CheckSpellState([PC.0.0.THIEF],HOLD_IMMUNITY_SEEN)
      !CheckSpellState([PC.0.0.THIEF],HOLD_IMMUNITY)
  OR(2)
      !CheckStatGT([PC.0.0.THIEF],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.THIEF],ENEMY)
  !CheckStatGT([PC.0.0.THIEF],0,MINORGLOBE)
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell([PC.0.0.THIEF],CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  RESPONSE #30
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  !StateCheck([PC],STATE_NOT_TARGETABLE)
  !CheckStatGT([PC],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([PC],DO_NOT_TARGET_SPELLS)
  See([PC])
  !StateCheck([PC],STATE_DISABLED)
  !CheckStatGT([PC],0,HELD)
  !Kit([PC],UNDEADHUNTER)
  !Kit([PC],INQUISITOR)
  !CheckStatGT([PC],0,CLERIC_FREE_ACTION)
  OR(2)
      !CheckSpellState([PC],HOLD_IMMUNITY_SEEN)
      !CheckSpellState([PC],HOLD_IMMUNITY)
  OR(2)
      !CheckStatGT([PC],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance([PC],ENEMY)
  !CheckStatGT([PC],0,MINORGLOBE)
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell([PC],CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  RESPONSE #30
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  !StateCheck(SecondNearest([PC]),STATE_NOT_TARGETABLE)
  !CheckStatGT(SecondNearest([PC]),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(SecondNearest([PC]),DO_NOT_TARGET_SPELLS)
  See(SecondNearest([PC]))
  !StateCheck(SecondNearest([PC]),STATE_DISABLED)
  !CheckStatGT(SecondNearest([PC]),0,HELD)
  !Kit(SecondNearest([PC]),UNDEADHUNTER)
  !Kit(SecondNearest([PC]),INQUISITOR)
  !CheckStatGT(SecondNearest([PC]),0,CLERIC_FREE_ACTION)
  OR(2)
      !CheckSpellState(SecondNearest([PC]),HOLD_IMMUNITY_SEEN)
      !CheckSpellState(SecondNearest([PC]),HOLD_IMMUNITY)
  OR(2)
      !CheckStatGT(SecondNearest([PC]),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance(SecondNearest([PC]),ENEMY)
  !CheckStatGT(SecondNearest([PC]),0,MINORGLOBE)
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(SecondNearest([PC]),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  RESPONSE #30
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  !StateCheck(ThirdNearest([PC]),STATE_NOT_TARGETABLE)
  !CheckStatGT(ThirdNearest([PC]),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(ThirdNearest([PC]),DO_NOT_TARGET_SPELLS)
  See(ThirdNearest([PC]))
  !StateCheck(ThirdNearest([PC]),STATE_DISABLED)
  !CheckStatGT(ThirdNearest([PC]),0,HELD)
  !Kit(ThirdNearest([PC]),UNDEADHUNTER)
  !Kit(ThirdNearest([PC]),INQUISITOR)
  !CheckStatGT(ThirdNearest([PC]),0,CLERIC_FREE_ACTION)
  OR(2)
      !CheckSpellState(ThirdNearest([PC]),HOLD_IMMUNITY_SEEN)
      !CheckSpellState(ThirdNearest([PC]),HOLD_IMMUNITY)
  OR(2)
      !CheckStatGT(ThirdNearest([PC]),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Allegiance(Myself,ENEMY)
  !Allegiance(ThirdNearest([PC]),ENEMY)
  !CheckStatGT(ThirdNearest([PC]),0,MINORGLOBE)
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(ThirdNearest([PC]),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  RESPONSE #30
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(NearestEnemyOf(Myself),DO_NOT_TARGET_SPELLS)
  See(NearestEnemyOf(Myself))
  ActionListEmpty()
  !Allegiance(Myself,ENEMY)
  !StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
  !CheckStatGT(NearestEnemyOf(Myself),0,HELD)
  !Kit(NearestEnemyOf(Myself),UNDEADHUNTER)
  !Kit(NearestEnemyOf(Myself),INQUISITOR)
  !CheckStatGT(NearestEnemyOf(Myself),0,CLERIC_FREE_ACTION)
  OR(2)
      !CheckSpellState(NearestEnemyOf(Myself),HOLD_IMMUNITY_SEEN)
      !CheckSpellState(NearestEnemyOf(Myself),HOLD_IMMUNITY)
  OR(2)
      !CheckStatGT(NearestEnemyOf(Myself),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  CheckStatGT(NearestEnemyOf(Myself),4,SAVEVSSPELL)
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(NearestEnemyOf(Myself),WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  RESPONSE #30
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(SecondNearestEnemyOf(Myself),DO_NOT_TARGET_SPELLS)
  See(SecondNearestEnemyOf(Myself))
  ActionListEmpty()
  !Allegiance(Myself,ENEMY)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
  !Kit(SecondNearestEnemyOf(Myself),UNDEADHUNTER)
  !Kit(SecondNearestEnemyOf(Myself),INQUISITOR)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,CLERIC_FREE_ACTION)
  OR(2)
      !CheckSpellState(SecondNearestEnemyOf(Myself),HOLD_IMMUNITY_SEEN)
      !CheckSpellState(SecondNearestEnemyOf(Myself),HOLD_IMMUNITY)
  OR(2)
      !CheckStatGT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  CheckStatGT(SecondNearestEnemyOf(Myself),4,SAVEVSSPELL)
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(SecondNearestEnemyOf(Myself),WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  RESPONSE #30
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),DO_NOT_TARGET_SPELLS)
  See(ThirdNearestEnemyOf(Myself))
  ActionListEmpty()
  !Allegiance(Myself,ENEMY)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
  !Kit(ThirdNearestEnemyOf(Myself),UNDEADHUNTER)
  !Kit(ThirdNearestEnemyOf(Myself),INQUISITOR)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,CLERIC_FREE_ACTION)
  OR(2)
      !CheckSpellState(ThirdNearestEnemyOf(Myself),HOLD_IMMUNITY_SEEN)
      !CheckSpellState(ThirdNearestEnemyOf(Myself),HOLD_IMMUNITY)
  OR(2)
      !CheckStatGT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  CheckStatGT(ThirdNearestEnemyOf(Myself),4,SAVEVSSPELL)
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(ThirdNearestEnemyOf(Myself),WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  RESPONSE #30
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(FourthNearestEnemyOf(Myself),DO_NOT_TARGET_SPELLS)
  See(FourthNearestEnemyOf(Myself))
  ActionListEmpty()
  !Allegiance(Myself,ENEMY)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
  !Kit(FourthNearestEnemyOf(Myself),UNDEADHUNTER)
  !Kit(FourthNearestEnemyOf(Myself),INQUISITOR)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,CLERIC_FREE_ACTION)
  OR(2)
      !CheckSpellState(FourthNearestEnemyOf(Myself),HOLD_IMMUNITY_SEEN)
      !CheckSpellState(FourthNearestEnemyOf(Myself),HOLD_IMMUNITY)
  OR(2)
      !CheckStatGT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  CheckStatGT(FourthNearestEnemyOf(Myself),4,SAVEVSSPELL)
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(FourthNearestEnemyOf(Myself),WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  RESPONSE #30
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(FifthNearestEnemyOf(Myself),DO_NOT_TARGET_SPELLS)
  See(FifthNearestEnemyOf(Myself))
  ActionListEmpty()
  !Allegiance(Myself,ENEMY)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
  !Kit(FifthNearestEnemyOf(Myself),UNDEADHUNTER)
  !Kit(FifthNearestEnemyOf(Myself),INQUISITOR)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,CLERIC_FREE_ACTION)
  OR(2)
      !CheckSpellState(FifthNearestEnemyOf(Myself),HOLD_IMMUNITY_SEEN)
      !CheckSpellState(FifthNearestEnemyOf(Myself),HOLD_IMMUNITY)
  OR(2)
      !CheckStatGT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  CheckStatGT(FifthNearestEnemyOf(Myself),4,SAVEVSSPELL)
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(FifthNearestEnemyOf(Myself),WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  RESPONSE #30
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(SixthNearestEnemyOf(Myself),DO_NOT_TARGET_SPELLS)
  See(SixthNearestEnemyOf(Myself))
  ActionListEmpty()
  !Allegiance(Myself,ENEMY)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
  !Kit(SixthNearestEnemyOf(Myself),UNDEADHUNTER)
  !Kit(SixthNearestEnemyOf(Myself),INQUISITOR)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,CLERIC_FREE_ACTION)
  OR(2)
      !CheckSpellState(SixthNearestEnemyOf(Myself),HOLD_IMMUNITY_SEEN)
      !CheckSpellState(SixthNearestEnemyOf(Myself),HOLD_IMMUNITY)
  OR(2)
      !CheckStatGT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  CheckStatGT(SixthNearestEnemyOf(Myself),4,SAVEVSSPELL)
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(SixthNearestEnemyOf(Myself),WIZARD_HOLD_MONSTER)  // SPWI507.SPL (Hold Monster)
  RESPONSE #30
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  !StateCheck([ENEMY.HUMANOID],STATE_NOT_TARGETABLE)
  !CheckStatGT([ENEMY.HUMANOID],0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState([ENEMY.HUMANOID],DO_NOT_TARGET_SPELLS)
  See([ENEMY.HUMANOID])
  ActionListEmpty()
  !Allegiance(Myself,ENEMY)
  !StateCheck([ENEMY.HUMANOID],STATE_DISABLED)
  !CheckStatGT([ENEMY.HUMANOID],0,HELD)
  !Kit([ENEMY.HUMANOID],UNDEADHUNTER)
  !Kit([ENEMY.HUMANOID],INQUISITOR)
  !CheckStatGT([ENEMY.HUMANOID],0,CLERIC_FREE_ACTION)
  OR(2)
      !CheckSpellState([ENEMY.HUMANOID],HOLD_IMMUNITY_SEEN)
      !CheckSpellState([ENEMY.HUMANOID],HOLD_IMMUNITY)
  !CheckStatGT([ENEMY.HUMANOID],0,MINORGLOBE)
  OR(2)
      !CheckStatGT([ENEMY.HUMANOID],50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  CheckStatGT([ENEMY.HUMANOID],4,SAVEVSSPELL)
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell([ENEMY.HUMANOID],CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  RESPONSE #30
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  !StateCheck(SecondNearest([ENEMY.HUMANOID]),STATE_NOT_TARGETABLE)
  !CheckStatGT(SecondNearest([ENEMY.HUMANOID]),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(SecondNearest([ENEMY.HUMANOID]),DO_NOT_TARGET_SPELLS)
  See(SecondNearest([ENEMY.HUMANOID]))
  ActionListEmpty()
  !Allegiance(Myself,ENEMY)
  !StateCheck(SecondNearest([ENEMY.HUMANOID]),STATE_DISABLED)
  !CheckStatGT(SecondNearest([ENEMY.HUMANOID]),0,HELD)
  !Kit(SecondNearest([ENEMY.HUMANOID]),UNDEADHUNTER)
  !Kit(SecondNearest([ENEMY.HUMANOID]),INQUISITOR)
  !CheckStatGT(SecondNearest([ENEMY.HUMANOID]),0,CLERIC_FREE_ACTION)
  OR(2)
      !CheckSpellState(SecondNearest([ENEMY.HUMANOID]),HOLD_IMMUNITY_SEEN)
      !CheckSpellState(SecondNearest([ENEMY.HUMANOID]),HOLD_IMMUNITY)
  !CheckStatGT(SecondNearest([ENEMY.HUMANOID]),0,MINORGLOBE)
  OR(2)
      !CheckStatGT(SecondNearest([ENEMY.HUMANOID]),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  CheckStatGT(SecondNearest([ENEMY.HUMANOID]),4,SAVEVSSPELL)
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(SecondNearest([ENEMY.HUMANOID]),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  RESPONSE #30
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  !StateCheck(ThirdNearest([ENEMY.HUMANOID]),STATE_NOT_TARGETABLE)
  !CheckStatGT(ThirdNearest([ENEMY.HUMANOID]),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(ThirdNearest([ENEMY.HUMANOID]),DO_NOT_TARGET_SPELLS)
  See(ThirdNearest([ENEMY.HUMANOID]))
  ActionListEmpty()
  !Allegiance(Myself,ENEMY)
  !StateCheck(ThirdNearest([ENEMY.HUMANOID]),STATE_DISABLED)
  !CheckStatGT(ThirdNearest([ENEMY.HUMANOID]),0,HELD)
  !Kit(ThirdNearest([ENEMY.HUMANOID]),UNDEADHUNTER)
  !Kit(ThirdNearest([ENEMY.HUMANOID]),INQUISITOR)
  !CheckStatGT(ThirdNearest([ENEMY.HUMANOID]),0,CLERIC_FREE_ACTION)
  OR(2)
      !CheckSpellState(ThirdNearest([ENEMY.HUMANOID]),HOLD_IMMUNITY_SEEN)
      !CheckSpellState(ThirdNearest([ENEMY.HUMANOID]),HOLD_IMMUNITY)
  !CheckStatGT(ThirdNearest([ENEMY.HUMANOID]),0,MINORGLOBE)
  OR(2)
      !CheckStatGT(ThirdNearest([ENEMY.HUMANOID]),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  CheckStatGT(ThirdNearest([ENEMY.HUMANOID]),4,SAVEVSSPELL)
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(ThirdNearest([ENEMY.HUMANOID]),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  RESPONSE #30
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  !StateCheck(FourthNearest([ENEMY.HUMANOID]),STATE_NOT_TARGETABLE)
  !CheckStatGT(FourthNearest([ENEMY.HUMANOID]),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(FourthNearest([ENEMY.HUMANOID]),DO_NOT_TARGET_SPELLS)
  See(FourthNearest([ENEMY.HUMANOID]))
  ActionListEmpty()
  !Allegiance(Myself,ENEMY)
  !StateCheck(FourthNearest([ENEMY.HUMANOID]),STATE_DISABLED)
  !CheckStatGT(FourthNearest([ENEMY.HUMANOID]),0,HELD)
  !Kit(FourthNearest([ENEMY.HUMANOID]),UNDEADHUNTER)
  !Kit(FourthNearest([ENEMY.HUMANOID]),INQUISITOR)
  !CheckStatGT(FourthNearest([ENEMY.HUMANOID]),0,CLERIC_FREE_ACTION)
  OR(2)
      !CheckSpellState(FourthNearest([ENEMY.HUMANOID]),HOLD_IMMUNITY_SEEN)
      !CheckSpellState(FourthNearest([ENEMY.HUMANOID]),HOLD_IMMUNITY)
  !CheckStatGT(FourthNearest([ENEMY.HUMANOID]),0,MINORGLOBE)
  OR(2)
      !CheckStatGT(FourthNearest([ENEMY.HUMANOID]),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  CheckStatGT(FourthNearest([ENEMY.HUMANOID]),4,SAVEVSSPELL)
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(FourthNearest([ENEMY.HUMANOID]),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  RESPONSE #30
      Continue()
END

IF
  !GlobalTimerNotExpired("castspell","LOCALS")
  HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  !StateCheck(FifthNearest([ENEMY.HUMANOID]),STATE_NOT_TARGETABLE)
  !CheckStatGT(FifthNearest([ENEMY.HUMANOID]),0,SANCTUARY)
  CheckStatLT(Myself,60,SPELLFAILUREPRIEST)
  !CheckSpellState(FifthNearest([ENEMY.HUMANOID]),DO_NOT_TARGET_SPELLS)
  See(FifthNearest([ENEMY.HUMANOID]))
  ActionListEmpty()
  !Allegiance(Myself,ENEMY)
  !StateCheck(FifthNearest([ENEMY.HUMANOID]),STATE_DISABLED)
  !CheckStatGT(FifthNearest([ENEMY.HUMANOID]),0,HELD)
  !Kit(FifthNearest([ENEMY.HUMANOID]),UNDEADHUNTER)
  !Kit(FifthNearest([ENEMY.HUMANOID]),INQUISITOR)
  !CheckStatGT(FifthNearest([ENEMY.HUMANOID]),0,CLERIC_FREE_ACTION)
  OR(2)
      !CheckSpellState(FifthNearest([ENEMY.HUMANOID]),HOLD_IMMUNITY_SEEN)
      !CheckSpellState(FifthNearest([ENEMY.HUMANOID]),HOLD_IMMUNITY)
  !CheckStatGT(FifthNearest([ENEMY.HUMANOID]),0,MINORGLOBE)
  OR(2)
      !CheckStatGT(FifthNearest([ENEMY.HUMANOID]),50,RESISTMAGIC)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  CheckStatGT(FifthNearest([ENEMY.HUMANOID]),4,SAVEVSSPELL)
THEN
  RESPONSE #70
      SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
      Spell(FifthNearest([ENEMY.HUMANOID]),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
  RESPONSE #30
      Continue()
END

IF
  See(NearestEnemyOf(Myself))
  ActionListEmpty()
  !Allegiance(Myself,ENEMY)
  OR(2)
      WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
THEN
  RESPONSE #100
      AttackOneRound(NearestEnemyOf(Myself))
END

IF
  See(SecondNearestEnemyOf(Myself))
  ActionListEmpty()
  !Allegiance(Myself,ENEMY)
  OR(2)
      WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
THEN
  RESPONSE #100
      AttackOneRound(SecondNearestEnemyOf(Myself))
END

IF
  See(ThirdNearestEnemyOf(Myself))
  ActionListEmpty()
  !Allegiance(Myself,ENEMY)
  OR(2)
      WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
THEN
  RESPONSE #100
      AttackOneRound(ThirdNearestEnemyOf(Myself))
END

IF
  See(LastTargetedBy(Myself))
  Global("validtarget","LOCALS",1)
  OR(2)
      !WeaponEffectiveVs(LastTargetedBy(Myself),MAINHAND)
      !WeaponCanDamage(LastTargetedBy(Myself),MAINHAND)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",0)
      ClearActions(Myself)
END

IF
  !StateCheck([PC.0.0.MAGE],STATE_INVISIBLE)
  See([PC.0.0.MAGE])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.MAGE],ENEMY)
  !StateCheck([PC.0.0.MAGE],STATE_IMMOBILE)
  !StateCheck([PC.0.0.MAGE],STATE_FEEBLEMINDED)
  !CheckStatGT([PC.0.0.MAGE],0,HELD)
  !StateCheck([PC.0.0.MAGE],STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs([PC.0.0.MAGE],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.MAGE],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.MAGE],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.MAGE],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC.0.0.MAGE],0,STONESKINS)
  !HPPercentGT([PC.0.0.MAGE],20)
  Range([PC.0.0.MAGE],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC.0.0.MAGE])
END

IF
  !StateCheck([PC.0.0.MAGE_THIEF],STATE_INVISIBLE)
  See([PC.0.0.MAGE_THIEF])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.MAGE_THIEF],ENEMY)
  !StateCheck([PC.0.0.MAGE_THIEF],STATE_IMMOBILE)
  !StateCheck([PC.0.0.MAGE_THIEF],STATE_FEEBLEMINDED)
  !CheckStatGT([PC.0.0.MAGE_THIEF],0,HELD)
  !StateCheck([PC.0.0.MAGE_THIEF],STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs([PC.0.0.MAGE_THIEF],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.MAGE_THIEF],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.MAGE_THIEF],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.MAGE_THIEF],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC.0.0.MAGE_THIEF],0,STONESKINS)
  !HPPercentGT([PC.0.0.MAGE_THIEF],20)
  Range([PC.0.0.MAGE_THIEF],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC.0.0.MAGE_THIEF])
END

IF
  !StateCheck([PC.0.0.LONG_BOW],STATE_INVISIBLE)
  See([PC.0.0.LONG_BOW])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.LONG_BOW],ENEMY)
  !StateCheck([PC.0.0.LONG_BOW],STATE_IMMOBILE)
  !StateCheck([PC.0.0.LONG_BOW],STATE_FEEBLEMINDED)
  !CheckStatGT([PC.0.0.LONG_BOW],0,HELD)
  !StateCheck([PC.0.0.LONG_BOW],STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs([PC.0.0.LONG_BOW],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.LONG_BOW],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.LONG_BOW],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.LONG_BOW],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC.0.0.LONG_BOW],0,STONESKINS)
  !HPPercentGT([PC.0.0.LONG_BOW],20)
  Range([PC.0.0.LONG_BOW],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC.0.0.LONG_BOW])
END

IF
  !StateCheck([PC.0.0.THIEF],STATE_INVISIBLE)
  See([PC.0.0.THIEF])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.THIEF],ENEMY)
  !StateCheck([PC.0.0.THIEF],STATE_IMMOBILE)
  !StateCheck([PC.0.0.THIEF],STATE_FEEBLEMINDED)
  !CheckStatGT([PC.0.0.THIEF],0,HELD)
  !StateCheck([PC.0.0.THIEF],STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs([PC.0.0.THIEF],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.THIEF],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.THIEF],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.THIEF],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC.0.0.THIEF],0,STONESKINS)
  !HPPercentGT([PC.0.0.THIEF],20)
  Range([PC.0.0.THIEF],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC.0.0.THIEF])
END

IF
  !StateCheck([PC.0.0.BARD],STATE_INVISIBLE)
  See([PC.0.0.BARD])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.BARD],ENEMY)
  !StateCheck([PC.0.0.BARD],STATE_IMMOBILE)
  !StateCheck([PC.0.0.BARD],STATE_FEEBLEMINDED)
  !CheckStatGT([PC.0.0.BARD],0,HELD)
  !StateCheck([PC.0.0.BARD],STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs([PC.0.0.BARD],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.BARD],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.BARD],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.BARD],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC.0.0.BARD],0,STONESKINS)
  !HPPercentGT([PC.0.0.BARD],20)
  Range([PC.0.0.BARD],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC.0.0.BARD])
END

IF
  !StateCheck([PC.0.0.THIEF_ALL],STATE_INVISIBLE)
  See([PC.0.0.THIEF_ALL])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.THIEF_ALL],ENEMY)
  !StateCheck([PC.0.0.THIEF_ALL],STATE_IMMOBILE)
  !StateCheck([PC.0.0.THIEF_ALL],STATE_FEEBLEMINDED)
  !CheckStatGT([PC.0.0.THIEF_ALL],0,HELD)
  !StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs([PC.0.0.THIEF_ALL],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.THIEF_ALL],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.THIEF_ALL],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
  !HPPercentGT([PC.0.0.THIEF_ALL],20)
  Range([PC.0.0.THIEF_ALL],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC.0.0.THIEF_ALL])
END

IF
  !StateCheck([PC.0.0.CLERIC],STATE_INVISIBLE)
  See([PC.0.0.CLERIC])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.CLERIC],ENEMY)
  !StateCheck([PC.0.0.CLERIC],STATE_IMMOBILE)
  !StateCheck([PC.0.0.CLERIC],STATE_FEEBLEMINDED)
  !CheckStatGT([PC.0.0.CLERIC],0,HELD)
  !StateCheck([PC.0.0.CLERIC],STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs([PC.0.0.CLERIC],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.CLERIC],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.CLERIC],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.CLERIC],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC.0.0.CLERIC],0,STONESKINS)
  !HPPercentGT([PC.0.0.CLERIC],20)
  Range([PC.0.0.CLERIC],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC.0.0.CLERIC])
END

IF
  !StateCheck([PC],STATE_INVISIBLE)
  See([PC])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC],ENEMY)
  !StateCheck([PC],STATE_IMMOBILE)
  !StateCheck([PC],STATE_FEEBLEMINDED)
  !CheckStatGT([PC],0,HELD)
  !StateCheck([PC],STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs([PC],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC],0,STONESKINS)
  !HPPercentGT([PC],20)
  Range([PC],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC])
END

IF
  !StateCheck(SecondNearest([PC]),STATE_INVISIBLE)
  See(SecondNearest([PC]))
  Allegiance(Myself,ENEMY)
  !Allegiance(SecondNearest([PC]),ENEMY)
  !StateCheck(SecondNearest([PC]),STATE_IMMOBILE)
  !StateCheck(SecondNearest([PC]),STATE_FEEBLEMINDED)
  !CheckStatGT(SecondNearest([PC]),0,HELD)
  !StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs(SecondNearest([PC]),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(SecondNearest([PC]),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(SecondNearest([PC]),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(SecondNearest([PC]),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT(SecondNearest([PC]),0,STONESKINS)
  !HPPercentGT(SecondNearest([PC]),20)
  Range(SecondNearest([PC]),4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound(SecondNearest([PC]))
END

IF
  !StateCheck(ThirdNearest([PC]),STATE_INVISIBLE)
  See(ThirdNearest([PC]))
  Allegiance(Myself,ENEMY)
  !Allegiance(ThirdNearest([PC]),ENEMY)
  !StateCheck(ThirdNearest([PC]),STATE_IMMOBILE)
  !StateCheck(ThirdNearest([PC]),STATE_FEEBLEMINDED)
  !CheckStatGT(ThirdNearest([PC]),0,HELD)
  !StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs(ThirdNearest([PC]),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(ThirdNearest([PC]),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(ThirdNearest([PC]),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(ThirdNearest([PC]),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
  !HPPercentGT(ThirdNearest([PC]),20)
  Range(ThirdNearest([PC]),4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound(ThirdNearest([PC]))
END

IF
  !StateCheck([PC.0.0.MAGE],STATE_INVISIBLE)
  See([PC.0.0.MAGE])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.MAGE],ENEMY)
  !StateCheck([PC.0.0.MAGE],STATE_IMMOBILE)
  !StateCheck([PC.0.0.MAGE],STATE_FEEBLEMINDED)
  !CheckStatGT([PC.0.0.MAGE],0,HELD)
  !StateCheck([PC.0.0.MAGE],STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs([PC.0.0.MAGE],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.MAGE],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.MAGE],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.MAGE],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC.0.0.MAGE],0,STONESKINS)
  !HPPercentGT([PC.0.0.MAGE],50)
  Range([PC.0.0.MAGE],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC.0.0.MAGE])
END

IF
  !StateCheck([PC.0.0.MAGE_THIEF],STATE_INVISIBLE)
  See([PC.0.0.MAGE_THIEF])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.MAGE_THIEF],ENEMY)
  !StateCheck([PC.0.0.MAGE_THIEF],STATE_IMMOBILE)
  !StateCheck([PC.0.0.MAGE_THIEF],STATE_FEEBLEMINDED)
  !CheckStatGT([PC.0.0.MAGE_THIEF],0,HELD)
  !StateCheck([PC.0.0.MAGE_THIEF],STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs([PC.0.0.MAGE_THIEF],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.MAGE_THIEF],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.MAGE_THIEF],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.MAGE_THIEF],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC.0.0.MAGE_THIEF],0,STONESKINS)
  !HPPercentGT([PC.0.0.MAGE_THIEF],50)
  Range([PC.0.0.MAGE_THIEF],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC.0.0.MAGE_THIEF])
END

IF
  !StateCheck([PC.0.0.LONG_BOW],STATE_INVISIBLE)
  See([PC.0.0.LONG_BOW])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.LONG_BOW],ENEMY)
  !StateCheck([PC.0.0.LONG_BOW],STATE_IMMOBILE)
  !StateCheck([PC.0.0.LONG_BOW],STATE_FEEBLEMINDED)
  !CheckStatGT([PC.0.0.LONG_BOW],0,HELD)
  !StateCheck([PC.0.0.LONG_BOW],STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs([PC.0.0.LONG_BOW],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.LONG_BOW],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.LONG_BOW],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.LONG_BOW],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC.0.0.LONG_BOW],0,STONESKINS)
  !HPPercentGT([PC.0.0.LONG_BOW],50)
  Range([PC.0.0.LONG_BOW],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC.0.0.LONG_BOW])
END

IF
  !StateCheck([PC.0.0.THIEF],STATE_INVISIBLE)
  See([PC.0.0.THIEF])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.THIEF],ENEMY)
  !StateCheck([PC.0.0.THIEF],STATE_IMMOBILE)
  !StateCheck([PC.0.0.THIEF],STATE_FEEBLEMINDED)
  !CheckStatGT([PC.0.0.THIEF],0,HELD)
  !StateCheck([PC.0.0.THIEF],STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs([PC.0.0.THIEF],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.THIEF],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.THIEF],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.THIEF],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC.0.0.THIEF],0,STONESKINS)
  !HPPercentGT([PC.0.0.THIEF],50)
  Range([PC.0.0.THIEF],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC.0.0.THIEF])
END

IF
  !StateCheck([PC.0.0.BARD],STATE_INVISIBLE)
  See([PC.0.0.BARD])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.BARD],ENEMY)
  !StateCheck([PC.0.0.BARD],STATE_IMMOBILE)
  !StateCheck([PC.0.0.BARD],STATE_FEEBLEMINDED)
  !CheckStatGT([PC.0.0.BARD],0,HELD)
  !StateCheck([PC.0.0.BARD],STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs([PC.0.0.BARD],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.BARD],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.BARD],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.BARD],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC.0.0.BARD],0,STONESKINS)
  !HPPercentGT([PC.0.0.BARD],50)
  Range([PC.0.0.BARD],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC.0.0.BARD])
END

IF
  !StateCheck([PC.0.0.THIEF_ALL],STATE_INVISIBLE)
  See([PC.0.0.THIEF_ALL])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.THIEF_ALL],ENEMY)
  !StateCheck([PC.0.0.THIEF_ALL],STATE_IMMOBILE)
  !StateCheck([PC.0.0.THIEF_ALL],STATE_FEEBLEMINDED)
  !CheckStatGT([PC.0.0.THIEF_ALL],0,HELD)
  !StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs([PC.0.0.THIEF_ALL],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.THIEF_ALL],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.THIEF_ALL],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
  !HPPercentGT([PC.0.0.THIEF_ALL],50)
  Range([PC.0.0.THIEF_ALL],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC.0.0.THIEF_ALL])
END

IF
  !StateCheck([PC.0.0.CLERIC],STATE_INVISIBLE)
  See([PC.0.0.CLERIC])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.CLERIC],ENEMY)
  !StateCheck([PC.0.0.CLERIC],STATE_IMMOBILE)
  !StateCheck([PC.0.0.CLERIC],STATE_FEEBLEMINDED)
  !CheckStatGT([PC.0.0.CLERIC],0,HELD)
  !StateCheck([PC.0.0.CLERIC],STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs([PC.0.0.CLERIC],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.CLERIC],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.CLERIC],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.CLERIC],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC.0.0.CLERIC],0,STONESKINS)
  !HPPercentGT([PC.0.0.CLERIC],50)
  Range([PC.0.0.CLERIC],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC.0.0.CLERIC])
END

IF
  !StateCheck([PC],STATE_INVISIBLE)
  See([PC])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC],ENEMY)
  !StateCheck([PC],STATE_IMMOBILE)
  !StateCheck([PC],STATE_FEEBLEMINDED)
  !CheckStatGT([PC],0,HELD)
  !StateCheck([PC],STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs([PC],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC],0,STONESKINS)
  !HPPercentGT([PC],50)
  Range([PC],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC])
END

IF
  !StateCheck(SecondNearest([PC]),STATE_INVISIBLE)
  See(SecondNearest([PC]))
  Allegiance(Myself,ENEMY)
  !Allegiance(SecondNearest([PC]),ENEMY)
  !StateCheck(SecondNearest([PC]),STATE_IMMOBILE)
  !StateCheck(SecondNearest([PC]),STATE_FEEBLEMINDED)
  !CheckStatGT(SecondNearest([PC]),0,HELD)
  !StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs(SecondNearest([PC]),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(SecondNearest([PC]),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(SecondNearest([PC]),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(SecondNearest([PC]),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT(SecondNearest([PC]),0,STONESKINS)
  !HPPercentGT(SecondNearest([PC]),50)
  Range(SecondNearest([PC]),4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound(SecondNearest([PC]))
END

IF
  !StateCheck(ThirdNearest([PC]),STATE_INVISIBLE)
  See(ThirdNearest([PC]))
  Allegiance(Myself,ENEMY)
  !Allegiance(ThirdNearest([PC]),ENEMY)
  !StateCheck(ThirdNearest([PC]),STATE_IMMOBILE)
  !StateCheck(ThirdNearest([PC]),STATE_FEEBLEMINDED)
  !CheckStatGT(ThirdNearest([PC]),0,HELD)
  !StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs(ThirdNearest([PC]),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(ThirdNearest([PC]),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(ThirdNearest([PC]),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(ThirdNearest([PC]),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
  !HPPercentGT(ThirdNearest([PC]),50)
  Range(ThirdNearest([PC]),4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound(ThirdNearest([PC]))
END

IF
  !StateCheck([PC.0.0.MAGE],STATE_INVISIBLE)
  See([PC.0.0.MAGE])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.MAGE],ENEMY)
  !StateCheck([PC.0.0.MAGE],STATE_IMMOBILE)
  !StateCheck([PC.0.0.MAGE],STATE_FEEBLEMINDED)
  !CheckStatGT([PC.0.0.MAGE],0,HELD)
  !StateCheck([PC.0.0.MAGE],STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs([PC.0.0.MAGE],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.MAGE],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.MAGE],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.MAGE],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC.0.0.MAGE],0,STONESKINS)
  Range([PC.0.0.MAGE],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC.0.0.MAGE])
END

IF
  !StateCheck([PC.0.0.MAGE_THIEF],STATE_INVISIBLE)
  See([PC.0.0.MAGE_THIEF])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.MAGE_THIEF],ENEMY)
  !StateCheck([PC.0.0.MAGE_THIEF],STATE_IMMOBILE)
  !StateCheck([PC.0.0.MAGE_THIEF],STATE_FEEBLEMINDED)
  !CheckStatGT([PC.0.0.MAGE_THIEF],0,HELD)
  !StateCheck([PC.0.0.MAGE_THIEF],STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs([PC.0.0.MAGE_THIEF],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.MAGE_THIEF],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.MAGE_THIEF],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.MAGE_THIEF],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC.0.0.MAGE_THIEF],0,STONESKINS)
  Range([PC.0.0.MAGE_THIEF],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC.0.0.MAGE_THIEF])
END

IF
  !StateCheck([PC.0.0.LONG_BOW],STATE_INVISIBLE)
  See([PC.0.0.LONG_BOW])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.LONG_BOW],ENEMY)
  !StateCheck([PC.0.0.LONG_BOW],STATE_IMMOBILE)
  !StateCheck([PC.0.0.LONG_BOW],STATE_FEEBLEMINDED)
  !CheckStatGT([PC.0.0.LONG_BOW],0,HELD)
  !StateCheck([PC.0.0.LONG_BOW],STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs([PC.0.0.LONG_BOW],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.LONG_BOW],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.LONG_BOW],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.LONG_BOW],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC.0.0.LONG_BOW],0,STONESKINS)
  Range([PC.0.0.LONG_BOW],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC.0.0.LONG_BOW])
END

IF
  !StateCheck([PC.0.0.THIEF],STATE_INVISIBLE)
  See([PC.0.0.THIEF])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.THIEF],ENEMY)
  !StateCheck([PC.0.0.THIEF],STATE_IMMOBILE)
  !StateCheck([PC.0.0.THIEF],STATE_FEEBLEMINDED)
  !CheckStatGT([PC.0.0.THIEF],0,HELD)
  !StateCheck([PC.0.0.THIEF],STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs([PC.0.0.THIEF],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.THIEF],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.THIEF],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.THIEF],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC.0.0.THIEF],0,STONESKINS)
  Range([PC.0.0.THIEF],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC.0.0.THIEF])
END

IF
  !StateCheck([PC.0.0.BARD],STATE_INVISIBLE)
  See([PC.0.0.BARD])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.BARD],ENEMY)
  !StateCheck([PC.0.0.BARD],STATE_IMMOBILE)
  !StateCheck([PC.0.0.BARD],STATE_FEEBLEMINDED)
  !CheckStatGT([PC.0.0.BARD],0,HELD)
  !StateCheck([PC.0.0.BARD],STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs([PC.0.0.BARD],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.BARD],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.BARD],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.BARD],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC.0.0.BARD],0,STONESKINS)
  Range([PC.0.0.BARD],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC.0.0.BARD])
END

IF
  !StateCheck([PC.0.0.THIEF_ALL],STATE_INVISIBLE)
  See([PC.0.0.THIEF_ALL])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.THIEF_ALL],ENEMY)
  !StateCheck([PC.0.0.THIEF_ALL],STATE_IMMOBILE)
  !StateCheck([PC.0.0.THIEF_ALL],STATE_FEEBLEMINDED)
  !CheckStatGT([PC.0.0.THIEF_ALL],0,HELD)
  !StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs([PC.0.0.THIEF_ALL],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.THIEF_ALL],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.THIEF_ALL],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
  Range([PC.0.0.THIEF_ALL],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC.0.0.THIEF_ALL])
END

IF
  !StateCheck([PC.0.0.CLERIC],STATE_INVISIBLE)
  See([PC.0.0.CLERIC])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.CLERIC],ENEMY)
  !StateCheck([PC.0.0.CLERIC],STATE_IMMOBILE)
  !StateCheck([PC.0.0.CLERIC],STATE_FEEBLEMINDED)
  !CheckStatGT([PC.0.0.CLERIC],0,HELD)
  !StateCheck([PC.0.0.CLERIC],STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs([PC.0.0.CLERIC],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.CLERIC],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.CLERIC],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.CLERIC],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC.0.0.CLERIC],0,STONESKINS)
  Range([PC.0.0.CLERIC],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC.0.0.CLERIC])
END

IF
  !StateCheck([PC],STATE_INVISIBLE)
  See([PC])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC],ENEMY)
  !StateCheck([PC],STATE_IMMOBILE)
  !StateCheck([PC],STATE_FEEBLEMINDED)
  !CheckStatGT([PC],0,HELD)
  !StateCheck([PC],STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs([PC],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT([PC],0,STONESKINS)
  Range([PC],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC])
END

IF
  !StateCheck(SecondNearest([PC]),STATE_INVISIBLE)
  See(SecondNearest([PC]))
  Allegiance(Myself,ENEMY)
  !Allegiance(SecondNearest([PC]),ENEMY)
  !StateCheck(SecondNearest([PC]),STATE_IMMOBILE)
  !StateCheck(SecondNearest([PC]),STATE_FEEBLEMINDED)
  !CheckStatGT(SecondNearest([PC]),0,HELD)
  !StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs(SecondNearest([PC]),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(SecondNearest([PC]),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(SecondNearest([PC]),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(SecondNearest([PC]),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT(SecondNearest([PC]),0,STONESKINS)
  Range(SecondNearest([PC]),4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound(SecondNearest([PC]))
END

IF
  !StateCheck(ThirdNearest([PC]),STATE_INVISIBLE)
  See(ThirdNearest([PC]))
  Allegiance(Myself,ENEMY)
  !Allegiance(ThirdNearest([PC]),ENEMY)
  !StateCheck(ThirdNearest([PC]),STATE_IMMOBILE)
  !StateCheck(ThirdNearest([PC]),STATE_FEEBLEMINDED)
  !CheckStatGT(ThirdNearest([PC]),0,HELD)
  !StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
  OR(2)
      WeaponEffectiveVs(ThirdNearest([PC]),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(ThirdNearest([PC]),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(ThirdNearest([PC]),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(ThirdNearest([PC]),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
  Range(ThirdNearest([PC]),4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound(ThirdNearest([PC]))
END

IF
  !StateCheck([PC.0.0.MAGE],STATE_INVISIBLE)
  See([PC.0.0.MAGE])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.MAGE],ENEMY)
  !StateCheck([PC.0.0.MAGE],STATE_IMMOBILE)
  !StateCheck([PC.0.0.MAGE],STATE_FEEBLEMINDED)
  !CheckStatGT([PC.0.0.MAGE],0,HELD)
  OR(2)
      WeaponEffectiveVs([PC.0.0.MAGE],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.MAGE],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.MAGE],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.MAGE],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Range([PC.0.0.MAGE],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC.0.0.MAGE])
END

IF
  !StateCheck([PC.0.0.MAGE_THIEF],STATE_INVISIBLE)
  See([PC.0.0.MAGE_THIEF])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.MAGE_THIEF],ENEMY)
  !StateCheck([PC.0.0.MAGE_THIEF],STATE_IMMOBILE)
  !StateCheck([PC.0.0.MAGE_THIEF],STATE_FEEBLEMINDED)
  !CheckStatGT([PC.0.0.MAGE_THIEF],0,HELD)
  OR(2)
      WeaponEffectiveVs([PC.0.0.MAGE_THIEF],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.MAGE_THIEF],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.MAGE_THIEF],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.MAGE_THIEF],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Range([PC.0.0.MAGE_THIEF],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC.0.0.MAGE_THIEF])
END

IF
  !StateCheck([PC.0.0.LONG_BOW],STATE_INVISIBLE)
  See([PC.0.0.LONG_BOW])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.LONG_BOW],ENEMY)
  !StateCheck([PC.0.0.LONG_BOW],STATE_IMMOBILE)
  !StateCheck([PC.0.0.LONG_BOW],STATE_FEEBLEMINDED)
  !CheckStatGT([PC.0.0.LONG_BOW],0,HELD)
  OR(2)
      WeaponEffectiveVs([PC.0.0.LONG_BOW],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.LONG_BOW],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.LONG_BOW],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.LONG_BOW],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Range([PC.0.0.LONG_BOW],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC.0.0.LONG_BOW])
END

IF
  !StateCheck([PC.0.0.THIEF],STATE_INVISIBLE)
  See([PC.0.0.THIEF])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.THIEF],ENEMY)
  !StateCheck([PC.0.0.THIEF],STATE_IMMOBILE)
  !StateCheck([PC.0.0.THIEF],STATE_FEEBLEMINDED)
  !CheckStatGT([PC.0.0.THIEF],0,HELD)
  OR(2)
      WeaponEffectiveVs([PC.0.0.THIEF],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.THIEF],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.THIEF],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.THIEF],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Range([PC.0.0.THIEF],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC.0.0.THIEF])
END

IF
  !StateCheck([PC.0.0.BARD],STATE_INVISIBLE)
  See([PC.0.0.BARD])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.BARD],ENEMY)
  !StateCheck([PC.0.0.BARD],STATE_IMMOBILE)
  !StateCheck([PC.0.0.BARD],STATE_FEEBLEMINDED)
  !CheckStatGT([PC.0.0.BARD],0,HELD)
  OR(2)
      WeaponEffectiveVs([PC.0.0.BARD],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.BARD],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.BARD],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.BARD],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Range([PC.0.0.BARD],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC.0.0.BARD])
END

IF
  !StateCheck([PC.0.0.THIEF_ALL],STATE_INVISIBLE)
  See([PC.0.0.THIEF_ALL])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.THIEF_ALL],ENEMY)
  !StateCheck([PC.0.0.THIEF_ALL],STATE_IMMOBILE)
  !StateCheck([PC.0.0.THIEF_ALL],STATE_FEEBLEMINDED)
  !CheckStatGT([PC.0.0.THIEF_ALL],0,HELD)
  OR(2)
      WeaponEffectiveVs([PC.0.0.THIEF_ALL],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.THIEF_ALL],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.THIEF_ALL],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Range([PC.0.0.THIEF_ALL],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC.0.0.THIEF_ALL])
END

IF
  !StateCheck([PC.0.0.CLERIC],STATE_INVISIBLE)
  See([PC.0.0.CLERIC])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.CLERIC],ENEMY)
  !StateCheck([PC.0.0.CLERIC],STATE_IMMOBILE)
  !StateCheck([PC.0.0.CLERIC],STATE_FEEBLEMINDED)
  !CheckStatGT([PC.0.0.CLERIC],0,HELD)
  OR(2)
      WeaponEffectiveVs([PC.0.0.CLERIC],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.CLERIC],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.CLERIC],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.CLERIC],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Range([PC.0.0.CLERIC],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC.0.0.CLERIC])
END

IF
  !StateCheck([PC],STATE_INVISIBLE)
  See([PC])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC],ENEMY)
  !StateCheck([PC],STATE_IMMOBILE)
  !StateCheck([PC],STATE_FEEBLEMINDED)
  !CheckStatGT([PC],0,HELD)
  OR(2)
      WeaponEffectiveVs([PC],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Range([PC],4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound([PC])
END

IF
  !StateCheck(SecondNearest([PC]),STATE_INVISIBLE)
  See(SecondNearest([PC]))
  Allegiance(Myself,ENEMY)
  !Allegiance(SecondNearest([PC]),ENEMY)
  !StateCheck(SecondNearest([PC]),STATE_IMMOBILE)
  !StateCheck(SecondNearest([PC]),STATE_FEEBLEMINDED)
  !CheckStatGT(SecondNearest([PC]),0,HELD)
  OR(2)
      WeaponEffectiveVs(SecondNearest([PC]),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(SecondNearest([PC]),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(SecondNearest([PC]),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(SecondNearest([PC]),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Range(SecondNearest([PC]),4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound(SecondNearest([PC]))
END

IF
  !StateCheck(ThirdNearest([PC]),STATE_INVISIBLE)
  See(ThirdNearest([PC]))
  Allegiance(Myself,ENEMY)
  !Allegiance(ThirdNearest([PC]),ENEMY)
  !StateCheck(ThirdNearest([PC]),STATE_IMMOBILE)
  !StateCheck(ThirdNearest([PC]),STATE_FEEBLEMINDED)
  !CheckStatGT(ThirdNearest([PC]),0,HELD)
  OR(2)
      WeaponEffectiveVs(ThirdNearest([PC]),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(ThirdNearest([PC]),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(ThirdNearest([PC]),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(ThirdNearest([PC]),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Range(ThirdNearest([PC]),4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound(ThirdNearest([PC]))
END

IF
  !StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
  See(NearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(NearestEnemyOf(Myself),ENEMY)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMMOBILE)
  !StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(NearestEnemyOf(Myself),0,HELD)
  OR(2)
      WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(NearestEnemyOf(Myself),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(NearestEnemyOf(Myself),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Range(NearestEnemyOf(Myself),4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound(NearestEnemyOf(Myself))
END

IF
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_INVISIBLE)
  See(SecondNearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(SecondNearestEnemyOf(Myself),ENEMY)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMMOBILE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
  OR(2)
      WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Range(SecondNearestEnemyOf(Myself),4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound(SecondNearestEnemyOf(Myself))
END

IF
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_INVISIBLE)
  See(ThirdNearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(ThirdNearestEnemyOf(Myself),ENEMY)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMMOBILE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
  OR(2)
      WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Range(ThirdNearestEnemyOf(Myself),4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound(ThirdNearestEnemyOf(Myself))
END

IF
  !StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
  See(NearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(NearestEnemyOf(Myself),ENEMY)
  OR(2)
      WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(NearestEnemyOf(Myself),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(NearestEnemyOf(Myself),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Range(NearestEnemyOf(Myself),4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound(NearestEnemyOf(Myself))
END

IF
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_INVISIBLE)
  See(SecondNearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(SecondNearestEnemyOf(Myself),ENEMY)
  OR(2)
      WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Range(SecondNearestEnemyOf(Myself),4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound(SecondNearestEnemyOf(Myself))
END

IF
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_INVISIBLE)
  See(ThirdNearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(ThirdNearestEnemyOf(Myself),ENEMY)
  OR(2)
      WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  Range(ThirdNearestEnemyOf(Myself),4)
THEN
  RESPONSE #100
      SetGlobal("validtarget","LOCALS",1)
      SetGlobal("melee","LOCALS",1)
      EquipMostDamagingMelee()
      AttackOneRound(ThirdNearestEnemyOf(Myself))
END

IF
  !CanEquipRanged()
  ActionListEmpty()
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
  RESPONSE #100
      SetGlobalTimer("targetcompromise","LOCALS",FOUR_ROUNDS)
END

IF
  HasItem("dw#move0",Myself)  // Mirror
THEN
  RESPONSE #100
      NoAction()
END

IF
  ActionListEmpty()
  See(NearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(NearestEnemyOf(Myself),ENEMY)
  OR(2)
      WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(NearestEnemyOf(Myself),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(NearestEnemyOf(Myself),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  OR(2)
      StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
      StateCheck(NearestEnemyOf(Myself),STATE_IMMOBILE)
  Range(NearestEnemyOf(Myself),10)
THEN
  RESPONSE #100
      MoveToObject(NearestEnemyOf(Myself))
END

IF
  ActionListEmpty()
  See(SecondNearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(SecondNearestEnemyOf(Myself),ENEMY)
  OR(2)
      WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  OR(2)
      StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
      StateCheck(SecondNearestEnemyOf(Myself),STATE_IMMOBILE)
  Range(SecondNearestEnemyOf(Myself),10)
THEN
  RESPONSE #100
      MoveToObject(SecondNearestEnemyOf(Myself))
END

IF
  ActionListEmpty()
  See(ThirdNearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(ThirdNearestEnemyOf(Myself),ENEMY)
  OR(2)
      WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  OR(2)
      StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
      StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMMOBILE)
  Range(ThirdNearestEnemyOf(Myself),10)
THEN
  RESPONSE #100
      MoveToObject(ThirdNearestEnemyOf(Myself))
END

IF
  ActionListEmpty()
  See(FourthNearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(FourthNearestEnemyOf(Myself),ENEMY)
  OR(2)
      WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(FourthNearestEnemyOf(Myself),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  OR(2)
      StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
      StateCheck(FourthNearestEnemyOf(Myself),STATE_IMMOBILE)
  Range(FourthNearestEnemyOf(Myself),10)
THEN
  RESPONSE #100
      MoveToObject(FourthNearestEnemyOf(Myself))
END

IF
  ActionListEmpty()
  See(FifthNearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(FifthNearestEnemyOf(Myself),ENEMY)
  OR(2)
      WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(FifthNearestEnemyOf(Myself),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  OR(2)
      StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
      StateCheck(FifthNearestEnemyOf(Myself),STATE_IMMOBILE)
  Range(FifthNearestEnemyOf(Myself),10)
THEN
  RESPONSE #100
      MoveToObject(FifthNearestEnemyOf(Myself))
END

IF
  ActionListEmpty()
  See(SixthNearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(SixthNearestEnemyOf(Myself),ENEMY)
  OR(2)
      WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(SixthNearestEnemyOf(Myself),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(SixthNearestEnemyOf(Myself),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  OR(2)
      StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
      StateCheck(SixthNearestEnemyOf(Myself),STATE_IMMOBILE)
  Range(SixthNearestEnemyOf(Myself),10)
THEN
  RESPONSE #100
      MoveToObject(SixthNearestEnemyOf(Myself))
END

IF
  ActionListEmpty()
  See([PC.0.0.MAGE])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.MAGE],ENEMY)
  !StateCheck([PC.0.0.MAGE],STATE_DISABLED)
  !CheckStatGT([PC.0.0.MAGE],0,HELD)
  OR(2)
      WeaponEffectiveVs([PC.0.0.MAGE],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.MAGE],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.MAGE],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.MAGE],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !HPPercentGT([PC.0.0.MAGE],40)
THEN
  RESPONSE #100
      MoveToObject([PC.0.0.MAGE])
END

IF
  ActionListEmpty()
  See([PC.0.0.MAGE_THIEF])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.MAGE_THIEF],ENEMY)
  !StateCheck([PC.0.0.MAGE_THIEF],STATE_DISABLED)
  !CheckStatGT([PC.0.0.MAGE_THIEF],0,HELD)
  OR(2)
      WeaponEffectiveVs([PC.0.0.MAGE_THIEF],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.MAGE_THIEF],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.MAGE_THIEF],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.MAGE_THIEF],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !HPPercentGT([PC.0.0.MAGE_THIEF],40)
THEN
  RESPONSE #100
      MoveToObject([PC.0.0.MAGE_THIEF])
END

IF
  ActionListEmpty()
  See([PC.0.0.LONG_BOW])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.LONG_BOW],ENEMY)
  !StateCheck([PC.0.0.LONG_BOW],STATE_DISABLED)
  !CheckStatGT([PC.0.0.LONG_BOW],0,HELD)
  OR(2)
      WeaponEffectiveVs([PC.0.0.LONG_BOW],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.LONG_BOW],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.LONG_BOW],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.LONG_BOW],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !HPPercentGT([PC.0.0.LONG_BOW],40)
THEN
  RESPONSE #100
      MoveToObject([PC.0.0.LONG_BOW])
END

IF
  ActionListEmpty()
  See([PC.0.0.THIEF])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.THIEF],ENEMY)
  !StateCheck([PC.0.0.THIEF],STATE_DISABLED)
  !CheckStatGT([PC.0.0.THIEF],0,HELD)
  OR(2)
      WeaponEffectiveVs([PC.0.0.THIEF],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.THIEF],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.THIEF],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.THIEF],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !HPPercentGT([PC.0.0.THIEF],40)
THEN
  RESPONSE #100
      MoveToObject([PC.0.0.THIEF])
END

IF
  ActionListEmpty()
  See([PC.0.0.BARD])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.BARD],ENEMY)
  !StateCheck([PC.0.0.BARD],STATE_DISABLED)
  !CheckStatGT([PC.0.0.BARD],0,HELD)
  OR(2)
      WeaponEffectiveVs([PC.0.0.BARD],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.BARD],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.BARD],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.BARD],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !HPPercentGT([PC.0.0.BARD],40)
THEN
  RESPONSE #100
      MoveToObject([PC.0.0.BARD])
END

IF
  ActionListEmpty()
  See([PC.0.0.THIEF_ALL])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.THIEF_ALL],ENEMY)
  !StateCheck([PC.0.0.THIEF_ALL],STATE_DISABLED)
  !CheckStatGT([PC.0.0.THIEF_ALL],0,HELD)
  OR(2)
      WeaponEffectiveVs([PC.0.0.THIEF_ALL],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.THIEF_ALL],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.THIEF_ALL],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !HPPercentGT([PC.0.0.THIEF_ALL],40)
THEN
  RESPONSE #100
      MoveToObject([PC.0.0.THIEF_ALL])
END

IF
  ActionListEmpty()
  See([PC.0.0.CLERIC])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.CLERIC],ENEMY)
  !StateCheck([PC.0.0.CLERIC],STATE_DISABLED)
  !CheckStatGT([PC.0.0.CLERIC],0,HELD)
  OR(2)
      WeaponEffectiveVs([PC.0.0.CLERIC],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.CLERIC],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.CLERIC],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.CLERIC],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !HPPercentGT([PC.0.0.CLERIC],40)
THEN
  RESPONSE #100
      MoveToObject([PC.0.0.CLERIC])
END

IF
  ActionListEmpty()
  See([PC])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC],ENEMY)
  !StateCheck([PC],STATE_DISABLED)
  !CheckStatGT([PC],0,HELD)
  OR(2)
      WeaponEffectiveVs([PC],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !HPPercentGT([PC],40)
THEN
  RESPONSE #100
      MoveToObject([PC])
END

IF
  ActionListEmpty()
  See(SecondNearest([PC]))
  Allegiance(Myself,ENEMY)
  !Allegiance(SecondNearest([PC]),ENEMY)
  !StateCheck(SecondNearest([PC]),STATE_DISABLED)
  !CheckStatGT(SecondNearest([PC]),0,HELD)
  OR(2)
      WeaponEffectiveVs(SecondNearest([PC]),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(SecondNearest([PC]),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(SecondNearest([PC]),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(SecondNearest([PC]),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !HPPercentGT(SecondNearest([PC]),40)
THEN
  RESPONSE #100
      MoveToObject(SecondNearest([PC]))
END

IF
  ActionListEmpty()
  See(ThirdNearest([PC]))
  Allegiance(Myself,ENEMY)
  !Allegiance(ThirdNearest([PC]),ENEMY)
  !StateCheck(ThirdNearest([PC]),STATE_DISABLED)
  !CheckStatGT(ThirdNearest([PC]),0,HELD)
  OR(2)
      WeaponEffectiveVs(ThirdNearest([PC]),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(ThirdNearest([PC]),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(ThirdNearest([PC]),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(ThirdNearest([PC]),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
  !HPPercentGT(ThirdNearest([PC]),40)
THEN
  RESPONSE #100
      MoveToObject(ThirdNearest([PC]))
END

IF
  ActionListEmpty()
  See([PC.0.0.MAGE])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.MAGE],ENEMY)
  !StateCheck([PC.0.0.MAGE],STATE_DISABLED)
  !CheckStatGT([PC.0.0.MAGE],0,HELD)
  OR(2)
      WeaponEffectiveVs([PC.0.0.MAGE],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.MAGE],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.MAGE],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.MAGE],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
  RESPONSE #100
      MoveToObject([PC.0.0.MAGE])
END

IF
  ActionListEmpty()
  See([PC.0.0.MAGE_THIEF])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.MAGE_THIEF],ENEMY)
  !StateCheck([PC.0.0.MAGE_THIEF],STATE_DISABLED)
  !CheckStatGT([PC.0.0.MAGE_THIEF],0,HELD)
  OR(2)
      WeaponEffectiveVs([PC.0.0.MAGE_THIEF],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.MAGE_THIEF],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.MAGE_THIEF],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.MAGE_THIEF],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
  RESPONSE #100
      MoveToObject([PC.0.0.MAGE_THIEF])
END

IF
  ActionListEmpty()
  See([PC.0.0.LONG_BOW])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.LONG_BOW],ENEMY)
  !StateCheck([PC.0.0.LONG_BOW],STATE_DISABLED)
  !CheckStatGT([PC.0.0.LONG_BOW],0,HELD)
  OR(2)
      WeaponEffectiveVs([PC.0.0.LONG_BOW],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.LONG_BOW],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.LONG_BOW],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.LONG_BOW],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
  RESPONSE #100
      MoveToObject([PC.0.0.LONG_BOW])
END

IF
  ActionListEmpty()
  See([PC.0.0.THIEF])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.THIEF],ENEMY)
  !StateCheck([PC.0.0.THIEF],STATE_DISABLED)
  !CheckStatGT([PC.0.0.THIEF],0,HELD)
  OR(2)
      WeaponEffectiveVs([PC.0.0.THIEF],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.THIEF],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.THIEF],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.THIEF],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
  RESPONSE #100
      MoveToObject([PC.0.0.THIEF])
END

IF
  ActionListEmpty()
  See([PC.0.0.BARD])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.BARD],ENEMY)
  !StateCheck([PC.0.0.BARD],STATE_DISABLED)
  !CheckStatGT([PC.0.0.BARD],0,HELD)
  OR(2)
      WeaponEffectiveVs([PC.0.0.BARD],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.BARD],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.BARD],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.BARD],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
  RESPONSE #100
      MoveToObject([PC.0.0.BARD])
END

IF
  ActionListEmpty()
  See([PC.0.0.THIEF_ALL])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.THIEF_ALL],ENEMY)
  !StateCheck([PC.0.0.THIEF_ALL],STATE_DISABLED)
  !CheckStatGT([PC.0.0.THIEF_ALL],0,HELD)
  OR(2)
      WeaponEffectiveVs([PC.0.0.THIEF_ALL],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.THIEF_ALL],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.THIEF_ALL],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
  RESPONSE #100
      MoveToObject([PC.0.0.THIEF_ALL])
END

IF
  ActionListEmpty()
  See([PC.0.0.CLERIC])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC.0.0.CLERIC],ENEMY)
  !StateCheck([PC.0.0.CLERIC],STATE_DISABLED)
  !CheckStatGT([PC.0.0.CLERIC],0,HELD)
  OR(2)
      WeaponEffectiveVs([PC.0.0.CLERIC],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC.0.0.CLERIC],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC.0.0.CLERIC],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC.0.0.CLERIC],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
  RESPONSE #100
      MoveToObject([PC.0.0.CLERIC])
END

IF
  ActionListEmpty()
  See([PC])
  Allegiance(Myself,ENEMY)
  !Allegiance([PC],ENEMY)
  !StateCheck([PC],STATE_DISABLED)
  !CheckStatGT([PC],0,HELD)
  OR(2)
      WeaponEffectiveVs([PC],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage([PC],MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT([PC],100,RESISTCRUSHING)
  OR(2)
      CheckStatLT([PC],75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
  RESPONSE #100
      MoveToObject([PC])
END

IF
  ActionListEmpty()
  See(SecondNearest([PC]))
  Allegiance(Myself,ENEMY)
  !Allegiance(SecondNearest([PC]),ENEMY)
  !StateCheck(SecondNearest([PC]),STATE_DISABLED)
  !CheckStatGT(SecondNearest([PC]),0,HELD)
  OR(2)
      WeaponEffectiveVs(SecondNearest([PC]),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(SecondNearest([PC]),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(SecondNearest([PC]),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(SecondNearest([PC]),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
  RESPONSE #100
      MoveToObject(SecondNearest([PC]))
END

IF
  ActionListEmpty()
  See(ThirdNearest([PC]))
  Allegiance(Myself,ENEMY)
  !Allegiance(ThirdNearest([PC]),ENEMY)
  !StateCheck(ThirdNearest([PC]),STATE_DISABLED)
  !CheckStatGT(ThirdNearest([PC]),0,HELD)
  OR(2)
      WeaponEffectiveVs(ThirdNearest([PC]),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(ThirdNearest([PC]),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(ThirdNearest([PC]),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(ThirdNearest([PC]),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
  RESPONSE #100
      MoveToObject(ThirdNearest([PC]))
END

IF
  ActionListEmpty()
  See(NearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(NearestEnemyOf(Myself),ENEMY)
  !StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
  !CheckStatGT(NearestEnemyOf(Myself),0,HELD)
  OR(2)
      WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(NearestEnemyOf(Myself),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(NearestEnemyOf(Myself),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
  RESPONSE #100
      MoveToObject(NearestEnemyOf(Myself))
END

IF
  ActionListEmpty()
  See(SecondNearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(SecondNearestEnemyOf(Myself),ENEMY)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
  OR(2)
      WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
  RESPONSE #100
      MoveToObject(SecondNearestEnemyOf(Myself))
END

IF
  ActionListEmpty()
  See(ThirdNearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(ThirdNearestEnemyOf(Myself),ENEMY)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
  OR(2)
      WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
  RESPONSE #100
      MoveToObject(ThirdNearestEnemyOf(Myself))
END

IF
  ActionListEmpty()
  See(FourthNearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(FourthNearestEnemyOf(Myself),ENEMY)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
  OR(2)
      WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(FourthNearestEnemyOf(Myself),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
  RESPONSE #100
      MoveToObject(FourthNearestEnemyOf(Myself))
END

IF
  ActionListEmpty()
  See(FifthNearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(FifthNearestEnemyOf(Myself),ENEMY)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
  OR(2)
      WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(FifthNearestEnemyOf(Myself),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
  RESPONSE #100
      MoveToObject(FifthNearestEnemyOf(Myself))
END

IF
  ActionListEmpty()
  See(SixthNearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(SixthNearestEnemyOf(Myself),ENEMY)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
  OR(2)
      WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  CheckStatLT(SixthNearestEnemyOf(Myself),100,RESISTCRUSHING)
  OR(2)
      CheckStatLT(SixthNearestEnemyOf(Myself),75,RESISTCRUSHING)
      GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
  RESPONSE #100
      MoveToObject(SixthNearestEnemyOf(Myself))
END

IF
  !StateCheck(Player4,STATE_INVISIBLE)
  ActionListEmpty()
  See(Player4)
  Allegiance(Myself,ENEMY)
  OR(2)
      WeaponEffectiveVs(Player4,MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(Player4,MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
THEN
  RESPONSE #100
      EquipMostDamagingMelee()
      SetGlobal("melee","LOCALS",1)
      AttackOneRound(Player4)
END

IF
  !StateCheck(Player5,STATE_INVISIBLE)
  ActionListEmpty()
  See(Player5)
  Allegiance(Myself,ENEMY)
  OR(2)
      WeaponEffectiveVs(Player5,MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(Player5,MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
THEN
  RESPONSE #100
      EquipMostDamagingMelee()
      SetGlobal("melee","LOCALS",1)
      AttackOneRound(Player5)
END

IF
  !StateCheck(Player6,STATE_INVISIBLE)
  ActionListEmpty()
  See(Player6)
  Allegiance(Myself,ENEMY)
  OR(2)
      WeaponEffectiveVs(Player6,MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(Player6,MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
THEN
  RESPONSE #100
      EquipMostDamagingMelee()
      SetGlobal("melee","LOCALS",1)
      AttackOneRound(Player6)
END

IF
  !StateCheck(Player3,STATE_INVISIBLE)
  ActionListEmpty()
  See(Player3)
  Allegiance(Myself,ENEMY)
  OR(2)
      WeaponEffectiveVs(Player3,MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(Player3,MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
THEN
  RESPONSE #100
      EquipMostDamagingMelee()
      SetGlobal("melee","LOCALS",1)
      AttackOneRound(Player3)
END

IF
  !StateCheck(Player2,STATE_INVISIBLE)
  ActionListEmpty()
  See(Player2)
  Allegiance(Myself,ENEMY)
  OR(2)
      WeaponEffectiveVs(Player2,MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(Player2,MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
THEN
  RESPONSE #100
      EquipMostDamagingMelee()
      SetGlobal("melee","LOCALS",1)
      AttackOneRound(Player2)
END

IF
  !StateCheck(Player1,STATE_INVISIBLE)
  ActionListEmpty()
  See(Player1)
  Allegiance(Myself,ENEMY)
  OR(2)
      WeaponEffectiveVs(Player1,MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(Player1,MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
THEN
  RESPONSE #100
      EquipMostDamagingMelee()
      SetGlobal("melee","LOCALS",1)
      AttackOneRound(Player1)
END

IF
  !StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
  ActionListEmpty()
  See(NearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
  OR(2)
      WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
  OR(2)
      WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
      GlobalTimerNotExpired("seedefences","LOCALS")
THEN
  RESPONSE #100
      EquipMostDamagingMelee()
      SetGlobal("melee","LOCALS",1)
      AttackOneRound(NearestEnemyOf(Myself))
END

IF
  !StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
  ActionListEmpty()
  See(NearestEnemyOf(Myself))
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
      EquipMostDamagingMelee()
      SetGlobal("melee","LOCALS",1)
      AttackOneRound(NearestEnemyOf(Myself))
END

