// Initiate dialog
IF
	Global("JA#DIALOG","LOCALS",0)
	OR(4)
		Name("MEIALA",Myself)
		Name("NTSILUA",Myself)
		Name("SIL",Myself)
		Name("LARRIA",Myself)
	NumTimesTalkedTo(0)
	See([PC])
THEN
	RESPONSE #100
		SetGlobal("JA#DIALOG","LOCALS",1)
		FaceObject([PC])
		StartDialogueNoSet([PC])
END

// Init
IF
	Global("JA#INIT","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("JA#INIT","LOCALS",1)
		SetGlobal("JA#COMBAT","LOCALS",0)
		SetGlobalTimer("JA#REST","LOCALS",2400)
END

// Rest (reset everything and heal if applicable)
IF
	Global("JA#INIT","LOCALS",1)
	GlobalTimerExpired("JA#REST","LOCALS")
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA#INIT","LOCALS",0)
		Rest()
		ApplySpell(Myself,RESTORE_FULL_HEALTH)
END

// Turn hostile if attacked
IF
	Allegiance(Myself,NEUTRAL)
	OR(4)
		AttackedBy([GOODCUTOFF],DEFAULT)
		SpellCastOnMe([GOODCUTOFF],0)
		TookDamage()
		Heard([EVILCUTOFF.0.FAIRY],99)
THEN
	RESPONSE #100
		Enemy()
END

// Detect combat
IF
	Global("JA#COMBAT","LOCALS",0)
	Allegiance(Myself,EVILCUTOFF)
	See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
END

// Detect combat
IF
	Global("JA#COMBAT","LOCALS",0)
	Allegiance(Myself,GOODCUTOFF)
	See([EVILCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
END

// Shouts every 3 rounds
IF
	Global("JA#COMBAT","LOCALS",1)
	!GlobalTimerNotExpired("JA#HELP","LOCALS")
THEN
	RESPONSE #100
		Shout(99)
		SetGlobalTimer("JA#HELP","LOCALS",18)
END

// React to shouts
IF
	Global("JA#COMBAT","LOCALS",0)
	Heard([EVILCUTOFF.0.FAIRY],99)
	InMyArea([EVILCUTOFF.0.FAIRY])
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
		MoveToObject(LastHeardBy(Myself))
END

IF
	Global("JA#COMBAT","LOCALS",1)
	Heard([EVILCUTOFF.0.FAIRY],99)
	InMyArea([EVILCUTOFF.0.FAIRY])
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		MoveToObject(LastHeardBy(Myself))
END

// Do nothing if...
IF
	OR(4)
		Global("JA#COMBAT","LOCALS",0)
		!Allegiance(Myself,EVILCUTOFF)
		StateCheck(Myself,STATE_IMMOBILE)
		StateCheck(Myself,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		NoAction()
END

IF
	!InActiveArea(Myself)
	!Range(NearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		NoAction()
END

// Random walk on panic
IF
	StateCheck(Myself,STATE_PANIC)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

// Dire Charm
IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race([PC.0.0.FIGHTER_ALL],ELF)
	!Race([PC.0.0.FIGHTER_ALL],HALF_ELF)
	!CheckStatGT([PC.0.0.FIGHTER_ALL],0,HELD)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_STUNNED)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_PANIC)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_CONFUSED)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_FEEBLEMINDED)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_SLEEPING)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_HELPLESS)
	!General([PC.0.0.FIGHTER_ALL],WEAPON)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_IMPROVEDINVISIBILITY)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_INVISIBLE)
	!CheckStatGT([PC.0.0.FIGHTER_ALL],0,SANCTUARY)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_REALLY_DEAD)
	See([PC.0.0.FIGHTER_ALL])
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SecondNearest([PC.0.0.FIGHTER_ALL]),ELF)
	!Race(SecondNearest([PC.0.0.FIGHTER_ALL]),HALF_ELF)
	!CheckStatGT(SecondNearest([PC.0.0.FIGHTER_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_HELPLESS)
	!General(SecondNearest([PC.0.0.FIGHTER_ALL]),WEAPON)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_INVISIBLE)
	!CheckStatGT(SecondNearest([PC.0.0.FIGHTER_ALL]),0,SANCTUARY)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_REALLY_DEAD)
	See(SecondNearest([PC.0.0.FIGHTER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(ThirdNearest([PC.0.0.FIGHTER_ALL]),ELF)
	!Race(ThirdNearest([PC.0.0.FIGHTER_ALL]),HALF_ELF)
	!CheckStatGT(ThirdNearest([PC.0.0.FIGHTER_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_HELPLESS)
	!General(ThirdNearest([PC.0.0.FIGHTER_ALL]),WEAPON)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_INVISIBLE)
	!CheckStatGT(ThirdNearest([PC.0.0.FIGHTER_ALL]),0,SANCTUARY)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_REALLY_DEAD)
	See(ThirdNearest([PC.0.0.FIGHTER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race([PC.0.0.RANGER_ALL],ELF)
	!Race([PC.0.0.RANGER_ALL],HALF_ELF)
	!CheckStatGT([PC.0.0.RANGER_ALL],0,HELD)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_STUNNED)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_PANIC)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_CONFUSED)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_FEEBLEMINDED)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_SLEEPING)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_HELPLESS)
	!General([PC.0.0.RANGER_ALL],WEAPON)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_IMPROVEDINVISIBILITY)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_INVISIBLE)
	!CheckStatGT([PC.0.0.RANGER_ALL],0,SANCTUARY)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_REALLY_DEAD)
	See([PC.0.0.RANGER_ALL])
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SecondNearest([PC.0.0.RANGER_ALL]),ELF)
	!Race(SecondNearest([PC.0.0.RANGER_ALL]),HALF_ELF)
	!CheckStatGT(SecondNearest([PC.0.0.RANGER_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_HELPLESS)
	!General(SecondNearest([PC.0.0.RANGER_ALL]),WEAPON)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_INVISIBLE)
	!CheckStatGT(SecondNearest([PC.0.0.RANGER_ALL]),0,SANCTUARY)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_REALLY_DEAD)
	See(SecondNearest([PC.0.0.RANGER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(ThirdNearest([PC.0.0.RANGER_ALL]),ELF)
	!Race(ThirdNearest([PC.0.0.RANGER_ALL]),HALF_ELF)
	!CheckStatGT(ThirdNearest([PC.0.0.RANGER_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_HELPLESS)
	!General(ThirdNearest([PC.0.0.RANGER_ALL]),WEAPON)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_INVISIBLE)
	!CheckStatGT(ThirdNearest([PC.0.0.RANGER_ALL]),0,SANCTUARY)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_REALLY_DEAD)
	See(ThirdNearest([PC.0.0.RANGER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race([PC.0.0.PALADIN_ALL],ELF)
	!Race([PC.0.0.PALADIN_ALL],HALF_ELF)
	!CheckStatGT([PC.0.0.PALADIN_ALL],0,HELD)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_STUNNED)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_PANIC)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_CONFUSED)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_FEEBLEMINDED)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_SLEEPING)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_HELPLESS)
	!General([PC.0.0.PALADIN_ALL],WEAPON)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_IMPROVEDINVISIBILITY)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_INVISIBLE)
	!CheckStatGT([PC.0.0.PALADIN_ALL],0,SANCTUARY)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_REALLY_DEAD)
	See([PC.0.0.PALADIN_ALL])
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SecondNearest([PC.0.0.PALADIN_ALL]),ELF)
	!Race(SecondNearest([PC.0.0.PALADIN_ALL]),HALF_ELF)
	!CheckStatGT(SecondNearest([PC.0.0.PALADIN_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
	!General(SecondNearest([PC.0.0.PALADIN_ALL]),WEAPON)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_INVISIBLE)
	!CheckStatGT(SecondNearest([PC.0.0.PALADIN_ALL]),0,SANCTUARY)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_REALLY_DEAD)
	See(SecondNearest([PC.0.0.PALADIN_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(ThirdNearest([PC.0.0.PALADIN_ALL]),ELF)
	!Race(ThirdNearest([PC.0.0.PALADIN_ALL]),HALF_ELF)
	!CheckStatGT(ThirdNearest([PC.0.0.PALADIN_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
	!General(ThirdNearest([PC.0.0.PALADIN_ALL]),WEAPON)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_INVISIBLE)
	!CheckStatGT(ThirdNearest([PC.0.0.PALADIN_ALL]),0,SANCTUARY)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_REALLY_DEAD)
	See(ThirdNearest([PC.0.0.PALADIN_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

// Dire Charm
IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race([PC],ELF)
	!Race([PC],HALF_ELF)
	!CheckStatGT([PC],0,HELD)
	!StateCheck([PC],STATE_STUNNED)
	!StateCheck([PC],STATE_PANIC)
	!StateCheck([PC],STATE_CONFUSED)
	!StateCheck([PC],STATE_FEEBLEMINDED)
	!StateCheck([PC],STATE_SLEEPING)
	!StateCheck([PC],STATE_HELPLESS)
	!General([PC],WEAPON)
	!StateCheck([PC],STATE_IMPROVEDINVISIBILITY)
	!StateCheck([PC],STATE_INVISIBLE)
	!CheckStatGT([PC],0,SANCTUARY)
	!StateCheck([PC],STATE_REALLY_DEAD)
	See([PC])
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SecondNearest([PC]),ELF)
	!Race(SecondNearest([PC]),HALF_ELF)
	!CheckStatGT(SecondNearest([PC]),0,HELD)
	!StateCheck(SecondNearest([PC]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC]),STATE_PANIC)
	!StateCheck(SecondNearest([PC]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC]),STATE_HELPLESS)
	!General(SecondNearest([PC]),WEAPON)
	!StateCheck(SecondNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(SecondNearest([PC]),STATE_INVISIBLE)
	!CheckStatGT(SecondNearest([PC]),0,SANCTUARY)
	!StateCheck(SecondNearest([PC]),STATE_REALLY_DEAD)
	See(SecondNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(ThirdNearest([PC]),ELF)
	!Race(ThirdNearest([PC]),HALF_ELF)
	!CheckStatGT(ThirdNearest([PC]),0,HELD)
	!StateCheck(ThirdNearest([PC]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC]),STATE_HELPLESS)
	!General(ThirdNearest([PC]),WEAPON)
	!StateCheck(ThirdNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(ThirdNearest([PC]),STATE_INVISIBLE)
	!CheckStatGT(ThirdNearest([PC]),0,SANCTUARY)
	!StateCheck(ThirdNearest([PC]),STATE_REALLY_DEAD)
	See(ThirdNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(FourthNearest([PC]),ELF)
	!Race(FourthNearest([PC]),HALF_ELF)
	!CheckStatGT(FourthNearest([PC]),0,HELD)
	!StateCheck(FourthNearest([PC]),STATE_STUNNED)
	!StateCheck(FourthNearest([PC]),STATE_PANIC)
	!StateCheck(FourthNearest([PC]),STATE_CONFUSED)
	!StateCheck(FourthNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(FourthNearest([PC]),STATE_SLEEPING)
	!StateCheck(FourthNearest([PC]),STATE_HELPLESS)
	!General(FourthNearest([PC]),WEAPON)
	!StateCheck(FourthNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(FourthNearest([PC]),STATE_INVISIBLE)
	!CheckStatGT(FourthNearest([PC]),0,SANCTUARY)
	!StateCheck(FourthNearest([PC]),STATE_REALLY_DEAD)
	See(FourthNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(FifthNearest([PC]),ELF)
	!Race(FifthNearest([PC]),HALF_ELF)
	!CheckStatGT(FifthNearest([PC]),0,HELD)
	!StateCheck(FifthNearest([PC]),STATE_STUNNED)
	!StateCheck(FifthNearest([PC]),STATE_PANIC)
	!StateCheck(FifthNearest([PC]),STATE_CONFUSED)
	!StateCheck(FifthNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(FifthNearest([PC]),STATE_SLEEPING)
	!StateCheck(FifthNearest([PC]),STATE_HELPLESS)
	!General(FifthNearest([PC]),WEAPON)
	!StateCheck(FifthNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(FifthNearest([PC]),STATE_INVISIBLE)
	!CheckStatGT(FifthNearest([PC]),0,SANCTUARY)
	!StateCheck(FifthNearest([PC]),STATE_REALLY_DEAD)
	See(FifthNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SixthNearest([PC]),ELF)
	!Race(SixthNearest([PC]),HALF_ELF)
	!CheckStatGT(SixthNearest([PC]),0,HELD)
	!StateCheck(SixthNearest([PC]),STATE_STUNNED)
	!StateCheck(SixthNearest([PC]),STATE_PANIC)
	!StateCheck(SixthNearest([PC]),STATE_CONFUSED)
	!StateCheck(SixthNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(SixthNearest([PC]),STATE_SLEEPING)
	!StateCheck(SixthNearest([PC]),STATE_HELPLESS)
	!General(SixthNearest([PC]),WEAPON)
	!StateCheck(SixthNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(SixthNearest([PC]),STATE_INVISIBLE)
	!CheckStatGT(SixthNearest([PC]),0,SANCTUARY)
	!StateCheck(SixthNearest([PC]),STATE_REALLY_DEAD)
	See(SixthNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

// Dire Charm
IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race([PC.0.0.FIGHTER_ALL],ELF)
	!CheckStatGT([PC.0.0.FIGHTER_ALL],0,HELD)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_STUNNED)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_PANIC)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_CONFUSED)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_FEEBLEMINDED)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_SLEEPING)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_HELPLESS)
	!General([PC.0.0.FIGHTER_ALL],WEAPON)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_IMPROVEDINVISIBILITY)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_INVISIBLE)
	!CheckStatGT([PC.0.0.FIGHTER_ALL],0,SANCTUARY)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_REALLY_DEAD)
	See([PC.0.0.FIGHTER_ALL])
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SecondNearest([PC.0.0.FIGHTER_ALL]),ELF)
	!CheckStatGT(SecondNearest([PC.0.0.FIGHTER_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_HELPLESS)
	!General(SecondNearest([PC.0.0.FIGHTER_ALL]),WEAPON)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_INVISIBLE)
	!CheckStatGT(SecondNearest([PC.0.0.FIGHTER_ALL]),0,SANCTUARY)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_REALLY_DEAD)
	See(SecondNearest([PC.0.0.FIGHTER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(ThirdNearest([PC.0.0.FIGHTER_ALL]),ELF)
	!CheckStatGT(ThirdNearest([PC.0.0.FIGHTER_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_HELPLESS)
	!General(ThirdNearest([PC.0.0.FIGHTER_ALL]),WEAPON)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_INVISIBLE)
	!CheckStatGT(ThirdNearest([PC.0.0.FIGHTER_ALL]),0,SANCTUARY)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_REALLY_DEAD)
	See(ThirdNearest([PC.0.0.FIGHTER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race([PC.0.0.RANGER_ALL],ELF)
	!CheckStatGT([PC.0.0.RANGER_ALL],0,HELD)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_STUNNED)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_PANIC)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_CONFUSED)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_FEEBLEMINDED)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_SLEEPING)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_HELPLESS)
	!General([PC.0.0.RANGER_ALL],WEAPON)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_IMPROVEDINVISIBILITY)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_INVISIBLE)
	!CheckStatGT([PC.0.0.RANGER_ALL],0,SANCTUARY)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_REALLY_DEAD)
	See([PC.0.0.RANGER_ALL])
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SecondNearest([PC.0.0.RANGER_ALL]),ELF)
	!CheckStatGT(SecondNearest([PC.0.0.RANGER_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_HELPLESS)
	!General(SecondNearest([PC.0.0.RANGER_ALL]),WEAPON)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_INVISIBLE)
	!CheckStatGT(SecondNearest([PC.0.0.RANGER_ALL]),0,SANCTUARY)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_REALLY_DEAD)
	See(SecondNearest([PC.0.0.RANGER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(ThirdNearest([PC.0.0.RANGER_ALL]),ELF)
	!CheckStatGT(ThirdNearest([PC.0.0.RANGER_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_HELPLESS)
	!General(ThirdNearest([PC.0.0.RANGER_ALL]),WEAPON)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_INVISIBLE)
	!CheckStatGT(ThirdNearest([PC.0.0.RANGER_ALL]),0,SANCTUARY)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_REALLY_DEAD)
	See(ThirdNearest([PC.0.0.RANGER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race([PC.0.0.PALADIN_ALL],ELF)
	!CheckStatGT([PC.0.0.PALADIN_ALL],0,HELD)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_STUNNED)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_PANIC)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_CONFUSED)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_FEEBLEMINDED)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_SLEEPING)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_HELPLESS)
	!General([PC.0.0.PALADIN_ALL],WEAPON)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_IMPROVEDINVISIBILITY)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_INVISIBLE)
	!CheckStatGT([PC.0.0.PALADIN_ALL],0,SANCTUARY)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_REALLY_DEAD)
	See([PC.0.0.PALADIN_ALL])
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SecondNearest([PC.0.0.PALADIN_ALL]),ELF)
	!CheckStatGT(SecondNearest([PC.0.0.PALADIN_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
	!General(SecondNearest([PC.0.0.PALADIN_ALL]),WEAPON)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_INVISIBLE)
	!CheckStatGT(SecondNearest([PC.0.0.PALADIN_ALL]),0,SANCTUARY)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_REALLY_DEAD)
	See(SecondNearest([PC.0.0.PALADIN_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(ThirdNearest([PC.0.0.PALADIN_ALL]),ELF)
	!CheckStatGT(ThirdNearest([PC.0.0.PALADIN_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
	!General(ThirdNearest([PC.0.0.PALADIN_ALL]),WEAPON)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_INVISIBLE)
	!CheckStatGT(ThirdNearest([PC.0.0.PALADIN_ALL]),0,SANCTUARY)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_REALLY_DEAD)
	See(ThirdNearest([PC.0.0.PALADIN_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

// Dire Charm
IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!CheckStatGT([PC],0,HELD)
	!StateCheck([PC],STATE_STUNNED)
	!StateCheck([PC],STATE_PANIC)
	!StateCheck([PC],STATE_CONFUSED)
	!StateCheck([PC],STATE_FEEBLEMINDED)
	!StateCheck([PC],STATE_SLEEPING)
	!StateCheck([PC],STATE_HELPLESS)
	!General([PC],WEAPON)
	!StateCheck([PC],STATE_IMPROVEDINVISIBILITY)
	!StateCheck([PC],STATE_INVISIBLE)
	!CheckStatGT([PC],0,SANCTUARY)
	!StateCheck([PC],STATE_REALLY_DEAD)
	See([PC])
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!CheckStatGT(SecondNearest([PC]),0,HELD)
	!StateCheck(SecondNearest([PC]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC]),STATE_PANIC)
	!StateCheck(SecondNearest([PC]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC]),STATE_HELPLESS)
	!General(SecondNearest([PC]),WEAPON)
	!StateCheck(SecondNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(SecondNearest([PC]),STATE_INVISIBLE)
	!CheckStatGT(SecondNearest([PC]),0,SANCTUARY)
	!StateCheck(SecondNearest([PC]),STATE_REALLY_DEAD)
	See(SecondNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!CheckStatGT(ThirdNearest([PC]),0,HELD)
	!StateCheck(ThirdNearest([PC]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC]),STATE_HELPLESS)
	!General(ThirdNearest([PC]),WEAPON)
	!StateCheck(ThirdNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(ThirdNearest([PC]),STATE_INVISIBLE)
	!CheckStatGT(ThirdNearest([PC]),0,SANCTUARY)
	!StateCheck(ThirdNearest([PC]),STATE_REALLY_DEAD)
	See(ThirdNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!CheckStatGT(FourthNearest([PC]),0,HELD)
	!StateCheck(FourthNearest([PC]),STATE_STUNNED)
	!StateCheck(FourthNearest([PC]),STATE_PANIC)
	!StateCheck(FourthNearest([PC]),STATE_CONFUSED)
	!StateCheck(FourthNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(FourthNearest([PC]),STATE_SLEEPING)
	!StateCheck(FourthNearest([PC]),STATE_HELPLESS)
	!General(FourthNearest([PC]),WEAPON)
	!StateCheck(FourthNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(FourthNearest([PC]),STATE_INVISIBLE)
	!CheckStatGT(FourthNearest([PC]),0,SANCTUARY)
	!StateCheck(FourthNearest([PC]),STATE_REALLY_DEAD)
	See(FourthNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!CheckStatGT(FifthNearest([PC]),0,HELD)
	!StateCheck(FifthNearest([PC]),STATE_STUNNED)
	!StateCheck(FifthNearest([PC]),STATE_PANIC)
	!StateCheck(FifthNearest([PC]),STATE_CONFUSED)
	!StateCheck(FifthNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(FifthNearest([PC]),STATE_SLEEPING)
	!StateCheck(FifthNearest([PC]),STATE_HELPLESS)
	!General(FifthNearest([PC]),WEAPON)
	!StateCheck(FifthNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(FifthNearest([PC]),STATE_INVISIBLE)
	!CheckStatGT(FifthNearest([PC]),0,SANCTUARY)
	!StateCheck(FifthNearest([PC]),STATE_REALLY_DEAD)
	See(FifthNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fcsng")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!CheckStatGT(SixthNearest([PC]),0,HELD)
	!StateCheck(SixthNearest([PC]),STATE_STUNNED)
	!StateCheck(SixthNearest([PC]),STATE_PANIC)
	!StateCheck(SixthNearest([PC]),STATE_CONFUSED)
	!StateCheck(SixthNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(SixthNearest([PC]),STATE_SLEEPING)
	!StateCheck(SixthNearest([PC]),STATE_HELPLESS)
	!General(SixthNearest([PC]),WEAPON)
	!StateCheck(SixthNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(SixthNearest([PC]),STATE_INVISIBLE)
	!CheckStatGT(SixthNearest([PC]),0,SANCTUARY)
	!StateCheck(SixthNearest([PC]),STATE_REALLY_DEAD)
	See(SixthNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fcsng",LastSeenBy(Myself))
		RemoveSpellRES("rr#fcsng")
		SetInterrupt(TRUE)
END

// Touch of Tranquility (The touch is automatic for charmed individuals)
IF
	CheckStat(Myself,0,POLYMORPHED)
	!GlobalTimerNotExpired("Touch","LOCALS")
	HaveSpellRES("rr#ftrnq")
	StateCheck(NearestAllyOf(Myself),STATE_CHARMED)
	!See(NearestEnemyOf(Myself))
	!CheckStatGT(NearestAllyOf(Myself),0,HELD)
	!StateCheck(NearestAllyOf(Myself),STATE_STUNNED)
	!StateCheck(NearestAllyOf(Myself),STATE_PANIC)
	!StateCheck(NearestAllyOf(Myself),STATE_CONFUSED)
	!StateCheck(NearestAllyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(NearestAllyOf(Myself),STATE_SLEEPING)
	!StateCheck(NearestAllyOf(Myself),STATE_HELPLESS)
	!General(NearestAllyOf(Myself),WEAPON)
	!StateCheck(NearestAllyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(NearestAllyOf(Myself),STATE_INVISIBLE)
	!CheckStatGT(NearestAllyOf(Myself),0,SANCTUARY)
	!StateCheck(NearestAllyOf(Myself),STATE_REALLY_DEAD)
	See(NearestAllyOf(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("Touch","LOCALS",6)
		EquipMostDamagingMelee()
		MoveToObjectNoInterrupt(LastSeenBy(Myself))
		ForceSpellRES("rr#ftrnq",LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!GlobalTimerNotExpired("Touch","LOCALS")
	HaveSpellRES("rr#ftrnq")
	StateCheck(SecondNearestAllyOf(Myself),STATE_CHARMED)
	!See(NearestEnemyOf(Myself))
	!CheckStatGT(SecondNearestAllyOf(Myself),0,HELD)
	!StateCheck(SecondNearestAllyOf(Myself),STATE_STUNNED)
	!StateCheck(SecondNearestAllyOf(Myself),STATE_PANIC)
	!StateCheck(SecondNearestAllyOf(Myself),STATE_CONFUSED)
	!StateCheck(SecondNearestAllyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearestAllyOf(Myself),STATE_SLEEPING)
	!StateCheck(SecondNearestAllyOf(Myself),STATE_HELPLESS)
	!General(SecondNearestAllyOf(Myself),WEAPON)
	!StateCheck(SecondNearestAllyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(SecondNearestAllyOf(Myself),STATE_INVISIBLE)
	!CheckStatGT(SecondNearestAllyOf(Myself),0,SANCTUARY)
	!StateCheck(SecondNearestAllyOf(Myself),STATE_REALLY_DEAD)
	See(SecondNearestAllyOf(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("Touch","LOCALS",6)
		EquipMostDamagingMelee()
		MoveToObjectNoInterrupt(LastSeenBy(Myself))
		ForceSpellRES("rr#ftrnq",LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!GlobalTimerNotExpired("Touch","LOCALS")
	HaveSpellRES("rr#ftrnq")
	StateCheck(ThirdNearestAllyOf(Myself),STATE_CHARMED)
	!See(NearestEnemyOf(Myself))
	!CheckStatGT(ThirdNearestAllyOf(Myself),0,HELD)
	!StateCheck(ThirdNearestAllyOf(Myself),STATE_STUNNED)
	!StateCheck(ThirdNearestAllyOf(Myself),STATE_PANIC)
	!StateCheck(ThirdNearestAllyOf(Myself),STATE_CONFUSED)
	!StateCheck(ThirdNearestAllyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearestAllyOf(Myself),STATE_SLEEPING)
	!StateCheck(ThirdNearestAllyOf(Myself),STATE_HELPLESS)
	!General(ThirdNearestAllyOf(Myself),WEAPON)
	!StateCheck(ThirdNearestAllyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(ThirdNearestAllyOf(Myself),STATE_INVISIBLE)
	!CheckStatGT(ThirdNearestAllyOf(Myself),0,SANCTUARY)
	!StateCheck(ThirdNearestAllyOf(Myself),STATE_REALLY_DEAD)
	See(ThirdNearestAllyOf(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("Touch","LOCALS",6)
		EquipMostDamagingMelee()
		MoveToObjectNoInterrupt(LastSeenBy(Myself))
		ForceSpellRES("rr#ftrnq",LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!GlobalTimerNotExpired("Touch","LOCALS")
	HaveSpellRES("rr#ftrnq")
	StateCheck(FourthNearestAllyOf(Myself),STATE_CHARMED)
	!See(NearestEnemyOf(Myself))
	!CheckStatGT(FourthNearestAllyOf(Myself),0,HELD)
	!StateCheck(FourthNearestAllyOf(Myself),STATE_STUNNED)
	!StateCheck(FourthNearestAllyOf(Myself),STATE_PANIC)
	!StateCheck(FourthNearestAllyOf(Myself),STATE_CONFUSED)
	!StateCheck(FourthNearestAllyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(FourthNearestAllyOf(Myself),STATE_SLEEPING)
	!StateCheck(FourthNearestAllyOf(Myself),STATE_HELPLESS)
	!General(FourthNearestAllyOf(Myself),WEAPON)
	!StateCheck(FourthNearestAllyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(FourthNearestAllyOf(Myself),STATE_INVISIBLE)
	!CheckStatGT(FourthNearestAllyOf(Myself),0,SANCTUARY)
	!StateCheck(FourthNearestAllyOf(Myself),STATE_REALLY_DEAD)
	See(FourthNearestAllyOf(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("Touch","LOCALS",6)
		EquipMostDamagingMelee()
		MoveToObjectNoInterrupt(LastSeenBy(Myself))
		ForceSpellRES("rr#ftrnq",LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!GlobalTimerNotExpired("Touch","LOCALS")
	HaveSpellRES("rr#ftrnq")
	StateCheck(FifthNearestAllyOf(Myself),STATE_CHARMED)
	!See(NearestEnemyOf(Myself))
	!CheckStatGT(FifthNearestAllyOf(Myself),0,HELD)
	!StateCheck(FifthNearestAllyOf(Myself),STATE_STUNNED)
	!StateCheck(FifthNearestAllyOf(Myself),STATE_PANIC)
	!StateCheck(FifthNearestAllyOf(Myself),STATE_CONFUSED)
	!StateCheck(FifthNearestAllyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(FifthNearestAllyOf(Myself),STATE_SLEEPING)
	!StateCheck(FifthNearestAllyOf(Myself),STATE_HELPLESS)
	!General(FifthNearestAllyOf(Myself),WEAPON)
	!StateCheck(FifthNearestAllyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(FifthNearestAllyOf(Myself),STATE_INVISIBLE)
	!CheckStatGT(FifthNearestAllyOf(Myself),0,SANCTUARY)
	!StateCheck(FifthNearestAllyOf(Myself),STATE_REALLY_DEAD)
	See(FifthNearestAllyOf(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("Touch","LOCALS",6)
		EquipMostDamagingMelee()
		MoveToObjectNoInterrupt(LastSeenBy(Myself))
		ForceSpellRES("rr#ftrnq",LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	CheckStat(Myself,0,POLYMORPHED)
	!GlobalTimerNotExpired("Touch","LOCALS")
	HaveSpellRES("rr#ftrnq")
	StateCheck(SixthNearestAllyOf(Myself),STATE_CHARMED)
	!See(NearestEnemyOf(Myself))
	!CheckStatGT(SixthNearestAllyOf(Myself),0,HELD)
	!StateCheck(SixthNearestAllyOf(Myself),STATE_STUNNED)
	!StateCheck(SixthNearestAllyOf(Myself),STATE_PANIC)
	!StateCheck(SixthNearestAllyOf(Myself),STATE_CONFUSED)
	!StateCheck(SixthNearestAllyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(SixthNearestAllyOf(Myself),STATE_SLEEPING)
	!StateCheck(SixthNearestAllyOf(Myself),STATE_HELPLESS)
	!General(SixthNearestAllyOf(Myself),WEAPON)
	!StateCheck(SixthNearestAllyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(SixthNearestAllyOf(Myself),STATE_INVISIBLE)
	!CheckStatGT(SixthNearestAllyOf(Myself),0,SANCTUARY)
	!StateCheck(SixthNearestAllyOf(Myself),STATE_REALLY_DEAD)
	See(SixthNearestAllyOf(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("Touch","LOCALS",6)
		EquipMostDamagingMelee()
		MoveToObjectNoInterrupt(LastSeenBy(Myself))
		ForceSpellRES("rr#ftrnq",LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

// Track players if allegiance is not GOODCUTOFF
IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player1)
	Range(Player1,150)
	HaveSpellRES("rr#fchrm")
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStatGT(Player1,0,SANCTUARY)
	!StateCheck(Player1,STATE_CHARMED)
	!StateCheck(Player1,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player2)
	Range(Player2,150)
	HaveSpellRES("rr#fchrm")
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStatGT(Player2,0,SANCTUARY)
	!StateCheck(Player2,STATE_CHARMED)
	!StateCheck(Player2,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player3)
	Range(Player3,150)
	HaveSpellRES("rr#fchrm")
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStatGT(Player3,0,SANCTUARY)
	!StateCheck(Player3,STATE_CHARMED)
	!StateCheck(Player3,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player4)
	Range(Player4,150)
	HaveSpellRES("rr#fchrm")
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStatGT(Player4,0,SANCTUARY)
	!StateCheck(Player4,STATE_CHARMED)
	!StateCheck(Player4,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player5)
	Range(Player5,150)
	HaveSpellRES("rr#fchrm")
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStatGT(Player5,0,SANCTUARY)
	!StateCheck(Player5,STATE_CHARMED)
	!StateCheck(Player5,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player6)
	Range(Player6,150)
	HaveSpellRES("rr#fchrm")
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStatGT(Player6,0,SANCTUARY)
	!StateCheck(Player6,STATE_CHARMED)
	!StateCheck(Player6,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

// Track last seen enemy if allegiance is GOODCUTOFF
IF
	Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(LastSeenBy(Myself))
	Range(LastSeenBy(Myself),150)
	HaveSpellRES("rr#fchrm")
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

// Open door
IF
	Global("RR#NOPND","GLOBAL",0)
	Allegiance(Myself,EVILCUTOFF)
	!AreaType(OUTDOOR)
	!Range(NearestEnemyOf(Myself),30)
	Range(NearestDoor,15)
	OpenState(NearestDoor,FALSE)
THEN
	RESPONSE #100
		MoveToObject(NearestDoor)
		OpenDoor(NearestDoor)
END

// Random walking (in combat) 
IF
	Global("JA#COMBAT","LOCALS",1)
	ActionListEmpty()
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		RandomWalk()
		Wait(2)
END

// Random facing
IF
	!Range(NearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		RandomTurn()
END

