// Dryad

// Initiate dialog
IF
	Global("JA#DIALOG","LOCALS",0)
	OR(3)
		Name("CDryad",Myself)
		Name("Ulene",Myself)
		Name("L#APEST",Myself)
	NumTimesTalkedTo(0)
	See([PC])
THEN
	RESPONSE #100
		SetGlobal("JA#DIALOG","LOCALS",1)
		FaceObject([PC])
		StartDialogueNoSet([PC])
END

// Init
IF
	Global("JA#INIT","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("JA#INIT","LOCALS",1)
		SetGlobal("JA#COMBAT","LOCALS",0)
		SetGlobalTimer("JA#REST","LOCALS",2400)
END

// Rest (reset everything and heal if applicable)
IF
	Global("JA#INIT","LOCALS",1)
	GlobalTimerExpired("JA#REST","LOCALS")
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA#INIT","LOCALS",0)
		Rest()
END

// Turn hostile if attacked
IF
	Allegiance(Myself,NEUTRAL)
	OR(4)
		AttackedBy([GOODCUTOFF],DEFAULT)
		SpellCastOnMe([GOODCUTOFF],0)
		TookDamage()
		Heard([EVILCUTOFF.0.FAIRY],99)
THEN
	RESPONSE #100
		Enemy()
END

// Detect combat
IF
	Global("JA#COMBAT","LOCALS",0)
	Allegiance(Myself,EVILCUTOFF)
	See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
END

// Detect combat
IF
	Global("JA#COMBAT","LOCALS",0)
	Allegiance(Myself,GOODCUTOFF)
	See([EVILCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
END

// Shouts every 3 rounds
IF
	Global("JA#COMBAT","LOCALS",1)
	!GlobalTimerNotExpired("JA#HELP","LOCALS")
THEN
	RESPONSE #100
		Shout(99)
		SetGlobalTimer("JA#HELP","LOCALS",18)
END

// React to shouts
IF
	Global("JA#COMBAT","LOCALS",0)
	Heard([EVILCUTOFF.0.FAIRY],99)
	InMyArea([EVILCUTOFF.0.FAIRY])
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
		MoveToObject(LastHeardBy(Myself))
END

IF
	Global("JA#COMBAT","LOCALS",1)
	Heard([EVILCUTOFF.0.FAIRY],99)
	InMyArea([EVILCUTOFF.0.FAIRY])
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		MoveToObject(LastHeardBy(Myself))
END

// Do nothing if...
IF
	OR(4)
		Global("JA#COMBAT","LOCALS",0)
		!Allegiance(Myself,EVILCUTOFF)
		StateCheck(Myself,STATE_IMMOBILE)
		StateCheck(Myself,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		NoAction()
END

IF
	!InActiveArea(Myself)
	!Range(NearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		NoAction()
END

// Handle Panic state
IF
	StateCheck(Myself,STATE_PANIC)
	Range(NearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),15)
END

IF
	StateCheck(Myself,STATE_PANIC)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

// Stream of acidic enzymes
IF
	HaveSpellRES("ja#1m41")
	HPPercentLT(Myself,50)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	Range([PC.0.0.MAGE],30)
	!General([PC.0.0.MAGE],WEAPON)
	!StateCheck([PC.0.0.MAGE],STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT([PC.0.0.MAGE],0,SANCTUARY)
	!StateCheck([PC.0.0.MAGE],STATE_REALLY_DEAD)
	See([PC.0.0.MAGE])
	RandomNumGT(1000,100)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("ja#1m41",LastSeenBy(Myself))
		RemoveSpellRES("ja#1m41")
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	HPPercentLT(Myself,50)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	Range([PC.0.0.MAGE_THIEF],30)
	!General([PC.0.0.MAGE_THIEF],WEAPON)
	!StateCheck([PC.0.0.MAGE_THIEF],STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT([PC.0.0.MAGE_THIEF],0,SANCTUARY)
	!StateCheck([PC.0.0.MAGE_THIEF],STATE_REALLY_DEAD)
	See([PC.0.0.MAGE_THIEF])
	RandomNumGT(1000,111)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("ja#1m41",LastSeenBy(Myself))
		RemoveSpellRES("ja#1m41")
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	HPPercentLT(Myself,50)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	Range([PC.0.0.MAGE_ALL],30)
	!General([PC.0.0.MAGE_ALL],WEAPON)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT([PC.0.0.MAGE_ALL],0,SANCTUARY)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_REALLY_DEAD)
	See([PC.0.0.MAGE_ALL])
	RandomNumGT(1000,125)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("ja#1m41",LastSeenBy(Myself))
		RemoveSpellRES("ja#1m41")
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	HPPercentLT(Myself,50)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	Range([PC.0.0.THIEF],30)
	!General([PC.0.0.THIEF],WEAPON)
	!StateCheck([PC.0.0.THIEF],STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT([PC.0.0.THIEF],0,SANCTUARY)
	!StateCheck([PC.0.0.THIEF],STATE_REALLY_DEAD)
	See([PC.0.0.THIEF])
	RandomNumGT(1000,143)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("ja#1m41",LastSeenBy(Myself))
		RemoveSpellRES("ja#1m41")
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	HPPercentLT(Myself,50)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	Range([PC.0.0.BARD],30)
	!General([PC.0.0.BARD],WEAPON)
	!StateCheck([PC.0.0.BARD],STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT([PC.0.0.BARD],0,SANCTUARY)
	!StateCheck([PC.0.0.BARD],STATE_REALLY_DEAD)
	See([PC.0.0.BARD])
	RandomNumGT(1000,167)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("ja#1m41",LastSeenBy(Myself))
		RemoveSpellRES("ja#1m41")
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	HPPercentLT(Myself,50)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	Range([PC.0.0.THIEF_ALL],30)
	!General([PC.0.0.THIEF_ALL],WEAPON)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT([PC.0.0.THIEF_ALL],0,SANCTUARY)
	!StateCheck([PC.0.0.THIEF_ALL],STATE_REALLY_DEAD)
	See([PC.0.0.THIEF_ALL])
	RandomNumGT(1000,200)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("ja#1m41",LastSeenBy(Myself))
		RemoveSpellRES("ja#1m41")
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	HPPercentLT(Myself,50)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	Range([PC.0.0.CLERIC],30)
	!General([PC.0.0.CLERIC],WEAPON)
	!StateCheck([PC.0.0.CLERIC],STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT([PC.0.0.CLERIC],0,SANCTUARY)
	!StateCheck([PC.0.0.CLERIC],STATE_REALLY_DEAD)
	See([PC.0.0.CLERIC])
	RandomNumGT(1000,250)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("ja#1m41",LastSeenBy(Myself))
		RemoveSpellRES("ja#1m41")
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	HPPercentLT(Myself,50)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	Range([PC],30)
	!General([PC],WEAPON)
	!StateCheck([PC],STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT([PC],0,SANCTUARY)
	!StateCheck([PC],STATE_REALLY_DEAD)
	See([PC])
	RandomNumGT(1000,333)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("ja#1m41",LastSeenBy(Myself))
		RemoveSpellRES("ja#1m41")
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	HPPercentLT(Myself,50)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	Range(SecondNearest([PC]),30)
	!General(SecondNearest([PC]),WEAPON)
	!StateCheck(SecondNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(SecondNearest([PC]),0,SANCTUARY)
	!StateCheck(SecondNearest([PC]),STATE_REALLY_DEAD)
	See(SecondNearest([PC]))
	RandomNumGT(1000,500)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("ja#1m41",LastSeenBy(Myself))
		RemoveSpellRES("ja#1m41")
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	HPPercentLT(Myself,50)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	Range(ThirdNearest([PC]),30)
	!General(ThirdNearest([PC]),WEAPON)
	!StateCheck(ThirdNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(ThirdNearest([PC]),0,SANCTUARY)
	!StateCheck(ThirdNearest([PC]),STATE_REALLY_DEAD)
	See(ThirdNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("ja#1m41",LastSeenBy(Myself))
		RemoveSpellRES("ja#1m41")
		SetInterrupt(TRUE)
END

// Run away from enemies
IF
	Range(NearestEnemyOf(Myself),20)
THEN
	RESPONSE #100
		RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),45)
END

// Track players if allegiance is not GOODCUTOFF
IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player1)
	Range(Player1,150)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStatGT(Player1,0,SANCTUARY)
	!StateCheck(Player1,STATE_CHARMED)
	!StateCheck(Player1,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player2)
	Range(Player2,150)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStatGT(Player2,0,SANCTUARY)
	!StateCheck(Player2,STATE_CHARMED)
	!StateCheck(Player2,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player3)
	Range(Player3,150)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStatGT(Player3,0,SANCTUARY)
	!StateCheck(Player3,STATE_CHARMED)
	!StateCheck(Player3,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player4)
	Range(Player4,150)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStatGT(Player4,0,SANCTUARY)
	!StateCheck(Player4,STATE_CHARMED)
	!StateCheck(Player4,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player5)
	Range(Player5,150)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStatGT(Player5,0,SANCTUARY)
	!StateCheck(Player5,STATE_CHARMED)
	!StateCheck(Player5,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player6)
	Range(Player6,150)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStatGT(Player6,0,SANCTUARY)
	!StateCheck(Player6,STATE_CHARMED)
	!StateCheck(Player6,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

// Track last seen enemy if allegiance is GOODCUTOFF
IF
	Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(LastSeenBy(Myself))
	Range(LastSeenBy(Myself),150)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

// Open door
IF
	Global("RR#NOPND","GLOBAL",0)
	Allegiance(Myself,EVILCUTOFF)
	!AreaType(OUTDOOR)
	!Range(NearestEnemyOf(Myself),30)
	Range(NearestDoor,15)
	OpenState(NearestDoor,FALSE)
THEN
	RESPONSE #100
		MoveToObject(NearestDoor)
		OpenDoor(NearestDoor)
END

// Random walking (in combat) 
IF
	Global("JA#COMBAT","LOCALS",1)
	ActionListEmpty()
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		RandomWalk()
		Wait(2)
END

// Random facing
IF
	!Range(NearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		RandomTurn()
END

