// Initiate dialog
IF
	Global("JA#DIALOG","LOCALS",0)
	Name("VAELASA",Myself)
	NumTimesTalkedTo(0)
	See([PC])
THEN
	RESPONSE #100
		SetGlobal("JA#DIALOG","LOCALS",1)
		FaceObject([PC])
		StartDialogueNoSet([PC])
END

// Can use dimension door and detect traps
IF
	Global("ja#wilderness","LOCALS",0)
	AreaType(OUTDOOR)
	!AreaType(CITY)
	!AreaType(DUNGEON)
THEN
	RESPONSE #100
		SetGlobal("ja#wilderness","LOCALS",1)
END

IF
	Global("ja#wilderness","LOCALS",0)
	OR(2)
		HaveSpellRES("rr#ddoor")
		HaveSpellRES("rr#fdsnr")
THEN
	RESPONSE #100
		RemoveSpellRES("rr#ddoor")
		RemoveSpellRES("rr#fdsnr")
		SetGlobal("ja#wilderness","LOCALS",2)
END

// Vaelasa, the Fairy Queen
IF
	Name("VAELASA",Myself)
	AreaCheck("AR1200")
	Global("SummonDryads","AR1200",1)
THEN
	RESPONSE #100
		SetGlobal("SummonDryads","AR1200",2)
		StartCutSceneMode()
		StartCutScene("Cut23a")
END

IF
	Name("VAELASA",Myself)
	AreaCheck("AR0602")
	AttackedBy([GOODCUTOFF],DEFAULT)
	Global("VaelasaHostile","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("VaelasaHostile","GLOBAL",1)
		Enemy()
END

IF
	Global("rr#chama","MYAREA",1)
	Global("rr#hamat","LOCALS",0)
	See([PC])
THEN
	RESPONSE #100
		SetGlobal("rr#hamat","LOCALS",1)
		FaceObject([PC])
		DisplayStringHead(Myself,5184)
END

// Init
IF
	Global("JA#INIT","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("JA#INIT","LOCALS",1)
		SetGlobal("JA#COMBAT","LOCALS",0)
		SetGlobalTimer("JA#REST","LOCALS",2400)
END

// Rest (reset everything and heal if applicable)
IF
	Global("JA#INIT","LOCALS",1)
	GlobalTimerExpired("JA#REST","LOCALS")
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA#INIT","LOCALS",0)
		Rest()
END

// Turn hostile if attacked
IF
	Allegiance(Myself,NEUTRAL)
	OR(4)
		AttackedBy([GOODCUTOFF],DEFAULT)
		SpellCastOnMe([GOODCUTOFF],0)
		TookDamage()
		Heard([EVILCUTOFF.0.FAIRY],99)
THEN
	RESPONSE #100
		Enemy()
END

// Detect combat
IF
	Global("JA#COMBAT","LOCALS",0)
	Allegiance(Myself,EVILCUTOFF)
	See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
END

// Detect combat
IF
	Global("JA#COMBAT","LOCALS",0)
	Allegiance(Myself,GOODCUTOFF)
	See([EVILCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
END

// Shouts every 3 rounds
IF
	Global("JA#COMBAT","LOCALS",1)
	!GlobalTimerNotExpired("JA#HELP","LOCALS")
THEN
	RESPONSE #100
		Shout(99)
		SetGlobalTimer("JA#HELP","LOCALS",18)
END

// React to shouts
IF
	Global("JA#COMBAT","LOCALS",0)
	Heard([EVILCUTOFF.0.FAIRY],99)
	InMyArea([EVILCUTOFF.0.FAIRY])
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
		MoveToObject(LastHeardBy(Myself))
END

IF
	Global("JA#COMBAT","LOCALS",1)
	Heard([EVILCUTOFF.0.FAIRY],99)
	InMyArea([EVILCUTOFF.0.FAIRY])
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		MoveToObject(LastHeardBy(Myself))
END

// Do nothing if...
IF
	OR(4)
		Global("JA#COMBAT","LOCALS",0)
		!Allegiance(Myself,EVILCUTOFF)
		StateCheck(Myself,STATE_IMMOBILE)
		StateCheck(Myself,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		NoAction()
END

IF
	!InActiveArea(Myself)
	!Range(NearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		NoAction()
END

// Handle Panic state
IF
	StateCheck(Myself,STATE_PANIC)
	Range(NearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),15)
END

IF
	StateCheck(Myself,STATE_PANIC)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

// Dimension Door
IF
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	HaveSpellRES("rr#ddoor")
	OR(2)
		Range(NearestEnemyOf(Myself),10)
		AttackedBy([ANYONE],DEFAULT)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		CreateCreatureOffscreen("RR#TRAT",0)
		ForceSpellRES("rr#ddoor","RR#TRAT")
		Wait(1)
		SetInterrupt(TRUE)
END

// Speak with plants
IF
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!GlobalTimerNotExpired("speakWithPlants","LOCALS")
	HaveSpellRES("rr#fspkp")
	CheckStatGT(Myself,0,ENTANGLE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fspkp",LastSeenBy(Myself))
		SetGlobalTimer("speakWithPlants","LOCALS",60)
		SetInterrupt(TRUE)
END

// Entangle
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("entangle","LOCALS")
	HaveSpellRES("RR#FENTG")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	CheckStat(NearestEnemyOf(Myself),0,ENTANGLE)
	!CheckStatGT(NearestEnemyOf(Myself),0,HELD)
	!StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
	!General(NearestEnemyOf(Myself),WEAPON)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(NearestEnemyOf(Myself),STATE_REALLY_DEAD)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetGlobalTimer("entangle","LOCALS",18)
		ForceSpellRES("RR#FENTG",LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("entangle","LOCALS")
	HaveSpellRES("RR#FENTG")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	CheckStat(SecondNearestEnemyOf(Myself),0,ENTANGLE)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
	!General(SecondNearestEnemyOf(Myself),WEAPON)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_REALLY_DEAD)
	See(SecondNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetGlobalTimer("entangle","LOCALS",18)
		ForceSpellRES("RR#FENTG",LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("entangle","LOCALS")
	HaveSpellRES("RR#FENTG")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	CheckStat(ThirdNearestEnemyOf(Myself),0,ENTANGLE)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
	!General(ThirdNearestEnemyOf(Myself),WEAPON)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_REALLY_DEAD)
	See(ThirdNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetGlobalTimer("entangle","LOCALS",18)
		ForceSpellRES("RR#FENTG",LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("entangle","LOCALS")
	HaveSpellRES("RR#FENTG")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	CheckStat(FourthNearestEnemyOf(Myself),0,ENTANGLE)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
	!General(FourthNearestEnemyOf(Myself),WEAPON)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
	See(FourthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetGlobalTimer("entangle","LOCALS",18)
		ForceSpellRES("RR#FENTG",LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("entangle","LOCALS")
	HaveSpellRES("RR#FENTG")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	CheckStat(FifthNearestEnemyOf(Myself),0,ENTANGLE)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
	!General(FifthNearestEnemyOf(Myself),WEAPON)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
	See(FifthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetGlobalTimer("entangle","LOCALS",18)
		ForceSpellRES("RR#FENTG",LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("entangle","LOCALS")
	HaveSpellRES("RR#FENTG")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	CheckStat(SixthNearestEnemyOf(Myself),0,ENTANGLE)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
	!General(SixthNearestEnemyOf(Myself),WEAPON)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
	See(SixthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetGlobalTimer("entangle","LOCALS",18)
		ForceSpellRES("RR#FENTG",LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("entangle","LOCALS")
	HaveSpellRES("RR#FENTG")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	CheckStat(SeventhNearestEnemyOf(Myself),0,ENTANGLE)
	!CheckStatGT(SeventhNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_HELPLESS)
	!General(SeventhNearestEnemyOf(Myself),WEAPON)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(SeventhNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_REALLY_DEAD)
	See(SeventhNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetGlobalTimer("entangle","LOCALS",18)
		ForceSpellRES("RR#FENTG",LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("entangle","LOCALS")
	HaveSpellRES("RR#FENTG")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	CheckStat(EighthNearestEnemyOf(Myself),0,ENTANGLE)
	!CheckStatGT(EighthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_HELPLESS)
	!General(EighthNearestEnemyOf(Myself),WEAPON)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(EighthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
	See(EighthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetGlobalTimer("entangle","LOCALS",18)
		ForceSpellRES("RR#FENTG",LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("entangle","LOCALS")
	HaveSpellRES("RR#FENTG")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	CheckStat(NinthNearestEnemyOf(Myself),0,ENTANGLE)
	!CheckStatGT(NinthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_HELPLESS)
	!General(NinthNearestEnemyOf(Myself),WEAPON)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(NinthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
	See(NinthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetGlobalTimer("entangle","LOCALS",18)
		ForceSpellRES("RR#FENTG",LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("entangle","LOCALS")
	HaveSpellRES("RR#FENTG")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	CheckStat(TenthNearestEnemyOf(Myself),0,ENTANGLE)
	!CheckStatGT(TenthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_HELPLESS)
	!General(TenthNearestEnemyOf(Myself),WEAPON)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(TenthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
	See(TenthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetGlobalTimer("entangle","LOCALS",18)
		ForceSpellRES("RR#FENTG",LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

// Dire Charm
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race([PC.0.0.FIGHTER_ALL],ELF)
	!Race([PC.0.0.FIGHTER_ALL],HALF_ELF)
	!CheckStatGT([PC.0.0.FIGHTER_ALL],0,HELD)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_STUNNED)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_PANIC)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_CONFUSED)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_FEEBLEMINDED)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_SLEEPING)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_HELPLESS)
	!General([PC.0.0.FIGHTER_ALL],WEAPON)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT([PC.0.0.FIGHTER_ALL],0,SANCTUARY)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_REALLY_DEAD)
	See([PC.0.0.FIGHTER_ALL])
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SecondNearest([PC.0.0.FIGHTER_ALL]),ELF)
	!Race(SecondNearest([PC.0.0.FIGHTER_ALL]),HALF_ELF)
	!CheckStatGT(SecondNearest([PC.0.0.FIGHTER_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_HELPLESS)
	!General(SecondNearest([PC.0.0.FIGHTER_ALL]),WEAPON)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(SecondNearest([PC.0.0.FIGHTER_ALL]),0,SANCTUARY)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_REALLY_DEAD)
	See(SecondNearest([PC.0.0.FIGHTER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(ThirdNearest([PC.0.0.FIGHTER_ALL]),ELF)
	!Race(ThirdNearest([PC.0.0.FIGHTER_ALL]),HALF_ELF)
	!CheckStatGT(ThirdNearest([PC.0.0.FIGHTER_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_HELPLESS)
	!General(ThirdNearest([PC.0.0.FIGHTER_ALL]),WEAPON)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(ThirdNearest([PC.0.0.FIGHTER_ALL]),0,SANCTUARY)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_REALLY_DEAD)
	See(ThirdNearest([PC.0.0.FIGHTER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race([PC.0.0.RANGER_ALL],ELF)
	!Race([PC.0.0.RANGER_ALL],HALF_ELF)
	!CheckStatGT([PC.0.0.RANGER_ALL],0,HELD)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_STUNNED)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_PANIC)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_CONFUSED)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_FEEBLEMINDED)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_SLEEPING)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_HELPLESS)
	!General([PC.0.0.RANGER_ALL],WEAPON)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT([PC.0.0.RANGER_ALL],0,SANCTUARY)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_REALLY_DEAD)
	See([PC.0.0.RANGER_ALL])
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SecondNearest([PC.0.0.RANGER_ALL]),ELF)
	!Race(SecondNearest([PC.0.0.RANGER_ALL]),HALF_ELF)
	!CheckStatGT(SecondNearest([PC.0.0.RANGER_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_HELPLESS)
	!General(SecondNearest([PC.0.0.RANGER_ALL]),WEAPON)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(SecondNearest([PC.0.0.RANGER_ALL]),0,SANCTUARY)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_REALLY_DEAD)
	See(SecondNearest([PC.0.0.RANGER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(ThirdNearest([PC.0.0.RANGER_ALL]),ELF)
	!Race(ThirdNearest([PC.0.0.RANGER_ALL]),HALF_ELF)
	!CheckStatGT(ThirdNearest([PC.0.0.RANGER_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_HELPLESS)
	!General(ThirdNearest([PC.0.0.RANGER_ALL]),WEAPON)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(ThirdNearest([PC.0.0.RANGER_ALL]),0,SANCTUARY)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_REALLY_DEAD)
	See(ThirdNearest([PC.0.0.RANGER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race([PC.0.0.PALADIN_ALL],ELF)
	!Race([PC.0.0.PALADIN_ALL],HALF_ELF)
	!CheckStatGT([PC.0.0.PALADIN_ALL],0,HELD)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_STUNNED)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_PANIC)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_CONFUSED)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_FEEBLEMINDED)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_SLEEPING)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_HELPLESS)
	!General([PC.0.0.PALADIN_ALL],WEAPON)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT([PC.0.0.PALADIN_ALL],0,SANCTUARY)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_REALLY_DEAD)
	See([PC.0.0.PALADIN_ALL])
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SecondNearest([PC.0.0.PALADIN_ALL]),ELF)
	!Race(SecondNearest([PC.0.0.PALADIN_ALL]),HALF_ELF)
	!CheckStatGT(SecondNearest([PC.0.0.PALADIN_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
	!General(SecondNearest([PC.0.0.PALADIN_ALL]),WEAPON)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(SecondNearest([PC.0.0.PALADIN_ALL]),0,SANCTUARY)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_REALLY_DEAD)
	See(SecondNearest([PC.0.0.PALADIN_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(ThirdNearest([PC.0.0.PALADIN_ALL]),ELF)
	!Race(ThirdNearest([PC.0.0.PALADIN_ALL]),HALF_ELF)
	!CheckStatGT(ThirdNearest([PC.0.0.PALADIN_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
	!General(ThirdNearest([PC.0.0.PALADIN_ALL]),WEAPON)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(ThirdNearest([PC.0.0.PALADIN_ALL]),0,SANCTUARY)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_REALLY_DEAD)
	See(ThirdNearest([PC.0.0.PALADIN_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

// Dire Charm
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race([PC],ELF)
	!Race([PC],HALF_ELF)
	!CheckStatGT([PC],0,HELD)
	!StateCheck([PC],STATE_STUNNED)
	!StateCheck([PC],STATE_PANIC)
	!StateCheck([PC],STATE_CONFUSED)
	!StateCheck([PC],STATE_FEEBLEMINDED)
	!StateCheck([PC],STATE_SLEEPING)
	!StateCheck([PC],STATE_HELPLESS)
	!General([PC],WEAPON)
	!StateCheck([PC],STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT([PC],0,SANCTUARY)
	!StateCheck([PC],STATE_REALLY_DEAD)
	See([PC])
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SecondNearest([PC]),ELF)
	!Race(SecondNearest([PC]),HALF_ELF)
	!CheckStatGT(SecondNearest([PC]),0,HELD)
	!StateCheck(SecondNearest([PC]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC]),STATE_PANIC)
	!StateCheck(SecondNearest([PC]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC]),STATE_HELPLESS)
	!General(SecondNearest([PC]),WEAPON)
	!StateCheck(SecondNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(SecondNearest([PC]),0,SANCTUARY)
	!StateCheck(SecondNearest([PC]),STATE_REALLY_DEAD)
	See(SecondNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(ThirdNearest([PC]),ELF)
	!Race(ThirdNearest([PC]),HALF_ELF)
	!CheckStatGT(ThirdNearest([PC]),0,HELD)
	!StateCheck(ThirdNearest([PC]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC]),STATE_HELPLESS)
	!General(ThirdNearest([PC]),WEAPON)
	!StateCheck(ThirdNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(ThirdNearest([PC]),0,SANCTUARY)
	!StateCheck(ThirdNearest([PC]),STATE_REALLY_DEAD)
	See(ThirdNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(FourthNearest([PC]),ELF)
	!Race(FourthNearest([PC]),HALF_ELF)
	!CheckStatGT(FourthNearest([PC]),0,HELD)
	!StateCheck(FourthNearest([PC]),STATE_STUNNED)
	!StateCheck(FourthNearest([PC]),STATE_PANIC)
	!StateCheck(FourthNearest([PC]),STATE_CONFUSED)
	!StateCheck(FourthNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(FourthNearest([PC]),STATE_SLEEPING)
	!StateCheck(FourthNearest([PC]),STATE_HELPLESS)
	!General(FourthNearest([PC]),WEAPON)
	!StateCheck(FourthNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(FourthNearest([PC]),0,SANCTUARY)
	!StateCheck(FourthNearest([PC]),STATE_REALLY_DEAD)
	See(FourthNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(FifthNearest([PC]),ELF)
	!Race(FifthNearest([PC]),HALF_ELF)
	!CheckStatGT(FifthNearest([PC]),0,HELD)
	!StateCheck(FifthNearest([PC]),STATE_STUNNED)
	!StateCheck(FifthNearest([PC]),STATE_PANIC)
	!StateCheck(FifthNearest([PC]),STATE_CONFUSED)
	!StateCheck(FifthNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(FifthNearest([PC]),STATE_SLEEPING)
	!StateCheck(FifthNearest([PC]),STATE_HELPLESS)
	!General(FifthNearest([PC]),WEAPON)
	!StateCheck(FifthNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(FifthNearest([PC]),0,SANCTUARY)
	!StateCheck(FifthNearest([PC]),STATE_REALLY_DEAD)
	See(FifthNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SixthNearest([PC]),ELF)
	!Race(SixthNearest([PC]),HALF_ELF)
	!CheckStatGT(SixthNearest([PC]),0,HELD)
	!StateCheck(SixthNearest([PC]),STATE_STUNNED)
	!StateCheck(SixthNearest([PC]),STATE_PANIC)
	!StateCheck(SixthNearest([PC]),STATE_CONFUSED)
	!StateCheck(SixthNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(SixthNearest([PC]),STATE_SLEEPING)
	!StateCheck(SixthNearest([PC]),STATE_HELPLESS)
	!General(SixthNearest([PC]),WEAPON)
	!StateCheck(SixthNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(SixthNearest([PC]),0,SANCTUARY)
	!StateCheck(SixthNearest([PC]),STATE_REALLY_DEAD)
	See(SixthNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

// Dire Charm
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race([PC.0.0.FIGHTER_ALL],ELF)
	!CheckStatGT([PC.0.0.FIGHTER_ALL],0,HELD)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_STUNNED)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_PANIC)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_CONFUSED)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_FEEBLEMINDED)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_SLEEPING)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_HELPLESS)
	!General([PC.0.0.FIGHTER_ALL],WEAPON)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT([PC.0.0.FIGHTER_ALL],0,SANCTUARY)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_REALLY_DEAD)
	See([PC.0.0.FIGHTER_ALL])
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SecondNearest([PC.0.0.FIGHTER_ALL]),ELF)
	!CheckStatGT(SecondNearest([PC.0.0.FIGHTER_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_HELPLESS)
	!General(SecondNearest([PC.0.0.FIGHTER_ALL]),WEAPON)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(SecondNearest([PC.0.0.FIGHTER_ALL]),0,SANCTUARY)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_REALLY_DEAD)
	See(SecondNearest([PC.0.0.FIGHTER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(ThirdNearest([PC.0.0.FIGHTER_ALL]),ELF)
	!CheckStatGT(ThirdNearest([PC.0.0.FIGHTER_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_HELPLESS)
	!General(ThirdNearest([PC.0.0.FIGHTER_ALL]),WEAPON)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(ThirdNearest([PC.0.0.FIGHTER_ALL]),0,SANCTUARY)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_REALLY_DEAD)
	See(ThirdNearest([PC.0.0.FIGHTER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race([PC.0.0.RANGER_ALL],ELF)
	!CheckStatGT([PC.0.0.RANGER_ALL],0,HELD)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_STUNNED)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_PANIC)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_CONFUSED)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_FEEBLEMINDED)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_SLEEPING)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_HELPLESS)
	!General([PC.0.0.RANGER_ALL],WEAPON)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT([PC.0.0.RANGER_ALL],0,SANCTUARY)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_REALLY_DEAD)
	See([PC.0.0.RANGER_ALL])
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SecondNearest([PC.0.0.RANGER_ALL]),ELF)
	!CheckStatGT(SecondNearest([PC.0.0.RANGER_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_HELPLESS)
	!General(SecondNearest([PC.0.0.RANGER_ALL]),WEAPON)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(SecondNearest([PC.0.0.RANGER_ALL]),0,SANCTUARY)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_REALLY_DEAD)
	See(SecondNearest([PC.0.0.RANGER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(ThirdNearest([PC.0.0.RANGER_ALL]),ELF)
	!CheckStatGT(ThirdNearest([PC.0.0.RANGER_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_HELPLESS)
	!General(ThirdNearest([PC.0.0.RANGER_ALL]),WEAPON)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(ThirdNearest([PC.0.0.RANGER_ALL]),0,SANCTUARY)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_REALLY_DEAD)
	See(ThirdNearest([PC.0.0.RANGER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race([PC.0.0.PALADIN_ALL],ELF)
	!CheckStatGT([PC.0.0.PALADIN_ALL],0,HELD)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_STUNNED)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_PANIC)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_CONFUSED)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_FEEBLEMINDED)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_SLEEPING)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_HELPLESS)
	!General([PC.0.0.PALADIN_ALL],WEAPON)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT([PC.0.0.PALADIN_ALL],0,SANCTUARY)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_REALLY_DEAD)
	See([PC.0.0.PALADIN_ALL])
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SecondNearest([PC.0.0.PALADIN_ALL]),ELF)
	!CheckStatGT(SecondNearest([PC.0.0.PALADIN_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
	!General(SecondNearest([PC.0.0.PALADIN_ALL]),WEAPON)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(SecondNearest([PC.0.0.PALADIN_ALL]),0,SANCTUARY)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_REALLY_DEAD)
	See(SecondNearest([PC.0.0.PALADIN_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(ThirdNearest([PC.0.0.PALADIN_ALL]),ELF)
	!CheckStatGT(ThirdNearest([PC.0.0.PALADIN_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
	!General(ThirdNearest([PC.0.0.PALADIN_ALL]),WEAPON)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(ThirdNearest([PC.0.0.PALADIN_ALL]),0,SANCTUARY)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_REALLY_DEAD)
	See(ThirdNearest([PC.0.0.PALADIN_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

// Dire Charm
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!CheckStatGT([PC],0,HELD)
	!StateCheck([PC],STATE_STUNNED)
	!StateCheck([PC],STATE_PANIC)
	!StateCheck([PC],STATE_CONFUSED)
	!StateCheck([PC],STATE_FEEBLEMINDED)
	!StateCheck([PC],STATE_SLEEPING)
	!StateCheck([PC],STATE_HELPLESS)
	!General([PC],WEAPON)
	!StateCheck([PC],STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT([PC],0,SANCTUARY)
	!StateCheck([PC],STATE_REALLY_DEAD)
	See([PC])
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!CheckStatGT(SecondNearest([PC]),0,HELD)
	!StateCheck(SecondNearest([PC]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC]),STATE_PANIC)
	!StateCheck(SecondNearest([PC]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC]),STATE_HELPLESS)
	!General(SecondNearest([PC]),WEAPON)
	!StateCheck(SecondNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(SecondNearest([PC]),0,SANCTUARY)
	!StateCheck(SecondNearest([PC]),STATE_REALLY_DEAD)
	See(SecondNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!CheckStatGT(ThirdNearest([PC]),0,HELD)
	!StateCheck(ThirdNearest([PC]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC]),STATE_HELPLESS)
	!General(ThirdNearest([PC]),WEAPON)
	!StateCheck(ThirdNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(ThirdNearest([PC]),0,SANCTUARY)
	!StateCheck(ThirdNearest([PC]),STATE_REALLY_DEAD)
	See(ThirdNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!CheckStatGT(FourthNearest([PC]),0,HELD)
	!StateCheck(FourthNearest([PC]),STATE_STUNNED)
	!StateCheck(FourthNearest([PC]),STATE_PANIC)
	!StateCheck(FourthNearest([PC]),STATE_CONFUSED)
	!StateCheck(FourthNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(FourthNearest([PC]),STATE_SLEEPING)
	!StateCheck(FourthNearest([PC]),STATE_HELPLESS)
	!General(FourthNearest([PC]),WEAPON)
	!StateCheck(FourthNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(FourthNearest([PC]),0,SANCTUARY)
	!StateCheck(FourthNearest([PC]),STATE_REALLY_DEAD)
	See(FourthNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!CheckStatGT(FifthNearest([PC]),0,HELD)
	!StateCheck(FifthNearest([PC]),STATE_STUNNED)
	!StateCheck(FifthNearest([PC]),STATE_PANIC)
	!StateCheck(FifthNearest([PC]),STATE_CONFUSED)
	!StateCheck(FifthNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(FifthNearest([PC]),STATE_SLEEPING)
	!StateCheck(FifthNearest([PC]),STATE_HELPLESS)
	!General(FifthNearest([PC]),WEAPON)
	!StateCheck(FifthNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(FifthNearest([PC]),0,SANCTUARY)
	!StateCheck(FifthNearest([PC]),STATE_REALLY_DEAD)
	See(FifthNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!CheckStatGT(SixthNearest([PC]),0,HELD)
	!StateCheck(SixthNearest([PC]),STATE_STUNNED)
	!StateCheck(SixthNearest([PC]),STATE_PANIC)
	!StateCheck(SixthNearest([PC]),STATE_CONFUSED)
	!StateCheck(SixthNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(SixthNearest([PC]),STATE_SLEEPING)
	!StateCheck(SixthNearest([PC]),STATE_HELPLESS)
	!General(SixthNearest([PC]),WEAPON)
	!StateCheck(SixthNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(SixthNearest([PC]),0,SANCTUARY)
	!StateCheck(SixthNearest([PC]),STATE_REALLY_DEAD)
	See(SixthNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fchrm",LastSeenBy(Myself))
		RemoveSpellRES("rr#fchrm")
		SetInterrupt(TRUE)
END

// Animal Friendship
IF
	HaveSpellRES("rr#fafrn")
	RandomNumGT(802,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!General(NearestEnemyOfType([0.ANIMAL]),WEAPON)
	!StateCheck(NearestEnemyOfType([0.ANIMAL]),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(NearestEnemyOfType([0.ANIMAL]),0,SANCTUARY)
	!StateCheck(NearestEnemyOfType([0.ANIMAL]),STATE_REALLY_DEAD)
	See(NearestEnemyOfType([0.ANIMAL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fafrn",LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fafrn")
	RandomNumGT(802,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!General(SecondNearestEnemyOfType([0.ANIMAL]),WEAPON)
	!StateCheck(SecondNearestEnemyOfType([0.ANIMAL]),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(SecondNearestEnemyOfType([0.ANIMAL]),0,SANCTUARY)
	!StateCheck(SecondNearestEnemyOfType([0.ANIMAL]),STATE_REALLY_DEAD)
	See(SecondNearestEnemyOfType([0.ANIMAL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fafrn",LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fafrn")
	RandomNumGT(802,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!General(ThirdNearestEnemyOfType([0.ANIMAL]),WEAPON)
	!StateCheck(ThirdNearestEnemyOfType([0.ANIMAL]),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(ThirdNearestEnemyOfType([0.ANIMAL]),0,SANCTUARY)
	!StateCheck(ThirdNearestEnemyOfType([0.ANIMAL]),STATE_REALLY_DEAD)
	See(ThirdNearestEnemyOfType([0.ANIMAL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fafrn",LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fafrn")
	RandomNumGT(802,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!General([NEUTRAL.ANIMAL],WEAPON)
	!StateCheck([NEUTRAL.ANIMAL],STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT([NEUTRAL.ANIMAL],0,SANCTUARY)
	!StateCheck([NEUTRAL.ANIMAL],STATE_REALLY_DEAD)
	See([NEUTRAL.ANIMAL])
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fafrn",LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fafrn")
	RandomNumGT(802,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!General(SecondNearest([NEUTRAL.ANIMAL]),WEAPON)
	!StateCheck(SecondNearest([NEUTRAL.ANIMAL]),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(SecondNearest([NEUTRAL.ANIMAL]),0,SANCTUARY)
	!StateCheck(SecondNearest([NEUTRAL.ANIMAL]),STATE_REALLY_DEAD)
	See(SecondNearest([NEUTRAL.ANIMAL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fafrn",LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fafrn")
	RandomNumGT(802,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!General(ThirdNearest([NEUTRAL.ANIMAL]),WEAPON)
	!StateCheck(ThirdNearest([NEUTRAL.ANIMAL]),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(ThirdNearest([NEUTRAL.ANIMAL]),0,SANCTUARY)
	!StateCheck(ThirdNearest([NEUTRAL.ANIMAL]),STATE_REALLY_DEAD)
	See(ThirdNearest([NEUTRAL.ANIMAL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fafrn",LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

// Detect Snares And Pits
IF
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	HaveSpellRES("rr#fdsnr")
	RandomNumGT(803,241)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		ForceSpellRES("rr#fdsnr",LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

// Run away from enemies
IF
	Range(NearestEnemyOf(Myself),20)
THEN
	RESPONSE #100
		RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),45)
END

// Track players if allegiance is not GOODCUTOFF
IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player1)
	Range(Player1,150)
	HaveSpellRES("rr#fchrm")
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStatGT(Player1,0,SANCTUARY)
	!StateCheck(Player1,STATE_CHARMED)
	!StateCheck(Player1,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player2)
	Range(Player2,150)
	HaveSpellRES("rr#fchrm")
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStatGT(Player2,0,SANCTUARY)
	!StateCheck(Player2,STATE_CHARMED)
	!StateCheck(Player2,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player3)
	Range(Player3,150)
	HaveSpellRES("rr#fchrm")
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStatGT(Player3,0,SANCTUARY)
	!StateCheck(Player3,STATE_CHARMED)
	!StateCheck(Player3,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player4)
	Range(Player4,150)
	HaveSpellRES("rr#fchrm")
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStatGT(Player4,0,SANCTUARY)
	!StateCheck(Player4,STATE_CHARMED)
	!StateCheck(Player4,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player5)
	Range(Player5,150)
	HaveSpellRES("rr#fchrm")
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStatGT(Player5,0,SANCTUARY)
	!StateCheck(Player5,STATE_CHARMED)
	!StateCheck(Player5,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player6)
	Range(Player6,150)
	HaveSpellRES("rr#fchrm")
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStatGT(Player6,0,SANCTUARY)
	!StateCheck(Player6,STATE_CHARMED)
	!StateCheck(Player6,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

// Track last seen enemy if allegiance is GOODCUTOFF
IF
	Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(LastSeenBy(Myself))
	Range(LastSeenBy(Myself),150)
	HaveSpellRES("rr#fchrm")
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

// Open door
IF
	Global("RR#NOPND","GLOBAL",0)
	Allegiance(Myself,EVILCUTOFF)
	!AreaType(OUTDOOR)
	!Range(NearestEnemyOf(Myself),30)
	Range(NearestDoor,15)
	OpenState(NearestDoor,FALSE)
THEN
	RESPONSE #100
		MoveToObject(NearestDoor)
		OpenDoor(NearestDoor)
END

// Random walking (in combat) 
IF
	Global("JA#COMBAT","LOCALS",1)
	ActionListEmpty()
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		RandomWalk()
		Wait(2)
END

// Random facing
IF
	!Range(NearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		RandomTurn()
END

