// Ability to literally step through a tree and then dimension door to the oak tree she is part of
IF
	Global("ja#trees","LOCALS",0)
	HaveSpell(WIZARD_DIMENSION_DOOR)
	AreaType(OUTDOOR)
	!AreaType(CITY)
	!AreaType(DUNGEON)
THEN
	RESPONSE #100
		SetGlobal("ja#trees","LOCALS",1)
END

IF
	Global("ja#trees","LOCALS",0)
	HaveSpell(WIZARD_DIMENSION_DOOR)
THEN
	RESPONSE #100
		RemoveSpell(WIZARD_DIMENSION_DOOR)
END

// Init
IF
	Global("JA#INIT","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("JA#INIT","LOCALS",1)
		SetGlobal("JA#COMBAT","LOCALS",0)
		SetGlobalTimer("JA#REST","LOCALS",2400)
END

// Rest (reset everything and heal if applicable)
IF
	Global("JA#INIT","LOCALS",1)
	GlobalTimerExpired("JA#REST","LOCALS")
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA#INIT","LOCALS",0)
		Rest()
END

// Turn hostile if attacked
IF
	Allegiance(Myself,NEUTRAL)
	OR(4)
		AttackedBy([GOODCUTOFF],DEFAULT)
		SpellCastOnMe([GOODCUTOFF],0)
		TookDamage()
		Heard([EVILCUTOFF.0.FAIRY],99)
THEN
	RESPONSE #100
		Enemy()
END

// Detect combat
IF
	Global("JA#COMBAT","LOCALS",0)
	Allegiance(Myself,EVILCUTOFF)
	See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
END

// Detect combat
IF
	Global("JA#COMBAT","LOCALS",0)
	Allegiance(Myself,GOODCUTOFF)
	See([EVILCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
END

// Shouts every 3 rounds
IF
	Global("JA#COMBAT","LOCALS",1)
	!GlobalTimerNotExpired("JA#HELP","LOCALS")
THEN
	RESPONSE #100
		Shout(99)
		SetGlobalTimer("JA#HELP","LOCALS",18)
END

// React to shouts
IF
	Global("JA#COMBAT","LOCALS",0)
	Heard([EVILCUTOFF.0.FAIRY],99)
	InMyArea([EVILCUTOFF.0.FAIRY])
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
		MoveToObject(LastHeardBy(Myself))
END

IF
	Global("JA#COMBAT","LOCALS",1)
	Heard([EVILCUTOFF.0.FAIRY],99)
	InMyArea([EVILCUTOFF.0.FAIRY])
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		MoveToObject(LastHeardBy(Myself))
END

// Random walk on panic
IF
	StateCheck(Myself,STATE_PANIC)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

// Do nothing if...
IF
	OR(3)
		Global("JA#COMBAT","LOCALS",0)
		StateCheck(Myself,STATE_IMMOBILE)
		StateCheck(Myself,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		NoAction()
END

// Dimension Door
IF
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	HaveSpell(WIZARD_DIMENSION_DOOR)
	OR(2)
		Range(NearestEnemyOf(Myself),10)
		AttackedBy([ANYONE],DEFAULT)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		CreateCreatureOffscreen("RR#TRAT",0)
		ForceSpell("RR#TRAT",WIZARD_DIMENSION_DOOR)
		Wait(1)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

// Speak with plants
IF
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!GlobalTimerNotExpired("speakWithPlants","LOCALS")
	HaveSpellRES("rr#fspkp")
	HaveSpellRES("rr#fspkp")
	CheckStatGT(Myself,0,ENTANGLE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fspkp",Myself)
		SetGlobalTimer("speakWithPlants","LOCALS",60)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

// Entangle
IF
	!GlobalTimerNotExpired("entangle","LOCALS")
	HaveSpellRES("RR#FENTG")
	RandomNumGT(800,240)
	CheckStat(NearestEnemyOf(Myself),0,ENTANGLE)
	!General(NearestEnemyOf(Myself),WEAPON)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
	!CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(NearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(NearestEnemyOf(Myself),STATE_REALLY_DEAD)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		ForceSpellRES("RR#FENTG",NearestEnemyOf(Myself))
		SetGlobalTimer("entangle","LOCALS",30)
END

IF
	!GlobalTimerNotExpired("entangle","LOCALS")
	HaveSpellRES("RR#FENTG")
	RandomNumGT(800,240)
	CheckStat(SecondNearestEnemyOf(Myself),0,ENTANGLE)
	!General(SecondNearestEnemyOf(Myself),WEAPON)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_INVISIBLE)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_REALLY_DEAD)
	See(SecondNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		ForceSpellRES("RR#FENTG",SecondNearestEnemyOf(Myself))
		SetGlobalTimer("entangle","LOCALS",30)
END

IF
	!GlobalTimerNotExpired("entangle","LOCALS")
	HaveSpellRES("RR#FENTG")
	RandomNumGT(800,240)
	CheckStat(ThirdNearestEnemyOf(Myself),0,ENTANGLE)
	!General(ThirdNearestEnemyOf(Myself),WEAPON)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_INVISIBLE)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_REALLY_DEAD)
	See(ThirdNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		ForceSpellRES("RR#FENTG",ThirdNearestEnemyOf(Myself))
		SetGlobalTimer("entangle","LOCALS",30)
END

IF
	!GlobalTimerNotExpired("entangle","LOCALS")
	HaveSpellRES("RR#FENTG")
	RandomNumGT(800,240)
	CheckStat(FourthNearestEnemyOf(Myself),0,ENTANGLE)
	!General(FourthNearestEnemyOf(Myself),WEAPON)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_INVISIBLE)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
	See(FourthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		ForceSpellRES("RR#FENTG",FourthNearestEnemyOf(Myself))
		SetGlobalTimer("entangle","LOCALS",30)
END

IF
	!GlobalTimerNotExpired("entangle","LOCALS")
	HaveSpellRES("RR#FENTG")
	RandomNumGT(800,240)
	CheckStat(FifthNearestEnemyOf(Myself),0,ENTANGLE)
	!General(FifthNearestEnemyOf(Myself),WEAPON)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_INVISIBLE)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
	See(FifthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		ForceSpellRES("RR#FENTG",FifthNearestEnemyOf(Myself))
		SetGlobalTimer("entangle","LOCALS",30)
END

IF
	!GlobalTimerNotExpired("entangle","LOCALS")
	HaveSpellRES("RR#FENTG")
	RandomNumGT(800,240)
	CheckStat(SixthNearestEnemyOf(Myself),0,ENTANGLE)
	!General(SixthNearestEnemyOf(Myself),WEAPON)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_INVISIBLE)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
	See(SixthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		ForceSpellRES("RR#FENTG",SixthNearestEnemyOf(Myself))
		SetGlobalTimer("entangle","LOCALS",30)
END

IF
	!GlobalTimerNotExpired("entangle","LOCALS")
	HaveSpellRES("RR#FENTG")
	RandomNumGT(800,240)
	CheckStat(SeventhNearestEnemyOf(Myself),0,ENTANGLE)
	!General(SeventhNearestEnemyOf(Myself),WEAPON)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_INVISIBLE)
	!CheckStatGT(SeventhNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_REALLY_DEAD)
	See(SeventhNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		ForceSpellRES("RR#FENTG",SeventhNearestEnemyOf(Myself))
		SetGlobalTimer("entangle","LOCALS",30)
END

IF
	!GlobalTimerNotExpired("entangle","LOCALS")
	HaveSpellRES("RR#FENTG")
	RandomNumGT(800,240)
	CheckStat(EighthNearestEnemyOf(Myself),0,ENTANGLE)
	!General(EighthNearestEnemyOf(Myself),WEAPON)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_INVISIBLE)
	!CheckStatGT(EighthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
	See(EighthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		ForceSpellRES("RR#FENTG",EighthNearestEnemyOf(Myself))
		SetGlobalTimer("entangle","LOCALS",30)
END

IF
	!GlobalTimerNotExpired("entangle","LOCALS")
	HaveSpellRES("RR#FENTG")
	RandomNumGT(800,240)
	CheckStat(NinthNearestEnemyOf(Myself),0,ENTANGLE)
	!General(NinthNearestEnemyOf(Myself),WEAPON)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_INVISIBLE)
	!CheckStatGT(NinthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
	See(NinthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		ForceSpellRES("RR#FENTG",NinthNearestEnemyOf(Myself))
		SetGlobalTimer("entangle","LOCALS",30)
END

IF
	!GlobalTimerNotExpired("entangle","LOCALS")
	HaveSpellRES("RR#FENTG")
	RandomNumGT(800,240)
	CheckStat(TenthNearestEnemyOf(Myself),0,ENTANGLE)
	!General(TenthNearestEnemyOf(Myself),WEAPON)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_INVISIBLE)
	!CheckStatGT(TenthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
	See(TenthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		ForceSpellRES("RR#FENTG",TenthNearestEnemyOf(Myself))
		SetGlobalTimer("entangle","LOCALS",30)
END

// Dire Charm
IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SecondNearest([PC.0.0.RANGER_ALL]),ELF)
	!Race(SecondNearest([PC.0.0.RANGER_ALL]),HALF_ELF)
	!CheckStatGT(SecondNearest([PC.0.0.RANGER_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_HELPLESS)
	!General(SecondNearest([PC.0.0.RANGER_ALL]),WEAPON)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_INVISIBLE)
	!CheckStatGT(SecondNearest([PC.0.0.RANGER_ALL]),0,SANCTUARY)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_CHARMED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_REALLY_DEAD)
	See(SecondNearest([PC.0.0.RANGER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",SecondNearest([PC.0.0.RANGER_ALL]))
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race([PC.0.0.RANGER_ALL],ELF)
	!Race([PC.0.0.RANGER_ALL],HALF_ELF)
	!CheckStatGT([PC.0.0.RANGER_ALL],0,HELD)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_STUNNED)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_PANIC)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_CONFUSED)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_FEEBLEMINDED)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_SLEEPING)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_HELPLESS)
	!General([PC.0.0.RANGER_ALL],WEAPON)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_IMPROVEDINVISIBILITY)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_INVISIBLE)
	!CheckStatGT([PC.0.0.RANGER_ALL],0,SANCTUARY)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_CHARMED)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_REALLY_DEAD)
	See([PC.0.0.RANGER_ALL])
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",[PC.0.0.RANGER_ALL])
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(ThirdNearest([PC.0.0.RANGER_ALL]),ELF)
	!Race(ThirdNearest([PC.0.0.RANGER_ALL]),HALF_ELF)
	!CheckStatGT(ThirdNearest([PC.0.0.RANGER_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_HELPLESS)
	!General(ThirdNearest([PC.0.0.RANGER_ALL]),WEAPON)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_INVISIBLE)
	!CheckStatGT(ThirdNearest([PC.0.0.RANGER_ALL]),0,SANCTUARY)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_CHARMED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_REALLY_DEAD)
	See(ThirdNearest([PC.0.0.RANGER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",ThirdNearest([PC.0.0.RANGER_ALL]))
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race([PC.0.0.PALADIN_ALL],ELF)
	!Race([PC.0.0.PALADIN_ALL],HALF_ELF)
	!CheckStatGT([PC.0.0.PALADIN_ALL],0,HELD)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_STUNNED)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_PANIC)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_CONFUSED)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_FEEBLEMINDED)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_SLEEPING)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_HELPLESS)
	!General([PC.0.0.PALADIN_ALL],WEAPON)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_IMPROVEDINVISIBILITY)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_INVISIBLE)
	!CheckStatGT([PC.0.0.PALADIN_ALL],0,SANCTUARY)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_CHARMED)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_REALLY_DEAD)
	See([PC.0.0.PALADIN_ALL])
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",[PC.0.0.PALADIN_ALL])
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SecondNearest([PC.0.0.FIGHTER_ALL]),ELF)
	!Race(SecondNearest([PC.0.0.FIGHTER_ALL]),HALF_ELF)
	!CheckStatGT(SecondNearest([PC.0.0.FIGHTER_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_HELPLESS)
	!General(SecondNearest([PC.0.0.FIGHTER_ALL]),WEAPON)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_INVISIBLE)
	!CheckStatGT(SecondNearest([PC.0.0.FIGHTER_ALL]),0,SANCTUARY)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_CHARMED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_REALLY_DEAD)
	See(SecondNearest([PC.0.0.FIGHTER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",SecondNearest([PC.0.0.FIGHTER_ALL]))
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race([PC.0.0.FIGHTER_ALL],ELF)
	!Race([PC.0.0.FIGHTER_ALL],HALF_ELF)
	!CheckStatGT([PC.0.0.FIGHTER_ALL],0,HELD)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_STUNNED)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_PANIC)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_CONFUSED)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_FEEBLEMINDED)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_SLEEPING)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_HELPLESS)
	!General([PC.0.0.FIGHTER_ALL],WEAPON)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_IMPROVEDINVISIBILITY)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_INVISIBLE)
	!CheckStatGT([PC.0.0.FIGHTER_ALL],0,SANCTUARY)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_CHARMED)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_REALLY_DEAD)
	See([PC.0.0.FIGHTER_ALL])
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",[PC.0.0.FIGHTER_ALL])
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(ThirdNearest([PC.0.0.FIGHTER_ALL]),ELF)
	!Race(ThirdNearest([PC.0.0.FIGHTER_ALL]),HALF_ELF)
	!CheckStatGT(ThirdNearest([PC.0.0.FIGHTER_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_HELPLESS)
	!General(ThirdNearest([PC.0.0.FIGHTER_ALL]),WEAPON)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_INVISIBLE)
	!CheckStatGT(ThirdNearest([PC.0.0.FIGHTER_ALL]),0,SANCTUARY)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_CHARMED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_REALLY_DEAD)
	See(ThirdNearest([PC.0.0.FIGHTER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",ThirdNearest([PC.0.0.FIGHTER_ALL]))
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SecondNearest([PC.0.0.PALADIN_ALL]),ELF)
	!Race(SecondNearest([PC.0.0.PALADIN_ALL]),HALF_ELF)
	!CheckStatGT(SecondNearest([PC.0.0.PALADIN_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
	!General(SecondNearest([PC.0.0.PALADIN_ALL]),WEAPON)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_INVISIBLE)
	!CheckStatGT(SecondNearest([PC.0.0.PALADIN_ALL]),0,SANCTUARY)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_REALLY_DEAD)
	See(SecondNearest([PC.0.0.PALADIN_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",SecondNearest([PC.0.0.PALADIN_ALL]))
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(ThirdNearest([PC.0.0.PALADIN_ALL]),ELF)
	!Race(ThirdNearest([PC.0.0.PALADIN_ALL]),HALF_ELF)
	!CheckStatGT(ThirdNearest([PC.0.0.PALADIN_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
	!General(ThirdNearest([PC.0.0.PALADIN_ALL]),WEAPON)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_INVISIBLE)
	!CheckStatGT(ThirdNearest([PC.0.0.PALADIN_ALL]),0,SANCTUARY)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_REALLY_DEAD)
	See(ThirdNearest([PC.0.0.PALADIN_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",ThirdNearest([PC.0.0.PALADIN_ALL]))
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

// Dire Charm
IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SecondNearest([PC]),ELF)
	!Race(SecondNearest([PC]),HALF_ELF)
	!CheckStatGT(SecondNearest([PC]),0,HELD)
	!StateCheck(SecondNearest([PC]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC]),STATE_PANIC)
	!StateCheck(SecondNearest([PC]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC]),STATE_HELPLESS)
	!General(SecondNearest([PC]),WEAPON)
	!StateCheck(SecondNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(SecondNearest([PC]),STATE_INVISIBLE)
	!CheckStatGT(SecondNearest([PC]),0,SANCTUARY)
	!StateCheck(SecondNearest([PC]),STATE_CHARMED)
	!StateCheck(SecondNearest([PC]),STATE_REALLY_DEAD)
	See(SecondNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",SecondNearest([PC]))
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race([PC],ELF)
	!Race([PC],HALF_ELF)
	!CheckStatGT([PC],0,HELD)
	!StateCheck([PC],STATE_STUNNED)
	!StateCheck([PC],STATE_PANIC)
	!StateCheck([PC],STATE_CONFUSED)
	!StateCheck([PC],STATE_FEEBLEMINDED)
	!StateCheck([PC],STATE_SLEEPING)
	!StateCheck([PC],STATE_HELPLESS)
	!General([PC],WEAPON)
	!StateCheck([PC],STATE_IMPROVEDINVISIBILITY)
	!StateCheck([PC],STATE_INVISIBLE)
	!CheckStatGT([PC],0,SANCTUARY)
	!StateCheck([PC],STATE_CHARMED)
	!StateCheck([PC],STATE_REALLY_DEAD)
	See([PC])
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",[PC])
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(FourthNearest([PC]),ELF)
	!Race(FourthNearest([PC]),HALF_ELF)
	!CheckStatGT(FourthNearest([PC]),0,HELD)
	!StateCheck(FourthNearest([PC]),STATE_STUNNED)
	!StateCheck(FourthNearest([PC]),STATE_PANIC)
	!StateCheck(FourthNearest([PC]),STATE_CONFUSED)
	!StateCheck(FourthNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(FourthNearest([PC]),STATE_SLEEPING)
	!StateCheck(FourthNearest([PC]),STATE_HELPLESS)
	!General(FourthNearest([PC]),WEAPON)
	!StateCheck(FourthNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(FourthNearest([PC]),STATE_INVISIBLE)
	!CheckStatGT(FourthNearest([PC]),0,SANCTUARY)
	!StateCheck(FourthNearest([PC]),STATE_CHARMED)
	!StateCheck(FourthNearest([PC]),STATE_REALLY_DEAD)
	See(FourthNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",FourthNearest([PC]))
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SixthNearest([PC]),ELF)
	!Race(SixthNearest([PC]),HALF_ELF)
	!CheckStatGT(SixthNearest([PC]),0,HELD)
	!StateCheck(SixthNearest([PC]),STATE_STUNNED)
	!StateCheck(SixthNearest([PC]),STATE_PANIC)
	!StateCheck(SixthNearest([PC]),STATE_CONFUSED)
	!StateCheck(SixthNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(SixthNearest([PC]),STATE_SLEEPING)
	!StateCheck(SixthNearest([PC]),STATE_HELPLESS)
	!General(SixthNearest([PC]),WEAPON)
	!StateCheck(SixthNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(SixthNearest([PC]),STATE_INVISIBLE)
	!CheckStatGT(SixthNearest([PC]),0,SANCTUARY)
	!StateCheck(SixthNearest([PC]),STATE_CHARMED)
	!StateCheck(SixthNearest([PC]),STATE_REALLY_DEAD)
	See(SixthNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",SixthNearest([PC]))
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(FifthNearest([PC]),ELF)
	!Race(FifthNearest([PC]),HALF_ELF)
	!CheckStatGT(FifthNearest([PC]),0,HELD)
	!StateCheck(FifthNearest([PC]),STATE_STUNNED)
	!StateCheck(FifthNearest([PC]),STATE_PANIC)
	!StateCheck(FifthNearest([PC]),STATE_CONFUSED)
	!StateCheck(FifthNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(FifthNearest([PC]),STATE_SLEEPING)
	!StateCheck(FifthNearest([PC]),STATE_HELPLESS)
	!General(FifthNearest([PC]),WEAPON)
	!StateCheck(FifthNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(FifthNearest([PC]),STATE_INVISIBLE)
	!CheckStatGT(FifthNearest([PC]),0,SANCTUARY)
	!StateCheck(FifthNearest([PC]),STATE_CHARMED)
	!StateCheck(FifthNearest([PC]),STATE_REALLY_DEAD)
	See(FifthNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",FifthNearest([PC]))
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(ThirdNearest([PC]),ELF)
	!Race(ThirdNearest([PC]),HALF_ELF)
	!CheckStatGT(ThirdNearest([PC]),0,HELD)
	!StateCheck(ThirdNearest([PC]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC]),STATE_HELPLESS)
	!General(ThirdNearest([PC]),WEAPON)
	!StateCheck(ThirdNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(ThirdNearest([PC]),STATE_INVISIBLE)
	!CheckStatGT(ThirdNearest([PC]),0,SANCTUARY)
	!StateCheck(ThirdNearest([PC]),STATE_CHARMED)
	!StateCheck(ThirdNearest([PC]),STATE_REALLY_DEAD)
	See(ThirdNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",ThirdNearest([PC]))
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

// Dire Charm
IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race([PC.0.0.RANGER_ALL],ELF)
	!CheckStatGT([PC.0.0.RANGER_ALL],0,HELD)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_STUNNED)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_PANIC)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_CONFUSED)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_FEEBLEMINDED)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_SLEEPING)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_HELPLESS)
	!General([PC.0.0.RANGER_ALL],WEAPON)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_IMPROVEDINVISIBILITY)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_INVISIBLE)
	!CheckStatGT([PC.0.0.RANGER_ALL],0,SANCTUARY)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_CHARMED)
	!StateCheck([PC.0.0.RANGER_ALL],STATE_REALLY_DEAD)
	See([PC.0.0.RANGER_ALL])
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",[PC.0.0.RANGER_ALL])
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(ThirdNearest([PC.0.0.FIGHTER_ALL]),ELF)
	!CheckStatGT(ThirdNearest([PC.0.0.FIGHTER_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_HELPLESS)
	!General(ThirdNearest([PC.0.0.FIGHTER_ALL]),WEAPON)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_INVISIBLE)
	!CheckStatGT(ThirdNearest([PC.0.0.FIGHTER_ALL]),0,SANCTUARY)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_CHARMED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_REALLY_DEAD)
	See(ThirdNearest([PC.0.0.FIGHTER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",ThirdNearest([PC.0.0.FIGHTER_ALL]))
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SecondNearest([PC.0.0.FIGHTER_ALL]),ELF)
	!CheckStatGT(SecondNearest([PC.0.0.FIGHTER_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_HELPLESS)
	!General(SecondNearest([PC.0.0.FIGHTER_ALL]),WEAPON)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_INVISIBLE)
	!CheckStatGT(SecondNearest([PC.0.0.FIGHTER_ALL]),0,SANCTUARY)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_CHARMED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_REALLY_DEAD)
	See(SecondNearest([PC.0.0.FIGHTER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",SecondNearest([PC.0.0.FIGHTER_ALL]))
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(ThirdNearest([PC.0.0.PALADIN_ALL]),ELF)
	!CheckStatGT(ThirdNearest([PC.0.0.PALADIN_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
	!General(ThirdNearest([PC.0.0.PALADIN_ALL]),WEAPON)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_INVISIBLE)
	!CheckStatGT(ThirdNearest([PC.0.0.PALADIN_ALL]),0,SANCTUARY)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_REALLY_DEAD)
	See(ThirdNearest([PC.0.0.PALADIN_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",ThirdNearest([PC.0.0.PALADIN_ALL]))
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race([PC.0.0.FIGHTER_ALL],ELF)
	!CheckStatGT([PC.0.0.FIGHTER_ALL],0,HELD)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_STUNNED)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_PANIC)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_CONFUSED)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_FEEBLEMINDED)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_SLEEPING)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_HELPLESS)
	!General([PC.0.0.FIGHTER_ALL],WEAPON)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_IMPROVEDINVISIBILITY)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_INVISIBLE)
	!CheckStatGT([PC.0.0.FIGHTER_ALL],0,SANCTUARY)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_CHARMED)
	!StateCheck([PC.0.0.FIGHTER_ALL],STATE_REALLY_DEAD)
	See([PC.0.0.FIGHTER_ALL])
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",[PC.0.0.FIGHTER_ALL])
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SecondNearest([PC.0.0.PALADIN_ALL]),ELF)
	!CheckStatGT(SecondNearest([PC.0.0.PALADIN_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
	!General(SecondNearest([PC.0.0.PALADIN_ALL]),WEAPON)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_INVISIBLE)
	!CheckStatGT(SecondNearest([PC.0.0.PALADIN_ALL]),0,SANCTUARY)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_REALLY_DEAD)
	See(SecondNearest([PC.0.0.PALADIN_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",SecondNearest([PC.0.0.PALADIN_ALL]))
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race([PC.0.0.PALADIN_ALL],ELF)
	!CheckStatGT([PC.0.0.PALADIN_ALL],0,HELD)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_STUNNED)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_PANIC)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_CONFUSED)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_FEEBLEMINDED)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_SLEEPING)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_HELPLESS)
	!General([PC.0.0.PALADIN_ALL],WEAPON)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_IMPROVEDINVISIBILITY)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_INVISIBLE)
	!CheckStatGT([PC.0.0.PALADIN_ALL],0,SANCTUARY)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_CHARMED)
	!StateCheck([PC.0.0.PALADIN_ALL],STATE_REALLY_DEAD)
	See([PC.0.0.PALADIN_ALL])
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",[PC.0.0.PALADIN_ALL])
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(ThirdNearest([PC.0.0.RANGER_ALL]),ELF)
	!CheckStatGT(ThirdNearest([PC.0.0.RANGER_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_HELPLESS)
	!General(ThirdNearest([PC.0.0.RANGER_ALL]),WEAPON)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_INVISIBLE)
	!CheckStatGT(ThirdNearest([PC.0.0.RANGER_ALL]),0,SANCTUARY)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_CHARMED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_REALLY_DEAD)
	See(ThirdNearest([PC.0.0.RANGER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",ThirdNearest([PC.0.0.RANGER_ALL]))
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SecondNearest([PC.0.0.RANGER_ALL]),ELF)
	!CheckStatGT(SecondNearest([PC.0.0.RANGER_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_HELPLESS)
	!General(SecondNearest([PC.0.0.RANGER_ALL]),WEAPON)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_INVISIBLE)
	!CheckStatGT(SecondNearest([PC.0.0.RANGER_ALL]),0,SANCTUARY)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_CHARMED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_REALLY_DEAD)
	See(SecondNearest([PC.0.0.RANGER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",SecondNearest([PC.0.0.RANGER_ALL]))
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

// Dire Charm
IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!CheckStatGT(SixthNearest([PC]),0,HELD)
	!StateCheck(SixthNearest([PC]),STATE_STUNNED)
	!StateCheck(SixthNearest([PC]),STATE_PANIC)
	!StateCheck(SixthNearest([PC]),STATE_CONFUSED)
	!StateCheck(SixthNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(SixthNearest([PC]),STATE_SLEEPING)
	!StateCheck(SixthNearest([PC]),STATE_HELPLESS)
	!General(SixthNearest([PC]),WEAPON)
	!StateCheck(SixthNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(SixthNearest([PC]),STATE_INVISIBLE)
	!CheckStatGT(SixthNearest([PC]),0,SANCTUARY)
	!StateCheck(SixthNearest([PC]),STATE_CHARMED)
	!StateCheck(SixthNearest([PC]),STATE_REALLY_DEAD)
	See(SixthNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",SixthNearest([PC]))
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!CheckStatGT(SecondNearest([PC]),0,HELD)
	!StateCheck(SecondNearest([PC]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC]),STATE_PANIC)
	!StateCheck(SecondNearest([PC]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC]),STATE_HELPLESS)
	!General(SecondNearest([PC]),WEAPON)
	!StateCheck(SecondNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(SecondNearest([PC]),STATE_INVISIBLE)
	!CheckStatGT(SecondNearest([PC]),0,SANCTUARY)
	!StateCheck(SecondNearest([PC]),STATE_CHARMED)
	!StateCheck(SecondNearest([PC]),STATE_REALLY_DEAD)
	See(SecondNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",SecondNearest([PC]))
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!CheckStatGT(FifthNearest([PC]),0,HELD)
	!StateCheck(FifthNearest([PC]),STATE_STUNNED)
	!StateCheck(FifthNearest([PC]),STATE_PANIC)
	!StateCheck(FifthNearest([PC]),STATE_CONFUSED)
	!StateCheck(FifthNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(FifthNearest([PC]),STATE_SLEEPING)
	!StateCheck(FifthNearest([PC]),STATE_HELPLESS)
	!General(FifthNearest([PC]),WEAPON)
	!StateCheck(FifthNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(FifthNearest([PC]),STATE_INVISIBLE)
	!CheckStatGT(FifthNearest([PC]),0,SANCTUARY)
	!StateCheck(FifthNearest([PC]),STATE_CHARMED)
	!StateCheck(FifthNearest([PC]),STATE_REALLY_DEAD)
	See(FifthNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",FifthNearest([PC]))
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!CheckStatGT([PC],0,HELD)
	!StateCheck([PC],STATE_STUNNED)
	!StateCheck([PC],STATE_PANIC)
	!StateCheck([PC],STATE_CONFUSED)
	!StateCheck([PC],STATE_FEEBLEMINDED)
	!StateCheck([PC],STATE_SLEEPING)
	!StateCheck([PC],STATE_HELPLESS)
	!General([PC],WEAPON)
	!StateCheck([PC],STATE_IMPROVEDINVISIBILITY)
	!StateCheck([PC],STATE_INVISIBLE)
	!CheckStatGT([PC],0,SANCTUARY)
	!StateCheck([PC],STATE_CHARMED)
	!StateCheck([PC],STATE_REALLY_DEAD)
	See([PC])
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",[PC])
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!CheckStatGT(ThirdNearest([PC]),0,HELD)
	!StateCheck(ThirdNearest([PC]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC]),STATE_HELPLESS)
	!General(ThirdNearest([PC]),WEAPON)
	!StateCheck(ThirdNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(ThirdNearest([PC]),STATE_INVISIBLE)
	!CheckStatGT(ThirdNearest([PC]),0,SANCTUARY)
	!StateCheck(ThirdNearest([PC]),STATE_CHARMED)
	!StateCheck(ThirdNearest([PC]),STATE_REALLY_DEAD)
	See(ThirdNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",ThirdNearest([PC]))
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("rr#fchrm")
	RandomNumGT(801,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!CheckStatGT(FourthNearest([PC]),0,HELD)
	!StateCheck(FourthNearest([PC]),STATE_STUNNED)
	!StateCheck(FourthNearest([PC]),STATE_PANIC)
	!StateCheck(FourthNearest([PC]),STATE_CONFUSED)
	!StateCheck(FourthNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(FourthNearest([PC]),STATE_SLEEPING)
	!StateCheck(FourthNearest([PC]),STATE_HELPLESS)
	!General(FourthNearest([PC]),WEAPON)
	!StateCheck(FourthNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(FourthNearest([PC]),STATE_INVISIBLE)
	!CheckStatGT(FourthNearest([PC]),0,SANCTUARY)
	!StateCheck(FourthNearest([PC]),STATE_CHARMED)
	!StateCheck(FourthNearest([PC]),STATE_REALLY_DEAD)
	See(FourthNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("rr#fchrm",FourthNearest([PC]))
		RemoveSpellRES("rr#fchrm")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

// Run away from enemies
IF
	Range(NearestEnemyOf(Myself),20)
THEN
	RESPONSE #100
		RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),45)
END

// Track players if allegiance is not GOODCUTOFF
IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player1,150)
	HaveSpellRES("rr#fchrm")
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStatGT(Player1,0,SANCTUARY)
	!StateCheck(Player1,STATE_CHARMED)
	!StateCheck(Player1,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player2,150)
	HaveSpellRES("rr#fchrm")
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStatGT(Player2,0,SANCTUARY)
	!StateCheck(Player2,STATE_CHARMED)
	!StateCheck(Player2,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player2)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player3,150)
	HaveSpellRES("rr#fchrm")
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStatGT(Player3,0,SANCTUARY)
	!StateCheck(Player3,STATE_CHARMED)
	!StateCheck(Player3,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player3)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player4,150)
	HaveSpellRES("rr#fchrm")
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStatGT(Player4,0,SANCTUARY)
	!StateCheck(Player4,STATE_CHARMED)
	!StateCheck(Player4,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player4)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player5,150)
	HaveSpellRES("rr#fchrm")
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStatGT(Player5,0,SANCTUARY)
	!StateCheck(Player5,STATE_CHARMED)
	!StateCheck(Player5,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player5)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player6,150)
	HaveSpellRES("rr#fchrm")
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStatGT(Player6,0,SANCTUARY)
	!StateCheck(Player6,STATE_CHARMED)
	!StateCheck(Player6,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player6)
END

// Track last seen enemy if allegiance is GOODCUTOFF
IF
	Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(LastSeenBy(Myself),150)
	HaveSpellRES("rr#fchrm")
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

// Open door
IF
	Global("RR#NOPND","GLOBAL",0)
	Allegiance(Myself,EVILCUTOFF)
	!AreaType(OUTDOOR)
	!Range(NearestEnemyOf(Myself),30)
	Range(NearestDoor,15)
	OpenState(NearestDoor,FALSE)
THEN
	RESPONSE #100
		MoveToObject(NearestDoor)
		OpenDoor(NearestDoor)
END

// Random walking (in combat) 
IF
	Global("JA#COMBAT","LOCALS",1)
	ActionListEmpty()
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		RandomWalk()
		Wait(2)
END

// Random facing
IF
	!Range(NearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		RandomTurn()
END

