// Ability to literally step through a tree and then dimension door to the oak tree she is part of
IF
	Global("ja#trees","LOCALS",0)
	HaveSpell(WIZARD_DIMENSION_DOOR)
	AreaType(OUTDOOR)
	!AreaType(CITY)
	!AreaType(DUNGEON)
THEN
	RESPONSE #100
		SetGlobal("ja#trees","LOCALS",1)
END

IF
	Global("ja#trees","LOCALS",0)
	HaveSpell(WIZARD_DIMENSION_DOOR)
THEN
	RESPONSE #100
		RemoveSpell(WIZARD_DIMENSION_DOOR)
END

// Initiate dialog
IF
	Global("ja#dialog","LOCALS",0)
	OR(2)
		Name("CDryad",Myself)
		Name("Ulene",Myself)
	NumTimesTalkedTo(0)
	See([PC])
THEN
	RESPONSE #100
		SetGlobal("ja#dialog","LOCALS",1)
		FaceObject([PC])
		StartDialogueNoSet([PC])
END

// Irenicus' Dungeon specific code
IF
	Name("Ulene",Myself)
	AreaCheck("AR0602")
	Global("MinscCharmed","AR0602",1)
	Global("HelpDryads","GLOBAL",0)
	!See("Minsc")
	!Range("Minsc",4)
THEN
	RESPONSE #100
		ActionOverride("Minsc",JumpToPoint([4069.1222]))
END

IF
	Name("Ulene",Myself)
	AreaCheck("AR0602")
	Global("MinscCharmed","AR0602",1)
	Global("HelpDryads","GLOBAL",0)
	See("Minsc")
	!Range("Minsc",4)
THEN
	RESPONSE #100
		ActionOverride("Minsc",MoveToObject("Ulene"))
END

// Init
IF
	Global("JA#INIT","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("JA#INIT","LOCALS",1)
		SetGlobal("JA#COMBAT","LOCALS",0)
		SetGlobal("JA#MELEE","LOCALS",0)
		SetGlobal("JA#DISABLE_SPELLCASTING","LOCALS",0)
		SetGlobalTimer("JA#REST","LOCALS",2400)
END

// Rest (reset everything and heal if applicable)
IF
	Global("JA#INIT","LOCALS",1)
	GlobalTimerExpired("JA#REST","LOCALS")
	!Detect([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA#INIT","LOCALS",0)
		Rest()
END

// Turn hostile if attacked
IF
	!Allegiance(Myself,ENEMY)
	OR(6)
		AttackedBy([GOODCUTOFF],DEFAULT)
		AttackedBy([CONTROLLED],DEFAULT)
		AttackedBy([CHARMED],DEFAULT)
		SpellCastOnMe([GOODCUTOFF],0)
		SpellCastOnMe([CONTROLLED],0)
		SpellCastOnMe([CHARMED],0)
THEN
	RESPONSE #100
		Enemy()
END

// Random walk on panic
IF
	StateCheck(Myself,STATE_PANIC)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

// Detect combat
IF
	Global("JA#COMBAT","LOCALS",0)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
		Shout(95)
END

// React to shouts
IF
	Global("JA#COMBAT","LOCALS",0)
	Heard([EVILCUTOFF.0.FAIRY],95)
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
END

// Do nothing if combat is not started
IF
	Global("JA#COMBAT","LOCALS",0)
	ActionListEmpty()
THEN
	RESPONSE #100
		NoAction()
END

// Dire Charm
IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race([PC.0.0.FIGHTER],ELF)
	!CheckStatGT([PC.0.0.FIGHTER],0,HELD)
	!StateCheck([PC.0.0.FIGHTER],STATE_STUNNED)
	!StateCheck([PC.0.0.FIGHTER],STATE_PANIC)
	!StateCheck([PC.0.0.FIGHTER],STATE_CONFUSED)
	!StateCheck([PC.0.0.FIGHTER],STATE_FEEBLEMINDED)
	!StateCheck([PC.0.0.FIGHTER],STATE_SLEEPING)
	!StateCheck([PC.0.0.FIGHTER],STATE_HELPLESS)
	!General([PC.0.0.FIGHTER],WEAPON)
	!StateCheck([PC.0.0.FIGHTER],STATE_IMPROVEDINVISIBILITY)
	!StateCheck([PC.0.0.FIGHTER],STATE_INVISIBLE)
	!CheckStatGT([PC.0.0.FIGHTER],0,SANCTUARY)
	!StateCheck([PC.0.0.FIGHTER],STATE_CHARMED)
	!StateCheck([PC.0.0.FIGHTER],STATE_REALLY_DEAD)
	See([PC.0.0.FIGHTER])
	RandomNumGT(1000,111)
THEN
	RESPONSE #100
		SpellRES("ja#1m41",[PC.0.0.FIGHTER])
		SetGlobalTimer("JA#ROUND","LOCALS",6)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race([PC.0.0.RANGER],ELF)
	!CheckStatGT([PC.0.0.RANGER],0,HELD)
	!StateCheck([PC.0.0.RANGER],STATE_STUNNED)
	!StateCheck([PC.0.0.RANGER],STATE_PANIC)
	!StateCheck([PC.0.0.RANGER],STATE_CONFUSED)
	!StateCheck([PC.0.0.RANGER],STATE_FEEBLEMINDED)
	!StateCheck([PC.0.0.RANGER],STATE_SLEEPING)
	!StateCheck([PC.0.0.RANGER],STATE_HELPLESS)
	!General([PC.0.0.RANGER],WEAPON)
	!StateCheck([PC.0.0.RANGER],STATE_IMPROVEDINVISIBILITY)
	!StateCheck([PC.0.0.RANGER],STATE_INVISIBLE)
	!CheckStatGT([PC.0.0.RANGER],0,SANCTUARY)
	!StateCheck([PC.0.0.RANGER],STATE_CHARMED)
	!StateCheck([PC.0.0.RANGER],STATE_REALLY_DEAD)
	See([PC.0.0.RANGER])
	RandomNumGT(1000,125)
THEN
	RESPONSE #100
		SpellRES("ja#1m41",[PC.0.0.RANGER])
		SetGlobalTimer("JA#ROUND","LOCALS",6)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race([PC.0.0.PALADIN],ELF)
	!CheckStatGT([PC.0.0.PALADIN],0,HELD)
	!StateCheck([PC.0.0.PALADIN],STATE_STUNNED)
	!StateCheck([PC.0.0.PALADIN],STATE_PANIC)
	!StateCheck([PC.0.0.PALADIN],STATE_CONFUSED)
	!StateCheck([PC.0.0.PALADIN],STATE_FEEBLEMINDED)
	!StateCheck([PC.0.0.PALADIN],STATE_SLEEPING)
	!StateCheck([PC.0.0.PALADIN],STATE_HELPLESS)
	!General([PC.0.0.PALADIN],WEAPON)
	!StateCheck([PC.0.0.PALADIN],STATE_IMPROVEDINVISIBILITY)
	!StateCheck([PC.0.0.PALADIN],STATE_INVISIBLE)
	!CheckStatGT([PC.0.0.PALADIN],0,SANCTUARY)
	!StateCheck([PC.0.0.PALADIN],STATE_CHARMED)
	!StateCheck([PC.0.0.PALADIN],STATE_REALLY_DEAD)
	See([PC.0.0.PALADIN])
	RandomNumGT(1000,143)
THEN
	RESPONSE #100
		SpellRES("ja#1m41",[PC.0.0.PALADIN])
		SetGlobalTimer("JA#ROUND","LOCALS",6)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race([PC.0.0.FIGHTER_THIEF],ELF)
	!CheckStatGT([PC.0.0.FIGHTER_THIEF],0,HELD)
	!StateCheck([PC.0.0.FIGHTER_THIEF],STATE_STUNNED)
	!StateCheck([PC.0.0.FIGHTER_THIEF],STATE_PANIC)
	!StateCheck([PC.0.0.FIGHTER_THIEF],STATE_CONFUSED)
	!StateCheck([PC.0.0.FIGHTER_THIEF],STATE_FEEBLEMINDED)
	!StateCheck([PC.0.0.FIGHTER_THIEF],STATE_SLEEPING)
	!StateCheck([PC.0.0.FIGHTER_THIEF],STATE_HELPLESS)
	!General([PC.0.0.FIGHTER_THIEF],WEAPON)
	!StateCheck([PC.0.0.FIGHTER_THIEF],STATE_IMPROVEDINVISIBILITY)
	!StateCheck([PC.0.0.FIGHTER_THIEF],STATE_INVISIBLE)
	!CheckStatGT([PC.0.0.FIGHTER_THIEF],0,SANCTUARY)
	!StateCheck([PC.0.0.FIGHTER_THIEF],STATE_CHARMED)
	!StateCheck([PC.0.0.FIGHTER_THIEF],STATE_REALLY_DEAD)
	See([PC.0.0.FIGHTER_THIEF])
	RandomNumGT(1000,167)
THEN
	RESPONSE #100
		SpellRES("ja#1m41",[PC.0.0.FIGHTER_THIEF])
		SetGlobalTimer("JA#ROUND","LOCALS",6)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race([PC.0.0.BARD],ELF)
	!CheckStatGT([PC.0.0.BARD],0,HELD)
	!StateCheck([PC.0.0.BARD],STATE_STUNNED)
	!StateCheck([PC.0.0.BARD],STATE_PANIC)
	!StateCheck([PC.0.0.BARD],STATE_CONFUSED)
	!StateCheck([PC.0.0.BARD],STATE_FEEBLEMINDED)
	!StateCheck([PC.0.0.BARD],STATE_SLEEPING)
	!StateCheck([PC.0.0.BARD],STATE_HELPLESS)
	!General([PC.0.0.BARD],WEAPON)
	!StateCheck([PC.0.0.BARD],STATE_IMPROVEDINVISIBILITY)
	!StateCheck([PC.0.0.BARD],STATE_INVISIBLE)
	!CheckStatGT([PC.0.0.BARD],0,SANCTUARY)
	!StateCheck([PC.0.0.BARD],STATE_CHARMED)
	!StateCheck([PC.0.0.BARD],STATE_REALLY_DEAD)
	See([PC.0.0.BARD])
	RandomNumGT(1000,200)
THEN
	RESPONSE #100
		SpellRES("ja#1m41",[PC.0.0.BARD])
		SetGlobalTimer("JA#ROUND","LOCALS",6)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race([PC.0.0.THIEF],ELF)
	!CheckStatGT([PC.0.0.THIEF],0,HELD)
	!StateCheck([PC.0.0.THIEF],STATE_STUNNED)
	!StateCheck([PC.0.0.THIEF],STATE_PANIC)
	!StateCheck([PC.0.0.THIEF],STATE_CONFUSED)
	!StateCheck([PC.0.0.THIEF],STATE_FEEBLEMINDED)
	!StateCheck([PC.0.0.THIEF],STATE_SLEEPING)
	!StateCheck([PC.0.0.THIEF],STATE_HELPLESS)
	!General([PC.0.0.THIEF],WEAPON)
	!StateCheck([PC.0.0.THIEF],STATE_IMPROVEDINVISIBILITY)
	!StateCheck([PC.0.0.THIEF],STATE_INVISIBLE)
	!CheckStatGT([PC.0.0.THIEF],0,SANCTUARY)
	!StateCheck([PC.0.0.THIEF],STATE_CHARMED)
	!StateCheck([PC.0.0.THIEF],STATE_REALLY_DEAD)
	See([PC.0.0.THIEF])
	RandomNumGT(1000,250)
THEN
	RESPONSE #100
		SpellRES("ja#1m41",[PC.0.0.THIEF])
		SetGlobalTimer("JA#ROUND","LOCALS",6)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race([PC],ELF)
	!CheckStatGT([PC],0,HELD)
	!StateCheck([PC],STATE_STUNNED)
	!StateCheck([PC],STATE_PANIC)
	!StateCheck([PC],STATE_CONFUSED)
	!StateCheck([PC],STATE_FEEBLEMINDED)
	!StateCheck([PC],STATE_SLEEPING)
	!StateCheck([PC],STATE_HELPLESS)
	!General([PC],WEAPON)
	!StateCheck([PC],STATE_IMPROVEDINVISIBILITY)
	!StateCheck([PC],STATE_INVISIBLE)
	!CheckStatGT([PC],0,SANCTUARY)
	!StateCheck([PC],STATE_CHARMED)
	!StateCheck([PC],STATE_REALLY_DEAD)
	See([PC])
	RandomNumGT(1000,333)
THEN
	RESPONSE #100
		SpellRES("ja#1m41",[PC])
		SetGlobalTimer("JA#ROUND","LOCALS",6)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SecondNearest([PC]),ELF)
	!CheckStatGT(SecondNearest([PC]),0,HELD)
	!StateCheck(SecondNearest([PC]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC]),STATE_PANIC)
	!StateCheck(SecondNearest([PC]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC]),STATE_HELPLESS)
	!General(SecondNearest([PC]),WEAPON)
	!StateCheck(SecondNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(SecondNearest([PC]),STATE_INVISIBLE)
	!CheckStatGT(SecondNearest([PC]),0,SANCTUARY)
	!StateCheck(SecondNearest([PC]),STATE_CHARMED)
	!StateCheck(SecondNearest([PC]),STATE_REALLY_DEAD)
	See(SecondNearest([PC]))
	RandomNumGT(1000,500)
THEN
	RESPONSE #100
		SpellRES("ja#1m41",SecondNearest([PC]))
		SetGlobalTimer("JA#ROUND","LOCALS",6)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(ThirdNearest([PC]),ELF)
	!CheckStatGT(ThirdNearest([PC]),0,HELD)
	!StateCheck(ThirdNearest([PC]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC]),STATE_HELPLESS)
	!General(ThirdNearest([PC]),WEAPON)
	!StateCheck(ThirdNearest([PC]),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(ThirdNearest([PC]),STATE_INVISIBLE)
	!CheckStatGT(ThirdNearest([PC]),0,SANCTUARY)
	!StateCheck(ThirdNearest([PC]),STATE_CHARMED)
	!StateCheck(ThirdNearest([PC]),STATE_REALLY_DEAD)
	See(ThirdNearest([PC]))
THEN
	RESPONSE #100
		SpellRES("ja#1m41",ThirdNearest([PC]))
		SetGlobalTimer("JA#ROUND","LOCALS",6)
END

IF
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!GlobalTimerNotExpired("speakWithPlants","LOCALS")
	HaveSpellRES("ja#2m41")
THEN
	RESPONSE #100
		ForceSpellRES("ja#2m41",Myself)
		SetGlobalTimer("speakWithPlants","LOCALS",60)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
END

// Potion of extra healing (40hp)
IF
	HasItem("POTN55",Myself)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!General(Myself,UNDEAD)
	HPPercentLT(Myself,30)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@3002)
		UseItem("POTN55",Myself)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
END

// Potion of extra healing (30hp)
IF
	HasItem("POTN52",Myself)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!General(Myself,UNDEAD)
	HPPercentLT(Myself,40)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@3002)
		UseItem("POTN52",Myself)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
END

// Exilir of health (10hp)
IF
	HasItem("POTN08",Myself)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!General(Myself,UNDEAD)
	HPPercentLT(Myself,75)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@3002)
		UseItem("POTN08",Myself)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
END

// Potion of healing (10hp)
IF
	HasItem("POTN08",Myself)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!General(Myself,UNDEAD)
	HPPercentLT(Myself,75)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@3002)
		UseItem("POTN08",Myself)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
END

// Potion of speed
IF
	HasItem("POTN14",Myself)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	RandomNumLT(888,100)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@3002)
		UseItem("POTN14",Myself)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
END

// Run away from enemies
IF
	Range(NearestEnemyOf(Myself),20)
THEN
	RESPONSE #100
		RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),45)
END

// Track players if allegiance is not GOODCUTOFF
IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player1,150)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStatGT(Player1,0,SANCTUARY)
	!StateCheck(Player1,STATE_CHARMED)
	!StateCheck(Player1,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player2,150)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStatGT(Player2,0,SANCTUARY)
	!StateCheck(Player2,STATE_CHARMED)
	!StateCheck(Player2,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player2)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player3,150)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStatGT(Player3,0,SANCTUARY)
	!StateCheck(Player3,STATE_CHARMED)
	!StateCheck(Player3,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player3)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player4,150)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStatGT(Player4,0,SANCTUARY)
	!StateCheck(Player4,STATE_CHARMED)
	!StateCheck(Player4,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player4)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player5,150)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStatGT(Player5,0,SANCTUARY)
	!StateCheck(Player5,STATE_CHARMED)
	!StateCheck(Player5,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player5)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player6,150)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStatGT(Player6,0,SANCTUARY)
	!StateCheck(Player6,STATE_CHARMED)
	!StateCheck(Player6,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player6)
END

// Track last seen enemy if allegiance is GOODCUTOFF
IF
	Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(LastSeenBy(Myself),150)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

