// Summons are destroyed on death
IF
	Die()
THEN
	RESPONSE #100
		DestroySelf()
END

// Ability to literally step through a tree and then dimension door to the oak tree she is part of
IF
	Global("ja#trees","LOCALS",0)
	HaveSpell(WIZARD_DIMENSION_DOOR)
	AreaType(OUTDOOR)
	!AreaType(CITY)
	!AreaType(DUNGEON)
THEN
	RESPONSE #100
		SetGlobal("ja#trees","LOCALS",1)
END

IF
	Global("ja#trees","LOCALS",0)
	HaveSpell(WIZARD_DIMENSION_DOOR)
THEN
	RESPONSE #100
		RemoveSpell(WIZARD_DIMENSION_DOOR)
END

// Initiate dialog
IF
	Global("ja#dialog","LOCALS",0)
	OR(2)
		Name("CDryad",Myself)
		Name("Ulene",Myself)
	NumTimesTalkedTo(0)
	See([PC])
THEN
	RESPONSE #100
		SetGlobal("ja#dialog","LOCALS",1)
		FaceObject([PC])
		StartDialogueNoSet([PC])
END

// Irenicus' Dungeon specific code
IF
	Name("Ulene",Myself)
	AreaCheck("AR0602")
	Global("MinscCharmed","AR0602",1)
	Global("HelpDryads","GLOBAL",0)
	!See("Minsc")
	!Range("Minsc",4)
THEN
	RESPONSE #100
		ActionOverride("Minsc",JumpToPoint([4069.1222]))
END

IF
	Name("Ulene",Myself)
	AreaCheck("AR0602")
	Global("MinscCharmed","AR0602",1)
	Global("HelpDryads","GLOBAL",0)
	See("Minsc")
	!Range("Minsc",4)
THEN
	RESPONSE #100
		ActionOverride("Minsc",MoveToObject("Ulene"))
END

// Detect combat
IF
	Global("JA#COMBAT","LOCALS",0)
	Allegiance(Myself,EVILCUTOFF)
	See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
END

// Detect combat
IF
	Global("JA#COMBAT","LOCALS",0)
	Allegiance(Myself,GOODCUTOFF)
	See([EVILCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
END

// Shouts every 3 rounds
IF
	Global("JA#COMBAT","LOCALS",1)
	!GlobalTimerNotExpired("JA#HELP","LOCALS")
THEN
	RESPONSE #100
		Shout(98)
		SetGlobalTimer("JA#HELP","LOCALS",18)
END

// React to shouts
IF
	Global("JA#COMBAT","LOCALS",0)
	Heard(LastSummonerOf(Myself),98)
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
		MoveToObject(LastHeardBy(Myself))
END

IF
	Global("JA#COMBAT","LOCALS",1)
	Heard(LastSummonerOf(Myself),98)
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		MoveToObject(LastHeardBy(Myself))
END

// Random walk on panic
IF
	StateCheck(Myself,STATE_PANIC)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

// Summon follow summoner
IF
	Global("JA#COMBAT","LOCALS",0)
	!StateCheck(Myself,STATE_BLIND)
	ActionListEmpty()
	!See(NearestEnemyOf(Myself))
	!See(LastSummonerOf(Myself))
	HPGT(LastSummonerOf(Myself),0)
	Range(LastSummonerOf(Myself),150)
THEN
	RESPONSE #100
		MoveToObject(LastSummonerOf(Myself))
END

// Do nothing if...
IF
	OR(3)
		Global("JA#COMBAT","LOCALS",0)
		StateCheck(Myself,STATE_IMMOBILE)
		StateCheck(Myself,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		NoAction()
END

IF
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!GlobalTimerNotExpired("speakWithPlants","LOCALS")
	CheckStatGT(Myself,0,ENTANGLE)
	HaveSpellRES("ja#2m41")
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#2m41",Myself)
		SetGlobalTimer("speakWithPlants","LOCALS",60)
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

// Dire Charm (less important targets) (most important targets)
IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(Nearest([PC.0.0.PALADIN_ALL]),ELF)
	!Race(Nearest([PC.0.0.PALADIN_ALL]),HALF_ELF)
	!CheckStatGT(Nearest([PC.0.0.PALADIN_ALL]),0,HELD)
	!StateCheck(Nearest([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
	!StateCheck(Nearest([PC.0.0.PALADIN_ALL]),STATE_PANIC)
	!StateCheck(Nearest([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
	!StateCheck(Nearest([PC.0.0.PALADIN_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(Nearest([PC.0.0.PALADIN_ALL]),STATE_SLEEPING)
	!StateCheck(Nearest([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
	See(Nearest([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(Nearest([PC.0.0.PALADIN_ALL]),0,HELD)
	!StateCheck(Nearest([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
	!StateCheck(Nearest([PC.0.0.PALADIN_ALL]),STATE_PANIC)
	!StateCheck(Nearest([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
	!StateCheck(Nearest([PC.0.0.PALADIN_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(Nearest([PC.0.0.PALADIN_ALL]),STATE_SLEEPING)
	!StateCheck(Nearest([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
	See(Nearest([PC.0.0.PALADIN_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",Nearest([PC.0.0.PALADIN_ALL]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SecondNearest([PC.0.0.PALADIN_ALL]),ELF)
	!Race(SecondNearest([PC.0.0.PALADIN_ALL]),HALF_ELF)
	!CheckStatGT(SecondNearest([PC.0.0.PALADIN_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
	See(SecondNearest([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(SecondNearest([PC.0.0.PALADIN_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
	See(SecondNearest([PC.0.0.PALADIN_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",SecondNearest([PC.0.0.PALADIN_ALL]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(ThirdNearest([PC.0.0.PALADIN_ALL]),ELF)
	!Race(ThirdNearest([PC.0.0.PALADIN_ALL]),HALF_ELF)
	!CheckStatGT(ThirdNearest([PC.0.0.PALADIN_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
	See(ThirdNearest([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(ThirdNearest([PC.0.0.PALADIN_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
	See(ThirdNearest([PC.0.0.PALADIN_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",ThirdNearest([PC.0.0.PALADIN_ALL]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SecondNearest([PC.0.0.RANGER_ALL]),ELF)
	!Race(SecondNearest([PC.0.0.RANGER_ALL]),HALF_ELF)
	!CheckStatGT(SecondNearest([PC.0.0.RANGER_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_HELPLESS)
	See(SecondNearest([PC.0.0.RANGER_ALL]))
	!CheckStatGT(SecondNearest([PC.0.0.RANGER_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_HELPLESS)
	See(SecondNearest([PC.0.0.RANGER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",SecondNearest([PC.0.0.RANGER_ALL]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(Nearest([PC.0.0.RANGER_ALL]),ELF)
	!Race(Nearest([PC.0.0.RANGER_ALL]),HALF_ELF)
	!CheckStatGT(Nearest([PC.0.0.RANGER_ALL]),0,HELD)
	!StateCheck(Nearest([PC.0.0.RANGER_ALL]),STATE_STUNNED)
	!StateCheck(Nearest([PC.0.0.RANGER_ALL]),STATE_PANIC)
	!StateCheck(Nearest([PC.0.0.RANGER_ALL]),STATE_CONFUSED)
	!StateCheck(Nearest([PC.0.0.RANGER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(Nearest([PC.0.0.RANGER_ALL]),STATE_SLEEPING)
	!StateCheck(Nearest([PC.0.0.RANGER_ALL]),STATE_HELPLESS)
	See(Nearest([PC.0.0.RANGER_ALL]))
	!CheckStatGT(Nearest([PC.0.0.RANGER_ALL]),0,HELD)
	!StateCheck(Nearest([PC.0.0.RANGER_ALL]),STATE_STUNNED)
	!StateCheck(Nearest([PC.0.0.RANGER_ALL]),STATE_PANIC)
	!StateCheck(Nearest([PC.0.0.RANGER_ALL]),STATE_CONFUSED)
	!StateCheck(Nearest([PC.0.0.RANGER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(Nearest([PC.0.0.RANGER_ALL]),STATE_SLEEPING)
	!StateCheck(Nearest([PC.0.0.RANGER_ALL]),STATE_HELPLESS)
	See(Nearest([PC.0.0.RANGER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",Nearest([PC.0.0.RANGER_ALL]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(ThirdNearest([PC.0.0.RANGER_ALL]),ELF)
	!Race(ThirdNearest([PC.0.0.RANGER_ALL]),HALF_ELF)
	!CheckStatGT(ThirdNearest([PC.0.0.RANGER_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_HELPLESS)
	See(ThirdNearest([PC.0.0.RANGER_ALL]))
	!CheckStatGT(ThirdNearest([PC.0.0.RANGER_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_HELPLESS)
	See(ThirdNearest([PC.0.0.RANGER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",ThirdNearest([PC.0.0.RANGER_ALL]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(ThirdNearest([PC.0.0.FIGHTER_ALL]),ELF)
	!Race(ThirdNearest([PC.0.0.FIGHTER_ALL]),HALF_ELF)
	!CheckStatGT(ThirdNearest([PC.0.0.FIGHTER_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_HELPLESS)
	See(ThirdNearest([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(ThirdNearest([PC.0.0.FIGHTER_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_HELPLESS)
	See(ThirdNearest([PC.0.0.FIGHTER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",ThirdNearest([PC.0.0.FIGHTER_ALL]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SecondNearest([PC.0.0.FIGHTER_ALL]),ELF)
	!Race(SecondNearest([PC.0.0.FIGHTER_ALL]),HALF_ELF)
	!CheckStatGT(SecondNearest([PC.0.0.FIGHTER_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_HELPLESS)
	See(SecondNearest([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(SecondNearest([PC.0.0.FIGHTER_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_HELPLESS)
	See(SecondNearest([PC.0.0.FIGHTER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",SecondNearest([PC.0.0.FIGHTER_ALL]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(Nearest([PC.0.0.FIGHTER_ALL]),ELF)
	!Race(Nearest([PC.0.0.FIGHTER_ALL]),HALF_ELF)
	!CheckStatGT(Nearest([PC.0.0.FIGHTER_ALL]),0,HELD)
	!StateCheck(Nearest([PC.0.0.FIGHTER_ALL]),STATE_STUNNED)
	!StateCheck(Nearest([PC.0.0.FIGHTER_ALL]),STATE_PANIC)
	!StateCheck(Nearest([PC.0.0.FIGHTER_ALL]),STATE_CONFUSED)
	!StateCheck(Nearest([PC.0.0.FIGHTER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(Nearest([PC.0.0.FIGHTER_ALL]),STATE_SLEEPING)
	!StateCheck(Nearest([PC.0.0.FIGHTER_ALL]),STATE_HELPLESS)
	See(Nearest([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(Nearest([PC.0.0.FIGHTER_ALL]),0,HELD)
	!StateCheck(Nearest([PC.0.0.FIGHTER_ALL]),STATE_STUNNED)
	!StateCheck(Nearest([PC.0.0.FIGHTER_ALL]),STATE_PANIC)
	!StateCheck(Nearest([PC.0.0.FIGHTER_ALL]),STATE_CONFUSED)
	!StateCheck(Nearest([PC.0.0.FIGHTER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(Nearest([PC.0.0.FIGHTER_ALL]),STATE_SLEEPING)
	!StateCheck(Nearest([PC.0.0.FIGHTER_ALL]),STATE_HELPLESS)
	See(Nearest([PC.0.0.FIGHTER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",Nearest([PC.0.0.FIGHTER_ALL]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

// Dire Charm (less important targets) (less important targets)
IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SixthNearest([PC]),ELF)
	!Race(SixthNearest([PC]),HALF_ELF)
	!CheckStatGT(SixthNearest([PC]),0,HELD)
	!StateCheck(SixthNearest([PC]),STATE_STUNNED)
	!StateCheck(SixthNearest([PC]),STATE_PANIC)
	!StateCheck(SixthNearest([PC]),STATE_CONFUSED)
	!StateCheck(SixthNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(SixthNearest([PC]),STATE_SLEEPING)
	!StateCheck(SixthNearest([PC]),STATE_HELPLESS)
	See(SixthNearest([PC]))
	!CheckStatGT(SixthNearest([PC]),0,HELD)
	!StateCheck(SixthNearest([PC]),STATE_STUNNED)
	!StateCheck(SixthNearest([PC]),STATE_PANIC)
	!StateCheck(SixthNearest([PC]),STATE_CONFUSED)
	!StateCheck(SixthNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(SixthNearest([PC]),STATE_SLEEPING)
	!StateCheck(SixthNearest([PC]),STATE_HELPLESS)
	See(SixthNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",SixthNearest([PC]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(ThirdNearest([PC]),ELF)
	!Race(ThirdNearest([PC]),HALF_ELF)
	!CheckStatGT(ThirdNearest([PC]),0,HELD)
	!StateCheck(ThirdNearest([PC]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC]),STATE_HELPLESS)
	See(ThirdNearest([PC]))
	!CheckStatGT(ThirdNearest([PC]),0,HELD)
	!StateCheck(ThirdNearest([PC]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC]),STATE_HELPLESS)
	See(ThirdNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",ThirdNearest([PC]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SecondNearest([PC]),ELF)
	!Race(SecondNearest([PC]),HALF_ELF)
	!CheckStatGT(SecondNearest([PC]),0,HELD)
	!StateCheck(SecondNearest([PC]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC]),STATE_PANIC)
	!StateCheck(SecondNearest([PC]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC]),STATE_HELPLESS)
	See(SecondNearest([PC]))
	!CheckStatGT(SecondNearest([PC]),0,HELD)
	!StateCheck(SecondNearest([PC]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC]),STATE_PANIC)
	!StateCheck(SecondNearest([PC]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC]),STATE_HELPLESS)
	See(SecondNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",SecondNearest([PC]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(FourthNearest([PC]),ELF)
	!Race(FourthNearest([PC]),HALF_ELF)
	!CheckStatGT(FourthNearest([PC]),0,HELD)
	!StateCheck(FourthNearest([PC]),STATE_STUNNED)
	!StateCheck(FourthNearest([PC]),STATE_PANIC)
	!StateCheck(FourthNearest([PC]),STATE_CONFUSED)
	!StateCheck(FourthNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(FourthNearest([PC]),STATE_SLEEPING)
	!StateCheck(FourthNearest([PC]),STATE_HELPLESS)
	See(FourthNearest([PC]))
	!CheckStatGT(FourthNearest([PC]),0,HELD)
	!StateCheck(FourthNearest([PC]),STATE_STUNNED)
	!StateCheck(FourthNearest([PC]),STATE_PANIC)
	!StateCheck(FourthNearest([PC]),STATE_CONFUSED)
	!StateCheck(FourthNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(FourthNearest([PC]),STATE_SLEEPING)
	!StateCheck(FourthNearest([PC]),STATE_HELPLESS)
	See(FourthNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",FourthNearest([PC]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(Nearest([PC]),ELF)
	!Race(Nearest([PC]),HALF_ELF)
	!CheckStatGT(Nearest([PC]),0,HELD)
	!StateCheck(Nearest([PC]),STATE_STUNNED)
	!StateCheck(Nearest([PC]),STATE_PANIC)
	!StateCheck(Nearest([PC]),STATE_CONFUSED)
	!StateCheck(Nearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(Nearest([PC]),STATE_SLEEPING)
	!StateCheck(Nearest([PC]),STATE_HELPLESS)
	See(Nearest([PC]))
	!CheckStatGT(Nearest([PC]),0,HELD)
	!StateCheck(Nearest([PC]),STATE_STUNNED)
	!StateCheck(Nearest([PC]),STATE_PANIC)
	!StateCheck(Nearest([PC]),STATE_CONFUSED)
	!StateCheck(Nearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(Nearest([PC]),STATE_SLEEPING)
	!StateCheck(Nearest([PC]),STATE_HELPLESS)
	See(Nearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",Nearest([PC]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(FifthNearest([PC]),ELF)
	!Race(FifthNearest([PC]),HALF_ELF)
	!CheckStatGT(FifthNearest([PC]),0,HELD)
	!StateCheck(FifthNearest([PC]),STATE_STUNNED)
	!StateCheck(FifthNearest([PC]),STATE_PANIC)
	!StateCheck(FifthNearest([PC]),STATE_CONFUSED)
	!StateCheck(FifthNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(FifthNearest([PC]),STATE_SLEEPING)
	!StateCheck(FifthNearest([PC]),STATE_HELPLESS)
	See(FifthNearest([PC]))
	!CheckStatGT(FifthNearest([PC]),0,HELD)
	!StateCheck(FifthNearest([PC]),STATE_STUNNED)
	!StateCheck(FifthNearest([PC]),STATE_PANIC)
	!StateCheck(FifthNearest([PC]),STATE_CONFUSED)
	!StateCheck(FifthNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(FifthNearest([PC]),STATE_SLEEPING)
	!StateCheck(FifthNearest([PC]),STATE_HELPLESS)
	See(FifthNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",FifthNearest([PC]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

// Dire Charm (less important targets) (less important targets)
IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(Nearest([PC.0.0.FIGHTER_ALL]),ELF)
	!CheckStatGT(Nearest([PC.0.0.FIGHTER_ALL]),0,HELD)
	!StateCheck(Nearest([PC.0.0.FIGHTER_ALL]),STATE_STUNNED)
	!StateCheck(Nearest([PC.0.0.FIGHTER_ALL]),STATE_PANIC)
	!StateCheck(Nearest([PC.0.0.FIGHTER_ALL]),STATE_CONFUSED)
	!StateCheck(Nearest([PC.0.0.FIGHTER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(Nearest([PC.0.0.FIGHTER_ALL]),STATE_SLEEPING)
	!StateCheck(Nearest([PC.0.0.FIGHTER_ALL]),STATE_HELPLESS)
	See(Nearest([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(Nearest([PC.0.0.FIGHTER_ALL]),0,HELD)
	!StateCheck(Nearest([PC.0.0.FIGHTER_ALL]),STATE_STUNNED)
	!StateCheck(Nearest([PC.0.0.FIGHTER_ALL]),STATE_PANIC)
	!StateCheck(Nearest([PC.0.0.FIGHTER_ALL]),STATE_CONFUSED)
	!StateCheck(Nearest([PC.0.0.FIGHTER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(Nearest([PC.0.0.FIGHTER_ALL]),STATE_SLEEPING)
	!StateCheck(Nearest([PC.0.0.FIGHTER_ALL]),STATE_HELPLESS)
	See(Nearest([PC.0.0.FIGHTER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",Nearest([PC.0.0.FIGHTER_ALL]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(ThirdNearest([PC.0.0.FIGHTER_ALL]),ELF)
	!CheckStatGT(ThirdNearest([PC.0.0.FIGHTER_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_HELPLESS)
	See(ThirdNearest([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(ThirdNearest([PC.0.0.FIGHTER_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.FIGHTER_ALL]),STATE_HELPLESS)
	See(ThirdNearest([PC.0.0.FIGHTER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",ThirdNearest([PC.0.0.FIGHTER_ALL]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(Nearest([PC.0.0.PALADIN_ALL]),ELF)
	!CheckStatGT(Nearest([PC.0.0.PALADIN_ALL]),0,HELD)
	!StateCheck(Nearest([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
	!StateCheck(Nearest([PC.0.0.PALADIN_ALL]),STATE_PANIC)
	!StateCheck(Nearest([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
	!StateCheck(Nearest([PC.0.0.PALADIN_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(Nearest([PC.0.0.PALADIN_ALL]),STATE_SLEEPING)
	!StateCheck(Nearest([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
	See(Nearest([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(Nearest([PC.0.0.PALADIN_ALL]),0,HELD)
	!StateCheck(Nearest([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
	!StateCheck(Nearest([PC.0.0.PALADIN_ALL]),STATE_PANIC)
	!StateCheck(Nearest([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
	!StateCheck(Nearest([PC.0.0.PALADIN_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(Nearest([PC.0.0.PALADIN_ALL]),STATE_SLEEPING)
	!StateCheck(Nearest([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
	See(Nearest([PC.0.0.PALADIN_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",Nearest([PC.0.0.PALADIN_ALL]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SecondNearest([PC.0.0.FIGHTER_ALL]),ELF)
	!CheckStatGT(SecondNearest([PC.0.0.FIGHTER_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_HELPLESS)
	See(SecondNearest([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(SecondNearest([PC.0.0.FIGHTER_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.FIGHTER_ALL]),STATE_HELPLESS)
	See(SecondNearest([PC.0.0.FIGHTER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",SecondNearest([PC.0.0.FIGHTER_ALL]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SecondNearest([PC.0.0.RANGER_ALL]),ELF)
	!CheckStatGT(SecondNearest([PC.0.0.RANGER_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_HELPLESS)
	See(SecondNearest([PC.0.0.RANGER_ALL]))
	!CheckStatGT(SecondNearest([PC.0.0.RANGER_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.RANGER_ALL]),STATE_HELPLESS)
	See(SecondNearest([PC.0.0.RANGER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",SecondNearest([PC.0.0.RANGER_ALL]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(ThirdNearest([PC.0.0.PALADIN_ALL]),ELF)
	!CheckStatGT(ThirdNearest([PC.0.0.PALADIN_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
	See(ThirdNearest([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(ThirdNearest([PC.0.0.PALADIN_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
	See(ThirdNearest([PC.0.0.PALADIN_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",ThirdNearest([PC.0.0.PALADIN_ALL]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(ThirdNearest([PC.0.0.RANGER_ALL]),ELF)
	!CheckStatGT(ThirdNearest([PC.0.0.RANGER_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_HELPLESS)
	See(ThirdNearest([PC.0.0.RANGER_ALL]))
	!CheckStatGT(ThirdNearest([PC.0.0.RANGER_ALL]),0,HELD)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC.0.0.RANGER_ALL]),STATE_HELPLESS)
	See(ThirdNearest([PC.0.0.RANGER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",ThirdNearest([PC.0.0.RANGER_ALL]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(SecondNearest([PC.0.0.PALADIN_ALL]),ELF)
	!CheckStatGT(SecondNearest([PC.0.0.PALADIN_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
	See(SecondNearest([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(SecondNearest([PC.0.0.PALADIN_ALL]),0,HELD)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_PANIC)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
	See(SecondNearest([PC.0.0.PALADIN_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",SecondNearest([PC.0.0.PALADIN_ALL]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!Race(Nearest([PC.0.0.RANGER_ALL]),ELF)
	!CheckStatGT(Nearest([PC.0.0.RANGER_ALL]),0,HELD)
	!StateCheck(Nearest([PC.0.0.RANGER_ALL]),STATE_STUNNED)
	!StateCheck(Nearest([PC.0.0.RANGER_ALL]),STATE_PANIC)
	!StateCheck(Nearest([PC.0.0.RANGER_ALL]),STATE_CONFUSED)
	!StateCheck(Nearest([PC.0.0.RANGER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(Nearest([PC.0.0.RANGER_ALL]),STATE_SLEEPING)
	!StateCheck(Nearest([PC.0.0.RANGER_ALL]),STATE_HELPLESS)
	See(Nearest([PC.0.0.RANGER_ALL]))
	!CheckStatGT(Nearest([PC.0.0.RANGER_ALL]),0,HELD)
	!StateCheck(Nearest([PC.0.0.RANGER_ALL]),STATE_STUNNED)
	!StateCheck(Nearest([PC.0.0.RANGER_ALL]),STATE_PANIC)
	!StateCheck(Nearest([PC.0.0.RANGER_ALL]),STATE_CONFUSED)
	!StateCheck(Nearest([PC.0.0.RANGER_ALL]),STATE_FEEBLEMINDED)
	!StateCheck(Nearest([PC.0.0.RANGER_ALL]),STATE_SLEEPING)
	!StateCheck(Nearest([PC.0.0.RANGER_ALL]),STATE_HELPLESS)
	See(Nearest([PC.0.0.RANGER_ALL]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",Nearest([PC.0.0.RANGER_ALL]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

// Dire Charm (less important targets) (less important targets)
IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!CheckStatGT(SecondNearest([PC]),0,HELD)
	!StateCheck(SecondNearest([PC]),STATE_STUNNED)
	!StateCheck(SecondNearest([PC]),STATE_PANIC)
	!StateCheck(SecondNearest([PC]),STATE_CONFUSED)
	!StateCheck(SecondNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearest([PC]),STATE_SLEEPING)
	!StateCheck(SecondNearest([PC]),STATE_HELPLESS)
	See(SecondNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",SecondNearest([PC]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!CheckStatGT(Nearest([PC]),0,HELD)
	!StateCheck(Nearest([PC]),STATE_STUNNED)
	!StateCheck(Nearest([PC]),STATE_PANIC)
	!StateCheck(Nearest([PC]),STATE_CONFUSED)
	!StateCheck(Nearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(Nearest([PC]),STATE_SLEEPING)
	!StateCheck(Nearest([PC]),STATE_HELPLESS)
	See(Nearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",Nearest([PC]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!CheckStatGT(ThirdNearest([PC]),0,HELD)
	!StateCheck(ThirdNearest([PC]),STATE_STUNNED)
	!StateCheck(ThirdNearest([PC]),STATE_PANIC)
	!StateCheck(ThirdNearest([PC]),STATE_CONFUSED)
	!StateCheck(ThirdNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearest([PC]),STATE_SLEEPING)
	!StateCheck(ThirdNearest([PC]),STATE_HELPLESS)
	See(ThirdNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",ThirdNearest([PC]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!CheckStatGT(FifthNearest([PC]),0,HELD)
	!StateCheck(FifthNearest([PC]),STATE_STUNNED)
	!StateCheck(FifthNearest([PC]),STATE_PANIC)
	!StateCheck(FifthNearest([PC]),STATE_CONFUSED)
	!StateCheck(FifthNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(FifthNearest([PC]),STATE_SLEEPING)
	!StateCheck(FifthNearest([PC]),STATE_HELPLESS)
	See(FifthNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",FifthNearest([PC]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!CheckStatGT(SixthNearest([PC]),0,HELD)
	!StateCheck(SixthNearest([PC]),STATE_STUNNED)
	!StateCheck(SixthNearest([PC]),STATE_PANIC)
	!StateCheck(SixthNearest([PC]),STATE_CONFUSED)
	!StateCheck(SixthNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(SixthNearest([PC]),STATE_SLEEPING)
	!StateCheck(SixthNearest([PC]),STATE_HELPLESS)
	See(SixthNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",SixthNearest([PC]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("ja#1m41")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	!CheckStatGT(FourthNearest([PC]),0,HELD)
	!StateCheck(FourthNearest([PC]),STATE_STUNNED)
	!StateCheck(FourthNearest([PC]),STATE_PANIC)
	!StateCheck(FourthNearest([PC]),STATE_CONFUSED)
	!StateCheck(FourthNearest([PC]),STATE_FEEBLEMINDED)
	!StateCheck(FourthNearest([PC]),STATE_SLEEPING)
	!StateCheck(FourthNearest([PC]),STATE_HELPLESS)
	See(FourthNearest([PC]))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ForceSpellRES("ja#1m41",FourthNearest([PC]))
		RemoveSpellRES("ja#1m41")
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		SetInterrupt(TRUE)
END

// Run away from enemies
IF
	Range(NearestEnemyOf(Myself),20)
THEN
	RESPONSE #100
		RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),45)
END

// Track players if allegiance is not GOODCUTOFF
IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player1,150)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStatGT(Player1,0,SANCTUARY)
	!StateCheck(Player1,STATE_CHARMED)
	!StateCheck(Player1,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player2,150)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStatGT(Player2,0,SANCTUARY)
	!StateCheck(Player2,STATE_CHARMED)
	!StateCheck(Player2,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player2)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player3,150)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStatGT(Player3,0,SANCTUARY)
	!StateCheck(Player3,STATE_CHARMED)
	!StateCheck(Player3,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player3)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player4,150)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStatGT(Player4,0,SANCTUARY)
	!StateCheck(Player4,STATE_CHARMED)
	!StateCheck(Player4,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player4)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player5,150)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStatGT(Player5,0,SANCTUARY)
	!StateCheck(Player5,STATE_CHARMED)
	!StateCheck(Player5,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player5)
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(Player6,150)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStatGT(Player6,0,SANCTUARY)
	!StateCheck(Player6,STATE_CHARMED)
	!StateCheck(Player6,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player6)
END

// Track last seen enemy if allegiance is GOODCUTOFF
IF
	Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	Range(LastSeenBy(Myself),150)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

