COPY ~%MOD_FOLDER%/bam/fey/rr#fspkp.bam~ ~override~       // Speak With Plants icon

ADD_PROJECTILE ~%MOD_FOLDER%/pro/rr#fentg.pro~            // New projectile for Entangle (party friendly)
COPY ~%MOD_FOLDER%/eff/fey/rr#fentg.eff~ ~override~       // Entangle EFF (for incorporeal and large creature immunity)
COPY ~%MOD_FOLDER%/spl/fey/rr#fentg.spl~ ~override~       // Entangle
  READ_LONG  0x64 ab_off
  READ_SHORT 0x68 ab_num
  FOR(i=0; i<ab_num; i+=1) BEGIN
    WRITE_SHORT (ab_off+i*0x28+0x26) %rr#fentg%           // use new projectile
  END

INCLUDE "%MOD_FOLDER%/lib/pnp-monster/fey/dryad.tpa"
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/fey/hamadryad.tpa"
