IF
    !StateCheck([PC.0.0.MAGE],STATE_INVISIBLE)
    See([PC.0.0.MAGE])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.MAGE],ENEMY)
    !StateCheck([PC.0.0.MAGE],STATE_IMMOBILE)
    !StateCheck([PC.0.0.MAGE],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.MAGE],0,HELD)
    !StateCheck([PC.0.0.MAGE],STATE_MIRRORIMAGE)
    !CheckStatGT([PC.0.0.MAGE],0,STONESKINS)
    !HPPercentGT([PC.0.0.MAGE],20)
    Range([PC.0.0.MAGE],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.MAGE])
END

IF
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_INVISIBLE)
    See([PC.0.0.MAGE_THIEF])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.MAGE_THIEF],ENEMY)
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_IMMOBILE)
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.MAGE_THIEF],0,HELD)
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_MIRRORIMAGE)
    !CheckStatGT([PC.0.0.MAGE_THIEF],0,STONESKINS)
    !HPPercentGT([PC.0.0.MAGE_THIEF],20)
    Range([PC.0.0.MAGE_THIEF],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.MAGE_THIEF])
END

IF
    !StateCheck([PC.0.0.LONG_BOW],STATE_INVISIBLE)
    See([PC.0.0.LONG_BOW])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.LONG_BOW],ENEMY)
    !StateCheck([PC.0.0.LONG_BOW],STATE_IMMOBILE)
    !StateCheck([PC.0.0.LONG_BOW],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.LONG_BOW],0,HELD)
    !StateCheck([PC.0.0.LONG_BOW],STATE_MIRRORIMAGE)
    !CheckStatGT([PC.0.0.LONG_BOW],0,STONESKINS)
    !HPPercentGT([PC.0.0.LONG_BOW],20)
    Range([PC.0.0.LONG_BOW],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.LONG_BOW])
END

IF
    !StateCheck([PC.0.0.THIEF],STATE_INVISIBLE)
    See([PC.0.0.THIEF])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.THIEF],ENEMY)
    !StateCheck([PC.0.0.THIEF],STATE_IMMOBILE)
    !StateCheck([PC.0.0.THIEF],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.THIEF],0,HELD)
    !StateCheck([PC.0.0.THIEF],STATE_MIRRORIMAGE)
    !CheckStatGT([PC.0.0.THIEF],0,STONESKINS)
    !HPPercentGT([PC.0.0.THIEF],20)
    Range([PC.0.0.THIEF],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.THIEF])
END

IF
    !StateCheck([PC.0.0.BARD],STATE_INVISIBLE)
    See([PC.0.0.BARD])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.BARD],ENEMY)
    !StateCheck([PC.0.0.BARD],STATE_IMMOBILE)
    !StateCheck([PC.0.0.BARD],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.BARD],0,HELD)
    !StateCheck([PC.0.0.BARD],STATE_MIRRORIMAGE)
    !CheckStatGT([PC.0.0.BARD],0,STONESKINS)
    !HPPercentGT([PC.0.0.BARD],20)
    Range([PC.0.0.BARD],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.BARD])
END

IF
    !StateCheck([PC.0.0.THIEF_ALL],STATE_INVISIBLE)
    See([PC.0.0.THIEF_ALL])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.THIEF_ALL],ENEMY)
    !StateCheck([PC.0.0.THIEF_ALL],STATE_IMMOBILE)
    !StateCheck([PC.0.0.THIEF_ALL],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.THIEF_ALL],0,HELD)
    !StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
    !CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
    !HPPercentGT([PC.0.0.THIEF_ALL],20)
    Range([PC.0.0.THIEF_ALL],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.THIEF_ALL])
END

IF
    !StateCheck([PC.0.0.CLERIC],STATE_INVISIBLE)
    See([PC.0.0.CLERIC])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.CLERIC],ENEMY)
    !StateCheck([PC.0.0.CLERIC],STATE_IMMOBILE)
    !StateCheck([PC.0.0.CLERIC],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.CLERIC],0,HELD)
    !StateCheck([PC.0.0.CLERIC],STATE_MIRRORIMAGE)
    !CheckStatGT([PC.0.0.CLERIC],0,STONESKINS)
    !HPPercentGT([PC.0.0.CLERIC],20)
    Range([PC.0.0.CLERIC],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.CLERIC])
END

IF
    !StateCheck([PC],STATE_INVISIBLE)
    See([PC])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC],ENEMY)
    !StateCheck([PC],STATE_IMMOBILE)
    !StateCheck([PC],STATE_FEEBLEMINDED)
    !CheckStatGT([PC],0,HELD)
    !StateCheck([PC],STATE_MIRRORIMAGE)
    !CheckStatGT([PC],0,STONESKINS)
    !HPPercentGT([PC],20)
    Range([PC],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC])
END

IF
    !StateCheck(SecondNearest([PC]),STATE_INVISIBLE)
    See(SecondNearest([PC]))
    Allegiance(Myself,ENEMY)
    !Allegiance(SecondNearest([PC]),ENEMY)
    !StateCheck(SecondNearest([PC]),STATE_IMMOBILE)
    !StateCheck(SecondNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(SecondNearest([PC]),0,HELD)
    !StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
    !CheckStatGT(SecondNearest([PC]),0,STONESKINS)
    !HPPercentGT(SecondNearest([PC]),20)
    Range(SecondNearest([PC]),4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(SecondNearest([PC]))
END

IF
    !StateCheck(ThirdNearest([PC]),STATE_INVISIBLE)
    See(ThirdNearest([PC]))
    Allegiance(Myself,ENEMY)
    !Allegiance(ThirdNearest([PC]),ENEMY)
    !StateCheck(ThirdNearest([PC]),STATE_IMMOBILE)
    !StateCheck(ThirdNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(ThirdNearest([PC]),0,HELD)
    !StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
    !CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
    !HPPercentGT(ThirdNearest([PC]),20)
    Range(ThirdNearest([PC]),4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(ThirdNearest([PC]))
END

IF
    !StateCheck([PC.0.0.MAGE],STATE_INVISIBLE)
    See([PC.0.0.MAGE])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.MAGE],ENEMY)
    !StateCheck([PC.0.0.MAGE],STATE_IMMOBILE)
    !StateCheck([PC.0.0.MAGE],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.MAGE],0,HELD)
    !StateCheck([PC.0.0.MAGE],STATE_MIRRORIMAGE)
    !CheckStatGT([PC.0.0.MAGE],0,STONESKINS)
    !HPPercentGT([PC.0.0.MAGE],50)
    Range([PC.0.0.MAGE],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.MAGE])
END

IF
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_INVISIBLE)
    See([PC.0.0.MAGE_THIEF])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.MAGE_THIEF],ENEMY)
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_IMMOBILE)
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.MAGE_THIEF],0,HELD)
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_MIRRORIMAGE)
    !CheckStatGT([PC.0.0.MAGE_THIEF],0,STONESKINS)
    !HPPercentGT([PC.0.0.MAGE_THIEF],50)
    Range([PC.0.0.MAGE_THIEF],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.MAGE_THIEF])
END

IF
    !StateCheck([PC.0.0.LONG_BOW],STATE_INVISIBLE)
    See([PC.0.0.LONG_BOW])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.LONG_BOW],ENEMY)
    !StateCheck([PC.0.0.LONG_BOW],STATE_IMMOBILE)
    !StateCheck([PC.0.0.LONG_BOW],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.LONG_BOW],0,HELD)
    !StateCheck([PC.0.0.LONG_BOW],STATE_MIRRORIMAGE)
    !CheckStatGT([PC.0.0.LONG_BOW],0,STONESKINS)
    !HPPercentGT([PC.0.0.LONG_BOW],50)
    Range([PC.0.0.LONG_BOW],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.LONG_BOW])
END

IF
    !StateCheck([PC.0.0.THIEF],STATE_INVISIBLE)
    See([PC.0.0.THIEF])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.THIEF],ENEMY)
    !StateCheck([PC.0.0.THIEF],STATE_IMMOBILE)
    !StateCheck([PC.0.0.THIEF],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.THIEF],0,HELD)
    !StateCheck([PC.0.0.THIEF],STATE_MIRRORIMAGE)
    !CheckStatGT([PC.0.0.THIEF],0,STONESKINS)
    !HPPercentGT([PC.0.0.THIEF],50)
    Range([PC.0.0.THIEF],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.THIEF])
END

IF
    !StateCheck([PC.0.0.BARD],STATE_INVISIBLE)
    See([PC.0.0.BARD])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.BARD],ENEMY)
    !StateCheck([PC.0.0.BARD],STATE_IMMOBILE)
    !StateCheck([PC.0.0.BARD],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.BARD],0,HELD)
    !StateCheck([PC.0.0.BARD],STATE_MIRRORIMAGE)
    !CheckStatGT([PC.0.0.BARD],0,STONESKINS)
    !HPPercentGT([PC.0.0.BARD],50)
    Range([PC.0.0.BARD],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.BARD])
END

IF
    !StateCheck([PC.0.0.THIEF_ALL],STATE_INVISIBLE)
    See([PC.0.0.THIEF_ALL])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.THIEF_ALL],ENEMY)
    !StateCheck([PC.0.0.THIEF_ALL],STATE_IMMOBILE)
    !StateCheck([PC.0.0.THIEF_ALL],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.THIEF_ALL],0,HELD)
    !StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
    !CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
    !HPPercentGT([PC.0.0.THIEF_ALL],50)
    Range([PC.0.0.THIEF_ALL],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.THIEF_ALL])
END

IF
    !StateCheck([PC.0.0.CLERIC],STATE_INVISIBLE)
    See([PC.0.0.CLERIC])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.CLERIC],ENEMY)
    !StateCheck([PC.0.0.CLERIC],STATE_IMMOBILE)
    !StateCheck([PC.0.0.CLERIC],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.CLERIC],0,HELD)
    !StateCheck([PC.0.0.CLERIC],STATE_MIRRORIMAGE)
    !CheckStatGT([PC.0.0.CLERIC],0,STONESKINS)
    !HPPercentGT([PC.0.0.CLERIC],50)
    Range([PC.0.0.CLERIC],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.CLERIC])
END

IF
    !StateCheck([PC],STATE_INVISIBLE)
    See([PC])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC],ENEMY)
    !StateCheck([PC],STATE_IMMOBILE)
    !StateCheck([PC],STATE_FEEBLEMINDED)
    !CheckStatGT([PC],0,HELD)
    !StateCheck([PC],STATE_MIRRORIMAGE)
    !CheckStatGT([PC],0,STONESKINS)
    !HPPercentGT([PC],50)
    Range([PC],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC])
END

IF
    !StateCheck(SecondNearest([PC]),STATE_INVISIBLE)
    See(SecondNearest([PC]))
    Allegiance(Myself,ENEMY)
    !Allegiance(SecondNearest([PC]),ENEMY)
    !StateCheck(SecondNearest([PC]),STATE_IMMOBILE)
    !StateCheck(SecondNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(SecondNearest([PC]),0,HELD)
    !StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
    !CheckStatGT(SecondNearest([PC]),0,STONESKINS)
    !HPPercentGT(SecondNearest([PC]),50)
    Range(SecondNearest([PC]),4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(SecondNearest([PC]))
END

IF
    !StateCheck(ThirdNearest([PC]),STATE_INVISIBLE)
    See(ThirdNearest([PC]))
    Allegiance(Myself,ENEMY)
    !Allegiance(ThirdNearest([PC]),ENEMY)
    !StateCheck(ThirdNearest([PC]),STATE_IMMOBILE)
    !StateCheck(ThirdNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(ThirdNearest([PC]),0,HELD)
    !StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
    !CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
    !HPPercentGT(ThirdNearest([PC]),50)
    Range(ThirdNearest([PC]),4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(ThirdNearest([PC]))
END

IF
    !StateCheck([PC.0.0.MAGE],STATE_INVISIBLE)
    See([PC.0.0.MAGE])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.MAGE],ENEMY)
    !StateCheck([PC.0.0.MAGE],STATE_IMMOBILE)
    !StateCheck([PC.0.0.MAGE],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.MAGE],0,HELD)
    !StateCheck([PC.0.0.MAGE],STATE_MIRRORIMAGE)
    !CheckStatGT([PC.0.0.MAGE],0,STONESKINS)
    Range([PC.0.0.MAGE],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.MAGE])
END

IF
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_INVISIBLE)
    See([PC.0.0.MAGE_THIEF])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.MAGE_THIEF],ENEMY)
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_IMMOBILE)
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.MAGE_THIEF],0,HELD)
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_MIRRORIMAGE)
    !CheckStatGT([PC.0.0.MAGE_THIEF],0,STONESKINS)
    Range([PC.0.0.MAGE_THIEF],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.MAGE_THIEF])
END

IF
    !StateCheck([PC.0.0.LONG_BOW],STATE_INVISIBLE)
    See([PC.0.0.LONG_BOW])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.LONG_BOW],ENEMY)
    !StateCheck([PC.0.0.LONG_BOW],STATE_IMMOBILE)
    !StateCheck([PC.0.0.LONG_BOW],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.LONG_BOW],0,HELD)
    !StateCheck([PC.0.0.LONG_BOW],STATE_MIRRORIMAGE)
    !CheckStatGT([PC.0.0.LONG_BOW],0,STONESKINS)
    Range([PC.0.0.LONG_BOW],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.LONG_BOW])
END

IF
    !StateCheck([PC.0.0.THIEF],STATE_INVISIBLE)
    See([PC.0.0.THIEF])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.THIEF],ENEMY)
    !StateCheck([PC.0.0.THIEF],STATE_IMMOBILE)
    !StateCheck([PC.0.0.THIEF],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.THIEF],0,HELD)
    !StateCheck([PC.0.0.THIEF],STATE_MIRRORIMAGE)
    !CheckStatGT([PC.0.0.THIEF],0,STONESKINS)
    Range([PC.0.0.THIEF],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.THIEF])
END

IF
    !StateCheck([PC.0.0.BARD],STATE_INVISIBLE)
    See([PC.0.0.BARD])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.BARD],ENEMY)
    !StateCheck([PC.0.0.BARD],STATE_IMMOBILE)
    !StateCheck([PC.0.0.BARD],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.BARD],0,HELD)
    !StateCheck([PC.0.0.BARD],STATE_MIRRORIMAGE)
    !CheckStatGT([PC.0.0.BARD],0,STONESKINS)
    Range([PC.0.0.BARD],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.BARD])
END

IF
    !StateCheck([PC.0.0.THIEF_ALL],STATE_INVISIBLE)
    See([PC.0.0.THIEF_ALL])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.THIEF_ALL],ENEMY)
    !StateCheck([PC.0.0.THIEF_ALL],STATE_IMMOBILE)
    !StateCheck([PC.0.0.THIEF_ALL],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.THIEF_ALL],0,HELD)
    !StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
    !CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
    Range([PC.0.0.THIEF_ALL],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.THIEF_ALL])
END

IF
    !StateCheck([PC.0.0.CLERIC],STATE_INVISIBLE)
    See([PC.0.0.CLERIC])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.CLERIC],ENEMY)
    !StateCheck([PC.0.0.CLERIC],STATE_IMMOBILE)
    !StateCheck([PC.0.0.CLERIC],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.CLERIC],0,HELD)
    !StateCheck([PC.0.0.CLERIC],STATE_MIRRORIMAGE)
    !CheckStatGT([PC.0.0.CLERIC],0,STONESKINS)
    Range([PC.0.0.CLERIC],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.CLERIC])
END

IF
    !StateCheck([PC],STATE_INVISIBLE)
    See([PC])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC],ENEMY)
    !StateCheck([PC],STATE_IMMOBILE)
    !StateCheck([PC],STATE_FEEBLEMINDED)
    !CheckStatGT([PC],0,HELD)
    !StateCheck([PC],STATE_MIRRORIMAGE)
    !CheckStatGT([PC],0,STONESKINS)
    Range([PC],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC])
END

IF
    !StateCheck(SecondNearest([PC]),STATE_INVISIBLE)
    See(SecondNearest([PC]))
    Allegiance(Myself,ENEMY)
    !Allegiance(SecondNearest([PC]),ENEMY)
    !StateCheck(SecondNearest([PC]),STATE_IMMOBILE)
    !StateCheck(SecondNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(SecondNearest([PC]),0,HELD)
    !StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
    !CheckStatGT(SecondNearest([PC]),0,STONESKINS)
    Range(SecondNearest([PC]),4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(SecondNearest([PC]))
END

IF
    !StateCheck(ThirdNearest([PC]),STATE_INVISIBLE)
    See(ThirdNearest([PC]))
    Allegiance(Myself,ENEMY)
    !Allegiance(ThirdNearest([PC]),ENEMY)
    !StateCheck(ThirdNearest([PC]),STATE_IMMOBILE)
    !StateCheck(ThirdNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(ThirdNearest([PC]),0,HELD)
    !StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
    !CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
    Range(ThirdNearest([PC]),4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(ThirdNearest([PC]))
END

IF
    !StateCheck([PC.0.0.MAGE],STATE_INVISIBLE)
    See([PC.0.0.MAGE])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.MAGE],ENEMY)
    !StateCheck([PC.0.0.MAGE],STATE_IMMOBILE)
    !StateCheck([PC.0.0.MAGE],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.MAGE],0,HELD)
    Range([PC.0.0.MAGE],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.MAGE])
END

IF
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_INVISIBLE)
    See([PC.0.0.MAGE_THIEF])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.MAGE_THIEF],ENEMY)
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_IMMOBILE)
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.MAGE_THIEF],0,HELD)
    Range([PC.0.0.MAGE_THIEF],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.MAGE_THIEF])
END

IF
    !StateCheck([PC.0.0.LONG_BOW],STATE_INVISIBLE)
    See([PC.0.0.LONG_BOW])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.LONG_BOW],ENEMY)
    !StateCheck([PC.0.0.LONG_BOW],STATE_IMMOBILE)
    !StateCheck([PC.0.0.LONG_BOW],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.LONG_BOW],0,HELD)
    Range([PC.0.0.LONG_BOW],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.LONG_BOW])
END

IF
    !StateCheck([PC.0.0.THIEF],STATE_INVISIBLE)
    See([PC.0.0.THIEF])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.THIEF],ENEMY)
    !StateCheck([PC.0.0.THIEF],STATE_IMMOBILE)
    !StateCheck([PC.0.0.THIEF],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.THIEF],0,HELD)
    Range([PC.0.0.THIEF],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.THIEF])
END

IF
    !StateCheck([PC.0.0.BARD],STATE_INVISIBLE)
    See([PC.0.0.BARD])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.BARD],ENEMY)
    !StateCheck([PC.0.0.BARD],STATE_IMMOBILE)
    !StateCheck([PC.0.0.BARD],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.BARD],0,HELD)
    Range([PC.0.0.BARD],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.BARD])
END

IF
    !StateCheck([PC.0.0.THIEF_ALL],STATE_INVISIBLE)
    See([PC.0.0.THIEF_ALL])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.THIEF_ALL],ENEMY)
    !StateCheck([PC.0.0.THIEF_ALL],STATE_IMMOBILE)
    !StateCheck([PC.0.0.THIEF_ALL],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.THIEF_ALL],0,HELD)
    Range([PC.0.0.THIEF_ALL],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.THIEF_ALL])
END

IF
    !StateCheck([PC.0.0.CLERIC],STATE_INVISIBLE)
    See([PC.0.0.CLERIC])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.CLERIC],ENEMY)
    !StateCheck([PC.0.0.CLERIC],STATE_IMMOBILE)
    !StateCheck([PC.0.0.CLERIC],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.CLERIC],0,HELD)
    Range([PC.0.0.CLERIC],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.CLERIC])
END

IF
    !StateCheck([PC],STATE_INVISIBLE)
    See([PC])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC],ENEMY)
    !StateCheck([PC],STATE_IMMOBILE)
    !StateCheck([PC],STATE_FEEBLEMINDED)
    !CheckStatGT([PC],0,HELD)
    Range([PC],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC])
END

IF
    !StateCheck(SecondNearest([PC]),STATE_INVISIBLE)
    See(SecondNearest([PC]))
    Allegiance(Myself,ENEMY)
    !Allegiance(SecondNearest([PC]),ENEMY)
    !StateCheck(SecondNearest([PC]),STATE_IMMOBILE)
    !StateCheck(SecondNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(SecondNearest([PC]),0,HELD)
    Range(SecondNearest([PC]),4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(SecondNearest([PC]))
END

IF
    !StateCheck(ThirdNearest([PC]),STATE_INVISIBLE)
    See(ThirdNearest([PC]))
    Allegiance(Myself,ENEMY)
    !Allegiance(ThirdNearest([PC]),ENEMY)
    !StateCheck(ThirdNearest([PC]),STATE_IMMOBILE)
    !StateCheck(ThirdNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(ThirdNearest([PC]),0,HELD)
    Range(ThirdNearest([PC]),4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(ThirdNearest([PC]))
END

IF
    !StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
    See(NearestEnemyOf(Myself))
    Allegiance(Myself,ENEMY)
    !Allegiance(NearestEnemyOf(Myself),ENEMY)
    !StateCheck(NearestEnemyOf(Myself),STATE_IMMOBILE)
    !StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
    !CheckStatGT(NearestEnemyOf(Myself),0,HELD)
    Range(NearestEnemyOf(Myself),4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(NearestEnemyOf(Myself))
END

IF
    !StateCheck(SecondNearestEnemyOf(Myself),STATE_INVISIBLE)
    See(SecondNearestEnemyOf(Myself))
    Allegiance(Myself,ENEMY)
    !Allegiance(SecondNearestEnemyOf(Myself),ENEMY)
    !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMMOBILE)
    !StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
    !CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
    Range(SecondNearestEnemyOf(Myself),4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(SecondNearestEnemyOf(Myself))
END

IF
    !StateCheck(ThirdNearestEnemyOf(Myself),STATE_INVISIBLE)
    See(ThirdNearestEnemyOf(Myself))
    Allegiance(Myself,ENEMY)
    !Allegiance(ThirdNearestEnemyOf(Myself),ENEMY)
    !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMMOBILE)
    !StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
    !CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
    Range(ThirdNearestEnemyOf(Myself),4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(ThirdNearestEnemyOf(Myself))
END

IF
    !StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
    See(NearestEnemyOf(Myself))
    Allegiance(Myself,ENEMY)
    !Allegiance(NearestEnemyOf(Myself),ENEMY)
    Range(NearestEnemyOf(Myself),4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(NearestEnemyOf(Myself))
END

IF
    !StateCheck(SecondNearestEnemyOf(Myself),STATE_INVISIBLE)
    See(SecondNearestEnemyOf(Myself))
    Allegiance(Myself,ENEMY)
    !Allegiance(SecondNearestEnemyOf(Myself),ENEMY)
    Range(SecondNearestEnemyOf(Myself),4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(SecondNearestEnemyOf(Myself))
END

IF
    !StateCheck(ThirdNearestEnemyOf(Myself),STATE_INVISIBLE)
    See(ThirdNearestEnemyOf(Myself))
    Allegiance(Myself,ENEMY)
    !Allegiance(ThirdNearestEnemyOf(Myself),ENEMY)
    Range(ThirdNearestEnemyOf(Myself),4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(ThirdNearestEnemyOf(Myself))
END

IF
    !CanEquipRanged()
    ActionListEmpty()
    Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("targetcompromise","LOCALS",FOUR_ROUNDS)
END

IF
    See(NearestEnemyOf(Myself))
    OR(24)
        CheckSpellState(Player1,PROTECTION_FROM_NORMAL_MISSILES)
        CheckSpellState(Player1,ENTROPY_SHIELD)
        CheckStat(Player1,1,CLERIC_PHYSICAL_MIRROR)
        HasItem("shld24",Player1)
        CheckSpellState(Player2,PROTECTION_FROM_NORMAL_MISSILES)
        CheckSpellState(Player2,ENTROPY_SHIELD)
        CheckStat(Player2,1,CLERIC_PHYSICAL_MIRROR)
        HasItem("shld24",Player2)
        CheckSpellState(Player3,PROTECTION_FROM_NORMAL_MISSILES)
        CheckSpellState(Player3,ENTROPY_SHIELD)
        CheckStat(Player3,1,CLERIC_PHYSICAL_MIRROR)
        HasItem("shld24",Player3)
        CheckSpellState(Player4,PROTECTION_FROM_NORMAL_MISSILES)
        CheckSpellState(Player4,ENTROPY_SHIELD)
        CheckStat(Player4,1,CLERIC_PHYSICAL_MIRROR)
        HasItem("shld24",Player4)
        CheckSpellState(Player5,PROTECTION_FROM_NORMAL_MISSILES)
        CheckSpellState(Player5,ENTROPY_SHIELD)
        CheckStat(Player5,1,CLERIC_PHYSICAL_MIRROR)
        HasItem("shld24",Player5)
        CheckSpellState(Player6,PROTECTION_FROM_NORMAL_MISSILES)
        CheckSpellState(Player6,ENTROPY_SHIELD)
        CheckStat(Player6,1,CLERIC_PHYSICAL_MIRROR)
        HasItem("shld24",Player6)
    !Global("DMWWinitialiseseePNM","LOCALS",1)
THEN
    RESPONSE #100
        SetGlobal("DMWWinitialiseseePNM","LOCALS",1)
        SetGlobalTimer("DMWWseePNM","LOCALS",ONE_ROUND)
    RESPONSE #100
        SetGlobal("DMWWinitialiseseePNM","LOCALS",1)
        SetGlobalTimer("DMWWseePNM","LOCALS",3)
END

IF
    ActionListEmpty()
    !StateCheck([PC],STATE_INVISIBLE)
    See([PC])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC],ENEMY)
    !StateCheck([PC],STATE_IMMOBILE)
    !StateCheck([PC],STATE_FEEBLEMINDED)
    !CheckStatGT([PC],0,HELD)
    OR(2)
        !CheckSpellState([PC],PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT([PC],100,RESISTMISSILE)
    OR(2)
        CheckStatLT([PC],75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    HPPercentLT([PC],40)
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate([PC],30)
    RESPONSE #50
        Continue()
END

IF
    ActionListEmpty()
    !StateCheck(SecondNearest([PC]),STATE_INVISIBLE)
    See(SecondNearest([PC]))
    Allegiance(Myself,ENEMY)
    !Allegiance(SecondNearest([PC]),ENEMY)
    !StateCheck(SecondNearest([PC]),STATE_IMMOBILE)
    !StateCheck(SecondNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(SecondNearest([PC]),0,HELD)
    OR(2)
        !CheckSpellState(SecondNearest([PC]),PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT(SecondNearest([PC]),100,RESISTMISSILE)
    OR(2)
        CheckStatLT(SecondNearest([PC]),75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    HPPercentLT(SecondNearest([PC]),40)
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate(SecondNearest([PC]),30)
    RESPONSE #50
        Continue()
END

IF
    ActionListEmpty()
    !StateCheck(ThirdNearest([PC]),STATE_INVISIBLE)
    See(ThirdNearest([PC]))
    Allegiance(Myself,ENEMY)
    !Allegiance(ThirdNearest([PC]),ENEMY)
    !StateCheck(ThirdNearest([PC]),STATE_IMMOBILE)
    !StateCheck(ThirdNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(ThirdNearest([PC]),0,HELD)
    OR(2)
        !CheckSpellState(ThirdNearest([PC]),PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT(ThirdNearest([PC]),100,RESISTMISSILE)
    OR(2)
        CheckStatLT(ThirdNearest([PC]),75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    HPPercentLT(ThirdNearest([PC]),40)
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate(ThirdNearest([PC]),30)
    RESPONSE #50
        Continue()
END

IF
    ActionListEmpty()
    !StateCheck(FourthNearest([PC]),STATE_INVISIBLE)
    See(FourthNearest([PC]))
    Allegiance(Myself,ENEMY)
    !Allegiance(FourthNearest([PC]),ENEMY)
    !StateCheck(FourthNearest([PC]),STATE_IMMOBILE)
    !StateCheck(FourthNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(FourthNearest([PC]),0,HELD)
    OR(2)
        !CheckSpellState(FourthNearest([PC]),PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT(FourthNearest([PC]),100,RESISTMISSILE)
    OR(2)
        CheckStatLT(FourthNearest([PC]),75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    HPPercentLT(FourthNearest([PC]),40)
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate(FourthNearest([PC]),30)
    RESPONSE #50
        Continue()
END

IF
    ActionListEmpty()
    !StateCheck(FifthNearest([PC]),STATE_INVISIBLE)
    See(FifthNearest([PC]))
    Allegiance(Myself,ENEMY)
    !Allegiance(FifthNearest([PC]),ENEMY)
    !StateCheck(FifthNearest([PC]),STATE_IMMOBILE)
    !StateCheck(FifthNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(FifthNearest([PC]),0,HELD)
    OR(2)
        !CheckSpellState(FifthNearest([PC]),PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT(FifthNearest([PC]),100,RESISTMISSILE)
    OR(2)
        CheckStatLT(FifthNearest([PC]),75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    HPPercentLT(FifthNearest([PC]),40)
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate(FifthNearest([PC]),30)
    RESPONSE #50
        Continue()
END

IF
    ActionListEmpty()
    !StateCheck(SixthNearest([PC]),STATE_INVISIBLE)
    See(SixthNearest([PC]))
    Allegiance(Myself,ENEMY)
    !Allegiance(SixthNearest([PC]),ENEMY)
    !StateCheck(SixthNearest([PC]),STATE_IMMOBILE)
    !StateCheck(SixthNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(SixthNearest([PC]),0,HELD)
    OR(2)
        !CheckSpellState(SixthNearest([PC]),PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT(SixthNearest([PC]),100,RESISTMISSILE)
    OR(2)
        CheckStatLT(SixthNearest([PC]),75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    HPPercentLT(SixthNearest([PC]),40)
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate(SixthNearest([PC]),30)
    RESPONSE #50
        Continue()
END

IF
    ActionListEmpty()
    !StateCheck([PC.0.0.LONG_BOW],STATE_INVISIBLE)
    See([PC.0.0.LONG_BOW])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.LONG_BOW],ENEMY)
    !StateCheck([PC.0.0.LONG_BOW],STATE_IMMOBILE)
    !StateCheck([PC.0.0.LONG_BOW],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.LONG_BOW],0,HELD)
    OR(2)
        !CheckSpellState([PC.0.0.LONG_BOW],PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT([PC.0.0.LONG_BOW],100,RESISTMISSILE)
    OR(2)
        CheckStatLT([PC.0.0.LONG_BOW],75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate([PC.0.0.LONG_BOW],30)
    RESPONSE #50
        Continue()
END

IF
    ActionListEmpty()
    !StateCheck([PC.0.0.CLERIC_ALL],STATE_INVISIBLE)
    See([PC.0.0.CLERIC_ALL])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.CLERIC_ALL],ENEMY)
    !StateCheck([PC.0.0.CLERIC_ALL],STATE_IMMOBILE)
    !StateCheck([PC.0.0.CLERIC_ALL],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.CLERIC_ALL],0,HELD)
    OR(2)
        !CheckSpellState([PC.0.0.CLERIC_ALL],PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT([PC.0.0.CLERIC_ALL],100,RESISTMISSILE)
    OR(2)
        CheckStatLT([PC.0.0.CLERIC_ALL],75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate([PC.0.0.CLERIC_ALL],30)
    RESPONSE #50
        Continue()
END

IF
    ActionListEmpty()
    !StateCheck([PC.0.0.DRUID_ALL],STATE_INVISIBLE)
    See([PC.0.0.DRUID_ALL])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.DRUID_ALL],ENEMY)
    !StateCheck([PC.0.0.DRUID_ALL],STATE_IMMOBILE)
    !StateCheck([PC.0.0.DRUID_ALL],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.DRUID_ALL],0,HELD)
    OR(2)
        !CheckSpellState([PC.0.0.DRUID_ALL],PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT([PC.0.0.DRUID_ALL],100,RESISTMISSILE)
    OR(2)
        CheckStatLT([PC.0.0.DRUID_ALL],75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate([PC.0.0.DRUID_ALL],30)
    RESPONSE #50
        Continue()
END

IF
    ActionListEmpty()
    !StateCheck([PC.0.0.BARD],STATE_INVISIBLE)
    See([PC.0.0.BARD])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.BARD],ENEMY)
    !StateCheck([PC.0.0.BARD],STATE_IMMOBILE)
    !StateCheck([PC.0.0.BARD],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.BARD],0,HELD)
    OR(2)
        !CheckSpellState([PC.0.0.BARD],PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT([PC.0.0.BARD],100,RESISTMISSILE)
    OR(2)
        CheckStatLT([PC.0.0.BARD],75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate([PC.0.0.BARD],30)
    RESPONSE #50
        Continue()
END

IF
    ActionListEmpty()
    !StateCheck([PC],STATE_INVISIBLE)
    See([PC])
    !HasItem("morsword",[PC])  // Such is the pull of the wandering way. It's a desire we have all heard much of through the tales of Littleman, though I must confess I cannot truly understand it. It's so much more comfortable spending the nights with family by the hearth. Fare thee well on your journeys.
    Allegiance(Myself,ENEMY)
    !Allegiance([PC],ENEMY)
    !StateCheck([PC],STATE_IMMOBILE)
    !StateCheck([PC],STATE_FEEBLEMINDED)
    !CheckStatGT([PC],0,HELD)
    OR(2)
        !CheckSpellState([PC],PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT([PC],100,RESISTMISSILE)
    OR(2)
        CheckStatLT([PC],75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate([PC],30)
END

IF
    ActionListEmpty()
    !StateCheck(SecondNearest([PC]),STATE_INVISIBLE)
    See(SecondNearest([PC]))
    !HasItem("morsword",SecondNearest([PC]))  // Such is the pull of the wandering way. It's a desire we have all heard much of through the tales of Littleman, though I must confess I cannot truly understand it. It's so much more comfortable spending the nights with family by the hearth. Fare thee well on your journeys.
    Allegiance(Myself,ENEMY)
    !Allegiance(SecondNearest([PC]),ENEMY)
    !StateCheck(SecondNearest([PC]),STATE_IMMOBILE)
    !StateCheck(SecondNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(SecondNearest([PC]),0,HELD)
    OR(2)
        !CheckSpellState(SecondNearest([PC]),PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT(SecondNearest([PC]),100,RESISTMISSILE)
    OR(2)
        CheckStatLT(SecondNearest([PC]),75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate(SecondNearest([PC]),30)
END

IF
    ActionListEmpty()
    !StateCheck(ThirdNearest([PC]),STATE_INVISIBLE)
    See(ThirdNearest([PC]))
    !HasItem("morsword",ThirdNearest([PC]))  // Such is the pull of the wandering way. It's a desire we have all heard much of through the tales of Littleman, though I must confess I cannot truly understand it. It's so much more comfortable spending the nights with family by the hearth. Fare thee well on your journeys.
    Allegiance(Myself,ENEMY)
    !Allegiance(ThirdNearest([PC]),ENEMY)
    !StateCheck(ThirdNearest([PC]),STATE_IMMOBILE)
    !StateCheck(ThirdNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(ThirdNearest([PC]),0,HELD)
    OR(2)
        !CheckSpellState(ThirdNearest([PC]),PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT(ThirdNearest([PC]),100,RESISTMISSILE)
    OR(2)
        CheckStatLT(ThirdNearest([PC]),75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate(ThirdNearest([PC]),30)
END

IF
    ActionListEmpty()
    !StateCheck(FourthNearest([PC]),STATE_INVISIBLE)
    See(FourthNearest([PC]))
    !HasItem("morsword",FourthNearest([PC]))  // Such is the pull of the wandering way. It's a desire we have all heard much of through the tales of Littleman, though I must confess I cannot truly understand it. It's so much more comfortable spending the nights with family by the hearth. Fare thee well on your journeys.
    Allegiance(Myself,ENEMY)
    !Allegiance(FourthNearest([PC]),ENEMY)
    !StateCheck(FourthNearest([PC]),STATE_IMMOBILE)
    !StateCheck(FourthNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(FourthNearest([PC]),0,HELD)
    OR(2)
        !CheckSpellState(FourthNearest([PC]),PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT(FourthNearest([PC]),100,RESISTMISSILE)
    OR(2)
        CheckStatLT(FourthNearest([PC]),75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate(FourthNearest([PC]),30)
END

IF
    ActionListEmpty()
    !StateCheck(FifthNearest([PC]),STATE_INVISIBLE)
    See(FifthNearest([PC]))
    !HasItem("morsword",FifthNearest([PC]))  // Such is the pull of the wandering way. It's a desire we have all heard much of through the tales of Littleman, though I must confess I cannot truly understand it. It's so much more comfortable spending the nights with family by the hearth. Fare thee well on your journeys.
    Allegiance(Myself,ENEMY)
    !Allegiance(FifthNearest([PC]),ENEMY)
    !StateCheck(FifthNearest([PC]),STATE_IMMOBILE)
    !StateCheck(FifthNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(FifthNearest([PC]),0,HELD)
    OR(2)
        !CheckSpellState(FifthNearest([PC]),PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT(FifthNearest([PC]),100,RESISTMISSILE)
    OR(2)
        CheckStatLT(FifthNearest([PC]),75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate(FifthNearest([PC]),30)
END

IF
    ActionListEmpty()
    !StateCheck(SixthNearest([PC]),STATE_INVISIBLE)
    See(SixthNearest([PC]))
    !HasItem("morsword",SixthNearest([PC]))  // Such is the pull of the wandering way. It's a desire we have all heard much of through the tales of Littleman, though I must confess I cannot truly understand it. It's so much more comfortable spending the nights with family by the hearth. Fare thee well on your journeys.
    Allegiance(Myself,ENEMY)
    !Allegiance(SixthNearest([PC]),ENEMY)
    !StateCheck(SixthNearest([PC]),STATE_IMMOBILE)
    !StateCheck(SixthNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(SixthNearest([PC]),0,HELD)
    OR(2)
        !CheckSpellState(SixthNearest([PC]),PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT(SixthNearest([PC]),100,RESISTMISSILE)
    OR(2)
        CheckStatLT(SixthNearest([PC]),75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate(SixthNearest([PC]),30)
END

IF
    ActionListEmpty()
    !StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
    See(NearestEnemyOf(Myself))
    !HasItem("morsword",NearestEnemyOf(Myself))  // Such is the pull of the wandering way. It's a desire we have all heard much of through the tales of Littleman, though I must confess I cannot truly understand it. It's so much more comfortable spending the nights with family by the hearth. Fare thee well on your journeys.
    Allegiance(Myself,ENEMY)
    !Allegiance(NearestEnemyOf(Myself),ENEMY)
    !StateCheck(NearestEnemyOf(Myself),STATE_IMMOBILE)
    !StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
    !CheckStatGT(NearestEnemyOf(Myself),0,HELD)
    OR(2)
        !CheckSpellState(NearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT(NearestEnemyOf(Myself),100,RESISTMISSILE)
    OR(2)
        CheckStatLT(NearestEnemyOf(Myself),75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
    ActionListEmpty()
    !StateCheck(SecondNearestEnemyOf(Myself),STATE_INVISIBLE)
    See(SecondNearestEnemyOf(Myself))
    !HasItem("morsword",SecondNearestEnemyOf(Myself))  // Such is the pull of the wandering way. It's a desire we have all heard much of through the tales of Littleman, though I must confess I cannot truly understand it. It's so much more comfortable spending the nights with family by the hearth. Fare thee well on your journeys.
    Allegiance(Myself,ENEMY)
    !Allegiance(SecondNearestEnemyOf(Myself),ENEMY)
    !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMMOBILE)
    !StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
    !CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
    OR(2)
        !CheckSpellState(SecondNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTMISSILE)
    OR(2)
        CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate(SecondNearestEnemyOf(Myself),30)
END

IF
    ActionListEmpty()
    !StateCheck(ThirdNearestEnemyOf(Myself),STATE_INVISIBLE)
    See(ThirdNearestEnemyOf(Myself))
    !HasItem("morsword",ThirdNearestEnemyOf(Myself))  // Such is the pull of the wandering way. It's a desire we have all heard much of through the tales of Littleman, though I must confess I cannot truly understand it. It's so much more comfortable spending the nights with family by the hearth. Fare thee well on your journeys.
    Allegiance(Myself,ENEMY)
    !Allegiance(ThirdNearestEnemyOf(Myself),ENEMY)
    !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMMOBILE)
    !StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
    !CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
    OR(2)
        !CheckSpellState(ThirdNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTMISSILE)
    OR(2)
        CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate(ThirdNearestEnemyOf(Myself),30)
END

IF
    ActionListEmpty()
    !StateCheck(FourthNearestEnemyOf(Myself),STATE_INVISIBLE)
    See(FourthNearestEnemyOf(Myself))
    !HasItem("morsword",FourthNearestEnemyOf(Myself))  // Such is the pull of the wandering way. It's a desire we have all heard much of through the tales of Littleman, though I must confess I cannot truly understand it. It's so much more comfortable spending the nights with family by the hearth. Fare thee well on your journeys.
    Allegiance(Myself,ENEMY)
    !Allegiance(FourthNearestEnemyOf(Myself),ENEMY)
    !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMMOBILE)
    !StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
    !CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
    OR(2)
        !CheckSpellState(FourthNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT(FourthNearestEnemyOf(Myself),100,RESISTMISSILE)
    OR(2)
        CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate(FourthNearestEnemyOf(Myself),30)
END

IF
    ActionListEmpty()
    !StateCheck(FifthNearestEnemyOf(Myself),STATE_INVISIBLE)
    See(FifthNearestEnemyOf(Myself))
    !HasItem("morsword",FifthNearestEnemyOf(Myself))  // Such is the pull of the wandering way. It's a desire we have all heard much of through the tales of Littleman, though I must confess I cannot truly understand it. It's so much more comfortable spending the nights with family by the hearth. Fare thee well on your journeys.
    Allegiance(Myself,ENEMY)
    !Allegiance(FifthNearestEnemyOf(Myself),ENEMY)
    !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMMOBILE)
    !StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
    !CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
    OR(2)
        !CheckSpellState(FifthNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT(FifthNearestEnemyOf(Myself),100,RESISTMISSILE)
    OR(2)
        CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate(FifthNearestEnemyOf(Myself),30)
END

IF
    ActionListEmpty()
    !StateCheck(SixthNearestEnemyOf(Myself),STATE_INVISIBLE)
    See(SixthNearestEnemyOf(Myself))
    !HasItem("morsword",SixthNearestEnemyOf(Myself))  // Such is the pull of the wandering way. It's a desire we have all heard much of through the tales of Littleman, though I must confess I cannot truly understand it. It's so much more comfortable spending the nights with family by the hearth. Fare thee well on your journeys.
    Allegiance(Myself,ENEMY)
    !Allegiance(SixthNearestEnemyOf(Myself),ENEMY)
    !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMMOBILE)
    !StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
    !CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
    OR(2)
        !CheckSpellState(SixthNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT(SixthNearestEnemyOf(Myself),100,RESISTMISSILE)
    OR(2)
        CheckStatLT(SixthNearestEnemyOf(Myself),75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate(SixthNearestEnemyOf(Myself),30)
END

IF
    ActionListEmpty()
    !StateCheck([PC],STATE_INVISIBLE)
    See([PC])
    !HasItem("morsword",[PC])  // Such is the pull of the wandering way. It's a desire we have all heard much of through the tales of Littleman, though I must confess I cannot truly understand it. It's so much more comfortable spending the nights with family by the hearth. Fare thee well on your journeys.
    Allegiance(Myself,ENEMY)
    !Allegiance([PC],ENEMY)
    OR(2)
        !CheckSpellState([PC],PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT([PC],100,RESISTMISSILE)
    OR(2)
        CheckStatLT([PC],75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate([PC],30)
END

IF
    ActionListEmpty()
    !StateCheck(SecondNearest([PC]),STATE_INVISIBLE)
    See(SecondNearest([PC]))
    !HasItem("morsword",SecondNearest([PC]))  // Such is the pull of the wandering way. It's a desire we have all heard much of through the tales of Littleman, though I must confess I cannot truly understand it. It's so much more comfortable spending the nights with family by the hearth. Fare thee well on your journeys.
    Allegiance(Myself,ENEMY)
    !Allegiance(SecondNearest([PC]),ENEMY)
    OR(2)
        !CheckSpellState(SecondNearest([PC]),PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT(SecondNearest([PC]),100,RESISTMISSILE)
    OR(2)
        CheckStatLT(SecondNearest([PC]),75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate(SecondNearest([PC]),30)
END

IF
    ActionListEmpty()
    !StateCheck(ThirdNearest([PC]),STATE_INVISIBLE)
    See(ThirdNearest([PC]))
    !HasItem("morsword",ThirdNearest([PC]))  // Such is the pull of the wandering way. It's a desire we have all heard much of through the tales of Littleman, though I must confess I cannot truly understand it. It's so much more comfortable spending the nights with family by the hearth. Fare thee well on your journeys.
    Allegiance(Myself,ENEMY)
    !Allegiance(ThirdNearest([PC]),ENEMY)
    OR(2)
        !CheckSpellState(ThirdNearest([PC]),PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT(ThirdNearest([PC]),100,RESISTMISSILE)
    OR(2)
        CheckStatLT(ThirdNearest([PC]),75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate(ThirdNearest([PC]),30)
END

IF
    ActionListEmpty()
    !StateCheck(FourthNearest([PC]),STATE_INVISIBLE)
    See(FourthNearest([PC]))
    !HasItem("morsword",FourthNearest([PC]))  // Such is the pull of the wandering way. It's a desire we have all heard much of through the tales of Littleman, though I must confess I cannot truly understand it. It's so much more comfortable spending the nights with family by the hearth. Fare thee well on your journeys.
    Allegiance(Myself,ENEMY)
    !Allegiance(FourthNearest([PC]),ENEMY)
    OR(2)
        !CheckSpellState(FourthNearest([PC]),PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT(FourthNearest([PC]),100,RESISTMISSILE)
    OR(2)
        CheckStatLT(FourthNearest([PC]),75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate(FourthNearest([PC]),30)
END

IF
    ActionListEmpty()
    !StateCheck(FifthNearest([PC]),STATE_INVISIBLE)
    See(FifthNearest([PC]))
    !HasItem("morsword",FifthNearest([PC]))  // Such is the pull of the wandering way. It's a desire we have all heard much of through the tales of Littleman, though I must confess I cannot truly understand it. It's so much more comfortable spending the nights with family by the hearth. Fare thee well on your journeys.
    Allegiance(Myself,ENEMY)
    !Allegiance(FifthNearest([PC]),ENEMY)
    OR(2)
        !CheckSpellState(FifthNearest([PC]),PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT(FifthNearest([PC]),100,RESISTMISSILE)
    OR(2)
        CheckStatLT(FifthNearest([PC]),75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate(FifthNearest([PC]),30)
END

IF
    ActionListEmpty()
    !StateCheck(SixthNearest([PC]),STATE_INVISIBLE)
    See(SixthNearest([PC]))
    !HasItem("morsword",SixthNearest([PC]))  // Such is the pull of the wandering way. It's a desire we have all heard much of through the tales of Littleman, though I must confess I cannot truly understand it. It's so much more comfortable spending the nights with family by the hearth. Fare thee well on your journeys.
    Allegiance(Myself,ENEMY)
    !Allegiance(SixthNearest([PC]),ENEMY)
    OR(2)
        !CheckSpellState(SixthNearest([PC]),PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT(SixthNearest([PC]),100,RESISTMISSILE)
    OR(2)
        CheckStatLT(SixthNearest([PC]),75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate(SixthNearest([PC]),30)
END

IF
    ActionListEmpty()
    !StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
    See(NearestEnemyOf(Myself))
    !HasItem("morsword",NearestEnemyOf(Myself))  // Such is the pull of the wandering way. It's a desire we have all heard much of through the tales of Littleman, though I must confess I cannot truly understand it. It's so much more comfortable spending the nights with family by the hearth. Fare thee well on your journeys.
    Allegiance(Myself,ENEMY)
    !Allegiance(NearestEnemyOf(Myself),ENEMY)
    OR(2)
        !CheckSpellState(NearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT(NearestEnemyOf(Myself),100,RESISTMISSILE)
    OR(2)
        CheckStatLT(NearestEnemyOf(Myself),75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
    ActionListEmpty()
    !StateCheck(SecondNearestEnemyOf(Myself),STATE_INVISIBLE)
    See(SecondNearestEnemyOf(Myself))
    !HasItem("morsword",SecondNearestEnemyOf(Myself))  // Such is the pull of the wandering way. It's a desire we have all heard much of through the tales of Littleman, though I must confess I cannot truly understand it. It's so much more comfortable spending the nights with family by the hearth. Fare thee well on your journeys.
    Allegiance(Myself,ENEMY)
    !Allegiance(SecondNearestEnemyOf(Myself),ENEMY)
    OR(2)
        !CheckSpellState(SecondNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTMISSILE)
    OR(2)
        CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate(SecondNearestEnemyOf(Myself),30)
END

IF
    ActionListEmpty()
    !StateCheck(ThirdNearestEnemyOf(Myself),STATE_INVISIBLE)
    See(ThirdNearestEnemyOf(Myself))
    !HasItem("morsword",ThirdNearestEnemyOf(Myself))  // Such is the pull of the wandering way. It's a desire we have all heard much of through the tales of Littleman, though I must confess I cannot truly understand it. It's so much more comfortable spending the nights with family by the hearth. Fare thee well on your journeys.
    Allegiance(Myself,ENEMY)
    !Allegiance(ThirdNearestEnemyOf(Myself),ENEMY)
    OR(2)
        !CheckSpellState(ThirdNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTMISSILE)
    OR(2)
        CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate(ThirdNearestEnemyOf(Myself),30)
END

IF
    ActionListEmpty()
    !StateCheck(FourthNearestEnemyOf(Myself),STATE_INVISIBLE)
    See(FourthNearestEnemyOf(Myself))
    !HasItem("morsword",FourthNearestEnemyOf(Myself))  // Such is the pull of the wandering way. It's a desire we have all heard much of through the tales of Littleman, though I must confess I cannot truly understand it. It's so much more comfortable spending the nights with family by the hearth. Fare thee well on your journeys.
    Allegiance(Myself,ENEMY)
    !Allegiance(FourthNearestEnemyOf(Myself),ENEMY)
    OR(2)
        !CheckSpellState(FourthNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT(FourthNearestEnemyOf(Myself),100,RESISTMISSILE)
    OR(2)
        CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate(FourthNearestEnemyOf(Myself),30)
END

IF
    ActionListEmpty()
    !StateCheck(FifthNearestEnemyOf(Myself),STATE_INVISIBLE)
    See(FifthNearestEnemyOf(Myself))
    !HasItem("morsword",FifthNearestEnemyOf(Myself))  // Such is the pull of the wandering way. It's a desire we have all heard much of through the tales of Littleman, though I must confess I cannot truly understand it. It's so much more comfortable spending the nights with family by the hearth. Fare thee well on your journeys.
    Allegiance(Myself,ENEMY)
    !Allegiance(FifthNearestEnemyOf(Myself),ENEMY)
    OR(2)
        !CheckSpellState(FifthNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT(FifthNearestEnemyOf(Myself),100,RESISTMISSILE)
    OR(2)
        CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate(FifthNearestEnemyOf(Myself),30)
END

IF
    ActionListEmpty()
    !StateCheck(SixthNearestEnemyOf(Myself),STATE_INVISIBLE)
    See(SixthNearestEnemyOf(Myself))
    !HasItem("morsword",SixthNearestEnemyOf(Myself))  // Such is the pull of the wandering way. It's a desire we have all heard much of through the tales of Littleman, though I must confess I cannot truly understand it. It's so much more comfortable spending the nights with family by the hearth. Fare thee well on your journeys.
    Allegiance(Myself,ENEMY)
    !Allegiance(SixthNearestEnemyOf(Myself),ENEMY)
    OR(2)
        !CheckSpellState(SixthNearestEnemyOf(Myself),PROTECTION_FROM_NORMAL_MISSILES)
        GlobalTimerNotExpired("DMWWseePNM","LOCALS")
    CheckStatLT(SixthNearestEnemyOf(Myself),100,RESISTMISSILE)
    OR(2)
        CheckStatLT(SixthNearestEnemyOf(Myself),75,RESISTMISSILE)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate(SixthNearestEnemyOf(Myself),30)
END

IF
    !StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
    ActionListEmpty()
    See(NearestEnemyOf(Myself))
    Allegiance(Myself,ENEMY)
THEN
    RESPONSE #100
        EquipMostDamagingMelee()
        SetGlobal("melee","LOCALS",1)
        AttackOneRound(NearestEnemyOf(Myself))
END

IF
    ActionListEmpty()
    !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    Allegiance(Myself,ENEMY)
    OR(6)
        See(Player1)
        See(Player2)
        See(Player3)
        See(Player4)
        See(Player5)
        See(Player6)
THEN
    RESPONSE #100
        EquipRanged()
        SetGlobal("validtarget","LOCALS",1)
        SetGlobal("melee","LOCALS",0)
        AttackReevaluate(LastSeenBy(Myself),30)
END

